### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.plugin.demo4.Entry

### ISSUE THREAD

**Issue by l123456789jy** [Qihoo360/RePlugin#101]
**RePlugin **: 2.1.0

**Android compile SDK **: 25

**Android ROM**: 三星s7

`07-04 13:35:59.461 32579-32579/? E/Zygote: v2
07-04 13:35:59.461 32579-32579/? E/Zygote: accessInfo : 0
07-04 13:36:03.821 32579-32579/com.qihoo360.replugin.sample.host E/ws001: Didn't find class "com.qihoo360.plugin.demo4.Entry" on path: DexPathList[[zip file "/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3/demo4-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo4-10-10-1, /vendor/lib64, /system/lib64]]
                                                                          java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.plugin.demo4.Entry" on path: DexPathList[[zip file "/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3/demo4-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.qihoo360.replugin.sample.host/app_plugins_v3_libs/demo4-10-10-1, /vendor/lib64, /system/lib64]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                              at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:76)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                              at com.qihoo360.loader2.Loader.loadEntryMethod2(Loader.java:419)
                                                                              at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:857)
                                                                              at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:822)
                                                                              at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:621)
                                                                              at com.qihoo360.loader2.Plugin.load(Plugin.java:432)
                                                                              at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1033)
                                                                              at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1018)
                                                                              at com.qihoo360.loader2.PmLocalImpl.getActivityInfo(PmLocalImpl.java:443)
                                                                              at com.qihoo360.loader2.PmLocalImpl.loadPluginActivity(PmLocalImpl.java:319)
                                                                              at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:230)
                                                                              at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                                              at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                                              at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                                              at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java:38)
                                                                              at android.view.View.performClick(View.java:5697)
                                                                              at android.widget.TextView.performClick(TextView.java:10815)
                                                                              at android.view.View$PerformClick.run(View.java:22526)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:158)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                          	Suppressed: java.lang.ClassNotFoundException: com.qihoo360.plugin.demo4.Entry
                                                                              at java.lang.Class.classForName(Native Method)
                                                                              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                              		... 26 more
                                                                           Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-04 13:36:03.891 32579-32579/com.qihoo360.replugin.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.qihoo360.replugin.sample.host, PID: 32579
                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1STNTS1}: android.content.res.Resources$NotFoundException: Resource ID #0x7f020053
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:158)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020053
                                                                                       at android.content.res.Resources.getValue(Resources.java:2558)
                                                                                       at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(AppCompatDrawableManager.java:231)
                                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:194)
                                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185)
                                                                                       at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:720)
                                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                                       at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                                       at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                                                       at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                                                       at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                                                       at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
                                                                                       at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java:29)
                                                                                       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:199)
                                                                                       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
                                                                                       at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
                                                                                       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                                       at com.Company.Demo.MainActivity.onCreate(MainActivity.java:13)
                                                                                       at android.app.Activity.performCreate(Activity.java:6876)
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:158) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
`

**Comment by zhaolei9527** [comment]
确定正确配置后，插件中的界面，都需要单独配置主题样式才能正常显示。

**Comment by zcm-hu** [comment]
@zhaolei9527 在插件里面给Activity单独配置样式后，在宿主app/build.gradle  加
repluginHostConfig {
    useAppCompat = true
} 
解决了！

**Comment by jiongxuan** [comment]
感谢 @zhaolei9527 的解答。FAQ和接入指南上也有说明，欢迎参考。谢谢！
