### ISSUE TITLE
java.lang.NullPointerException: Expected to unbox a 'boolean' primitive type but was returned null

### ISSUE THREAD

**Issue by 15130140362** [Qihoo360/RePlugin#1010]
#### 问题详细描述 Detailed description of the problem
java.lang.NullPointerException: Expected to unbox a 'boolean' primitive type but was returned null
	at $Proxy8.dispatchKeyEvent(Unknown Source)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:419)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6094)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5959)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5414)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5474)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5433)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5598)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5441)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5655)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5414)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5474)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5433)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5441)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5414)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5474)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5433)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5631)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5799)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3222)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2750)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2741)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3199)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:184)
	at android.app.ActivityThread.main(ActivityThread.java:7905)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：android 10
Android 手机型号&ROM(Phone model & ROM): 
华为 
#### Logcat上下文 Logcat context
[crash.docx](https://github.com/Qihoo360/RePlugin/files/6822951/crash.docx)

**Comment by 15130140362** [comment]
不是Replugin的问题
