### ISSUE TITLE
 org.apache.http.message.BasicNameValuePair cannot be cast to org.apache.http.NameValuePair

### ISSUE THREAD

**Issue by runfengai** [Qihoo360/RePlugin#1011]
#### 问题详细描述 Detailed description of the problem
插件中集成了apache的库
`useLibrary 'org.apache.http.legacy'`
宿主中也需要用到apache的库，所以也以同样的方式引用了。
`useLibrary 'org.apache.http.legacy'`
#### 复现问题步骤 Steps to reproduce the problem
1. 插件apk单独跑一个apk时没问题，代码可以正常运行。
2. 插件apk运行在宿主apk中，报错如下：

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.4
rePlugin-plugin-lib/gradle Version:2.3.4

Android API Version：>=19
Android 手机型号&ROM(Phone model & ROM):  小米8  android 9.0系统

#### Logcat上下文 Logcat context
`2021-07-19 17:13:53.006 12215-12215/com.test.app E/.test.data: Maybe bug 77342775, looking for Lorg/apache/http/NameValuePair; 0x15531cc0[continuous;main space (region space)] defined in /data/user/0/com.test.app/app_p_a/214022483.jar!classes48.dex/0xcf6de010
2021-07-19 17:13:53.006 12215-12215/com.test.app E/.test.data:   with loader: com.qihoo360.replugin.PluginDexClassLoader/0xba9f9170[hit:continuous;main space (region space)];dalvik.system.PathClassLoader/0xf2c1ddc0();java.lang.BootClassLoader/0xf2c1e9a0
2021-07-19 17:13:53.006 12215-12215/com.test.app E/.test.data:   in interface table for Lorg/apache/http/message/BasicNameValuePair; 0x138fb438[continuous;main space (region space)] defined in /system/framework/org.apache.http.legacy.boot.jar/0xf2c23340 ifcount=2
2021-07-19 17:13:53.007 12215-12215/com.test.app E/.test.data:   with loader dalvik.system.PathClassLoader/0xec1194e0[hit:continuous;main space (region space)](Anonymous-DexFile@0xeee78000-0xeee8974c/0xec7da720:/system/framework/org.apache.http.legacy.boot.jar/0xf2c23340:/data/app/com.test.app-kNIXlgjt7mh-0_aWKp0ePw==/base.apk/0xe587b600:+!classes2.dex/0xe587b540:+!classes3.dex/0xe587b720:+!classes4.dex/0xe587b840:+!classes5.dex/0xe587b960:+!classes6.dex/0xe587ba80:+!classes7.dex/0xe587bba0:+!classes8.dex/0xe587bd80:+!classes9.dex/0xe587bea0:+!classes10.dex/0xe587bfc0:+!classes11.dex/0xe587cd40);java.lang.BootClassLoader/0xf2c1e9a0
2021-07-19 17:13:53.007 12215-12215/com.test.app E/.test.data:   iface #0: org.apache.http.NameValuePair
2021-07-19 17:13:53.007 12215-12215/com.test.app E/.test.data:     descriptor match in dalvik.system.PathClassLoader/0xec1194e0[hit:continuous;main space (region space)](Anonymous-DexFile@0xeee78000-0xeee8974c/0xec7da720:/system/framework/org.apache.http.legacy.boot.jar/0xf2c23340:/data/app/com.test.app-kNIXlgjt7mh-0_aWKp0ePw==/base.apk/0xe587b600:+!classes2.dex/0xe587b540:+!classes3.dex/0xe587b720:+!classes4.dex/0xe587b840:+!classes5.dex/0xe587b960:+!classes6.dex/0xe587ba80:+!classes7.dex/0xe587bba0:+!classes8.dex/0xe587bd80:+!classes9.dex/0xe587bea0:+!classes10.dex/0xe587bfc0:+!classes11.dex/0xe587cd40);java.lang.BootClassLoader/0xf2c1e9a0 match? false
2021-07-19 17:13:53.007 12215-12215/com.test.app E/.test.data:   iface #1: java.lang.Cloneable
2021-07-19 17:13:53.008 12215-12215/com.test.app E/CacheHWV: CacheHybridWebView FECall Action = getLocation1 Desc: java.lang.ClassCastException: org.apache.http.message.BasicNameValuePair cannot be cast to org.apache.http.NameValuePair
        at com.test.widget.CacheHybridWebView$CacheHybridWebViewClient.shouldOverrideUrlLoading(CacheHybridWebView.java:511)
        at com.test.common.web.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:53)
        at com.test.common.web.proxy.SystemWebViewClientProxy.shouldOverrideUrlLoading(SystemWebViewClientProxy.java:55)
        at CU.a(PG:1)
        at kd.b(PG:79)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:150)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

**Comment by runfengai** [comment]
修改源码引用httpcomponent为prvided解决。
