### ISSUE TITLE
自己打包替换demo1.jar后报错

### ISSUE THREAD

**Issue by wojiaotianyong** [Qihoo360/RePlugin#1033]
#### 问题详细描述 Detailed description of the problem
运行官方replugin-sample时，当自己打包(签名打包或rebuild打debug包都试过)demo1.apk，然后该名为demo1.jar放入宿主工程assets-plugins目录下，再次点击运行宿主程序调起demo1插件报错

#### 复现问题步骤 Steps to reproduce the problem
1. 当自己打包(签名打包或rebuild打debug包都试过)demo1.apk
2. 然后该名为demo1.jar放入宿主工程assets-plugins目录下
3.再次点击运行宿主程序调起demo1插件报错

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:com.qihoo360.replugin:  replugin-host-gradle:2.3.4/com.android.tools.build:gradle:3.5.4
rePlugin-plugin-lib/gradle Version:  com.qihoo360.replugin:replugin-plugin-gradle:2.3.4'/'com.android.tools.build:gradle:3.5.4'

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
华为JLH-AN00&天玑900

#### Logcat上下文 Logcat context
2022-05-25 17:32:32.062 4260-4349/com.qihoo360.replugin.sample.host E/gin.sample.hos: [HOTFIX][Report]Bind hotfix monitor service fail!
2022-05-25 17:32:32.577 4260-4260/com.qihoo360.replugin.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qihoo360.replugin.sample.host, PID: 4260
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS0}: android.view.InflateException: Binary XML file line #17 in com.qihoo360.replugin.sample.host:animator/fragment_fade_exit: Binary XML file line #17 in com.qihoo360.replugin.sample.host:animator/fragment_fade_exit: Error inflating class objectAnimator
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4087)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4295)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:93)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2532)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:8731)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:613)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1085)
     Caused by: android.view.InflateException: Binary XML file line #17 in com.qihoo360.replugin.sample.host:animator/fragment_fade_exit: Binary XML file line #17 in com.qihoo360.replugin.sample.host:animator/fragment_fade_exit: Error inflating class objectAnimator
     Caused by: android.view.InflateException: Binary XML file line #17 in com.qihoo360.replugin.sample.host:animator/fragment_fade_exit: Error inflating class objectAnimator
     Caused by: java.lang.ClassNotFoundException: android.view.objectAnimator
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.view.LayoutInflater.createView(LayoutInflater.java:823)
        at android.view.LayoutInflater.createView(LayoutInflater.java:784)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:921)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
        at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:103)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:938)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:958)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1012)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:969)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:667)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:561)
        at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:357)
        at android.app.Activity.setContentView(Activity.java:3618)
        at com.qihoo360.replugin.sample.demo1.MainActivity.onCreate(MainActivity.java:75)
        at android.app.Activity.performCreate(Activity.java:8358)
        at android.app.Activity.performCreate(Activity.java:8341)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1323)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4058)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4295)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:93)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2532)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:228)
2022-05-25 17:32:32.577 4260-4260/com.qihoo360.replugin.sample.host E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:8731)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:613)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1085)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.objectAnimator" on path: DexPathList[[zip file "/data/app/~~Dx98DS0np6tYfcL90Q8jMw==/com.qihoo360.replugin.sample.host-wrUOC-EfBk2M5EQuXv49Hg==/base.apk"],nativeLibraryDirectories=[/data/app/~~Dx98DS0np6tYfcL90Q8jMw==/com.qihoo360.replugin.sample.host-wrUOC-EfBk2M5EQuXv49Hg==/lib/arm64, /system/lib64, /hw_product/lib64, /system_ext/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:172)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:163)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 33 more

**Comment by BinarySatan** [comment]
相同问题，解决了吗?

**Comment by heweimxcz** [comment]
> 相同问题，解决了吗?

这个是啥原因来着
