### ISSUE TITLE
华为mate50，鸿蒙系统，使用replugin，包含EditText的Activity，在点击EditText的时候直接崩溃

### ISSUE THREAD

**Issue by bdxtx** [Qihoo360/RePlugin#1043]
#### 问题详细描述 Detailed description of the problem
华为mate50，鸿蒙系统，使用replugin，包含EditText的Activity，在点击EditText的时候直接崩溃

#### 复现问题步骤 Steps to reproduce the problem
1. 华为mate50，鸿蒙系统，使用replugin，包含EditText的Activity，在点击EditText的时候直接崩溃
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bdxtx** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.content.res.Resources.getDrawable(int, android.content.res.Resources$Theme)' on a null object reference
        at com.qihoo360.replugin.loader.PluginResource.getDrawable(PluginResource.java:205)
        at android.content.Context.getDrawable(Context.java:753)
        at android.widget.TextView.getTextSelectHandle(TextView.java:3812)
        at android.widget.Editor.loadHandleDrawables(Editor.java:9324)
        at android.widget.Editor$InsertionPointCursorController.getHandle(Editor.java:8546)
        at android.widget.Editor.updateCursorPosition(Editor.java:2677)
        at android.widget.TextView.getUpdatedHighlightPath(TextView.java:8103)
        at android.widget.TextView.onDraw(TextView.java:8294)
        at android.view.View.draw(View.java:23345)
        at android.view.View.updateDisplayListIfDirty(View.java:22179)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
        at android.view.View.updateDisplayListIfDirty(View.java:22123)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
        at android.view.View.updateDisplayListIfDirty(View.java:22123)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
        at android.view.View.updateDisplayListIfDirty(View.java:22123)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
        at android.view.View.updateDisplayListIfDirty(View.java:22123)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
        at android.view.View.updateDisplayListIfDirty(View.java:22123)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
        at android.view.View.updateDisplayListIfDirty(View.java:22123)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
        at android.view.View.updateDisplayListIfDirty(View.java:22123)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
        at android.view.View.updateDisplayListIfDirty(View.java:22123)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
        at android.view.View.updateDisplayListIfDirty(View.java:22123)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:549)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:555)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:641)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:5589)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5317)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4339)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2812)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10547)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1115)
        at android.view.Choreographer.doFrame(Choreographer.java:1004)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1362)
        at android.os.Handler.handleCallback(Handler.java:966)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:293)
        at android.app.ActivityThread.main(ActivityThread.java:9478)
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by krubo** [comment]
用的哪个版本的replugin？

**Comment by krubo** [comment]
最新版本已解决
