### ISSUE TITLE
The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's

### ISSUE THREAD

**Issue by junyao-yu** [Qihoo360/RePlugin#1048]
#### 问题详细描述 Detailed description of the problem
打开插件黑屏，然后后台一直在输出日志

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:3.0.0
rePlugin-plugin-lib/gradle Version:3.0.0

Android API Version：12
Android 手机型号&ROM(Phone model & ROM): OPPO Find X3 

#### Logcat上下文 Logcat context

2022-11-08 19:04:51.149 6922-6922/com.dada.test360plugin D/RePlugin.ws001: activity create before: com.xxx.home.splash.ActivityNewWelcome this=227017063 taskid=317
2022-11-08 19:04:51.149 6922-6922/com.dada.test360plugin W/a.test360plugi: Accessing hidden method Landroid/view/ContextThemeWrapper;->getThemeResId()I (unsupported, reflection, allowed)
2022-11-08 19:04:51.149 6922-6922/com.dada.test360plugin D/RePlugin.theme: defaultThemeId = 2131689861
2022-11-08 19:04:51.149 6922-6922/com.dada.test360plugin D/RePlugin.theme: dynamicThemeId = 2131689861
2022-11-08 19:04:51.149 6922-6922/com.dada.test360plugin D/RePlugin.theme: manifestThemeId = 2131952063
2022-11-08 19:04:51.149 6922-6922/com.dada.test360plugin D/RePlugin.theme: themeId = 2131952063
2022-11-08 19:04:51.150 6922-6922/com.dada.test360plugin I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
2022-11-08 19:04:51.151 6922-6922/com.dada.test360plugin E/MultiApp.Impl: OplusMultiAppImpl
2022-11-08 19:04:51.151 6922-6922/com.dada.test360plugin D/AppCompatDelegate: Exception while getting ActivityInfo
    android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.dada.test360plugin/com.xxx.home.splash.ActivityNewWelcome}
        at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:536)
        at androidx.appcompat.app.AppCompatDelegateImpl.isActivityManifestHandlingUiMode(AppCompatDelegateImpl.java:2649)
        at androidx.appcompat.app.AppCompatDelegateImpl.updateForNightMode(AppCompatDelegateImpl.java:2499)
        at androidx.appcompat.app.AppCompatDelegateImpl.applyDayNight(AppCompatDelegateImpl.java:2374)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:494)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:114)
        at com.qihoo360.replugin.loader.a.PluginAppCompatXActivity.onCreate(Unknown Source:3)
        at com.tomkey.commons.base.BaseActivity.onCreate(BaseActivity.kt:54)
        at com.tomkey.commons.base.ToolbarActivity.onCreate(ToolbarActivity.kt:46)
        at com.xxx.common.base.ImdadaActivity.onCreate(ImdadaActivity.kt:153)
        at com.xxx.home.splash.ActivityNewWelcome.onCreate(ActivityNewWelcome.java:132)
        at android.app.Activity.performCreate(Activity.java:8145)
        at android.app.Activity.performCreate(Activity.java:8125)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3750)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3943)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2348)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8191)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by hejinyin273** [comment]
我也遇到了这个问题，有大神知道怎么解决吗，出现这个问题后，在Activity页面的LiveData的状态监听不到

**Comment by junyao-yu** [comment]
> 我也遇到了这个问题，有大神知道怎么解决吗，出现这个问题后，在Activity页面的LiveData的状态监听不到

这个报错不是本质原因，得找根源。
