### ISSUE TITLE
配置插件RePlugin.App.attachBaseContext(this);报错

### ISSUE THREAD

**Issue by Guanxxw** [Qihoo360/RePlugin#1056]
#### 问题详细描述 Detailed description of the problem

配置插件RePlugin.App.attachBaseContext(this); 时提示java.lang.ExceptionInInitializerError

#### 复现问题步骤 Steps to reproduce the problem
1. 按照文档配置最后一步时
2. 运行报错

#### 其它重要信息 Other important information
配置插件RePlugin.App.attachBaseContext(this); 时提示java.lang.ExceptionInInitializerError

replugin-host-lib/gradle Version:提示java.lang.ExceptionInInitializerError
rePlugin-plugin-lib/gradle Version:提示java.lang.ExceptionInInitializerError

Android API Version：api9
Android 手机型号&ROM(Phone model & ROM): 华为p20

#### Logcat上下文 Logcat context
FATAL EXCEPTION: main
Process: com.qihoo360.replugin.sample.host, PID: 8735
java.lang.ExceptionInInitializerError
at com.qihoo360.replugin.base.IPC.init(IPC.java:60)
at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:967)
at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)
at com.ubtech.sweepingrobot.Myapplication.attachBaseContext(Myapplication.java:22)
at android.app.Application.attach(Application.java:364)
at android.app.Instrumentation.newApplication(Instrumentation.java:1233)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1487)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1424)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7204)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
[logfile.log](https://github.com/Qihoo360/RePlugin/files/10952937/logfile.log)

**Comment by veryluckyhsy** [comment]
你好，请问解决了吗

**Comment by chengang151** [comment]
同问，问题解决了么
