### ISSUE TITLE
在host中设置useOccupyLand=true，采用RePlugin.startActivity跳转到Plugin activity时提示下面错误，但是设置成false后可以跳转，无法横屏。

### ISSUE THREAD

**Issue by zangzhang00** [Qihoo360/RePlugin#1076]
FATAL EXCEPTION: main
Process: com.jingdiao.jdsoft_iip_and, PID: 20601
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.jingdiao.jdsoft_iip_and/com.jingdiao.jdsoft_iip_and.loader.a.ActivityN1LANDNRNTS0}; have you declared this activity in your AndroidManifest.xml?
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2056)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
 at android.app.Activity.startActivityForResult(Activity.java:5192)
 at android.app.Activity.startActivityForResult(Activity.java:5150)
 at android.app.Activity.startActivity(Activity.java:5521)
 at android.app.Activity.startActivity(Activity.java:5489)
 at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:298)
 at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
 at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
 at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:249)
 at business.FunctionAdapter$1.onClick(FunctionAdapter.java:76)
 at android.view.View.performClick(View.java:7146)
 at android.view.View.performClickInternal(View.java:7119)
 at android.view.View.access$3500(View.java:803)
 at android.view.View$PerformClick.run(View.java:27533)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7386)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by ningzha** [comment]
> FATAL EXCEPTION: main Process: com.jingdiao.jdsoft_iip_and, PID: 20601 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.jingdiao.jdsoft_iip_and/com.jingdiao.jdsoft_iip_and.loader.a.ActivityN1LANDNRNTS0}; have you declared this activity in your AndroidManifest.xml? at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2056) at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716) at android.app.Activity.startActivityForResult(Activity.java:5192) at android.app.Activity.startActivityForResult(Activity.java:5150) at android.app.Activity.startActivity(Activity.java:5521) at android.app.Activity.startActivity(Activity.java:5489) at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:298) at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380) at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327) at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:249) at business.FunctionAdapter$1.onClick(FunctionAdapter.java:76) at android.view.View.performClick(View.java:7146) at android.view.View.performClickInternal(View.java:7119) at android.view.View.access$3500(View.java:803) at android.view.View$PerformClick.run(View.java:27533) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7386) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

你解决了吗？怎么解决的呢？我这也报acticity没找到
