### ISSUE TITLE
自己编译重新编译demo1后放入host的assets/plugins 再次用host启动demo1无法启动 程序崩溃

### ISSUE THREAD

**Issue by gubojun** [Qihoo360/RePlugin#116]
FATAL EXCEPTION: main
 Process: com.qihoo360.replugin.sample.host, PID: 5028
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
     at android.app.ActivityThread.-wrap12(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6119)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
     at com.qihoo360.replugin.sample.demo1.MainActivity.onCreate(MainActivity.java:191)
     at android.app.Activity.performCreate(Activity.java:6679)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:154) 
     at android.app.ActivityThread.main(ActivityThread.java:6119) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by gubojun** [comment]
原因找到了，是因为classpath 'com.android.tools.build:gradle:2.3.3' 应该使用classpath 'com.android.tools.build:gradle:2.1.3'
同时 apply plugin: 'replugin-plugin-gradle' 放到android{}后面

**Comment by qq634421026** [comment]
@gubojun 你好，你的demo1.jar 怎么生成啊

**Comment by gubojun** [comment]
@qq634421026 demo1.jar是用sample下demo1工程编译成的apk，现在已经没有问题了，之前是因为demo1的build.gradle文件配置错误产生的问题。

**Comment by ncguobiao** [comment]
![image](https://user-images.githubusercontent.com/20988969/27891699-d3ed6dbc-622d-11e7-8af6-1a49cb8cbdbd.png)

**Comment by ncguobiao** [comment]
@gubojun 为啥我放在android{}后面就报错

**Comment by lizhangqu** [comment]
请尝试运行gradle clean --stacktrace 将堆栈信息贴出，并提供插件版本号

**Comment by ncguobiao** [comment]
![image](https://user-images.githubusercontent.com/20988969/27892215-eb6bfdca-6230-11e7-914f-a1a76dbf03a1.png)
![image](https://user-images.githubusercontent.com/20988969/27892222-fb465ede-6230-11e7-9603-bde9d72ebe40.png)
![image](https://user-images.githubusercontent.com/20988969/27892226-fffb2cb6-6230-11e7-9172-0534b9b7cb2f.png)

**Comment by gubojun** [comment]
@ncguobiao classpath 'com.android.tools.build:gradle:2.1.3'  你的这个版本是2.1.3吗？我之前用高版本才报的错

**Comment by ncguobiao** [comment]
我用的 classpath 'com.android.tools.build:gradle:2.2.2' 版本

**Comment by jiongxuan** [comment]
@ncguobiao 请参考最新的Sample来看下。
