### ISSUE TITLE
经测试，5.0以下可以正常运行sample，5.0, 6.0 测试打开 点“启动demo1插件”奔溃，日志如下

### ISSUE THREAD

**Issue by lanshifu** [Qihoo360/RePlugin#121]
Process: com.qihoo360.replugin.sample.host, PID: 2201
                                                                                 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}; have you declared this activity in your AndroidManifest.xml?
                                                                                     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
                                                                                     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
                                                                                     at android.app.Activity.startActivityForResult(Activity.java:3745)
                                                                                     at android.app.Activity.startActivityForResult(Activity.java:3706)
                                                                                     at android.app.Activity.startActivity(Activity.java:4016)
                                                                                     at android.app.Activity.startActivity(Activity.java:3984)
                                                                                     at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:259)
                                                                                     at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                                                     at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                                                     at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                                                     at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java:38)
                                                                                     at android.view.View.performClick(View.java:4780)
                                                                                     at android.view.View$PerformClick.run(View.java:19866)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by EthanCo** [comment]
我也是，在魅族MX6(Android6.0)上打开插件崩溃，在Android4.4上运行正常。 

` android.content.ActivityNotFoundException: Unable to find explicit activity class {com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}; have you declared this activity in your AndroidManifest.xml?
                                                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1874)
                                                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1592)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3994)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3950)
                                                                                       at android.app.Activity.startActivity(Activity.java:4315)
                                                                                       at android.app.Activity.startActivity(Activity.java:4245)
                                                                                       at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:259)
                                                                                       at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                                                       at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                                                       at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                                                       at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java:38)
                                                                                       at android.view.View.performClick(View.java:5317)
                                                                                       at android.view.View$PerformClick.run(View.java:21648)
                                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                       at android.os.Looper.loop(Looper.java:207)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5985)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)`

**Comment by lany192** [comment]
同样的问题，求解

**Comment by tulongchao** [comment]
我也是，我在魅族max6上，小米max7上最新的系统7.0运行demo报一样的错误，我在模拟器上4.4.4版本没有问题

**Comment by BuLingzhuang** [comment]
7.0(s8)和6.0(一加2)上均boom...

**Comment by hseury** [comment]
close instant run

**Comment by sam-long-li** [comment]
你们的问题都解决了吗

**Comment by panhs** [comment]
我用的魅族mx5，第一次测试host打开插件demo1试过可以，然后增加测试升级插件的代码。 用的是Relugin.install  然后就提示找不到activity， 最后手机卸载掉 重新运行原来的apk还是提示找不到！！！！
 FATAL EXCEPTION: main
                                                   Process: com.qihoo360.replugin.sample.host, PID: 16305
                                                   android.content.ActivityNotFoundException: Unable to find explicit activity class {com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS5}; have you declared this activity in your AndroidManifest.xml?
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1842)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1566)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3830)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3787)
                                                       at android.app.Activity.startActivity(Activity.java:4139)
                                                       at android.app.Activity.startActivity(Activity.java:4069)
                                                       at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:259)
                                                       at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                       at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                       at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                       at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java:39)

**Comment by jiongxuan** [comment]
@panhs 您尝试关掉Instant Run后试试？
