### ISSUE TITLE
外置安装报错，有一个空指，用的自己的apk，内置安装没有问题

### ISSUE THREAD

**Issue by Jeremydcx** [Qihoo360/RePlugin#126]
![image](https://user-images.githubusercontent.com/16483594/27892195-cb3b6c16-6230-11e7-8c6a-95dbec2520ee.png)
![image](https://user-images.githubusercontent.com/16483594/27892211-e75e3a4a-6230-11e7-96af-80c616c270a1.png)

**Comment by maning0303** [comment]
是不是没有在插件项目的Manifest中配置版本信息：
```
     <meta-data
            android:name="com.qihoo360.plugin.name"
            android:value="plugin01"/>
        <meta-data
            android:name="com.qihoo360.plugin.version.ver"
            android:value="100"/>
```

**Comment by Jeremydcx** [comment]
加meta-data后 install 有返回信息，![image](https://user-images.githubusercontent.com/16483594/27892729-f2016d20-6233-11e7-96f4-7f039b57d301.png)
但是intent跳转时打印找不到插件
![Uploading image.png…]()

**Comment by Jeremydcx** [comment]
07-06 10:15:29.455 15883-15883/? D/RePlugin.ws001: plugin=app not found, start download ...
07-06 10:15:29.455 15883-15883/? D/RePlugin.ws001: isNeedToDownload(): V5 file not exists. Plugin = app

**Comment by aBenVip** [comment]
@Jeremydcx 需要更改一下插件的版本号试一下

**Comment by maning0303** [comment]
@Jeremydcx 你跳转插件Activity的代码怎么写的？ 看不到你的第二个图片！

**Comment by Jeremydcx** [comment]
修改了版本号也不行，安装打印是正常的。
```
07-06 10:32:10.852 19863-19863/? D/RePlugin.ws001: insert new plugin: ok: plugin=PInfo { <com.hht.terminal.hlauncher:1(4)> [APK] js={"pkgname":"com.hht.terminal.hlauncher","name":"com.hht.terminal.hlauncher","low":10,"high":10,"ver":1,"verv":2814792716779521,"path":"\/data\/user\/0\/com.qihoo360.replugin.sample.host\/app_p_a\/-780714744.jar","type":11,"frm_ver":4} dex=/data/user/0/com.qihoo360.replugin.sample.host/app_p_od/-780714744.dex nlib=/data/user/0/com.qihoo360.replugin.sample.host/app_p_n/-780714744 }
07-06 10:32:10.852 19863-19863/? D/RePlugin.ws001: PStatusC.setStatus(): Status is OK, Clear. pn=com.hht.terminal.hlauncher; ver=1
```
跳转代码应该是没问题，内置这样跳转是可以的
```
 RePlugin.startActivity(MainActivity.this, RePlugin.createIntent("app", "com.hht.terminal.hlauncher.MainActivity"));
```

**Comment by Jeremydcx** [comment]
@maning0303

**Comment by manymore13** [comment]
@Jeremydcx 你的问题解决了吗？
 PluginInfo pluginInfo = RePlugin.install(sdPath + "/plugin-demo1-debug.apk");
pluginInfo 为啥一直返回null ？sdcard有读写权限

**Comment by Jeremydcx** [comment]
@manymore13 内置可以嘛？把中间的“-”去掉试试？

**Comment by manymore13** [comment]
内置也不行，下面是日志
~~~java
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/networkbench/agent/impl/instrumentation/NBSEventTraceEngine;
                                                                                       at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java)
                                                                                       at android.view.View.performClick(View.java:5280)
                                                                                       at android.view.View$PerformClick.run(View.java:21782)
                                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                       at android.os.Looper.loop(Looper.java:207)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5966)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.networkbench.agent.impl.instrumentation.NBSEventTraceEngine" on path: DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-1/base.apk"],nativeLibraryDirectories=[/data/app/com.qihoo360.replugin.sample.host-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                       at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java) 
                                                                                       at android.view.View.performClick(View.java:5280) 
                                                                                       at android.view.View$PerformClick.run(View.java:21782) 
                                                                                       at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                       at android.os.Looper.loop(Looper.java:207) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5966) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                                   	Suppressed: java.lang.ClassNotFoundException: com.networkbench.agent.impl.instrumentation.NBSEventTraceEngine
                                                                                       at java.lang.Class.classForName(Native Method)
                                                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                       		... 11 more
                                                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
~~~

**Comment by maning0303** [comment]
@Jeremydcx 你的跳转代码有问题吧，看你之前截图PluginInfo 返回的插件信息中插件名字是你的包名com.hht...这个，你跳转应该这么写吧（createIntent第一个参数不是app吧）：
```
 RePlugin.startActivity(MainActivity.this, RePlugin.createIntent("com.hht.terminal.hlauncher", "com.hht.terminal.hlauncher.MainActivity"));
```

**Comment by Jeremydcx** [comment]
@maning0303 是的，我刚改了第一个参数后就可以了，改成com.hht.terminal.hlaunche ，这个name在哪里设置的？我的meta-data
不是这个名字
![image](https://user-images.githubusercontent.com/16483594/27894271-c25ca120-623d-11e7-8d0f-2ed19bdd4bbd.png)

**Comment by maning0303** [comment]
@Jeremydcx  你设置错了，meta-data 只能改value不能改name的（你这里把name都改了）。默认会已包名当名字！这样的：
```
     <meta-data
            android:name="com.qihoo360.plugin.name"
            android:value="app"/>
        <meta-data
            android:name="com.qihoo360.plugin.version.ver"
            android:value="100"/>
```

**Comment by Jeremydcx** [comment]
额，@maning0303  好吧，多谢指教。

**Comment by kuangye89757** [comment]
### 你好,我在用外置插件时候  RePlugin.install(path) 返回PluginInfo为null 
执行到这里时为空  插件名是plugin01
![_20170706174957](https://user-images.githubusercontent.com/15827114/27905926-21f4a412-6274-11e7-9a3b-76607810c12c.png)


这是我的插件设置
![_20170706175004](https://user-images.githubusercontent.com/15827114/27905919-1b022b02-6274-11e7-8e22-414c15307bda.png)

**Comment by Jeremydcx** [comment]
@kuangye89757  我这的打印是
![image](https://user-images.githubusercontent.com/16483594/27938248-494fdb3c-62ef-11e7-8a20-7dce830dc38b.png) 会执行2次，2次都是空嘛？确认一下你的路径是否正确

**Comment by panhs** [comment]
我也试了 该加的都加了 install返回的就是为null,

**Comment by kuangye89757** [comment]
@Jeremydcx 谢谢你的帮助,问题已经解决了  总结了一下给其他同学
[使用RePlugin时wiki上没说的一些坑.pdf](https://github.com/Qihoo360/RePlugin/files/1130553/RePlugin.wiki.pdf)

**Comment by jiongxuan** [comment]
非常感谢 @aBenVip @maning0303 的耐心解答！赞！

感谢 @kuangye89757 帮忙将您遇到的问题的解决方案，整理成文。
我已将您写的PDF内容放入“参考信息”页，供大家一起参考。

此外，关于“外置插件安装的示例”我们近期会放入Sample中。:)

**Comment by a1018875550** [comment]
外置安装需要加上读写权限，希望wiki可以加上小白少走弯路
