### ISSUE TITLE
启动插件没有反应，魅族max6

### ISSUE THREAD

**Issue by tulongchao** [Qihoo360/RePlugin#131]
public class App extends RePluginApplication {
    @Override
    public void onCreate() {
        super.onCreate();
        File file = new File(Environment.getExternalStorageDirectory().getPath() + "/app-debug.apk");
        if (file.exists()) {
            RePlugin.install(file.getPath());
        }

    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        // ======= REPLUGIN =======
        //-------------- 开发的时候不验证签名 -----------
        RePluginConfig config = new RePluginConfig();
        config.setVerifySign(!BuildConfig.DEBUG);
        RePlugin.App.attachBaseContext(this, config);
        // ========================
        // ======= REPLUGIN =======
        RePlugin.App.attachBaseContext(this);
        // ========================
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();

        // ======= REPLUGIN =======
        RePlugin.App.onLowMemory();
        // ========================
    }

    @Override
    public void onTrimMemory(int level) {
        super.onTrimMemory(level);

        // ======= REPLUGIN =======
        RePlugin.App.onTrimMemory(level);
        // ========================
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        // ======= REPLUGIN =======
        RePlugin.App.onConfigurationChanged(newConfig);
        // ========================
    }
 RePlugin.startActivity(MainActivity.this, RePlugin.createIntent("DEMO1", "com.qihoo360.replugin.sample.demo1.MainActivity"));
点击没有任何反应，插件用的你们demo1

**Comment by maning0303** [comment]
他示例中有个内置插件，你这个外置插件也用其中一个示例，会不会包名一样，导致一些问题。 RePlugin.install(file.getPath()); 这个返回值是什么呢？ 有返回值吗？

**Comment by tulongchao** [comment]
我用的是外置插件，主程序是我自己写的，file.getPath()的返回值就是插件的apk在sd卡中的位置

**Comment by tulongchao** [comment]
我就是按照你们的文档来的，我手机是魅族max6,系统6.0的

**Comment by tulongchao** [comment]
返回null,但是我这个apk在sd卡中是存在的，我权限也配置了

**Comment by maning0303** [comment]
能把Demo项目和插件项目传到github吗？我试试!

**Comment by maning0303** [comment]
我看你配置 Application 类 的时候既用了继承RePluginApplication的方式，还一起用了非继承的方式吗 ？ 不知道这两个是不是可以同时使用，你改成非继承的方式试试：
```
public class MyApplication extends Application {

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);

        // ======= REPLUGIN =======
        //-------------- 开发的时候不验证签名 -----------
        RePluginConfig config = new RePluginConfig();
        config.setVerifySign(false);
        config.setPrintDetailLog(true);
        RePlugin.App.attachBaseContext(this, config);
        // ========================
        // ========================
    }

    @Override
    public void onCreate() {
        super.onCreate();

        // ======= REPLUGIN =======
        RePlugin.App.onCreate();
        // ========================
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();

        // ======= REPLUGIN =======
        RePlugin.App.onLowMemory();
        // ========================
    }

    @Override
    public void onTrimMemory(int level) {
        super.onTrimMemory(level);

        // ======= REPLUGIN =======
        RePlugin.App.onTrimMemory(level);
        // ========================
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        // ======= REPLUGIN =======
        RePlugin.App.onConfigurationChanged(newConfig);
        // ========================
    }
}
```

**Comment by tulongchao** [comment]
https://github.com/tulongchao/RePluginDemo.git,主项目地址，插件用的是你们ddemo里面的demo1,apk是debug版的

**Comment by aBenVip** [comment]
@tulongchao 没有报错日志吗

**Comment by tulongchao** [comment]
: rpc.cam: do not modify
                                          java.lang.Throwable
                                              at com.qihoo360.replugin.RePluginConfig.checkAllowModify(RePluginConfig.java:371)
                                              at com.qihoo360.replugin.RePluginConfig.setVerifySign(RePluginConfig.java:140)
                                              at com.tfc.replugindemo.App.attachBaseContext(App.java:43)
                                              at android.app.Application.attach(Application.java:199)
                                              at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
                                              at android.app.Instrumentation.newApplication(Instrumentation.java:993)
                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:603)
                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5168)
                                              at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
                                              at android.os.Handler.dispatchMessage(Handler.java:111)
                                              at android.os.Looper.loop(Looper.java:207)
                                              at android.app.ActivityThread.main(ActivityThread.java:5985)
                                              at java.lang.reflect.Method.invoke(Native Method)
                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
07-06 16:49:02.759 32453-32453/? E/RePlugin.ws001: isPluginSignatures: unknown signature: BEA5014156EE57BC53ABD98F9819F175 package=com.qihoo360.replugin.sample.demo1
我已经设置了，不适用签名，我debug环境

**Comment by maning0303** [comment]
@tulongchao 我这边已经成功了！ 你试试这样：
```
public class App extends Application {

    private static final String TAG = "MainActivity";

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);

        // ======= REPLUGIN =======
        //-------------- 开发的时候不验证签名 -----------
        RePluginConfig config = new RePluginConfig();
        config.setVerifySign(false);
        config.setPrintDetailLog(true);
        RePlugin.App.attachBaseContext(this, config);
        // ========================
        // ========================
    }

    @Override
    public void onCreate() {
        super.onCreate();

        // ======= REPLUGIN =======
        RePlugin.App.onCreate();
        // ========================

        installPlugin();

    }

    private void installPlugin() {
        File file = new File(Environment.getExternalStorageDirectory().getPath() + "/app-debug.apk");
        if (file.exists()) {
            PluginInfo pluginInfo = RePlugin.install(file.getPath());
            if (pluginInfo != null) {
                Toast.makeText(this,pluginInfo.toString(),Toast.LENGTH_SHORT).show();
                Log.i(TAG, "pluginInfo :" + pluginInfo);
                RePlugin.preload(pluginInfo);
            } else {
                Log.i(TAG, "pluginInfo null");
            }
        }else{
            Log.i(TAG, "文件不存在");
        }
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();

        // ======= REPLUGIN =======
        RePlugin.App.onLowMemory();
        // ========================
    }

    @Override
    public void onTrimMemory(int level) {
        super.onTrimMemory(level);

        // ======= REPLUGIN =======
        RePlugin.App.onTrimMemory(level);
        // ========================
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        // ======= REPLUGIN =======
        RePlugin.App.onConfigurationChanged(newConfig);
        // ========================
    }
}
```

**Comment by maning0303** [comment]
@tulongchao 非继承和继承只能选其一吧！ 试了下不能混着来好像！

**Comment by aBenVip** [comment]
@maning0303 之前继承类型的，在attachBaseContext中设置取消签名校验，会在一个检查的方法中报错，说是不能更改已经创建的RePluginConfig

**Comment by tulongchao** [comment]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tfc.replugindemo/com.tfc.replugindemo.loader.a.ActivityN1NRNTS3}; have you declared this activity in your AndroidManifest.xml?
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1874)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1592)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3994)
                                                       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3950)
                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                       at android.app.Activity.startActivity(Activity.java:4315)
                                                       at android.app.Activity.startActivity(Activity.java:4245)
                                                       at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:259)
                                                       at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                       at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                       at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                       at com.tfc.replugindemo.MainActivity$1.onClick(MainActivity.java:18)
                                                       at android.view.View.performClick(View.java:5317)
                                                       at android.view.View$PerformClick.run(View.java:21648)
                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                       at android.os.Looper.loop(Looper.java:207)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5985)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
我打开插件报错的，这个错误有很多人反映，我在小米max上也报这个错误，但是在4.4.4的模拟器上就正常，麻烦看一下。谢谢

**Comment by maning0303** [comment]
@aBenVip 👍，我看了下日志是的，不让再修改了，不然报这个错误：
```
rpc.cam: do not modify
                                                             java.lang.Throwable
                                                                 at com.qihoo360.replugin.RePluginConfig.checkAllowModify(RePluginConfig.java:371)
                                                                 at com.qihoo360.replugin.RePluginConfig.setVerifySign(RePluginConfig.java:140)
                                                                 at com.tfc.replugindemo.App.attachBaseContext(App.java:37)
                                                                 at android.app.Application.attach(Application.java:189)
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:1011)
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:995)
                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5632)
                                                                 at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                 at android.os.Looper.loop(Looper.java:156)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by aBenVip** [comment]
@tulongchao 在Android studio中吧instart run关闭，如果开了会导致这个错误，instart run可能是导致出现此错误的一种情况，还有其他的情况，你可以先试一下，我看到区长提了修改不支持instart run的pr，估计下个版本会修复

**Comment by tulongchao** [comment]
是的关闭就可以了，谢谢
