### ISSUE TITLE
leshi x600 运行host 点击跳转至demo1按钮直接报错

### ISSUE THREAD

**Issue by manymore13** [Qihoo360/RePlugin#135]
~~~java
FATAL EXCEPTION: main
                                                                                 Process: com.qihoo360.replugin.sample.host, PID: 4062
                                                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/networkbench/agent/impl/instrumentation/NBSEventTraceEngine;
                                                                                     at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java)
                                                                                     at android.view.View.performClick(View.java:5280)
                                                                                     at android.view.View$PerformClick.run(View.java:21782)
                                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5966)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.networkbench.agent.impl.instrumentation.NBSEventTraceEngine" on path: DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-2/base.apk"],nativeLibraryDirectories=[/data/app/com.qihoo360.replugin.sample.host-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                     at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java) 
                                                                                     at android.view.View.performClick(View.java:5280) 
                                                                                     at android.view.View$PerformClick.run(View.java:21782) 
                                                                                     at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                     at android.os.Looper.loop(Looper.java:207) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5966) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                                 	Suppressed: java.lang.ClassNotFoundException: com.networkbench.agent.impl.instrumentation.NBSEventTraceEngine
                                                                                     at java.lang.Class.classForName(Native Method)
                                                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                     		... 11 more
                                                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
~~~
**RePlugin version**:
        classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.2'
        classpath 'com.qihoo360.replugin:replugin-plugin-gradle:2.1.2'
        compile 'com.qihoo360.replugin:replugin-host-lib:2.1.1'

**Android compile SDK version**:25

**Android ROM**: leshi x600

**Comment by jiongxuan** [comment]
com.networkbench.agent.impl.instrumentation.NBSEventTraceEngine。这个是您自己加的类吗？

**Comment by hseury** [comment]
close instant run
