### ISSUE TITLE
加载so报错

### ISSUE THREAD

**Issue by zzjthl** [Qihoo360/RePlugin#138]
**RePlugin version**: 2.1.2

**Android compile SDK version**: 25

**Android ROM**:7.0

使用System.loadLibrary加载so库，插件apk中只有 x86和v7a的so，插件安装独立运行无问题

07-06 21:00:18.495 31052-31052/com.pb.plugin E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.pb.plugin, PID: 31052
java.lang.UnsatisfiedLinkError: com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.pb.plugin/app_p_a/-1943406472.jar"],nativeLibraryDirectories=[/data/user/0/com.pb.plugin/app_p_n/-1943406472, /system/lib64, /vendor/lib64]]] couldn't find "libyuv.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:972)
at java.lang.System.loadLibrary(System.java:1530)
at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:629)
at net.ossrs.yasea.SrsPublisher.setEncodeHandler(SrsPublisher.java:303)
at com.partybuild.partybuildlive.MainActivity.onCreate(MainActivity.java:163)
at android.app.Activity.performCreate(Activity.java:6736)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2722)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6114)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by erhu** [comment]
This Bug is fixed, see https://github.com/Qihoo360/RePlugin/pull/156

**Comment by tokiii** [comment]
@zzjthl 你的问题解决了么
