### ISSUE TITLE
demo1中 MainActivity 添加 Toast 闪退

### ISSUE THREAD

**Issue by gunC** [Qihoo360/RePlugin#147]
**RePlugin version**: 2.1.2

**Android compile SDK version**:25

**Android ROM**:android 6.0 miui

在 demo1中 MainActivity onCreate 时,添加 Toast
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main);
        ListView lv = (ListView) findViewById(R.id.list_view);
        lv.setAdapter(new TestAdapter());


        Toast.makeText(this, "hello", Toast.LENGTH_SHORT).show();
    }

```

在 host 运行打开demo1 , 闪退
```
 android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@373cda -- permission denied for this window type
                                                                                       at android.view.ViewRootImpl.setView(ViewRootImpl.java:603)
                                                                                       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:313)
                                                                                       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
                                                                                       at com.qihoo360.loader2.PluginContext$WmWrapper.addView(PluginContext.java:183)
                                                                                       at android.widget.Toast$TN.handleShow(Toast.java:434)
                                                                                       at android.widget.Toast$TN$1.run(Toast.java:338)
                                                                                       at android.os.Handler.handleCallback(Handler.java:742)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5528)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
                                                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by jiongxuan** [comment]
您好，请先试下单品运行是否有问题（尤其注意声明的权限）。这个问题和RP并没有直接关系。

**Comment by gunC** [comment]
单品运行没问题 , 在宿主上调用就会闪退 
机型:小米Note 
系统: miui 8 开发版
其他机型还没尝试

**Comment by gunC** [comment]
更新到 v2.1.3 后没出现了
