### ISSUE TITLE
运行Demo，点击启动Demo1插件中得Fragment崩溃

### ISSUE THREAD

**Issue by VeryCure** [Qihoo360/RePlugin#148]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**: 2.1.1

**Android compile SDK version**:25.0.2

**Android ROM**:6.0

Process: com.qihoo360.replugin.sample.host, PID: 11252
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.PluginFragmentActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class fragment
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2479)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:168)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:150)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5665)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
                                                    Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class fragment
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:561)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:428)
                                                       at android.app.Activity.setContentView(Activity.java:2221)
                                                       at com.qihoo360.replugin.sample.host.PluginFragmentActivity.onCreate(PluginFragmentActivity.java:27)
                                                       at android.app.Activity.performCreate(Activity.java:6372)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:168) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5665) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
                                                    Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class fragment
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:809)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:437) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:428) 
                                                       at android.app.Activity.setContentView(Activity.java:2221) 
                                                       at com.qihoo360.replugin.sample.host.PluginFragmentActivity.onCreate(PluginFragmentActivity.java:27) 
                                                       at android.app.Activity.performCreate(Activity.java:6372) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:168) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5665) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
                                                    Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.qihoo360.replugin.sample.demo1.fragment.DemoFragment: make sure class name exists, is public, and has an empty constructor that is public
                                                       at android.app.Fragment.instantiate(Fragment.java:621)
                                                       at android.app.Fragment.instantiate(Fragment.java:585)
                                                       at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2201)
                                                       at android.app.FragmentController.onCreateView(FragmentController.java:98)
                                                       at android.app.Activity.onCreateView(Activity.java:5679)
                                                       at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:36)
                                                       at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:781)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:862) 
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:537) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:437) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:428) 
                                                       at android.app.Activity.setContentView(Activity.java:2221) 
                                                       at com.qihoo360.replugin.sample.host.PluginFragmentActivity.onCreate(PluginFragmentActivity.java:27) 
                                                       at android.app.Activity.performCreate(Activity.java:6372) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:168) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5665) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.sample.demo1.fragment.DemoFragment" on path: DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-2/base.apk"],nativeLibraryDirectories=[/data/app/com.qihoo360.replugin.sample.host-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:174)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:165)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at android.app.Fragment.instantiate(Fragment.java:607)
                                                       at android.app.Fragment.instantiate(Fragment.java:585) 
                                                       at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2201) 
                                                       at android.app.FragmentController.onCreateView(FragmentController.java:98) 
                                                       at android.app.Activity.onCreateView(Activity.java:5679) 
                                                       at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:36) 
                                                       at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:781) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:862) 
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:537) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:437) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:428) 
                                                       at android.app.Activity.setContentView(Activity.java:2221) 
                                                       at com.qihoo360.replugin.sample.host.PluginFragmentActivity.onCreate(PluginFragmentActivity.java:27) 
                                                       at android.app.Activity.performCreate(Activity.java:6372) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:168) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5665) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
                                                   	Suppressed: java.lang.ClassNotFoundException: com.qihoo360.replugin.sample.demo1.fragment.DemoFragment
                                                       at java.lang.Class.classForName(Native Method)
                                                   		at java.lang.BootClassLoader.findClass(ClassLoader

**Comment by weikano** [comment]
PluginDexClassLoader.loadClass()中super.loadClass没有catch掉exception。
jcenter里面没更新，github上的更新了。

**Comment by VeryCure** [comment]
怎么改？小白一个，谢谢

**Comment by weikano** [comment]
等jcenter上的library更新，要么就依赖github上的host-lib

**Comment by jiongxuan** [comment]
非常感谢 @weikano 解答！请稍等，我们正在全力以赴搞定新版。今晚就发布。不会让您们多等的。

感谢 @JavenCoder 帮我们解决了这个问题。

**Comment by jiongxuan** [comment]
问题已经修复。
