### ISSUE TITLE
so库仍然找不到 (问题升级) 2.1.4 host-lib  仍报错，内置jar也报错了!!!!!!!!!

### ISSUE THREAD

**Issue by tokiii** [Qihoo360/RePlugin#151]
replugin版本
host:2.1.1
plugin: 2.1.0

报错信息为：

```
07-07 17:17:22.757 8884-8884/com.lost.hostapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.lost.hostapp, PID: 8884
                                                                java.lang.UnsatisfiedLinkError: com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.lost.hostapp/app_p_a/-1383563512.jar"],nativeLibraryDirectories=[/data/user/0/com.lost.hostapp/app_p_n/-1383563512, /vendor/lib, /system/lib]]] couldn't find "libhyphenate.so"
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                    at java.lang.System.loadLibrary(System.java:1076)
                                                                    at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source)
                                                                    at com.hyphenate.chat.EMClient.getInstance(Unknown Source)
                                                                    at com.hyphenate.easeui.EaseUI.init(EaseUI.java:115)
                                                                    at com.hyphenate.easeui.ui.MainActivity.initEaseUI(MainActivity.java:163)
                                                                    at com.hyphenate.easeui.ui.MainActivity.onCreate(MainActivity.java:81)
                                                                    at android.app.Activity.performCreate(Activity.java:6366)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2667)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                    at android.os.Looper.loop(Looper.java:207)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5985)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
07-07 17:17:22.792 8884-8884/com.lost.hostapp I/Process: Sending signal. PID: 8884 SIG: 9


```

**Comment by tokiii** [comment]
好像是无法加载插件中的so库

**Comment by tokiii** [comment]
插件从apk转换成jar在导入到宿主apk中的过程中会丢失so库么？？

**Comment by jiongxuan** [comment]
问题已经修复了，很快会出一个版本来解决（host-lib 2.1.4）。敬请期待

**Comment by closedevice** [comment]
@jiongxuan so库丢失问题已经修复了?host-lib 2.14什么时候发布,急着用呢?

**Comment by tokiii** [comment]
静等修复

**Comment by tokiii** [comment]
2.14版还是同样的问题 @jiongxuan  , @closedevice 你试试看看好不好使 2.14版本的host-lib

**Comment by tokiii** [comment]
新版本内置jar 的so库都无法加载了。。。。。怎么越改越乱的感觉？？？？？

**Comment by tokiii** [comment]
这项目是黄了么。。。。

**Comment by jiongxuan** [comment]
您好。2.1.4版本已经修复了SO释放问题了。但需要确保：

1. 清除数据后再试一次
2. 32位和64位不能混用，这个是安卓加载时的问题，和RP无关

**Comment by tokiii** [comment]
@jiongxuan 您好，是否有能验证的Sample?      这个是我使用的插件[插件地址](https://github.com/tokiii/easeuiLib.git)，单独安装是可以运行的，如果与RP无关，是否单独运行都报错？

**Comment by tokiii** [comment]
这个实在Host里调用的代码：
`  RePlugin.startActivity(MainActivity.this,RePlugin.createIntent("easeplugin","com.hyphenate.easeui.ui.MainActivity"));
`

**Comment by jiongxuan** [comment]
@tokiii 请您参考今天上午我补充的这篇文章：

https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%92%E4%BB%B6%E7%9A%84%E7%BB%84%E4%BB%B6#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8so%E5%BA%93

**Comment by tokiii** [comment]
非常感谢您的回答，还特地写一篇文章出来，感谢！
