### ISSUE TITLE
自己写Demo，打开插件Fragment出现问题

### ISSUE THREAD

**Issue by VeryCure** [Qihoo360/RePlugin#152]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:
Caused by: java.lang.ClassCastException: class com.jeff.demo.repluginpatch.PluginFragment cannot be cast to android.support.v4.app.Fragment
                                                     at java.lang.Class.asSubclass(Class.java:2340)
                                                     at com.jeff.demo.repluginhost.MainActivity.initFragment(MainActivity.java:50)
                                                     at com.jeff.demo.repluginhost.MainActivity.onCreate(MainActivity.java:37)
                                                     at android.app.Activity.performCreate(Activity.java:6679)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

插件用得是v4包下得Fragment,为什么会出现这个问题呢？

**Comment by jiongxuan** [comment]
您好，您可以参考我们最新的Sample，内附关于这个“通过共享代码方式”实现Fragment的做法，您可以参考下。

**Comment by VeryCure** [comment]
@jiongxuan 试了下，还是么有解决，看了你么得更新，是对xml直接使用Fragment做了处理，代码使用没有变

**Comment by VeryCure** [comment]
@jiongxuan 把自己写的插件放到你们host里面也出现问题，感觉是插件配置或哪里出错了，请问插件需要做什么特殊声明或者什么处理，fragment.jar是什么？

**Comment by fanrenyi** [comment]
插件里面通过Provided fragment.jar， 我感觉有点不打靠谱，这就限制了插件是独立运行不了任何跟fragment相关的代码。

**Comment by wilsonssss** [comment]
如果plugin使用fragment.jar的话，开发时挺麻烦的喔，有木有plugin改动更少的做法？ @jiongxuan

**Comment by hynu605** [comment]
我在项目中extends MultiDexApplication 会出现fragment ClassCastException，extends RePluginApplication就不会

**Comment by jiongxuan** [comment]
目前正在想相对更好的解决办法，但这需要时间，且改动难度很大。还不确定时间点。

**Comment by lijunjieone** [comment]
我写了一个脚本来解决这个问题,仓库是https://github.com/lijunjieone/replugin-resolve-deps-conflict.git ,当遇到冲突的时候,通过脚本删掉冲突的文件.目前测试还算ok
