### ISSUE TITLE
Didn't find class "com.qihoo360.replugin.Entry" on path

### ISSUE THREAD

**Issue by yqjroy** [Qihoo360/RePlugin#165]
Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.bozhong.nurse/app_plugins_v3/train-10-10-47.jar"],nativeLibraryDirectories=[/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
                                                          java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.bozhong.nurse/app_plugins_v3/train-10-10-47.jar"],nativeLibraryDirectories=[/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                              at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:76)
                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                              at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:437)
                                                              at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:865)
                                                              at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:822)
                                                              at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:676)
                                                              at com.qihoo360.loader2.Plugin.load(Plugin.java:432)
                                                              at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1033)
                                                              at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1018)
                                                              at com.qihoo360.loader2.PmLocalImpl.getActivityInfo(PmLocalImpl.java:443)
                                                              at com.qihoo360.loader2.PmLocalImpl.loadPluginActivity(PmLocalImpl.java:319)
                                                              at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:230)
                                                              at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                              at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                              at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                              at com.bozhong.nurse.training.HomeTrainActivity.onClick(HomeTrainActivity.java:228)
                                                              at android.view.View.performClick(View.java:5646)
                                                              at android.view.View$PerformClick.run(View.java:22459)
                                                              at android.os.Handler.handleCallback(Handler.java:761)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:156)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
07-09 15:58:35.411 16818-16818/com.bozhong.nurse E/ws001: p.lel f train
07-09 15:58:35.411 16818-16818/com.bozhong.nurse I/RePlugin.ws001: load2 /data/user/0/com.bozhong.nurse/app_plugins_v3/train-10-10-47.jar 39356724 c=3 rc=false delta=5
07-09 15:58:35.411 16818-16818/com.bozhong.nurse E/ws001: try2: loading fail2
07-09 15:58:35.412 16818-16818/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }
07-09 15:58:35.412 16818-16818/com.bozhong.nurse I/Choreographer: Skipped 76 frames!  The application may be doing too much work on its main thread.
07-09 15:58:35.577 16894-16894/com.bozhong.nurse:GuardService I/RePlugin.ws001: load /data/user/0/com.bozhong.nurse/app_plugins_v3/train-10-10-47.jar 140885857 c=0 rc=true delta=160
07-09 15:58:35.577 16894-16894/com.bozhong.nurse:GuardService I/RePlugin.ws001: loadLocked(): Unlock! logtag = try1; pn = train
07-09 15:58:35.580 16818-19842/com.bozhong.nurse I/RePlugin.ws000: loadLocked(): Initialized, is loaded = false
07-09 15:58:35.581 16818-19842/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] [USING] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }
07-09 15:58:35.582 16818-16830/com.bozhong.nurse I/RePlugin.ws000: loadLocked(): Initialized, is loaded = false
07-09 15:58:35.583 16818-16830/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] [USING] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }
07-09 15:58:35.584 16818-19842/com.bozhong.nurse I/RePlugin.ws000: loadLocked(): Initialized, is loaded = false
07-09 15:58:35.585 16818-19842/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] [USING] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }
07-09 15:58:35.586 16818-16830/com.bozhong.nurse I/RePlugin.ws000: loadLocked(): Initialized, is loaded = false
07-09 15:58:35.587 16818-16830/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] [USING] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }
07-09 15:58:35.588 16818-19842/com.bozhong.nurse I/RePlugin.ws000: loadLocked(): Initialized, is loaded = false
07-09 15:58:35.588 16818-19842/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] [USING] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }
07-09 15:58:35.589 16818-17176/com.bozhong.nurse I/RePlugin.ws000: loadLocked(): Initialized, is loaded = false
07-09 15:58:35.590 16818-17176/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] [USING] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }
07-09 15:58:35.590 16818-19842/com.bozhong.nurse I/RePlugin.ws000: loadLocked(): Initialized, is loaded = false
07-09 15:58:35.591 16818-19842/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] [USING] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }
07-09 15:58:39.950 16818-16818/com.bozhong.nurse I/RePlugin.ws000: loadLocked(): Initialized, is loaded = false
07-09 15:58:39.952 16818-16818/com.bozhong.nurse E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <train:47(4)> [P-N] [USING] js={"pkgname":"train","ali":"train","name":"train","low":10,"high":10,"ver":47,"verv":2814792716779567,"path":"\/data\/user\/0\/com.bozhong.nurse\/app_plugins_v3\/train-10-10-47.jar","type":1,"v5type":0,"v5index":-1,"v5offset":-1,"v5length":-1,"frm_ver":4} dex=/data/user/0/com.bozhong.nurse/app_plugins_v3_odex/train-10-10-47.dex nlib=/data/user/0/com.bozhong.nurse/app_plugins_v3_libs/train-10-10-47 }
   

这是什么错呀

**Comment by jiongxuan** [comment]
请检查下您的插件是否引入了replugin-plugin-lib和replugin-plugin-gradle。详细请参见插件接入文档。

**Comment by yqjroy** [comment]
肯定引入了

**Comment by XiaYuShi17** [comment]
ava.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path、

我的也是

**Comment by byecode** [comment]
同样的问题，odex目录下面没有生成文件。不知道是不是这个原因

**Comment by winson007** [comment]
Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/data/com.vpgogo/app_plugins_v3/pluginA-10-10-100.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

同样的问题。用了demo1的工程编译也是一样，会不会和gradle版本有关系？

**Comment by jiongxuan** [comment]
@windon007 多谢提醒。您们用的Gradle版本和AS版本是？

**Comment by winson007** [comment]
我Android Studio是2.2.1， 在demo1上改了这几个东西：
compileSdkVersion 24
buildToolsVersion "24.0.3"

classpath 'com.android.tools.build:gradle:2.2.3'
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip

**Comment by zcm-hu** [comment]
我现在也也到这个问题了。

**Comment by yqjroy** [comment]
@jiongxuan  gradle-2.14.1-all.zip  as2.1.3 classpath 'com.android.tools.build:gradle:2.1.0'
如果这样 我都不知道你们360内部是怎么玩起来的

**Comment by zcm-hu** [comment]
在插件AndroidManifest里面给Activity单独配置样式后，在宿主app/build.gradle 加
repluginHostConfig {
useAppCompat = true
}
可以解决。我的弄好了

**Comment by sw950729** [comment]
同样的问题，内置和外置都这样，用的2.1.5

**Comment by yqjroy** [comment]
@jiongxuan 希望官方给个明确的回复，要怎么解决。这个问题大家都遇到了，还不是偶然的。所以如果360内部运行的没问题的，那么开源之后的这个版本大家是哪里出问题了？

**Comment by T-BayMax** [comment]
#258

**Comment by jiongxuan** [comment]
非常感谢 T-BayMax 的建议。如咱们在Q群中所述，出现这个问题很可能是因为分包导致的。

请楼上的朋友们参考 T-BayMax 的建议，应该能解决这个问题。同时我也将其同步到FAQ上，提醒后来者。
