### ISSUE TITLE
studio版本2.3.3 打开时xml文件报错

### ISSUE THREAD

**Issue by xiaobeizhaochao** [Qihoo360/RePlugin#169]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by xiaobeizhaochao** [comment]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}; have you declared this activity in your AndroidManifest.xml?
                                                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
                                                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3794)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3755)
                                                                                       at android.app.Activity.startActivity(Activity.java:4065)
                                                                                       at android.app.Activity.startActivity(Activity.java:4033)
                                                                                       at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:261)
                                                                                       at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:309)
                                                                                       at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:326)
                                                                                       at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238)
                                                                                       at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java:40)

**Comment by jiongxuan** [comment]
您好，能提供具体的信息吗？包括Logcat日志，截图等。
