### ISSUE TITLE
studio 升级到2.3.3版本后 运行demo报错

### ISSUE THREAD

**Issue by xiaobeizhaochao** [Qihoo360/RePlugin#170]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:

**Android compile SDK version**:

**Android ROM**:

**Comment by xiaobeizhaochao** [comment]
: FATAL EXCEPTION: main
                                                                                   Process: com.qihoo360.replugin.sample.host, PID: 16472
                                                                                   android.content.ActivityNotFoundException: Unable to find explicit activity class {com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}; have you declared this activity in your AndroidManifest.xml?
                                                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
                                                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3794)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3755)
                                                                                       at android.app.Activity.startActivity(Activity.java:4065)
                                                                                       at android.app.Activity.startActivity(Activity.java:4033)
                                                                                       at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:261)
                                                                                       at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:309)
                                                                                       at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:326)
                                                                                       at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238)
                                                                                       at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java:40)
                                                                                       at android.view.View.performClick(View.java:4783)
                                                                                       at android.view.View$PerformClick.run(View.java:19887)
                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by xiaobeizhaochao** [comment]
貌似和studio版本有关系

**Comment by xiaobeizhaochao** [comment]
问题 解决了 把studio的instansRun功能关闭就好了 真的好奇葩

**Comment by jiongxuan** [comment]
您依赖的host-gradle版本是多少呢？我们后来好像修复了这个问题。

**Comment by wangyupeng1-iri** [comment]
已经处理了，请等待马上将要发版的2.1.6版本
