### ISSUE TITLE
运行插件报错

### ISSUE THREAD

**Issue by LuoGuoXin** [Qihoo360/RePlugin#185]
程序异常退出
                                                                           java.lang.IllegalArgumentException: Component class com.squareup.leakcanary.internal.HeapAnalyzerService does not exist in com.qihoo360.replugin.sample.host
                                                                               at android.os.Parcel.readException(Parcel.java:1624)
                                                                               at android.os.Parcel.readException(Parcel.java:1573)
                                                                               at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:4057)
                                                                               at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:1864)
                                                                               at com.squareup.leakcanary.internal.LeakCanaryInternals.setEnabledBlocking(LeakCanaryInternals.java:83)
                                                                               at com.squareup.leakcanary.internal.LeakCanaryInternals$1.run(LeakCanaryInternals.java:72)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)

啥原因呢

**Comment by OOMROO** [comment]
我也遇到了这个问题，请问 怎么解决的哪？
