### ISSUE TITLE
插件引用第三方arr时，提示找不到资源错误

### ISSUE THREAD

**Issue by HolenZhou** [Qihoo360/RePlugin#210]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:
2.1.5
**Android compile SDK version**:
25
**Android ROM**:
红米note2  5.0.2

我新建了个插件工程PluginApp，里面引用了一个第三方开户证券的arr，单独运行pluginApp没有问题，在host中install插件可以安装成功，但是打开插件，启动插件应用的arr中的一个Activity时（不是我自己的Activity），提示找不到资源错误，请问可能是什么原因造成的啊？

com.qihoo360.replugin.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.qihoo360.replugin.sample.host, PID: 16962
                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1STNTS1}: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532)
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                       at android.os.Looper.loop(Looper.java:194)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5556)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                                    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                                       at android.content.res.Resources.getValue(Resources.java:1446)
                                                                                       at android.content.res.MiuiResources.getValue(MiuiResources.java:145)
                                                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2907)
                                                                                       at android.content.res.Resources.getLayout(Resources.java:1226)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:416)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                                       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:400)
                                                                                       at android.app.Activity.setContentView(Activity.java:2168)
                                                                                       at com.thinkive.android.ui.OpenMainActivity.onCreate(OpenMainActivity.java:46)
                                                                                       at android.app.Activity.performCreate(Activity.java:5975)
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532) 
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                       at android.os.Looper.loop(Looper.java:194) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5556) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by Recen** [comment]
+1

**Comment by wilsonssss** [comment]
Facing the same problem, anybody help?

**Comment by jiongxuan** [comment]
AAR内的Activity的基类没有替换成PluginXXXActivity，您看升级到2.1.6再试试？

**Comment by jiongxuan** [comment]
此外，2.1.7版本还会对此做进一步的处理，您可以等下，预计在本周发布。

**Comment by jiongxuan** [comment]
2.1.7已发布，应该能解决疑惑了。

**Comment by zuoqx** [comment]
@jiongxuan 2.2.3里任然存在这个问题，请问怎么解决？我是在插件里引入第三方的aar，调用aar里的Activity时候出现的问题
