### ISSUE TITLE
无法启动demo第3个PluginFragmentActivity

### ISSUE THREAD

**Issue by HarryLiu2** [Qihoo360/RePlugin#214]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:
2.1.4
**Android compile SDK version**:
6.0
**Android ROM**:
aosp

以非继承式的方式会出现如下错误（继承RePluginApplication没有问题）

FATAL EXCEPTION: main
                                                                          Process: cc.dex.com, PID: 11737
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{cc.dex.com/cc.dex.com.PluginFragmentActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class fragment
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class fragment
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                              at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
                                                                              at android.app.Activity.setContentView(Activity.java:2172)
                                                                              at cc.dex.com.PluginFragmentActivity.onCreate(PluginFragmentActivity.java:26)
                                                                              at android.app.Activity.performCreate(Activity.java:6251)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                           Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class fragment
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                              at android.app.Activity.setContentView(Activity.java:2172) 
                                                                              at cc.dex.com.PluginFragmentActivity.onCreate(PluginFragmentActivity.java:26) 
                                                                              at android.app.Activity.performCreate(Activity.java:6251) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                           Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.qihoo360.replugin.sample.demo1.fragment.DemoFragment: make sure class name exists, is public, and has an empty constructor that is public
                                                                              at android.app.Fragment.instantiate(Fragment.java:620)
                                                                              at android.app.Fragment.instantiate(Fragment.java:584)
                                                                              at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2192)
                                                                              at android.app.FragmentController.onCreateView(FragmentController.java:98)
                                                                              at android.app.Activity.onCreateView(Activity.java:5559)
                                                                              at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:34)
                                                                              at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:78)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:754)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                              at android.app.Activity.setContentView(Activity.java:2172) 
                                                                              at cc.dex.com.PluginFragmentActivity.onCreate(PluginFragmentActivity.java:26) 
                                                                              at android.app.Activity.performCreate(Activity.java:6251) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.sample.demo1.fragment.DemoFragment" on path: DexPathList[[zip file "/data/app/cc.dex.com-1/base.apk"],nativeLibraryDirectories=[/data/app/cc.dex.com-1/lib/arm, /vendor/lib, /system/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:174)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                              at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:165)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                              at android.app.Fragment.instantiate(Fragment.java:606)
                                                                              at android.app.Fragment.instantiate(Fragment.java:584) 
                                                                              at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2192) 
                                                                              at android.app.FragmentController.onCreateView(FragmentController.java:98) 
                                                                              at android.app.Activity.onCreateView(Activity.java:5559) 
                                                                              at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:34) 
                                                                              at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:78) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:754) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                              at android.app.Activity.setContentView(Activity.java:2172) 
                                                                              at cc.dex.com.PluginFragmentActivity.onCreate(PluginFragmentActivity.java:26) 
                                                                              at android.app.Activity.performCreate(Activity.java:6251) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                          	Suppressed: java.lang.ClassNotFoundException: com.qihoo360.replugin.sample.demo1.fragment.DemoFragment
                                                                              at java.lang.Class.classForName(Native Method)
                                                                              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                          		at java.lang.BootClassLoader.loadClass(ClassLoader.jav

**Comment by jiongxuan** [comment]
好的，这个我们再看看。

**Comment by jiongxuan** [comment]
您是不是没有调用setUseHostClassIfNotFound(true)方法？没有调用的话就会出这个Error，因为只有打开此开关后才会从宿主中读取Fragment等公共库
