### ISSUE TITLE
插件app好像不兼容百度地图

### ISSUE THREAD

**Issue by zSenT1100** [Qihoo360/RePlugin#226]
在开发插件app时，引用百度地图，当项目引用插件是就报错

Error:Error converting bytecode to dex:
Cause: java.lang.RuntimeException: Exception parsing classes
Error:1 error; aborting
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

当不引用插件的gradle时，可以正常运行，插件版本
 //360插件化
 classpath 'com.qihoo360.replugin:replugin-plugin-gradle:2.1.5'

**Comment by zSenT1100** [comment]
![111](https://user-images.githubusercontent.com/13899453/28308972-74cce25c-6bda-11e7-8507-91cc1ba603df.png)

**Comment by Hiram-Y** [comment]
我的的插件里有高德地图，是可以的，但是也会把高德地图jar里面的类有做替换，这个每次提交代码都得做还原操作，@jiongxuan 应该做个处理

**Comment by nwx546250** [comment]
我集成的时候也出现了问题   跑debug安装的时候
报错如下
`
Information:Gradle tasks [:app:assembleDebug]
Error:Error converting bytecode to dex:
Cause: java.lang.RuntimeException: Exception parsing classes
Error:1 error; aborting
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.


> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
Information:BUILD FAILED
Information:Total time: 25.599 secs
Information:3 errors
Information:0 warnings
Information:See complete output in console

`
跑assembleRelease的时候 出现的错误
`
Dex: Error converting bytecode to dex:
Cause: java.lang.RuntimeException: Exception parsing classes
    UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
	at com.android.dx.command.dexer.Main.processClass(Main.java:781)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:747)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:88)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1689)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:695)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:587)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:376)
	at com.android.dx.command.dexer.Main.run(Main.java:290)
	at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
	at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:174)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.dx.cf.iface.ParseException: class name (com/baidu/platform/comapi/map/A) does not match path (com/baidu/platform/comapi/map/a.class)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:520)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:793)
	at com.android.dx.command.dexer.Main.access$1600(Main.java:88)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1728)
	at com.android.dx.command.dexer.Main.processClass(Main.java:779)
	... 16 more

2 errors; aborting
:app:transformClassesWithDexForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


`

**Comment by jiongxuan** [comment]
这个问题应该和Gradle在替换百度地图的代码时出错了有关。我们会安排看下的，但需要一些时间，而且未必能快速解决。

社区的伙伴们，欢迎来挑战提PR哈！非常欢迎！

**Comment by jiongxuan** [comment]
和同事沟通了下，应该是因为Windows环境下编译时，大小写不区分导致的问题。换成Mac/Linux就没问题了。这个我们会再想想办法。

**Comment by yunTerry** [comment]
我的也是项目有使用百度地图jar包，一加入apply plugin: 'replugin-plugin-gradle'就会报错
```java
Error:Error converting bytecode to dex:
Cause: PARSE ERROR:
class name (com/baidu/platform/comapi/map/A) does not match path (com/baidu/platform/comapi/map/a.class)
...while parsing com/baidu/platform/comapi/map/a.class
```

**Comment by yunTerry** [comment]
![报错信息](https://user-images.githubusercontent.com/15991012/28451732-a6e694ce-6e21-11e7-96cc-752f95a324f3.png)

**Comment by a1018875550** [comment]
AS 3.0吧，那确实是百度地图Bug，他们说会在最新的sdk修复
http://bbs.lbsyun.baidu.com/forum.php?mod=viewthread&tid=130385&page=1#pid286724
这里有个他们发布的暂时测试版jar试试看

**Comment by yunTerry** [comment]
不是啊，我是Android Studio 2.3.3

**Comment by a1018875550** [comment]
那你先试试他们提供的jar吧；

**Comment by yunTerry** [comment]
嗯，换测试版jar不报错了

**Comment by CSDgod** [comment]
用科大讯飞的jar 同样报以上错误~ @jiongxuan @a1018875550

**Comment by jiongxuan** [comment]
@a1018875550 太赞了！解决了很多人的疑惑。这个确实是百度地图Jar包提供的不正确导致的，不过RP没有（也很难）在Win下做兼容，所以才有了这个问题。

这个Issue我们先不关。不过可能不承诺具体解决时间（因为太复杂了，涉及到改整个Gradle的流程）@a1018875550 太赞了！解决了很多人的疑惑。这个确实是百度地图Jar包提供的不正确导致的，不过RP没有（也很难）在Win下做兼容，所以才有了这个问题。

这个Issue我们先不关。不过可能不承诺具体解决时间（因为太复杂了，涉及到改整个Gradle的流程）

**Comment by zSenT1100** [comment]
试了最新的百度地图4.2.3，还是出现第一个提问的的问题

**Comment by zSenT1100** [comment]
试了最新的百度地图4.2.3，还是出现第一个提问的的问题，android studio版本是2.3.3，gradle版本是2.3.3

**Comment by zSenT1100** [comment]
试了最新的百度地图4.3.2，还是出现第一个提问的的问题，android studio版本是2.3.3，gradle版本是2.3.3

**Comment by chufengrongqing** [comment]
引用百度地图最新的jar，大小写的a.class这个问题解决了，但是初始化百度SDK “SDKInitializer.initialize(getApplicationContext());”的时候报了另一个错，是否是取不到插件的Context引起的问题？
E/ws001: l.p.a spp|aac: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
                                                                 at com.baidu.platform.comapi.util.PermissionCheck.init(Unknown Source)
                                                                 at com.baidu.platform.comapi.a.c(Unknown Source)
                                                                 at com.baidu.platform.comapi.c.a(Unknown Source)
                                                                 at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                                 at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                                 at com.mlgw.rptest.PJRPTestApplication.onCreate(PJRPTestApplication.java:20)
                                                                 at com.qihoo360.replugin.component.app.PluginApplicationClient.callOnCreate(PluginApplicationClient.java:224)
                                                                 at com.qihoo360.loader2.Plugin.callAppLocked(Plugin.java:925)
                                                                 at com.qihoo360.loader2.Plugin.callApp(Plugin.java:898)
                                                                 at com.qihoo360.loader2.Plugin.load(Plugin.java:438)
                                                                 at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1055)
                                                                 at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1040)
                                                                 at com.qihoo360.loader2.PluginCommImpl.getActivityInfo(PluginCommImpl.java:561)
                                                                 at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:411)
                                                                 at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:266)
                                                                 at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
                                                                 at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
                                                                 at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:244)
                                                                 at com.mlgw.replugin.host.MainActivity.simulateInstallExternalPlugin(MainActivity.java:187)
                                                                 at com.mlgw.replugin.host.MainActivity.access$000(MainActivity.java:40)
                                                                 at com.mlgw.replugin.host.MainActivity$5$1.run(MainActivity.java:102)
                                                                 at android.os.Handler.handleCallback(Handler.java:743)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:150)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by wardenlzr** [comment]
同遇到此问题；
我的错误信息是这样，mark 一下。
NativeLoader: found libBaiduMapSDK_base_v4_4_0.so error
art: No implementation found for int com.baidu.platform.comjni.tools.JNITools.initClass(java.lang.Object, int) (tried Java_com_baidu_platform_comjni_tools_JNITools_initClass and Java_com_baidu_platform_comjni_tools_JNITools_initClass__Ljava_lang_Object_2I)

**Comment by TongWeiLe** [comment]
Error:Error converting bytecode to dex:
Cause: java.lang.RuntimeException: Exception parsing classes
Error:1 error; aborting
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
Error:com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
Error:java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
Error:com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
Error:java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
Error:com.android.ide.common.process.ProcessException: Return code 1 for dex process

360内部没遇到过百度地图的问题吗？

**Comment by NiceW** [comment]
百度地图这行执行这行报错
SDKInitializer.initialize(getApplicationContext());
java.lang.RuntimeException: Unable to start activity ComponentInfo{host.dell.com.host/host.dell.com.host.loader.a.ActivityN1NRNTS0}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2855)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2930)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
        at com.baidu.mapsdkplatform.comapi.util.PermissionCheck.init(Unknown Source:33)
        at com.baidu.mapsdkplatform.comapi.a.c(Unknown Source:29)
        at com.baidu.mapsdkplatform.comapi.c.a(Unknown Source:35)
        at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source:0)
        at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source:1)
        at com.test.baidu.MainActivity.onCreate(MainActivity.java:92)
        at android.app.Activity.performCreate(Activity.java:7057)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2930) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6684) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by zlg2338781286** [comment]
@jiongxuan 你好，我是mac电脑在编译的时候也会出现百度地图大小写问题呢
![image](https://user-images.githubusercontent.com/8513587/46723967-a2f15900-ccab-11e8-90ce-ef1746e86869.png)
