### ISSUE TITLE
内置插件出现activity not  found 原因如下：

### ISSUE THREAD

**Issue by sw950729** [Qihoo360/RePlugin#233]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/app/com.angel.replugin-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

**Comment by jiongxuan** [comment]
您好，请上传详细的Logcat信息，这样方便定位。

**Comment by sw950729** [comment]
java.lang.ClassNotFoundException: ite
                                                             at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:107)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                             at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:437)
                                                             at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:865)
                                                             at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:822)
                                                             at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:676)
                                                             at com.qihoo360.loader2.Plugin.load(Plugin.java:432)
                                                             at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1033)
                                                             at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1018)
                                                             at com.qihoo360.loader2.PmLocalImpl.getActivityInfo(PmLocalImpl.java:454)
                                                             at com.qihoo360.loader2.PmLocalImpl.loadPluginActivity(PmLocalImpl.java:330)
                                                             at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:232)
                                                             at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:309)
                                                             at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:326)
                                                             at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238)
                                                             at com.angel.replugin.MainActivity$1.onClick(MainActivity.java:17)
                                                             at android.view.View.performClick(View.java:4438)
                                                             at android.view.View$PerformClick.run(View.java:18422)
                                                             at android.os.Handler.handleCallback(Handler.java:733)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:136)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                             at dalvik.system.NativeStart.main(Native Method)
                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                             at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:95)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:457) 
                                                             at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:437) 
                                                             at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:865) 
                                                             at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:822) 
                                                             at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:676) 
                                                             at com.qihoo360.loader2.Plugin.load(Plugin.java:432) 
                                                             at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1033) 
                                                             at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1018) 
                                                             at com.qihoo360.loader2.PmLocalImpl.getActivityInfo(PmLocalImpl.java:454) 
                                                             at com.qihoo360.loader2.PmLocalImpl.loadPluginActivity(PmLocalImpl.java:330) 
                                                             at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:232) 
                                                             at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:309) 
                                                             at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:326) 
                                                             at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238) 
                                                             at com.angel.replugin.MainActivity$1.onClick(MainActivity.java:17) 
                                                             at android.view.View.performClick(View.java:4438) 
                                                             at android.view.View$PerformClick.run(View.java:18422) 
                                                             at android.os.Handler.handleCallback(Handler.java:733) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                             at android.os.Looper.loop(Looper.java:136) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/app/com.angel.replugin-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.angel.replugin-2, /system/lib]]
                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                             at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:174)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                             at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:165)
                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                             at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:95) 
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:457) 
                                                             at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:437) 
                                                             at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:865) 
                                                             at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:822) 
                                                             at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:676) 
                                                             at com.qihoo360.loader2.Plugin.load(Plugin.java:432) 
                                                             at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1033) 
                                                             at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1018) 
                                                             at com.qihoo360.loader2.PmLocalImpl.getActivityInfo(PmLocalImpl.java:454) 
                                                             at com.qihoo360.loader2.PmLocalImpl.loadPluginActivity(PmLocalImpl.java:330) 
                                                             at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:232) 
                                                             at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:309) 
                                                             at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:326) 
                                                             at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238) 
                                                             at com.angel.replugin.MainActivity$1.onClick(MainActivity.java:17) 
                                                             at android.view.View.performClick(View.java:4438) 
                                                             at android.view.View$PerformClick.run(View.java:18422) 
                                                             at android.os.Handler.handleCallback(Handler.java:733) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                             at android.os.Looper.loop(Looper.java:136) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by jiongxuan** [comment]
请参考《插件接入指南》和FAQ中的来做，大部分是不会出现loadEntry失败的
