### ISSUE TITLE
Didn't find class "com.qihoo360.replugin.Entry" 

### ISSUE THREAD

**Issue by hanxiaofeng** [Qihoo360/RePlugin#245]
Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.coco.myapplication/app_plugins_v3/demo-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.coco.myapplication/app_plugins_v3_libs/demo-10-10-1, /vendor/lib, /system/lib]]
                                                             java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.coco.myapplication/app_plugins_v3/demo-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.coco.myapplication/app_plugins_v3_libs/demo-10-10-1, /vendor/lib, /system/lib]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                 at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:79)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                 at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:437)
                                                                 at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:865)
                                                                 at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:822)
                                                                 at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:621)
                                                                 at com.qihoo360.loader2.Plugin.load(Plugin.java:432)
                                                                 at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1033)
                                                                 at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1018)
                                                                 at com.qihoo360.loader2.PmLocalImpl.getActivityInfo(PmLocalImpl.java:454)
                                                                 at com.qihoo360.loader2.PmLocalImpl.loadPluginActivity(PmLocalImpl.java:330)
                                                                 at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:232)
                                                                 at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:309)
                                                                 at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:326)
                                                                 at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238)
                                                                 at com.coco.myapplication.MainActivity$1.onClick(MainActivity.java:19)
                                                                 at android.view.View.performClick(View.java:5207)
                                                                 at android.view.View$PerformClick.run(View.java:21177)
                                                                 at android.os.Handler.handleCallback(Handler.java:742)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5524)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
                                                             	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                 		... 25 more
                                                             		Suppressed: java.lang.ClassNotFoundException: com.qihoo360.replugin.Entry
                                                                 at java.lang.Class.classForName(Native Method)
                                                                 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                 			... 26 more
                                                              Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'com.qihoo360.replugin:replugin-host-gradle:2.1.5'

**Comment by erhu** [comment]
插件中是不是没有依赖  compile 'com.qihoo360.replugin:replugin-plugin-lib:2.1.6' 库
