### ISSUE TITLE
getIdentifier的方式获取不到资源

### ISSUE THREAD

**Issue by shibenli** [Qihoo360/RePlugin#251]
You may also want to read our [issue guide](https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%90%E5%87%BAIssue).

**RePlugin version**:2.1.5

**Android compile SDK version**:25

**Android ROM**:MiUI

我在插件中
```
 this.a = this.getContext().getPackageName();
        this.c = inflate(this.getContext(), this.getResources().getIdentifier("oliveapp_circular_count_down_progress_bar", "layout", this.a), this);
```
这种方式获取布局文件，但是获取到的layout是0。情况是这个代码是供应商的aar包，并且我也打到插件中了，而且也没有混淆。下面这是报错信息：
```
07-25 09:30:38.105 21091-21091/com.qihoo360.replugin.sample.host E/AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                                       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:201)
                                                                                       at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:91)
                                                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2123)
                                                                                       at android.content.res.Resources.getLayout(Resources.java:1129)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:428)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                       at android.view.View.inflate(View.java:20857)
                                                                                       at com.oliveapp.face.livenessdetectionviewsdk.uicomponents.CircularCountDownProgressBar.a(SourceFile:49)
                                                                                       at com.oliveapp.face.livenessdetectionviewsdk.uicomponents.CircularCountDownProgressBar.<init>(SourceFile:36)
                                                                                       	... 33 more
```

**Comment by byecode** [comment]
不能用这种方式获取id。
应该用

`  public static int getHostRes(String type,String name){
        Resources res = RePlugin.getHostContext().getResources();
        return res.getIdentifier(RePlugin.getHostContext().getPackageName()+ ":"+type+"/" + name, null, null);
    }
`

**Comment by shibenli** [comment]
@byecode ，可是我这是第三方库呢，无法修改其源代码。而且我这是资源是在插件中，并不是宿主中的，只不过是第三方aar包中这样写的

**Comment by byecode** [comment]
呃，你第三方的库为什么还要用getIdentifier来获取资源R值的？
第三方库如果完全在插件里面，直接用插件的context获取到的资源就是正确的。
一个原则：对应的Context（resource） 和 对应的R值匹配。

**Comment by shibenli** [comment]
母鸡呀，aar里面的还没有源码，完全独立

**Comment by jeozey** [comment]
有道理，很多第三方lib都是用getIdentifier方法来获取资源的，这种情况就比较麻烦

**Comment by lvtie** [comment]
oliveapp com.oliveapp.face.livenessdetectionviewsdk这是哪家公司的人脸识别啊  正在找找个公司麻烦您能否告知下

**Comment by beilly** [comment]
@lvtie 依图

**Comment by zhangbaogithub** [comment]
repluginPluginConfig {
    ignoredInjectors = ['GetIdentifierInjector']
}
我加入了这几行代码到plugin的build.gradle里面，调用getIdentifier就可以获取到resource](url) id了，你可以试一下

**Comment by weikano** [comment]
很多老的unity游戏用adt打包的时候都会去掉R文件，所以有些第三方的sdk获取资源的时候都用的getIdentifier……

**Comment by liuxu0718** [comment]
@byecode RePlugin又是什么库

**Comment by qet119** [comment]
> 不能用这种方式获取的ID。
> 应该用
> 
> ` public static int getHostRes(String type,String name){ Resources res = RePlugin.getHostContext().getResources(); return res.getIdentifier(RePlugin.getHostContext().getPackageName()+ ":"+type+"/" + name, null, null); }`

谢谢 我用你的方式解决了插件获取宿主资源 获取不到的问题，关键是我之前用的反射的方式可以获取到，但是插件apk给同事以后死活获取不到，他那边的工程是多渠道的 不知道是不是这个原因，真的坑死了
