### ISSUE TITLE
插件中 Service onCreate中  startForeground 让服务 前台运行 Service 空指针异常

### ISSUE THREAD

**Issue by liuqun567** [Qihoo360/RePlugin#254]
java.lang.NullPointerException: class name is null
        at android.content.ComponentName.<init>(ComponentName.java:114)
        at android.app.Service.startForeground(Service.java:653)
        at com.sina.news.service.DexService2.test(DexService2.java:32)
        at com.sina.news.service.DexService2.onCreate(DexService2.java:28)
        at com.qihoo360.replugin.component.service.server.PluginServiceServer.installServiceLocked(PluginServiceServer.java:419)
        at com.qihoo360.replugin.component.service.server.PluginServiceServer.access$000(PluginServiceServer.java:58)
        at com.qihoo360.replugin.component.service.server.PluginServiceServer$2.call(PluginServiceServer.java:365)
        at com.qihoo360.replugin.component.service.server.PluginServiceServer$2.call(PluginServiceServer.java:362)
        at com.qihoo360.replugin.base.ThreadUtils.syncToMainThread(ThreadUtils.java:50)
        at com.qihoo360.replugin.component.service.server.PluginServiceServer.installServiceIfNeededLocked(PluginServiceServer.jav

        at com.qihoo360.replugin.component.service.server.PluginServiceServer.startServiceLocked(PluginServiceServer.java:98)
        at com.qihoo360.replugin.component.service.server.PluginServiceServer$Stub.startService(PluginServiceServer.java:512)
        at com.qihoo360.replugin.component.service.PluginServiceClient.startService(PluginServiceClient.java:106)
        at com.qihoo360.loader2.PluginContext.startService(PluginContext.java:486)
        at android.content.ContextWrapper.startService(ContextWrapper.java:581)
        at com.sina.news.module.launch.activity.PowerOnScreen.test(PowerOnScreen.java:85)
        at com.sina.news.module.launch.activity.PowerOnScreen$1.onClick(PowerOnScreen.java:50)
        at android.view.View.performClick(View.java:5264)
        at android.view.View$PerformClick.run(View.java:21297)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5546)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

Service代码很简单：

public class DexService2 extends Service {

    public DexService2() {
        super();
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        startForeground(0, new Notification());
    }

}

**Comment by jiongxuan** [comment]
这是个已知问题，暂时不能使用startForeguard方法。

我们还有一个Service方案是可以支持的，您可以参见Factory.loadPluginService方法来试试

**Comment by zhuangzhitu** [comment]
我在Service：
  @Override
    public void onCreate() {
        super.onCreate();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
//            startForeground(1, new Notification());

        }
    }
报了同样的错误，应该如何修复？

**Comment by wogenhaosini** [comment]
这是我的代码  成功的使用了 `startForeground ` 没有报错。
```
Intent intent = new Intent();
intent.setComponent(Factory.loadPluginService(rePluginInfo.alias, rePluginInfo.ser, IPluginManager.PROCESS_AUTO));
mContext.startService(intent);
```

**Comment by 396767441** [comment]
Factory.loadPluginService这个方法是被废弃了么？没有用

**Comment by 396767441** [comment]
Intent intent = new Intent();
intent.setComponent(Factory.loadPluginService(rePluginInfo.alias, rePluginInfo.ser, IPluginManager.PROCESS_AUTO));
mContext.startService(intent);
AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.oppo.autotoolplatform.host, PID: 17693
                                                                                java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { (has extras) }

**Comment by 396767441** [comment]
使用loadPluginService返回的Component不行

**Comment by 396767441** [comment]
Log.d("StartService","pluginName:"+pluginName+"--className:"+className);
        Intent intent=new Intent();
        intent.putExtras(bundle);
        intent.setComponent(Factory.loadPluginService(pluginName, className, IPluginManager.PROCESS_AUTO));
        mContext.startService(intent);
StartService: pluginName:autotoolplatform--className:com.oppo.autotest.tools.execute.AtfRunService
ws001: l.p.p spp: null
                                                                     android.os.DeadObjectException
                                                                         at android.os.BinderProxy.transactNative(Native Method)
                                                                         at android.os.BinderProxy.transact(Binder.java:764)
                                                                         at com.qihoo360.loader2.IPluginHost$Stub$Proxy.startPluginProcess(IPluginHost.java:555)
                                                                         at com.qihoo360.loader2.MP.startPluginProcess(MP.java:425)
                                                                         at com.qihoo360.loader2.PluginCommImpl.loadPluginService(PluginCommImpl.java:483)
                                                                         at com.qihoo360.i.Factory.loadPluginService(Factory.java:353)
                                                                         at host.autotoolplatform.oppo.com.publicautotoolsdk.AutoPluginManager.loadPluginService(AutoPluginManager.java:42)
                                                                         at com.oppo.autotest.tools.execute.AtfExecute.execute(AtfExecute.java:77)
                                                                         at com.oppo.autotest.tools.model.system.monkey.MonkeyTestTool.onButtonClickTestStart(MonkeyTestTool.java:299)
                                                                         at com.oppo.autotest.tools.model.system.monkey.MonkeyTestTool.buttonClick(MonkeyTestTool.java:224)
                                                                         at com.oppo.autotest.tools.base.baseui.BaseTabToolActivity$MyButtoncliclListener.onClick(BaseTabToolActivity.java:959)
                                                                         at android.view.View.performClick(View.java:6391)
                                                                         at android.view.View$PerformClick.run(View.java:25103)
                                                                         at android.os.Handler.handleCallback(Handler.java:790)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:197)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7022)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

**Comment by liowmark** [comment]
原来正常service的启动过程中会调用attach这个函数，这个函数会给mClassName赋值
![1](https://user-images.githubusercontent.com/7448190/49851985-cbb5dc00-fe1d-11e8-9085-67bb4308f469.PNG)
RePlugin启动的过程中忽略了这一步,直接就调用onCreate函数，导致以上问题
![image](https://user-images.githubusercontent.com/7448190/49852087-15062b80-fe1e-11e8-8f3a-9061bc24a0c5.png)
attach函数是不对外暴露的，建议用反射调用修正下
![image](https://user-images.githubusercontent.com/7448190/49852231-834aee00-fe1e-11e8-9196-6b715f3c71b9.png)

**Comment by chinaShawn** [comment]
startForeground 这个函数现在还是不支持吗？现在target升级之后，基本都需要调用这个方法了。

**Comment by yylyingy** [comment]
> 原来正常service的启动过程中会调用attach这个函数，这个函数会给mClassName赋值
> ![1](https://user-images.githubusercontent.com/7448190/49851985-cbb5dc00-fe1d-11e8-9085-67bb4308f469.PNG)
> RePlugin启动的过程中忽略了这一步,直接就调用onCreate函数，导致以上问题
> ![image](https://user-images.githubusercontent.com/7448190/49852087-15062b80-fe1e-11e8-8f3a-9061bc24a0c5.png)
> attach函数
> ![image](https://user-images.githubusercontent.com/7448190/49852231-834aee00-fe1e-11e8-9196-6b715f3c71b9.png)

因为这个方法是@hide方法，9.0系统以上不允许用户api调用，所以RePlugin没有调用这个

**Comment by lioilwin** [comment]
> > 原来正常service的启动过程中会调用attach这个函数，这个函数会给mClassName赋值
> > ![1](https://user-images.githubusercontent.com/7448190/49851985-cbb5dc00-fe1d-11e8-9085-67bb4308f469.PNG)
> > RePlugin启动的过程中忽略了这一步,直接就调用onCreate函数，导致以上问题
> > ![image](https://user-images.githubusercontent.com/7448190/49852087-15062b80-fe1e-11e8-8f3a-9061bc24a0c5.png)
> > attach函数
> > ![image](https://user-images.githubusercontent.com/7448190/49852231-834aee00-fe1e-11e8-9196-6b715f3c71b9.png)
> 
> 因为这个方法是@hide方法，9.0系统以上不允许用户api调用，所以RePlugin没有调用这个

@yylyingy 
请问怎么解决这个问题，RePlugin确定无法使用前台服务吗
还有一个问题: Service.stopSelf() 失效

**Comment by jianiuqi** [comment]
@jiongxuan @lioilwin startForeguard无法使用和stopSelf()方法失效的问题可有替代方案

**Comment by qq2748** [comment]
干得漂亮

**Comment by wangqiancoder** [comment]
// 获取当前进程的坑位service
public Service getPitServive() {
        try {
            Class pluginPitServiceClass = Class.forName("com.qihoo360.replugin.component.service.server.PluginPitService");
            Method method = pluginPitServiceClass.getDeclaredMethod("get");
            method.setAccessible(true);
            Service service = (Service) method.invoke(null);
            return service;
        }catch (Exception e){
            e.printStackTrace();
        }
        return null;
    }
   // 用坑位service调用startForeground
    Service service =  getPitServive();
        if(service != null){
            service.startForeground(0,new Notification());
        }

**Comment by wangqiancoder** [comment]
// 获取当前进程的坑位service
public Service getPitServive() {
try {
Class pluginPitServiceClass = Class.forName("com.qihoo360.replugin.component.service.server.PluginPitService");
Method method = pluginPitServiceClass.getDeclaredMethod("get");
method.setAccessible(true);
Service service = (Service) method.invoke(null);
return service;
}catch (Exception e){
e.printStackTrace();
}
return null;
}
// 用坑位service调用startForeground
Service service = getPitServive();
if(service != null){
service.startForeground(0,new Notification());
}

**Comment by wangqiancoder** [comment]
// 获取当前进程的坑位service
public Service getPitService() {
try {
Class pluginPitServiceClass = Class.forName("com.qihoo360.replugin.component.service.server.PluginPitService");
Method method = pluginPitServiceClass.getDeclaredMethod("get");
method.setAccessible(true);
Service service = (Service) method.invoke(null);
return service;
}catch (Exception e){
e.printStackTrace();
}
return null;
}
// 用坑位service调用startForeground
Service service = getPitService();
if(service != null){
service.startForeground(0,new Notification());
}
研究代码发现，插件中同一个进程的所有的service都共用一个坑位的，所以使用这种方法，插件中的所有service都是前台服务了

**Comment by 13121221** [comment]
有人有方法解决插件不能启动前台服务的问题了吗

**Comment by Spider-007** [comment]
时隔三年，该问题还是存在

**Comment by Spider-007** [comment]
截至到目前，3.1.0最新的代码依然不支持前台service
Replugin的相关源码如下：installServiceLocked 
```
  private boolean installServiceLocked(ServiceRecord sr) {
        // 通过ServiceInfo创建Service对象
        Context plgc = Factory.queryPluginContext(sr.plugin);
        if (plgc == null) {
            if (LogDebug.LOG) {
                Log.e(TAG, "installServiceLocked(): Fetch Context Error! pn=" + sr.plugin);
            }
            return false;
        }
        ClassLoader cl = plgc.getClassLoader();
        if (cl == null) {
            if (LOGR) {
                LogRelease.e(PLUGIN_TAG, "psm.is: cl n " + sr.className);
            }
            return false;
        }

        // 构建Service对象
        Service s;
        try {
            s = (Service) cl.loadClass(sr.serviceInfo.name).newInstance();
        } catch (Throwable e) {
            if (LOGR) {
                LogRelease.e(TAG, "isl: ni f " + sr.plugin, e);
            }
            return false;
        }

        // 只复写Context，别的都不做
        try {
            attachBaseContextLocked(s, plgc);
        } catch (Throwable e) {
            if (LOGR) {
                LogRelease.e(PLUGIN_TAG, "psm.is: abc e", e);
            }
            return false;
        }
        s.onCreate();
        sr.service = s;

        // 开启“坑位”服务，防止进程被杀
        ComponentName pitCN = getPitComponentName();
        sr.pitComponentName = pitCN;
        startPitService(pitCN);
        return true;
    }
```
目前该插件很多漏洞暂未修复
