### ISSUE TITLE
 Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[dex file 

### ISSUE THREAD

**Issue by sw950729** [Qihoo360/RePlugin#262]
Calling the loadClass method failed (InvocationTargetException)
                                                           java.lang.ClassNotFoundException: Calling the loadClass method failed (InvocationTargetException)
                                                               at com.qihoo360.replugin.PluginDexClassLoader.loadClassFromHost(PluginDexClassLoader.java:122)
                                                               at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:95)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                               at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:436)
                                                               at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:864)
                                                               at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:821)
                                                               at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:675)
                                                               at com.qihoo360.loader2.Plugin.load(Plugin.java:431)
                                                               at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1045)
                                                               at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1030)
                                                               at com.qihoo360.loader2.PluginCommImpl.getActivityInfo(PluginCommImpl.java:561)
                                                               at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:411)
                                                               at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:266)
                                                               at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
                                                               at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
                                                               at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238)
                                                               at com.angel.replugin.MainActivity$1.onClick(MainActivity.java:17)
                                                               at android.view.View.performClick(View.java:5155)
                                                               at android.view.View$PerformClick.run(View.java:20747)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:145)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5835)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.qihoo360.replugin.PluginDexClassLoader.loadClassFromHost(PluginDexClassLoader.java:112)
                                                               at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:95) 
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469) 
                                                               at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:436) 
                                                               at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:864) 
                                                               at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:821) 
                                                               at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:675) 
                                                               at com.qihoo360.loader2.Plugin.load(Plugin.java:431) 
                                                               at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1045) 
                                                               at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1030) 
                                                               at com.qihoo360.loader2.PluginCommImpl.getActivityInfo(PluginCommImpl.java:561) 
                                                               at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:411) 
                                                               at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:266) 
                                                               at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380) 
                                                               at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327) 
                                                               at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238) 
                                                               at com.angel.replugin.MainActivity$1.onClick(MainActivity.java:17) 
                                                               at android.view.View.performClick(View.java:5155) 
                                                               at android.view.View$PerformClick.run(View.java:20747) 
                                                               at android.os.Handler.handleCallback(Handler.java:739) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                               at android.os.Looper.loop(Looper.java:145) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5835) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/app/com.angel.replugin-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                               at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:172)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                               at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:163)
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                               at com.qihoo360.replugin.PluginDexClassLoader.loadClassFromHost(PluginDexClassLoader.java:112) 
                                                               at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:95) 
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469) 
                                                               at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:436) 
                                                               at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:864) 
                                                               at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:821) 
                                                               at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:675) 
                                                               at com.qihoo360.loader2.Plugin.load(Plugin.java:431) 
                                                               at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1045) 
                                                               at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1030) 
                                                               at com.qihoo360.loader2.PluginCommImpl.getActivityInfo(PluginCommImpl.java:561) 
                                                               at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:411) 
                                                               at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:266) 
                                                               at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380) 
                                                               at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327) 
                                                               at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:238) 
                                                               at com.angel.replugin.MainActivity$1.onClick(MainActivity.java:17) 
                                                               at android.view.View.performClick(View.java:5155) 
                                                               at android.view.View$PerformClick.run(View.java:20747) 
                                                               at android.os.Handler.handleCallback(Handler.java:739) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                               at android.os.Looper.loop(Looper.java:145) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5835) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
                                                           	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-support-annotations-25.3.0_baf68660beeaa2a45a40e2532bc78635fc44fb36-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.angel.replugin/files/instant-run/dex/slice-com.qihoo360.replugin-replugin-host-lib-2.1.6_c667e9b21089ac75
07-27 13:22:53.306 20494-20494/com.angel.replugin E/ws001: p.lel f demo

**Comment by duning1204** [comment]
插件app需要build apk或者直接打出签名包，不用用build/outputs/apks/xxx.apk，否则肯定会报这个错误

**Comment by duning1204** [comment]
插件app需要build apk或者直接打出签名包，不用用build/outputs/apks/xxx.apk，否则肯定会报这个错误

**Comment by jiongxuan** [comment]
感谢 @duning1204 的解答。

或者可以尝试下关闭Instant Run后再试试
