### ISSUE TITLE
外置插件install()成功，但是startActivity()崩溃

### ISSUE THREAD

**Issue by arshcaria** [Qihoo360/RePlugin#289]
> **RePlugin version**: 2.1.7
> 
> **Android compile SDK version**:  25
> 
> **Android ROM**: Android 7.1 Emulator / Android 7.0 MIUI 8.0 Xiaomi 5

`RePlugin.install()`运行成功获得 `PluginInfo`。
但是调用`RePlugin.startActivity()`时崩溃：

```
FATAL EXCEPTION: main
Process: io.jiaqi.replugindemo, PID: 4612
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.jiaqi.replugindemo/io.jiaqi.replugindemo.loader.a.ActivityN1NRNTS2}: java.lang.ClassCastException: android.support.v7.widget.ActionBarOverlayLayout cannot be cast to android.support.v7.widget.DecorContentParent
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
 Caused by: java.lang.ClassCastException: android.support.v7.widget.ActionBarOverlayLayout cannot be cast to android.support.v7.widget.DecorContentParent
    at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:414)
    at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
    at io.jiaqi.aeoplugin.AeoPluginActivity.onCreate(AeoPluginActivity.java:11)
    at android.app.Activity.performCreate(Activity.java:6679)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6119) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

其中提到
```
java.lang.ClassCastException: android.support.v7.widget.ActionBarOverlayLayout cannot be cast to android.support.v7.widget.DecorContentParent
```
不明白是宿主或插件哪里配置错了？

**Comment by wangfuda** [comment]
你是不是宿主compile了v7包，插件也compile了v7包。这样因为class的classloader不同，class是无法cast的。
你可以插件中provided v7包（抽离了jar出来的包），宿主compile，并设c.setUseHostClassIfNotFound(true);
更多请阅读FAQ和sample代码。

**Comment by arshcaria** [comment]
找到原因了，我之前没有在plugin module的`build.gradle`中加上下面这些：
```
repluginPluginConfig {
    pluginName = "demo1"
    hostApplicationId = "io.jiaqi.replugindemo"
    hostAppLauncherActivity = "io.jiaqi.replugindemo.MainActivity"
}
```

**Comment by danjuan** [comment]
repluginPluginConfig {
    pluginName = "demo1"
    hostApplicationId = "io.jiaqi.replugindemo"
    hostAppLauncherActivity = "io.jiaqi.replugindemo.MainActivity"
}

如果每个插件都这样配置，是不是就意味着，不同的马甲包宿主没有办法公用一个插件

**Comment by CTO1987** [comment]
我解决了，在内置插件把AppCompatActivity改成PluginAppCompatActivity就好了！~
