### ISSUE TITLE
宿主调用插件出现ClassNotFoundException

### ISSUE THREAD

**Issue by VipMinF** [Qihoo360/RePlugin#306]
#### 问题详细描述 Detailed description of the problem
我在插件中集成了贝宝支付 在宿主中加载，然后在宿主中跳转到插件我自己写的一个Activity，这个Activity然后跳到贝宝支付的Activity（账号界面），然后贝宝支付跳转自己另一个界面 就出现这个异常
#### 复现问题步骤 Steps to reproduce the problem
1. 宿主跳转到插件
2. 插件启动第三方sdk
3.第三方sdk正常执行其内部逻辑时出现异常

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.1.7
rePlugin-plugin-lib/gradle Version:.2.1.7

Android API Version：23
Android 手机型号&ROM(Phone model & ROM): 所有机型

#### Logcat上下文 Logcat context

     java.lang.ClassNotFoundException: com.paypal.android.sdk.payments.PayPalPayment
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2405)
                                             at android.os.Parcel.readParcelable(Parcel.java:2359)
                                             at android.os.Parcel.readValue(Parcel.java:2265)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2620)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getString(BaseBundle.java:920)
                                             at android.content.Intent.getStringExtra(Intent.java:6228)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2759)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2223)
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6666)
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6399)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4209)
                                             at android.os.Binder.execTransact(Binder.java:453)
                                          Caused by: java.lang.ClassNotFoundException: com.paypal.android.sdk.payments.PayPalPayment
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2405) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2359) 
                                             at android.os.Parcel.readValue(Parcel.java:2265) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2620) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.getString(BaseBundle.java:920) 
                                             at android.content.Intent.getStringExtra(Intent.java:6228) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2759) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2223) 
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6666) 
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6399) 
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174) 
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4209) 
                                             at android.os.Binder.execTransact(Binder.java:453)

**Comment by goodev** [comment]
由于看不到你实际的代码，从上面的log中只能做如下猜猜：

在 **然后贝宝支付跳转自己另一个界面 就出现这个异常** 执行这一步的时候， PayPal 启动了一个回调的 Activity ，然后在启动这个 Activity 中包含了一些数据（.Intent.getExtra），这些数据中有个 com.paypal.android.sdk.payments.PayPalPayment Parcelable 对象，但是在你的回调 Activity 中找不到 com.paypal.android.sdk.payments.PayPalPayment 这个类所以导致解析数据失败抛出异常。

估计你的回调 Activity 在宿主app中，而PayPal 库位于插件中，这样当回调回到宿主中时候，宿主默认不加载插件的类库，所以出错。 可以尝试设置默认当类找不到的时候加载插件这个配置项看看能否解决问题。

**Comment by VipMinF** [comment]
谢谢你的回答，你的意思我大概明白。但还是有点出入，是我没有描述清楚。
背景：
1.宿主有一个Activity h1  有个充值按钮
2.插件中有一个Activity p1 这是我创建的
3.插件中集成了贝宝sdk
步骤：
1.在h1界面中 点击充值，然后调用插件中的类PayService.onPay()
2.插件中收到onPay事件后使用RePlugin.getPluginContext启动 p1 
3.p1 在 oncreate 中 使用startActivityForResult 启动贝宝sdk
4.贝宝sdk成功启动第一个界面，正当它start另一个界面时候就出现这个问题。
5.由于获取这个对象是在AMS中 ParcelableUtils也用不上
