### ISSUE TITLE
demo里的testThreadClassLoader()这个方法里抛出异常

### ISSUE THREAD

**Issue by MarkHan1213** [Qihoo360/RePlugin#308]
#### 问题详细描述 Detailed description of the problem
ClassLoader cl = Thread.currentThread().getContextClassLoader();
这个ClassLoader 不等于getClassLoader
抛出了
![image](https://user-images.githubusercontent.com/19663104/29557050-73f6938c-875a-11e7-9523-63d4610338ce.png)异常

#### 复现问题步骤 Steps to reproduce the problem
1. 拉下代码后直接运行host那个项目
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.1.7
rePlugin-plugin-lib/gradle Version: 2.1.7

Android API Version：22
Android 手机型号&ROM(Phone model & ROM): 红米3 MIUI8.5 稳定版

#### Logcat上下文 Logcat context
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.qihoo360.replugin.sample.host, PID: 2883
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.MainActivity}: java.lang.RuntimeException: Thread.current.classLoader != getClassLoader(). cl=dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]; getC=com.qihoo360.replugin.RePluginClassLoader[mBase=dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]]
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
                                                                                  Caused by: java.lang.RuntimeException: Thread.current.classLoader != getClassLoader(). cl=dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]; getC=com.qihoo360.replugin.RePluginClassLoader[mBase=dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]]]
                                                                                     at com.qihoo360.replugin.sample.host.MainActivity.testThreadClassLoader(MainActivity.java:111)
                                                                                     at com.qihoo360.replugin.sample.host.MainActivity.onCreate(MainActivity.java:103)
                                                                                     at android.app.Activity.performCreate(Activity.java:6039)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by fightingBirdCaiy** [comment]
遇到同样的问题 华为荣耀6 android4.4系统的手机

**Comment by MarkHan1213** [comment]
@fightingBirdCaiy  注释掉不让他执行这个方法就好，虽然我也不知道为什么要写那个方法，似乎没什么关系

**Comment by LNeway** [comment]
Nexus Android 5.0 同样的问题

**Comment by zhang625480** [comment]
我也遇到这个问题了

**Comment by zhang625480** [comment]
先屏蔽掉该方法吧，屏蔽后不影响使用 不清楚为什么要写那个方法

**Comment by cundong** [comment]
这个方法是用来测试的。

2.1.7及以前版本，Thread.currentThread().getContextClassLoader() != RePluginClassLoader

2.1.7以后，Thread.currentThread().getContextClassLoader() == RePluginClassLoader

这个方法纯粹为了测试而存在的。
