### ISSUE TITLE
使用插件将应用打包运行后报 VerifyError

### ISSUE THREAD

**Issue by jonyChina162** [Qihoo360/RePlugin#313]
#### 问题详细描述 Detailed description of the problem
apk 可以正常运行，使用 RP 插件打包后运行后崩溃，抛出 verifyError

#### 复现问题步骤 Steps to reproduce the problem
1. 不使用 RP，构建 apk ，手机可以正常运行；
2. 添加 RP plugin 配置，打包无问题，运行报错，详情见 logcat；
3. 其中 com.facebook.AccessTokenManager 我们是作为 jar 依赖引入的；v4 依赖的是 25.2.0

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version: 2.2.0

Android API Version：24
Android 手机型号&ROM(Phone model & ROM):  FRD-AL00 

#### Logcat上下文 Logcat context
FATAL EXCEPTION: AsyncTask #1
                                                                    Process: com.snaptube.premium, PID: 6348
                                                                    java.lang.NoClassDefFoundError: com.facebook.AccessTokenManager
                                                                        at com.facebook.AccessTokenManager.getInstance(AccessTokenManager.java:81)
                                                                        at com.facebook.GraphRequest.executeConnectionAndWait(GraphRequest.java:1286)
                                                                        at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1168)
                                                                        at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1134)
                                                                        at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1118)
                                                                        at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:1093)
                                                                        at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:987)
                                                                        at com.facebook.internal.FetchedAppSettingsManager.getAppSettingsQueryResponse(FetchedAppSettingsManager.java:207)
                                                                        at com.facebook.internal.FetchedAppSettingsManager.access$100(FetchedAppSettingsManager.java:47)
                                                                        at com.facebook.internal.FetchedAppSettingsManager$1.run(FetchedAppSettingsManager.java:122)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:776)
                                                                     Caused by: java.lang.VerifyError: Verifier rejected class com.facebook.AccessTokenManager: com.facebook.AccessTokenManager com.facebook.AccessTokenManager.getInstance() failed to verify: com.facebook.AccessTokenManager com.facebook.AccessTokenManager.getInstance(): [0x1A] register v2 has type Reference: java.lang.Object but expected Precise Reference: android.support.v4.content.LocalBroadcastManager (declaration of 'com.facebook.AccessTokenManager' appears in /data/app/com.snaptube.premium-2/base.apk)
                                                                        at com.facebook.AccessTokenManager.getInstance(AccessTokenManager.java:81)
                                                                        at com.facebook.FacebookSdk$3.call(FacebookSdk.java:303)
                                                                        at com.facebook.FacebookSdk$3.call(FacebookSdk.java:300)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                        at java.lang.Thread.run(Thread.java:776)

**Comment by cundong** [comment]
看您这个日志。

应该是插件中中用了一个facebook的token，可能这个token是按照插件的信息去申请的（包名或者APK的签名），要知道，当插件运行在宿主中的时候，申请的token是需要以宿主的名义去申请的。

**Comment by luoshengbo** [comment]
你好，请问这个问题，您解决了吗

**Comment by jonyChina162** [comment]
facebook 放宿主里，插件调用宿主的方法来完成
