### ISSUE TITLE
插件中使用 android.support.v4.widget.SwipeRefreshLayout崩溃

### ISSUE THREAD

**Issue by gokuo** [Qihoo360/RePlugin#330]
#### 复现问题步骤 Steps to reproduce the problem
1. 插件中使用类 android.support.v4.widget.SwipeRefreshLayout ，会有空指针异常，且只在android 4.3手机上出现

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：android 4.3
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
09-01 06:15:18.684 E/AndroidRuntime(20009): FATAL EXCEPTION: main
09-01 06:15:18.684 E/AndroidRuntime(20009): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jd.jrapp/com.jd.jrapp.loader.a.ActivityN1NRNTS5}: android.view.InflateException: Binary XML file line #6: Error inflating mobilesafe class com.jdjr.frame.widget.refresh.MySwipeRefreshLayout
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.os.Looper.loop(Looper.java:137)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at java.lang.reflect.Method.invoke(Method.java:525)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at dalvik.system.NativeStart.main(Native Method)
09-01 06:15:18.684 E/AndroidRuntime(20009): Caused by: android.view.InflateException: Binary XML file line #6: Error inflating mobilesafe class com.jdjr.frame.widget.refresh.MySwipeRefreshLayout
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at com.qihoo360.loader2.PluginContext.handleCreateView(PluginContext.java:419)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at com.qihoo360.loader2.PluginContext.access$000(PluginContext.java:57)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at com.qihoo360.loader2.PluginContext$1.onCreateView(PluginContext.java:83)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:200)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:798)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:520)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at com.jdjr.stock.navigation.StockFragment.onCreateView(Unknown Source)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.app.Activity.performStart(Activity.java:5143)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	... 11 more
09-01 06:15:18.684 E/AndroidRuntime(20009): Caused by: java.lang.reflect.InvocationTargetException
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at java.lang.reflect.Constructor.constructNative(Native Method)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at com.qihoo360.loader2.PluginContext.handleCreateView(PluginContext.java:412)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	... 29 more
09-01 06:15:18.684 E/AndroidRuntime(20009): Caused by: java.lang.NullPointerException
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.view.View.setLayerType(View.java:12408)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.view.ViewCompatHC.setLayerType(ViewCompatHC.java:34)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.view.ViewCompat$HCViewCompatImpl.setLayerType(ViewCompat.java:1105)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.view.ViewCompat.setLayerType(ViewCompat.java:2114)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.widget.CircleImageView.<init>(CircleImageView.java:67)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.widget.SwipeRefreshLayout.createProgressView(SwipeRefreshLayout.java:344)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at android.support.v4.widget.SwipeRefreshLayout.<init>(SwipeRefreshLayout.java:317)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	at com.jdjr.frame.widget.refresh.MySwipeRefreshLayout.<init>(Unknown Source)
09-01 06:15:18.684 E/AndroidRuntime(20009): 	... 32 more
09-01 06:15:18.684 W/ActivityManager(  539):   Force finishing activity com.jd.jrapp/.loader.a.ActivityN1NRNTS5

**Comment by gokuo** [comment]
@jiongxuan

**Comment by Leeii** [comment]
你是在xml布局中使用了?attr/ 吗？

**Comment by qingyongai** [comment]
@Leeii 不能使用?attr么
