### ISSUE TITLE
关于RePlugin的疑惑

### ISSUE THREAD

**Issue by 18649851495** [Qihoo360/RePlugin#332]
#### 问题详细描述 Detailed description of the problem
1、插件中声明的权限是否全部都无效，一定要在宿主中申明？如果是的话，如果要增加权限，是不是就只能通过发版来解决
2、关于QA中的高德地图Key值使用问题，发现用宿主的包去申请Key值，仍然是提示Key非法，后来尝试把key值的申明放在宿主中，就可以找到，UMeng的Key值也是同样的问题，这一点与描述不符合
3、定义常驻进程名的问题，修改为persistentName = ":StrongService"

#### 复现问题步骤 Steps to reproduce the problem
1. Demo中是把他给注释掉了，我这边开启了，修改了名称，发现启动的时候，app直接白屏，无限打印错误日志，进程名字也一直都是：:GuardService，并没有修改
2、如果和Demo一样，注释掉就没有问题

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：24
Android 手机型号&ROM(Phone model & ROM): 小米5 MIUI

#### Logcat上下文 Logcat context
09-04 17:26:39.728 2493-2700/? E/WtProcessController: Package name:ComponentInfo{net.strongsoft.rpdemo:GuardService/net.strongsoft.rpdemo:GuardService} not found packageinfo 
09-04 17:26:39.814 13726-13726/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: net.strongsoft.rpdemo:GuardService, PID: 13726
                                                   java.lang.RuntimeException: Unable to instantiate application net.strongsoft.rpdemo.RpApplication: java.lang.NullPointerException: Attempt to read from field 'android.os.IBinder com.qihoo360.loader2.BinderCursor$BinderParcelable.mBinder' on a null object reference
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:806)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5407)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:160)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6200)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
                                                    Caused by: java.lang.NullPointerException: Attempt to read from field 'android.os.IBinder com.qihoo360.loader2.BinderCursor$BinderParcelable.mBinder' on a null object reference
                                                       at com.qihoo360.loader2.BinderCursor.getBinder(BinderCursor.java:106)
                                                       at com.qihoo360.loader2.PluginProviderStub.proxyFetchHostBinder(PluginProviderStub.java:176)
                                                       at com.qihoo360.loader2.PluginProviderStub.proxyFetchHostBinder(PluginProviderStub.java:145)
                                                       at com.qihoo360.loader2.PluginProcessMain.connectToHostSvc(PluginProcessMain.java:290)
                                                       at com.qihoo360.loader2.PmBase.initForClient(PmBase.java:312)
                                                       at com.qihoo360.loader2.PmBase.init(PmBase.java:239)
                                                       at com.qihoo360.loader2.PMF.init(PMF.java:72)
                                                       at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:968)
                                                       at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)
                                                       at net.strongsoft.rpdemo.RpApplication.attachBaseContext(RpApplication.java:21)
                                                       at android.app.Application.attach(Application.java:194)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:993)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:800)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5407) 
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:160) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6200) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764) 
09-04 17:26:39.872 578-578/? E/lowmemorykiller: Error opening /proc/13726/oom_score_adj; errno=2
09-04 17:26:39.874 13741-13741/? E/ActivityThread: Failed to find provider info for net.strongsoft.rpdemo.loader.p.main
09-04 17:26:39.875 13741-13741/? E/ws001: p.p fhb fail

**Comment by cundong** [comment]
1.是的，Android特性，想改动的话，就得动底层了，目前市面上所有插件化解决方案都是如此；
2.能详细说下么。
3.修改后，需要重新构建一次应用程序，等待新的中转Java类别生成，才能被读取到，你修改后LOG依然打印 GuardService ，就说明还未生成。

**Comment by 18649851495** [comment]
![image](https://user-images.githubusercontent.com/20705287/30042682-61620a5a-9225-11e7-8c2b-5e917ca5b586.png)
这个标签值放在插件中，读取不到，如果放在宿主中就OK了。

**Comment by cundong** [comment]
宿主只用了插件AndroidMainfext.xml中的四大组件，其他信息都是无用的，所以meta-data是需要放置到宿主的，像这种第三方SDK的申请，也应该用宿主的信息去申请。
