### ISSUE TITLE
Didn't find class "com.qihoo360.replugin.Entry"

### ISSUE THREAD

**Issue by Caibou** [Qihoo360/RePlugin#339]
#### 问题详细描述 Detailed description of the problem
Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.zhiguan.repluginsample.host/app_plugins_v3/plugin_2-10-10-85.jar"],nativeLibraryDirectories=[/data/user/0/com.zhiguan.repluginsample.host/app_plugins_v3_libs/plugin_2-10-10-85, /vendor/lib, /system/lib]]
                                                                        java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.zhiguan.repluginsample.host/app_plugins_v3/plugin_2-10-10-85.jar"],nativeLibraryDirectories=[/data/user/0/com.zhiguan.repluginsample.host/app_plugins_v3_libs/plugin_2-10-10-85, /vendor/lib, /system/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                            at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:96)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                            at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:440)
                                                                            at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:878)
                                                                            at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:835)
                                                                            at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:689)
                                                                            at com.qihoo360.loader2.Plugin.load(Plugin.java:434)
                                                                            at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1055)
                                                                            at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1040)
                                                                            at com.qihoo360.loader2.PluginCommImpl.getActivityInfo(PluginCommImpl.java:561)
                                                                            at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:411)
                                                                            at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:266)
                                                                            at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
                                                                            at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
                                                                            at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:244)
                                                                            at com.zhiguan.repluginsample.host.MainActivity$2.onClick(MainActivity.java:33)
                                                                            at android.view.View.performClick(View.java:5204)
                                                                            at android.view.View$PerformClick.run(View.java:21158)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5471)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
                                                                        	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                            		... 26 more
                                                                        		Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                            			... 27 more
                                                                        			Suppressed: java.lang.ClassNotFoundException: com.qihoo360.replugin.Entry
                                                                            at java.lang.Class.classForName(Native Method)
                                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                            				... 28 more
                                                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
09-05 15:14:54.183 23700-23700/com.zhiguan.repluginsample.host E/ws001: p.lel f plugin_2

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.0
rePlugin-plugin-lib/gradle Version: 2.2.0

Android API Version：23
Android 手机型号&ROM(Phone model & ROM):  红米NOTE 1LTE
Android Studio Version : 2.3.3
Gradle Version : 2.3.3

已经引入'com.qihoo360.replugin:replugin-plugin-lib:2.2.0'

**Comment by mjwWell** [comment]
请问怎解决的？

**Comment by mengzhe1973** [comment]
这个问题怎么解决
