### ISSUE TITLE
按音量键后插件报NullPointerException

### ISSUE THREAD

**Issue by garylzb** [Qihoo360/RePlugin#346]
#### 问题详细描述 Detailed description of the problem
遇到的一个适配问题，在几个三星系列的机子上都有收集到崩溃日志。另外在360手机卫士(360MobileSafe_7.7.2.1029.apk)上也复现了这个问题。

宿主配置：
compileSdkVersion 21
buildToolsVersion "26.0.1"
minSdkVersion 18
targetSdkVersion 21

compile fileTree(include: ['*.jar'], dir: 'libs')
compile 'com.android.support:support-v4:21.0.0'
compile 'com.android.support:recyclerview-v7:21.0.0'
compile 'org.greenrobot:eventbus:3.0.0'
compile 'com.nineoldandroids:library:2.4.0'
compile 'com.google.code.gson:gson:2.2.4'
compile 'com.qihoo360.replugin:replugin-host-lib:2.2.0'

插件配置：
compileSdkVersion 21
buildToolsVersion "26.0.1"
minSdkVersion 18
targetSdkVersion 21

compile fileTree(include: ['*.jar'], dir: 'libs')
compile 'com.android.support:support-v4:21.0.0'
compile 'com.android.support:recyclerview-v7:21.0.0'
compile 'org.greenrobot:eventbus:3.0.0'
compile 'com.nineoldandroids:library:2.4.0'
compile 'com.google.code.gson:gson:2.2.4'
compile 'com.qihoo360.replugin:replugin-plugin-lib:2.2.0'

#### 复现问题步骤 Steps to reproduce the problem
1. 进入插件页面
2. 按下音量键

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：21
Android 手机型号&ROM(Phone model & ROM): 三星 SM-J200G(5.1.1)
![device-2017-09-09-112038](https://user-images.githubusercontent.com/5510655/30236659-f83fb426-9550-11e7-8b2f-94cda2c0846c.png)

#### Logcat上下文 Logcat context

09-09 11:08:55.626 2826-2893/? D/InputReader: Input event(3): value=0 when=33514085092000
09-09 11:08:55.626 2826-2892/? D/InputDispatcher: Waiting for application to become ready for input: 6171.  Reason: Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 1.
09-09 11:08:55.631 6171-6171/? E/InputEventSender: Exception dispatching finished signal.
09-09 11:08:55.631 6171-6171/? E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-09 11:08:55.641 6171-6171/? E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to read from field 'char[] java.lang.String.value' on a null object reference
                                                       at java.lang.String.<init>(String.java:421)
                                                       at android.media.session.MediaSessionLegacyHelper.<init>(MediaSessionLegacyHelper.java:100)
                                                       at android.media.session.MediaSessionLegacyHelper.getHelper(MediaSessionLegacyHelper.java:112)
                                                       at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1949)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2629)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4918)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4873)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4482)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4539)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4515)
                                                       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4757)
                                                       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2815)
                                                       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2407)
                                                       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2398)
                                                       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2792)
                                                       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:143)
                                                       at android.os.Looper.loop(Looper.java:130)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6946)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
09-09 11:08:55.641 6171-6171/? D/AndroidRuntime: Shutting down VM
09-09 11:08:55.646 2826-4638/? D/LocationManagerService: getLastLocation: Request[POWER_LOW network requested=0 fastest=0 num=1]
09-09 11:08:55.651 2826-2920/? D/LocationManagerService: getLastLocation: Request[POWER_LOW network requested=0 fastest=0 num=1]
09-09 11:08:55.656 6171-6171/? W/ws001: NRH lcl.fc: c=com.ak.torch.engine.i.d
09-09 11:08:55.656 6171-7629/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-09 11:08:55.656 6171-7629/? I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-09 11:08:55.656 2169-2819/? D/EnterpriseController: netId is 0
09-09 11:08:55.656 2169-2819/? D/Netd: getNetworkForDns: using netid 502 for uid 10155
09-09 11:08:55.661 6171-7629/? I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-09 11:08:55.671 2826-4636/? D/LocationManagerService: getLastLocation: Request[POWER_LOW network requested=0 fastest=0 num=1]
09-09 11:08:55.671 2826-3253/? D/LocationManagerService: getLastLocation: Request[POWER_LOW network requested=0 fastest=0 num=1]
09-09 11:08:55.686 6171-6171/? E/CrashHandler: Attempt to read from field 'char[] java.lang.String.value' on a null object reference
                                               java.lang.NullPointerException: Attempt to read from field 'char[] java.lang.String.value' on a null object reference
                                                   at java.lang.String.<init>(String.java:421)
                                                   at android.media.session.MediaSessionLegacyHelper.<init>(MediaSessionLegacyHelper.java:100)
                                                   at android.media.session.MediaSessionLegacyHelper.getHelper(MediaSessionLegacyHelper.java:112)
                                                   at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1949)
                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2629)
                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4918)
                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4873)
                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4482)
                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4539)
                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4515)
                                                   at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4757)
                                                   at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2815)
                                                   at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2407)
                                                   at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2398)
                                                   at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2792)
                                                   at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                   at android.os.MessageQueue.nativePollOnce(Native Method)
                                                   at android.os.MessageQueue.next(MessageQueue.java:143)
                                                   at android.os.Looper.loop(Looper.java:130)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6946)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
09-09 11:08:55.691 6171-7631/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-09 11:08:55.691 6171-7631/? I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-09 11:08:55.691 6171-7631/? I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-09 11:08:55.691 6171-6171/? E/CrashHandler: ----------Crash Handler Print Begin----------
09-09 11:08:55.691 6171-6171/? W/System.err: java.lang.NullPointerException: Attempt to read from field 'char[] java.lang.String.value' on a null object reference
09-09 11:08:55.691 6171-6171/? W/System.err:     at java.lang.String.<init>(String.java:421)
09-09 11:08:55.691 6171-6171/? W/System.err:     at android.media.session.MediaSessionLegacyHelper.<init>(MediaSessionLegacyHelper.java:100)
09-09 11:08:55.691 6171-6171/? W/System.err:     at android.media.session.MediaSessionLegacyHelper.getHelper(MediaSessionLegacyHelper.java:112)
09-09 11:08:55.691 6171-6171/? W/System.err:     at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1949)
09-09 11:08:55.691 6171-6171/? W/System.err:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2629)
09-09 11:08:55.691 6171-6171/? W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4918)
09-09 11:08:55.691 6171-6171/? W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4873)
09-09 11:08:55.691 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4482)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4539)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4515)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4757)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2815)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2407)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2398)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2792)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:143)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.os.Looper.loop(Looper.java:130)
09-09 11:08:55.696 6171-6171/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6946)
09-09 11:08:55.696 6171-6171/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-09 11:08:55.696 6171-6171/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
09-09 11:08:55.696 6171-6171/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
09-09 11:08:55.696 6171-6171/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
09-09 11:08:55.696 6171-6171/? E/CrashHandler: ----------Crash Handler Print End----------

**Comment by cundong** [comment]
按音量向上键，崩溃的类，位置在：/frameworks/base/media/java/android/media/session/MediaSessionLegacyHelper.java

官方的Android 5.1.1 MediaSessionLegacyHelper:
![image](https://user-images.githubusercontent.com/3348483/30468560-a5790076-9a1e-11e7-89f0-1468f8c08bc6.png)

三星的5.1.1 MediaSessionLegacyHelper：
![image](https://user-images.githubusercontent.com/3348483/30468579-b96ae3ba-9a1e-11e7-83dc-4f4e6765b6d3.png)

崩溃的原因：

1、	如果当前运行的是一个插件，getApplicationInfo()返回的是插件的ApplicationInfo，即通过PackageManager的getPackageArchiveInfo接口返回得来的，如果插件的<application标签中不填写android:process属性，getPackageArchiveInfo.process就是NULL(官方API就是如此设计的)。
![image](https://user-images.githubusercontent.com/3348483/30468665-1ed27632-9a1f-11e7-9606-ad2a10533915.png)

2、三星5.0，5.1.1 ROM改了MediaSessionLegacyHelper的实现，初始化的时候，用到getApplicationInfo().processName（很难理解的一处修改），并且没有判空，最新的ROM去掉了该改动。

修改起来也比较简单：给插件的ApplicationInfo赋值即可，后续马上就会提交PR。

感谢。
