### ISSUE TITLE
每次常驻进程启动会出现java.lang.NullPointerException异常

### ISSUE THREAD

**Issue by gokuo** [Qihoo360/RePlugin#355]
#### 复现问题步骤 Steps to reproduce the problem
1. 常驻进程启动
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                                 at com.qihoo360.loader2.PluginManager.evalPluginProcess(PluginManager.java:111)
                                                                                 at com.qihoo360.loader2.PluginManager.init(PluginManager.java:94)
                                                                                 at com.qihoo360.loader2.PMF.init(PMF.java:69)
                                                                                 at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:968)

**Comment by byecode** [comment]
本应用中是不是出现了包好 :p 的进程名

**Comment by gokuo** [comment]
@byecode 已经解决

**Comment by wuhenzhizao** [comment]
@byecode ，我们应用里也出现了类似的错误代码，请问是什么原因呢
