### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by TongWeiLe** [Qihoo360/RePlugin#373]
#### 问题详细描述 Detailed description of the problem
宿主调起外置插件报错

#### 复现问题步骤 Steps to reproduce the problem
1. RePlugin.startActivity(MainActivity.this, RePlugin.createIntent(info.getName()
2.为什么Activity前面有两个包名

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：5.1
Android 手机型号&ROM(Phone model & ROM): 
魅蓝note3&Flyme
#### Logcat上下文 Logcat context
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.test/com.xxx.test.loader.a.ActivityN1NRNTS3}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.xxx.test/com.xxx.app.yuesao.android.ui.activity.WelcomeActivity}; have you declared this activity in your AndroidManifest.xml?
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:187)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1585)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at android.os.Looper.loop(Looper.java:194)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5879)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
09-27 16:10:00.552 12615-12615/com.xxx.test W/System.err: Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.xxx.test/com.xxx.app.yuesao.android.ui.activity.WelcomeActivity}; have you declared this activity in your AndroidManifest.xml?
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1857)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1581)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3830)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3787)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.app.Activity.startActivity(Activity.java:4139)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.app.Activity.startActivity(Activity.java:4069)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at com.xxx.app.yuesao.android.ui.activity.WelcomeActivity.launch(WelcomeActivity.java:24)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at com.xxx.app.yuesao.android.ui.activity.QuickStartActivity.initData(QuickStartActivity.java:92)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at com.goomoo.aloha.android.ui.base.BaseActivity.onCreate(BaseActivity.java:71)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.app.Activity.performCreate(Activity.java:6127)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
09-27 16:10:00.553 12615-12615/com.xxx.test W/System.err: 	... 10 more
09-27 16:10:00.554 12615-12615/com.xxx.test W/CrashHandler: 2017年9月27日 16:10:00    F[CrashHandler]        L[169] saveCrashInfo2File    Unable to start activity ComponentInfo{com.xxx.test/com.xxx.test.loader.a.ActivityN1NRNTS3}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.xxx.test/com.xxx.app.yuesao.android.ui.activity.WelcomeActivity}; have you declared this activity in your AndroidManifest.xml?
```

**Comment by cundong** [comment]
需要先安装才可以的。
可以参考我们的外置插件DEMO
