### ISSUE TITLE
外置插件内使用反射功能崩溃

### ISSUE THREAD

**Issue by XuHX** [Qihoo360/RePlugin#374]
#### 问题详细描述 Detailed description of the problem
JavaBinder: *** Uncaught remote exception! (Exceptions are not yet supported across processes.)
java.lang.AbstractMethodError: abstract method not implemented
at android.content.pm.IPackageDataObserver$Stub.onRemoveCompleted(IPackageDataObserver.java)
at android.content.pm.IPackageDataObserver$Stub.onTransact(IPackageDataObserver.java:58)
at android.os.Binder.execTransact(Binder.java:351)
at dalvik.system.NativeStart.run(Native Method)

#### 复现问题步骤 Steps to reproduce the problem
1. 使用此功能就会复现
2. 获取应用缓存

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：25

Android Gradle Version：2.3.3

ROM(ROM): android 4.2.2

**Comment by cundong** [comment]
缺少必要的上下文，没办法帮你分析这个报错。

另，外置插件和内置插件，被加载后都是一样的，都用反射都是没问题的。
