### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with the design library.

### ISSUE THREAD

**Issue by Leeii** [Qihoo360/RePlugin#375]
#### 问题详细描述 Detailed description of the problem
host 使用 plugin的Fragment通过共享代码的方式，已经可以加载Fragment了
但是我在Fragment中使用了design.widget.TabLayout 它会报一个inflate的错误

#### 复现问题步骤 Steps to reproduce the problem
1. 在host 中使用plugin的Fragment
2. 在Fragment中使用TabLayout

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
android.view.InflateException: Binary XML file line #57: Binary XML file line #57: Error inflating mobilesafe class android.support.design.widget.TabLayout
                                                                 Caused by: android.view.InflateException: Binary XML file line #57: Error inflating mobilesafe class android.support.design.widget.TabLayout
                                                                     at com.qihoo360.loader2.PluginContext.handleCreateView(PluginContext.java:419)
                                                                     at com.qihoo360.loader2.PluginContext.access$000(PluginContext.java:57)
                                                                     at com.qihoo360.loader2.PluginContext$1.onCreateView(PluginContext.java:83)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:778)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                     at xxx.BaseFragment.createView(BaseFragment.java:40)
                                                                     at xxx.Fragment.onCreateView(AbstractFragment.java:39)
                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                     at android.support.v4.app.Fragment.performStart(Fragment.java:2214)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                     at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:1132)
                                                                     at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1632)
                                                                     at android.support.v4.app.FragmentManagerImpl.doPendingDeferredStart(FragmentManager.java:2465)
                                                                     at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1990)
                                                                     at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                     at android.view.View.measure(View.java:21046)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:911)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                     at android.view.View.measure(View.java:21046)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                     at android.view.View.measure(View.java:21046)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                     at android.view.View.measure(View.java:21046)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-28 15:09:38.365 19299-19299/net.dgg.oa.host E/AndroidRuntime:     at android.view.View.measure(View.java:21046)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                     at android.view.View.measure(View.java:21046)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:785)
                                                                     at android.view.View.measure(View.java:21046)
                                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2555)
                                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1622)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1871)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1502)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7044)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                     at com.qihoo360.loader2.PluginContext.handleCreateView(PluginContext.java:412)
                                                                     	... 73 more
                                                                  Caused by: java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
                                                                     at android.support.design.widget.ThemeUtils.checkAppCompatTheme(ThemeUtils.java:33)
                                                                     at android.support.design.widget.TabLayout.<init>(TabLayout.java:297)
                                                                     at android.support.design.widget.TabLayout.<init>(TabLayout.java:291)
                                                                     	... 76 more

**Comment by Leeii** [comment]
You need to use a Theme.AppCompat theme.
最后他是说需要使用一个AppCompat的主题，我已经用了，ver也改成100了
插件中主题也在每个Activity中设置了

**Comment by Leeii** [comment]
已解决：因为在项目中要用host使用Fragment，所有很多包都exclude了v4，然后complie fragment.jar Fragment是能用了，但是AppCompatActivity又提示没有主题

貌似现在并不能Fragment和AppCompatActivity都在宿主中使用，看Demo也是分开的 demo1有Fragment 但是没有使用AppCompatActivity, demo2中有AppCompatActivity，但是没有使用Fragment

目前是把Fragment写进了宿主，暂时解决

**Comment by LiuJQ** [comment]
最近也遇到此问题，貌似fragment和AppCompatActivity就是不能同时在plugin中使用？我相信这是一个bug。。

**Comment by Leeii** [comment]
@LiuJQ  是的 要么使用fragment + 不使用AppCompat主题，要么就要分开用，但是现在应该都使用的是AppCompat的Activity吧

**Comment by luohaoxuan320** [comment]
AppCompatActivity 和Fragment共存问题可以参考我的解决方案，希望能帮到你们
https://github.com/luohaoxuan320/RePluginDemo/wiki/%E6%8F%92%E4%BB%B6-AppCompatActivity-%E4%B8%8E-v4.Fragment%E5%85%B1%E5%AD%98
