### ISSUE TITLE
安装插件后。马上使用插件的fragment报错

### ISSUE THREAD

**Issue by 1321365765** [Qihoo360/RePlugin#383]
#### 问题详细描述 Detailed description of the problem
安装插件后。马上使用插件的fragment提示
android.content.res.Resources$NotFoundException: Resource ID #0x7f03002a
                                                                       at android.content.res.Resources.getValue(Resources.java:1123)
                                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2309)
                                                                       at android.content.res.Resources.getLayout(Resources.java:939)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
                                                                       at com.iotimc.notificationlibrary.fragment.NotificationFragment.onCreateView(NotificationFragment.java:43)
                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
                                                                       at dalvik.system.NativeStart.main(Native Method)

fragment onCreateView 方法是这样的
rootView;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        Log.d(TAG, "onCreateView() called with: inflater = [" + inflater + "], container = [" + container + "], savedInstanceState = [" + savedInstanceState + "]");
        /**
         * 需要注意不能使用inflater及container因为他们的Context是宿主的
         */
      
            if (RePlugin.getPluginContext() == null)
                rootView = inflater.inflate(getResId(), container, false);
            else
                rootView = LayoutInflater.from(RePlugin.getPluginContext()).inflate(getResId(), container, false);
            initView(rootView);
       
     
        return rootView;
    }
#### 复现问题步骤 Steps to reproduce the problem
1.  PluginInfo pi =  RePlugin.install(upgradeInfo.getFilePath());
2. RePlugin.preload(pi);
3.  //代码使用插件Fragment
        ClassLoader d1ClassLoader = RePlugin.fetchClassLoader("iotimcnotification");
        if (d1ClassLoader == null)
            return;
        try {

            Fragment fragment = d1ClassLoader.loadClass("com.iotimc.notificationlibrary.fragment.NotificationFragment").asSubclass(Fragment.class).newInstance()
            getSupportFragmentManager().beginTransaction().add(R.id.container, fragment).commit();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.0
rePlugin-plugin-lib/gradle Version:2.2.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
问题于：

你安装的外置插件，比如iotimcnotification.jar，安装成功后，插件的名字并不是"iotimcnotification"。你应该从PluginInfo pi 中取到这个插件的名字，然后再去执行：

> ClassLoader d1ClassLoader = RePlugin.fetchClassLoader("iotimcnotification");

**Comment by 1321365765** [comment]
RePlugin.fetchViewByLayoutName(upgradeInfo.getPluginName(),"activity_main",null);
            fragment = d1ClassLoader.loadClass("com.iotimc.notificationlibrary.fragment.NotificationFragment").asSubclass(Fragment.class).newInstance();//使用插件的Classloader获取指定Fragment实例
            getSupportFragmentManager().beginTransaction().add(R.id.container, fragment).commit();//添加Fragment到UI
安装完成之后加多这一步就能使用了

**Comment by 1321365765** [comment]
@cundong 其实更想问下升级，跟卸载的问题，在调用RePlugin.uninstall 或者 RePlugin.install 方法后
不知道调用什么方法或者执行什么步骤才能使卸载以及升级生效。
尝试过 Intent intent = getBaseContext().getPackageManager()
                .getLaunchIntentForPackage(getBaseContext().getPackageName());
        PendingIntent restartIntent = PendingIntent.getActivity(getApplicationContext(), 0, intent, PendingIntent.FLAG_ONE_SHOT);
        AlarmManager mgr = (AlarmManager)getSystemService(Context.ALARM_SERVICE);
        mgr.set(AlarmManager.RTC, System.currentTimeMillis() + 1000, restartIntent); // 1秒钟后重启应用
       System.exit(0);
        android.os.Process.killProcess(android.os.Process.myPid());
重启应用后还是未能生效

**Comment by cundong** [comment]
正确使用示例：

https://github.com/Qihoo360/RePlugin/blob/dev/replugin-sample/host/app/src/main/java/com/qihoo360/replugin/sample/host/PluginFragmentActivity.java
