### ISSUE TITLE
MI5s Crash:NoSuchMethodError: No static method removeFinalModifier

### ISSUE THREAD

**Issue by 456838** [Qihoo360/RePlugin#40]
java.lang.NoSuchMethodError: No static method removeFinalModifier(Ljava/lang/reflect/Field;)V in class Lorg/apache/commons/lang3/reflect/FieldUtils; or its super classes (declaration of 'org.apache.commons.lang3.reflect.FieldUtils' appears in /system/framework/framework.jar:classes2.dex)
     at com.qihoo360.replugin.RePluginClassLoader.copyFieldValue(RePluginClassLoader.java:128)
     at com.qihoo360.replugin.RePluginClassLoader.copyFromOriginal(RePluginClassLoader.java:113)
     at com.qihoo360.replugin.RePluginClassLoader.<init>(RePluginClassLoader.java:79)
     at com.qihoo360.replugin.DefaultRePluginCallbacks.createClassLoader(DefaultRePluginCallbacks.java:52)
     at com.qihoo360.loader.utils.PatchClassLoaderUtils.patch(PatchClassLoaderUtils.java:81)
     at com.qihoo360.loader2.PMF.init(PMF.java:79)
     at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:845)
     at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:789)
     at com.qihoo360.replugin.sample.host.SampleApplication.attachBaseContext(SampleApplication.java:35)
     at android.app.Application.attach(Application.java:191)
     at android.app.Instrumentation.newApplication(Instrumentation.java:998)
     at android.app.Instrumentation.newApplication(Instrumentation.java:982)
     at android.app.LoadedApk.makeApplication(LoadedApk.java:575)
     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4716)
     at android.app.ActivityThread.access$1600(ActivityThread.java:153)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5458)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by jiongxuan** [comment]
是这样，我们在去年底引入了Apache Commons库，这样可避免“重复造轮子”（并将之前的调用迁移到Apache上）。然而后来发现由于MIUI内置了“旧版本”的Apache库，且ClassLoader的双亲委派机制的原因（注意，和Hook无关），在“未混淆”的应用上，运行会出现找不到removeFinalModifier的情况。

换言之，只要在小米ROM上，用到Apache或第三方开源库的，且“未经混淆”的前提下，都会有这类问题，无论是哪个项目。当然，要解决这个问题也很简单，就是**出包时混淆**即可，只要Apache包名一改，则双亲委派就认为是两个Class，自然不会出现问题。

我们已将“替换Apache为原来自研类库”作为我们下一版的Issue，届时将不再使用Apache。就目前而言，您可以临时换一台非小米的手机来运行Sample，也可以像卫士那样混淆编译（我们AAR已自带混淆Proguard，引入即生效），也可以将Apache类库临时改名。

最后，非常感谢您提出的建议。

**Comment by jiongxuan** [comment]
抱歉，这段时间一直忙，忘了回复了，这个我们早在2.1.1上已经修复了。欢迎试用。
