### ISSUE TITLE
Android4.4 跳转插件

### ISSUE THREAD

**Issue by Joe-Blake** [Qihoo360/RePlugin#415]
#### 问题详细描述 Detailed description of the problem
跳转插件H5页面应用崩溃

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
华为Y635 Android4.4 EMUI3.0

#### Logcat上下文 Logcat context
replacements=[Ljava.lang.String;@41664a68
HARDWARE=qcom
matchers=[Ljava.lang.String;@416649e8
RADIO=unknown
versionCode=1
HOST=huawei-desktop
HIDE_PRODUCT_INFO=false
TAGS=release-keys
ID=HuaweiY635-CL00
MANUFACTURER=HUAWEI
TYPE=user
TIME=1441677110000
FINGERPRINT=Huawei/Y635-CL00/hwY635:4.4.4/HuaweiY635-CL00/C92B272:user/ota-rel-keys,release-keys
UNKNOWN=unknown
BOARD=Y635-CL00
PRODUCT=Y635-CL00
versionName=1.0.0
DISPLAY=Y635-CL00V100R001CHNC92B272
USER=huawei
DEVICE=hwY635
MODEL=HUAWEI  Y635-CL00
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=false
SERIAL=c4072f67ec88
BRAND=Huawei
java.lang.RuntimeException:  Unable  to  start  activity  ComponentInfo{com.daojia.jz.ayi/com.daojia.jz.ayi.loader.a.ActivityN1NRNTS1}:  java.lang.NullPointerException
at  android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
at  android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
at  android.app.ActivityThread.access$1100(ActivityThread.java:141)
at  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
at  android.os.Handler.dispatchMessage(Handler.java:102)
at  android.os.Looper.loop(Looper.java:136)
at  android.app.ActivityThread.main(ActivityThread.java:5336)
at  java.lang.reflect.Method.invokeNative(Native  Method)
at  java.lang.reflect.Method.invoke(Method.java:515)
at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
at  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
at  dalvik.system.NativeStart.main(Native  Method)
Caused  by:  java.lang.NullPointerException
at  com.daojia.app.yuesao.android.ui.activity.WebOneActivity.b(WebOneActivity.java:374)
at  com.daojia.app.yuesao.android.ui.activity.WebOneActivity.d(WebOneActivity.java:166)
at  com.daojia.app.yuesao.android.ui.activity.WebOneActivity.initData(WebOneActivity.java:149)
at  com.goomoo.aloha.android.ui.base.BaseActivity.onCreate(BaseActivity.java:73)
at  com.goomoo.aloha.android.ui.base.TitleBarActivity.onCreate(TitleBarActivity.java:41)
at  android.app.Activity.performCreate(Activity.java:5302)
at  android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
at  android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
...  11  more
java.lang.NullPointerException
at  com.daojia.app.yuesao.android.ui.activity.WebOneActivity.b(WebOneActivity.java:374)
at  com.daojia.app.yuesao.android.ui.activity.WebOneActivity.d(WebOneActivity.java:166)
at  com.daojia.app.yuesao.android.ui.activity.WebOneActivity.initData(WebOneActivity.java:149)
at  com.goomoo.aloha.android.ui.base.BaseActivity.onCreate(BaseActivity.java:73)
at  com.goomoo.aloha.android.ui.base.TitleBarActivity.onCreate(TitleBarActivity.java:41)
at  android.app.Activity.performCreate(Activity.java:5302)
at  android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
at  android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
at  android.app.ActivityThread.handleLaunchActivity(A ctivityThread.java:2313)
at android.app.ActivityThread.access$1100(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5336)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
at dalvik.system.NativeStart.main(Native Method)

**Comment by cundong** [comment]
看您这个报错，还是缺少游泳的信息，如果您有更详细的，可以发出来，或者直接加我的QQ：251306994.

**Comment by zhmcoder** [comment]
是对象序列化问题，在4.4版本上跳转传递时候对象序列化由 Serializable修改为Parcelable就可以了，这个在app本身跳转没有问题，主要是发生在插件之间调用
