### ISSUE TITLE
内置插件升级后，获取插件信息崩溃

### ISSUE THREAD

**Issue by lightshs** [Qihoo360/RePlugin#429]
#### 问题详细描述 Detailed description of the problem
内置插件install()和preload()后，调用RePlugin.getPluginInfo()方法会崩溃

#### 复现问题步骤 Steps to reproduce the problem
1. 内置插件升级，执行RePlugin.install()和RePlugin.preload()
2. 调用RePlugin.getPluginInfo()方法会崩溃

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
                                                 java.lang.StackOverflowError: stack size 1038KB
                                                     at java.lang.Character.digit(Character.java:2323)
                                                     at java.lang.Long.parse(Long.java:361)
                                                     at java.lang.Long.parseLong(Long.java:353)
                                                     at org.json.JSONTokener.readLiteral(JSONTokener.java:305)
                                                     at org.json.JSONTokener.nextValue(JSONTokener.java:111)
                                                     at org.json.JSONTokener.readObject(JSONTokener.java:384)
                                                     at org.json.JSONTokener.nextValue(JSONTokener.java:100)
                                                     at org.json.JSONTokener.readObject(JSONTokener.java:384)
                                                     at org.json.JSONTokener.nextValue(JSONTokener.java:100)
                                                     at org.json.JSONObject.<init>(JSONObject.java:156)
                                                     at org.json.JSONObject.<init>(JSONObject.java:173)
                                                     at com.qihoo360.replugin.helper.JSONHelper.cloneNoThrows(JSONHelper.java:66)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:161)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:173)
                                                     at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:163)
                                                 	at com.qihoo360.replugin.model.PluginInfo.<init>(PluginInfo.java:
11-22 20:02:27.302 1198-1416/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 3079308)

**Comment by cundong** [comment]
请参照dev分支，以解决。

**Comment by Poney1** [comment]
java.lang.StackOverflowError: stack size 1040KB 
at java.lang.Character.digit(Character.java:6765) 
at java.lang.Long.parseLong(Long.java:592) 
at org.json.JSONTokener.readLiteral(JSONTokener.java:313) 
at org.json.JSONTokener.nextValue(JSONTokener.java:115) 
at org.json.JSONTokener.readObject(JSONTokener.java:394) 
at org.json.JSONTokener.nextValue(JSONTokener.java:104) 
at org.json.JSONTokener.readObject(JSONTokener.java:394) 
at org.json.JSONTokener.nextValue(JSONTokener.java:104) 
at org.json.JSONObject.(JSONObject.java:164) 
at org.json.JSONObject.(JSONObject.java:181) 
at com.qihoo360.replugin.helper.JSONHelper.cloneNoThrows(JSONHelper.java:66) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:186) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:198) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:188) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:198) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:188) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:198) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:188) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:198) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:188) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:198) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:188) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:198) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:188) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:198) 
at com.qihoo360.replugin.model.PluginInfo.(PluginInfo.java:188)

最新版本的代码，仍然有此问题。原因是啥呀？
