### ISSUE TITLE
资源未释放 'close' not called

### ISSUE THREAD

**Issue by lightshs** [Qihoo360/RePlugin#430]
#### 问题详细描述 Detailed description of the problem
资源未释放

#### 复现问题步骤 Steps to reproduce the problem
1. 内置插件已经运行，执行RePlugin.install()后，执行RePlugin.preload()
2. 通过StrictMode日志看到资源未关闭

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
11-22 20:01:37.953 1198-1210/com.meizu.flyme.wallet E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                      at dalvik.system.DexFile.<init>(DexFile.java:113)
                                                                      at dalvik.system.DexFile.loadDex(DexFile.java:151)
                                                                      at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
                                                                      at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
                                                                      at dalvik.system.DexPathList.<init>(DexPathList.java:120)
                                                                      at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
                                                                      at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
                                                                      at com.qihoo360.replugin.PluginDexClassLoader.<init>(PluginDexClassLoader.java:71)
                                                                      at com.qihoo360.replugin.RePluginCallbacks.createPluginClassLoader(RePluginCallbacks.java:76)
                                                                      at com.qihoo360.loader2.Loader.loadDex(Loader.java:317)
                                                                      at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:817)
                                                                      at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:623)
                                                                      at com.qihoo360.loader2.Plugin.load(Plugin.java:434)
                                                                      at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1054)
                                                                      at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1046)
                                                                      at com.qihoo360.loader2.PluginCommImpl.loadPluginClassLoader(PluginCommImpl.java:335)
                                                                      at com.qihoo360.replugin.packages.PluginFastInstallProvider.install(PluginFastInstallProvider.java:95)
                                                                      at com.qihoo360.replugin.packages.PluginFastInstallProvider.update(PluginFastInstallProvider.java:77)
                                                                      at android.content.ContentProvider$Transport.update(ContentProvider.java:381)
                                                                      at android.content.ContentProviderClient.update(ContentProviderClient.java:280)
                                                                      at com.qihoo360.replugin.packages.PluginFastInstallProviderProxy.install(PluginFastInstallProviderProxy.java:69)
                                                                      at com.qihoo360.replugin.RePlugin.preload(RePlugin.java:208)
                                                                      at

**Comment by cundong** [comment]
看这个调用链，已经进入到 framework了，可以理解为，StrictMode对framework中的代码有误判：

http://androidxref.com/7.1.1_r6/xref/libcore/dalvik/src/main/java/dalvik/system**/CloseGuard.java**
