### ISSUE TITLE
集成360replugin,5.0 以下设备，宿主中引用高德等第三方。APP不能运行。

### ISSUE THREAD

**Issue by xy348735514** [Qihoo360/RePlugin#446]
replugin:GuardService E/RePlugin.ws001: plugins-builtin.json not found
12-08 13:16:30.314 10225-10225/com.jtv.replugin:GuardService E/RePlugin.PluginInfoList: load: Read Json error!
12-08 13:16:30.328 10225-10225/com.jtv.replugin:GuardService E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.jtv.replugin:GuardService, PID: 10225
                                                                               java.lang.RuntimeException: Unable to get provider com.qihoo360.mobilesafe.svcmanager.ServiceProvider: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.mobilesafe.svcmanager.ServiceProvider" on path: DexPathList[[zip file "/data/app/com.jtv.replugin-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.jtv.replugin-2, /vendor/lib, /system/lib]]
                                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:5042)
                                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:4613)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
                                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                   at android.os.Looper.loop(Looper.java:193)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5323)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.mobilesafe.svcmanager.ServiceProvider" on path: DexPathList[[zip file "/data/app/com.jtv.replugin-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.jtv.replugin-2, /vendor/lib, /system/lib]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:172)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                                   at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:163)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:5027)
                                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:4613) 
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553) 
                                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                                   at android.os.Looper.loop(Looper.java:193) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5323) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
12-08 13:16:32.786 10253-10253/com.jtv.replugin:GuardService E/RePlugin.ws001: plugins-builtin.json not found

4.0 ,4.1,4.2,4.3,4.4 都运行不起来，单独使用没有问题。

**Comment by cundong** [comment]
通过 日志 来看。
plugins-builtin.json not found
这个文件没有生成。

这个文件是什么时候生成的呢？是编译期，host-gradle生成的。
所以，可以检查一下host-gradle是否正确配置了，以及host-lib也正确配置了。

**Comment by xy348735514** [comment]
配置没问题，在5.0上没有问题，只有在5.0以下的设备上运行不上。

**Comment by xy348735514** [comment]
问题已经解决，本地SO 库冲突引起的。
