### ISSUE TITLE
sample 运行报错

### ISSUE THREAD

**Issue by snice** [Qihoo360/RePlugin#46]
用android studio运行到手机，报错如下：

`java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.sample.host.loader.p.ProviderN1"`

**RePlugin version**: 2.1.0

**Android compile SDK version**: 25

**Android ROM**: 红米1S

**Comment by jiongxuan** [comment]
您好，感谢反馈！

烦请将完整的Logcat信息上传到Issue中，我看下是什么问题。

**Comment by fanrenyi** [comment]
我也遇到同样的崩溃。
Process: com.example.fan.replugindemo, PID: 24632
                                                                              java.lang.RuntimeException: Unable to get provider com.example.fan.replugindemo.loader.p.ProviderN1: java.lang.ClassNotFoundException: Didn't find class "com.example.fan.replugindemo.loader.p.ProviderN1" on path: DexPathList[[zip file "/data/app/com.example.fan.replugindemo-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                                  at android.app.ActivityThread.installProvider(ActivityThread.java:5232)
                                                                                  at android.app.ActivityThread.installContentProviders(ActivityThread.java:4803)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4743)
                                                                                  at android.app.ActivityThread.access$1500(ActivityThread.java:169)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.fan.replugindemo.loader.p.ProviderN1" on path: DexPathList[[zip file "/data/app/com.example.fan.replugindemo-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                  at android.app.ActivityThread.installProvider(ActivityThread.java:5217)
                                                                                  at android.app.ActivityThread.installContentProviders(ActivityThread.java:4803) 
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4743) 
                                                                                  at android.app.ActivityThread.access$1500(ActivityThread.java:169) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
                                                                              	Suppressed: java.lang.ClassNotFoundException: com.example.fan.replugindemo.loader.p.ProviderN1
                                                                                  at java.lang.Class.classForName(Native Method)
                                                                                  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                  		... 13 more
                                                                               Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by jiongxuan** [comment]
您好，通常遇到这个问题是因为没有在Application中调用RePlugin.App.attachBaseContext等导致。

请严格按照“[主程序接入指南](https://github.com/Qihoo360/RePlugin/wiki/%E4%B8%BB%E7%A8%8B%E5%BA%8F%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)”所述来完成接入。插件亦是如此。

**Comment by fanrenyi** [comment]
你好，我跑了sample，没有改动任何代码，检查了RePlugin.App.attachBaseContext调用逻辑。还是出现这个崩溃，建议您刷个rom MIUI 8 6.9.29尝试下。

**Comment by chenzhiwei-github** [comment]
demo跟楼上同样错误

**Comment by ouer1994** [comment]
demo同样的错误，小米手机出错，oppo手机没问题

**Comment by ouer1994** [comment]
@snice 你的DebugReceivers里面的日志打印出来了吗？我的什么都没有输出

**Comment by chenzhiwei-github** [comment]
@ouer1994 刚我使用三星GT-I9300运行正常，小米报错，是否小米定制的ROM问题 小米原装系统 @jiongxuan

**Comment by xiangou** [comment]
小米手机有问题 乐视没有问题

**Comment by jiongxuan** [comment]
Duplicate #40 。通过描述来看，跟之前提到的是同一问题。

是这样，我们在去年底引入了Apache Commons库，这样可避免“重复造轮子”（并将之前的调用迁移到Apache上）。然而后来发现由于MIUI内置了“旧版本”的Apache库，且ClassLoader的双亲委派机制的原因（注意，和Hook无关），在“未混淆”的应用上，运行会出现找不到removeFinalModifier的情况。

换言之，只要在小米ROM上，用到Apache或第三方开源库的，且“未经混淆”的前提下，都会有这类问题，无论是哪个项目。当然，要解决这个问题也很简单，就是出包时混淆即可，只要Apache包名一改，则双亲委派就认为是两个Class，自然不会出现问题。

我们已将“替换Apache为原来自研类库”作为我们下一版的Issue，届时将不再使用Apache。就目前而言，您可以临时换一台非小米的手机来运行Sample，也可以像卫士那样混淆编译（我们AAR已自带混淆Proguard，引入即生效），也可以将Apache类库临时改名。

最后，非常感谢您提出的建议。

**Comment by lanshifu** [comment]
乐视 android 6.0 ，运行sample，点击启动demo插件，报错，说没有声明该activity。
07-04 23:36:24.018 1395-1395/com.qihoo360.replugin.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.qihoo360.replugin.sample.host, PID: 1395
                                                                                 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}; have you declared this activity in your AndroidManifest.xml?
                                                                                     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                                                     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
                                                                                     at android.app.Activity.startActivityForResult(Activity.java:3969)
                                                                                     at android.app.Activity.startActivityForResult(Activity.java:3929)
                                                                                     at android.app.Activity.startActivity(Activity.java:4252)
                                                                                     at android.app.Activity.startActivity(Activity.java:4220)
                                                                                     at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:259)
                                                                                     at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                                                     at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                                                     at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                                                     at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java:38)
                                                                                     at android.view.View.performClick(View.java:5277)
                                                                                     at android.view.View$PerformClick.run(View.java:21704)
                                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5896)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
                                                                                     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:100)

**Comment by manymore13** [comment]
@lanshifu 同问

**Comment by sam-long-li** [comment]
moto X运行demo也出现这个问题，并且核对是按文旦上配置的
07-06 16:23:04.606 31315-31315/com.qihoo360.replugin.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.qihoo360.replugin.sample.host, PID: 31315
                                                                                   android.content.ActivityNotFoundException: Unable to find explicit activity class {com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}; have you declared this activity in your AndroidManifest.xml?
                                                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1852)
                                                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1552)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3746)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3707)
                                                                                       at android.app.Activity.startActivity(Activity.java:4027)
                                                                                       at android.app.Activity.startActivity(Activity.java:3989)
                                                                                       at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:259)
                                                                                       at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                                                       at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                                                       at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                                                       at com.qihoo360.replugin.sample.host.MainActivity$1.onClick(MainActivity.java:38)
                                                                                       at android.view.View.performClick(View.java:4761)
                                                                                       at android.view.View$PerformClick.run(View.java:19767)
                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by sam-long-li** [comment]
@jiongxuan 运行的demo，配置和文档说明一致，但跳转就是出现上文的错误

**Comment by wangyupeng1-iri** [comment]
请clone最新的代码库试试
