### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS4}

### ISSUE THREAD

**Issue by wenge1215** [Qihoo360/RePlugin#475]
插件单独启动可以运行，但是添加到宿主中启动时就会报以下错误：

```
Process: com.qihoo360.replugin.sample.host, PID: 8876
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS4}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v7.widget.DecorContentParent.setWindowCallback(android.view.Window$Callback)' on a null object reference
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                                                     at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:150)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v7.widget.DecorContentParent.setWindowCallback(android.view.Window$Callback)' on a null object reference
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:410)
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                     at wenge.com.plugin3.LaunchActivity.onCreate(LaunchActivity.java:12)
                                                                                     at android.app.Activity.performCreate(Activity.java:6367)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504) 
                                                                                     at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:150) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
```

插件中只有一个Activity，继承AppCompatActivity，当修改为继承Activity是错误如下：
```
01-09 14:54:55.241 1736-1736/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.qihoo360.replugin.sample.host, PID: 1736
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS4}: java.lang.IllegalArgumentException: You must pass in a non null View
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:150)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                  Caused by: java.lang.IllegalArgumentException: You must pass in a non null View
                                                     at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:678)
                                                     at com.bumptech.glide.DrawableRequestBuilder.into(DrawableRequestBuilder.java:448)
                                                     at wenge.com.plugin3.LaunchActivity.onCreate(LaunchActivity.java:16)
                                                     at android.app.Activity.performCreate(Activity.java:6367)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:150) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 

```

下面是插件   project 的.gradle文件：
```
buildscript {
    
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'

        classpath 'com.qihoo360.replugin:replugin-plugin-gradle:2.2.1'      /*360 Replugin--plugin  */

    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

下面是插件    module 的.gradle文件：
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26



    defaultConfig {
        applicationId "wenge.com.plugin2"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
 
    compile 'com.qihoo360.replugin:replugin-plugin-lib:2.2.1'

}
```

最后，提供一下宿主 module 的.gradle文件：
```
apply plugin: 'com.android.application'
apply plugin: 'replugin-host-gradle'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "wenge.com.testreplugin"
        minSdkVersion 19
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        applicationId "com.qihoo360.replugin.sample.host"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
/**
 * 配置项均为可选配置，默认无需添加
 * 更多可选配置项参见replugin-host-gradle的RepluginConfig类
 * 可更改配置项参见 自动生成RePluginHostConfig.java
 */
repluginHostConfig {
    /**
     * 是否使用 AppCompat 库
     * 不需要个性化配置时，无需添加
     */
    useAppCompat = true

}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    compile 'com.qihoo360.replugin:replugin-host-lib:2.2.1'    /*360 Replugin*/
}

```
麻烦大佬们帮我看看，谢谢了

**Comment by techinsight** [comment]
同问，及时只是修改了demo代码，替换jar后，就有了问题
