### ISSUE TITLE
关于无法启动外置插件activity的问题

### ISSUE THREAD

**Issue by xilinch** [Qihoo360/RePlugin#504]
#### 问题详细描述 Detailed description of the problem
在项目中集成了replugin， 可以在项目安装内置插件和启动内置插件activity，但是无法启动外置插件activity。将同样的插件路径设置到 官方demo host中，是可以启动外置插件activity的。而项目中已经有文件读写权限，同时在插件中注册了该activity，该apk作为内置插件，activity可以被启动。

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information
始终提示该activity未在项目中注册
  

replugin-host-lib/gradle Version:2.2.2
rePlugin-plugin-lib/gradle Version:2.2.2

Android API Version：android 8.0
Android 手机型号&ROM(Phone model & ROM): 华为mate 10

#### Logcat上下文 Logcat context
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tangsoft.xkr.jiujiaotianxia/com.tangsoft.xkr.jiujiaotianxia.MainActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1977)
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1636)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4741)
                                                                        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4681)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                        at android.app.Activity.startActivity(Activity.java:5102)
                                                                        at android.app.Activity.startActivity(Activity.java:5070)
                                                                        at com.nfdaily.nfplus.ui.activity.TestActivity$3$1.run(TestActivity.java:104)

**Comment by cundong** [comment]
请参考demo3。

**Comment by xilinch** [comment]
感谢 ## 故梦追魂  解答，
经过提醒，发现在启动插件的activity 调用方法使用错误，换成RePlugin.startActivity(),即可。
谢谢replugin开发组
