### ISSUE TITLE
异常java.lang.ClassNotFoundException: com.testreplugin.loader.p.ProviderN1

### ISSUE THREAD

**Issue by ikakaxi** [Qihoo360/RePlugin#51]
插件问题:异常
java.lang.ClassNotFoundException: com.testreplugin.loader.p.ProviderN1

我的代码上传到了github:https://github.com/ikakaxi/testRePlugin.git

我是app->lib1->lib2
lib1和lib2有一个相同名字的color资源,然后在app里默认的activity_main里面把文字颜色设置了这个color,运行报错

详细堆栈信息:
`java.lang.RuntimeException: Unable to get provider com.testreplugin.loader.p.ProviderN1: java.lang.ClassNotFoundException: Didn't find class "com.testreplugin.loader.p.ProviderN1" on path: DexPathList[[zip file "/data/app/com.testreplugin-2/base.apk", zip file "/data/app/com.testreplugin-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.testreplugin-2/lib/x86_64, /vendor/lib64, /system/lib64]]
                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:5156)
                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
                                                                      at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.testreplugin.loader.p.ProviderN1" on path: DexPathList[[zip file "/data/app/com.testreplugin-2/base.apk", zip file "/data/app/com.testreplugin-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.testreplugin-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.testreplugin-2/lib/x86_64, /vendor/lib64, /system/lib64]]
                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:5141)
                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
                                                                      at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                  	Suppressed: java.lang.ClassNotFoundException: com.testreplugin.loader.p.ProviderN1
                                                                      at java.lang.Class.classForName(Native Method)
                                                                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                      		... 12 more
                                                                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by jiongxuan** [comment]
您好，通常遇到这个问题是因为没有在Application中调用RePlugin.App.attachBaseContext等导致。

请严格按照“[主程序接入指南](https://github.com/Qihoo360/RePlugin/wiki/%E4%B8%BB%E7%A8%8B%E5%BA%8F%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)”所述来完成接入。

**Comment by ikakaxi** [comment]
解决了,非常感谢,新建的项目忘了写RePlugin.App.attachBaseContext
