### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by wx2013** [Qihoo360/RePlugin#528]
#### 问题详细描述 Detailed description of the problem
 打开插件的页面报错,插件就一个页面,做测试跳转用的,页面的 layout 就几个 button

java.lang.RuntimeException: Unable to start activity ComponentInfo{包名/包名.loader.a.ActivityN1NRNTS4}: android.content.res.Resources$NotFoundException: Resource ID #0x7f060217
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:157)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:157)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5293)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f060217
                                                                       at android.content.res.Resources.getValue(Resources.java:2009)
                                                                       at android.content.res.Resources.getDrawable(Resources.java:1584)
                                                                       at com.android.internal.widget.ActionBarView.setIcon(ActionBarView.java:1002)
                                                                       at com.android.internal.policy.impl.PhoneWindow.setDefaultIcon(PhoneWindow.java:1515)
                                                                       at android.app.Activity.initActionBar(Activity.java:1964)
                                                                       at android.app.Activity.setContentView(Activity.java:1979)
                                                                       at 插件的activity.onCreate(插件的activity.java:45)
                                                                       at android.app.Activity.performCreate(Activity.java:5394)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2246)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:157) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:157) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5293) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
#### 复现问题步骤 Steps to reproduce the problem
1. 打开一个插件的 activity
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4
![image](https://user-images.githubusercontent.com/5744815/37508974-5bfefd82-2930-11e8-9c62-d730c1be2d6b.png)

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by shoedog5689** [comment]
麻烦问一下，解决了吗？

**Comment by liuxucool163** [comment]
同问

**Comment by Love-pudding** [comment]
同问
