### ISSUE TITLE
Didn't find class "com.qihoo360.replugin.Entry" 非必先

### ISSUE THREAD

**Issue by wx2013** [Qihoo360/RePlugin#529]
#### 问题详细描述 Detailed description of the problem
有时打包的时候会出现Didn't find class "com.qihoo360.replugin.Entry",这个问题非必先的,如果出现的话就需要 clean 项目,由于是非必先的,因此如果在多渠道打包的时候出现了这个问题,那不是很无语.

#### 复现问题步骤 Steps to reproduce the problem
1. 正常运行
2. 报错

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context

03-21 16:08:32.192 17722-17722/包名 E/ws001: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/包名/app_p_a/2028349455.jar"],nativeLibraryDirectories=[/data/data/包名/app_p_n/2028349455, /vendor/lib, /system/lib]]
                                                          java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/user/0/包名/app_p_a/2028349455.jar"],nativeLibraryDirectories=[/data/data/包名/app_p_n/2028349455, /vendor/lib, /system/lib]]
                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                              at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:96)
                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                              at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:469)
                                                              at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:878)
                                                              at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:835)
                                                              at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:689)
                                                              at com.qihoo360.loader2.Plugin.load(Plugin.java:434)
                                                              at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1093)
                                                              at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1078)
                                                              at com.qihoo360.loader2.PluginCommImpl.queryPluginContext(PluginCommImpl.java:196)
                                                              at com.qihoo360.i.Factory.queryPluginContext(Factory.java:184)
                                                              at com.qihoo360.replugin.component.service.server.PluginServiceServer.installServiceLocked(PluginServiceServer.java:417)
                                                              at com.qihoo360.replugin.component.service.server.PluginServiceServer.access$000(PluginServiceServer.java:67)
                                                              at com.qihoo360.replugin.component.service.server.PluginServiceServer$2.call(PluginServiceServer.java:398)
                                                              at com.qihoo360.replugin.component.service.server.PluginServiceServer$2.call(PluginServiceServer.java:395)
                                                              at com.qihoo360.replugin.base.ThreadUtils.syncToMainThread(ThreadUtils.java:50)
                                                              at com.qihoo360.replugin.component.service.server.PluginServiceServer.installServiceIfNeededLocked(PluginServiceServer.java:395)
                                                              at com.qihoo360.replugin.component.service.server.PluginServiceServer.bindServiceLocked(PluginServiceServer.java:184)
                                                              at com.qihoo360.replugin.component.service.server.PluginServiceServer$Stub.bindService(PluginServiceServer.java:563)
                                                              at com.qihoo360.replugin.component.service.PluginServiceClient.bindService(PluginServiceClient.java:215)
                                                              at com.qihoo360.replugin.component.service.PluginServiceClient.bindService(PluginServiceClient.java:179)
                                                              at 包名.bindTtsServeice(TtsUtils.java:762)
                                                              at 包名.ListenerManager$3.run(ListenerManager.java:375)
                                                              at 包名.WeakHandler$WeakRunnable.run(WeakHandler.java:443)
                                                              at android.os.Handler.handleCallback(Handler.java:733)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:157)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5293)
                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by cundong** [comment]
检查plugin gradle plugin lib配置

**Comment by YuDongZhang** [comment]
这个问题时有时无 就算你的配置没有问题 , 在你做内置插件的时候 也会出现 , 而且莫名其妙 , 没有好解决方式 , 你配置不动 , 在编译的过程中也会出错
