### ISSUE TITLE
小米MIX2手机单独运行plugin-demo2失败

### ISSUE THREAD

**Issue by 272152441** [Qihoo360/RePlugin#530]
#### 问题详细描述 Detailed description of the problem
单独运行plugin-demo2的demo，在小米mix2手机上，能看到app图标，但是点击提示您的手机上未安装应用程序,看log提示，没有配置MAIN和LAUNCHER，但是通过manifest中查看的确已经配置了。
```    
    <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation"
            android:exported="false"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="com.qihoo360.replugin.sample.demo2.action.theme_fullscreen_2" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```
#### 复现问题步骤 Steps to reproduce the problem
1. 直接导入plugin-demo2运行即可

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
小米MIX2 Android 7.1.1
#### Logcat上下文 Logcat context
03-22 10:12:57.518 2949-2949/? E/Launcher: Launcher does not have the permission to launch Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.qihoo360.replugin.sample.demo2/.MainActivity bnds=[329,1490][497,1658] (has extras) }. Make sure to create a MAIN intent-filter for the corresponding activity or use the exported attribute for this activity.
                                           java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.qihoo360.replugin.sample.demo2/.MainActivity bnds=[329,1490][497,1658] (has extras) } from ProcessRecord{6b27616 2949:com.miui.home/u0a21} (pid=2949, uid=10021) not exported from uid 10212
                                               at android.os.Parcel.readException(Parcel.java:1684)
                                               at android.os.Parcel.readException(Parcel.java:1637)
                                               at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3155)
                                               at android.app.Instrumentation.execStartActivity(Instrumentation.java:1520)
                                               at android.app.Activity.startActivityForResult(Activity.java:4399)
                                               at com.miui.home.launcher.Launcher.startActivityForResult(Launcher.java:3141)
                                               at android.app.Activity.startActivity(Activity.java:4692)
                                               at com.miui.home.launcher.Launcher.startActivity(Launcher.java:3102)
                                               at com.miui.home.launcher.Launcher$PerformLaunchAction.run(Launcher.java:3045)
                                               at com.miui.home.launcher.Launcher$PerformLaunchAction.launch(Launcher.java:3026)
                                               at com.miui.home.launcher.Launcher.onClick(Launcher.java:2993)
                                               at android.view.View.performClick(View.java:5647)
                                               at android.view.View$PerformClick.run(View.java:22462)
                                               at com.miui.home.launcher.ItemIcon.post(ItemIcon.java:398)
                                               at android.view.View.onTouchEvent(View.java:11233)
                                               at com.miui.home.launcher.ItemIcon.onTouchEvent(ItemIcon.java:376)
                                               at android.view.View.dispatchTouchEvent(View.java:10036)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2628)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at com.miui.home.launcher.CellLayout.dispatchTouchEvent(CellLayout.java:507)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at com.miui.home.launcher.Workspace.dispatchTouchEvent(Workspace.java:689)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at com.miui.home.launcher.MinusOneScreenView.dispatchTouchEvent(MinusOneScreenView.java:120)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at com.miui.home.launcher.ForceTouchLayer.dispatchTouchEvent(ForceTouchLayer.java:99)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                               at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)
                                               at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                               at android.app.Activity.dispatchTouchEvent(Activity.java:3195)
03-22 10:12:57.518 2949-2949/? E/Launcher:     at com.miui.home.launcher.Launcher.dispatchTouchEvent(Launcher.java:2853)
                                               at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
                                               at android.view.View.dispatchPointerEvent(View.java:10258)
                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4524)
                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4389)
                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3929)
                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3982)
                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3948)
                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4075)
                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3956)
                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4132)
                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3929)
                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3982)
                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3948)
                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3956)
                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3929)
                                               at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6339)
                                               at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6313)
                                               at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6274)
                                               at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6445)
                                               at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
                                               at android.os.MessageQueue.nativePollOnce(Native Method)
                                               at android.os.MessageQueue.next(MessageQueue.java:323)
                                               at android.os.Looper.loop(Looper.java:142)
                                               at android.app.ActivityThread.main(ActivityThread.java:6365)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
03-22 10:12:57.826 646-2633/? E/ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]

**Comment by cundong** [comment]
仔细看：

**android:exported="false"**

这种，当然不可见。

**Comment by 272152441** [comment]
@cundong  刚刚看到，怪不得。头一次遇到LAUNCHER的activity设置成android:exported="false"这种情况。多谢了。
