### ISSUE TITLE
系统App加载插件， 插件中需要加载/system/lib/***.so  报无权限Exception

### ISSUE THREAD

**Issue by jessema** [Qihoo360/RePlugin#532]
#### 问题详细描述 Detailed description of the problem
开发一个系统app， app用到的插件需要加载系统lib， 但是报无权限Exception。

01-01 08:00:37.217  3941  4004 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libjninativebitmap.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
01-01 08:00:37.217  3941  4004 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
01-01 08:00:37.217  3941  4004 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)

请问如何破？

**Comment by Alex-Linrk** [comment]
我也遇到了这个问题，还没解决，根据官方的说法应该是so包没处理好，我试了官方Wiki方式，还是不行，你可以参考官方的Wiki：看是否有帮助https://github.com/Qihoo360/RePlugin/wiki/%E6%8F%92%E4%BB%B6%E7%9A%84%E7%BB%84%E4%BB%B6#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8so%E5%BA%93

**Comment by huanfeng** [comment]
应该是在8.0系统上有问题吧?
8.0开始对so库做了限制, 可以找一下相关的问题.
如果是自己定制系统, 可以加入白名单或直接修改linker
