### ISSUE TITLE
android studio 升级到3.1 初始化错误

### ISSUE THREAD

**Issue by Bleach1** [Qihoo360/RePlugin#535]
#### 问题详细描述 Detailed description of the problem

java.lang.ExceptionInInitializerError
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964)
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4319)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by Bleach1** [comment]
换成非继承方式

**Comment by hprostudy** [comment]
Android studio3.1.2 同问
java.lang.ExceptionInInitializerError
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964)
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)
        at com.qq.reader.AbsReaderApplication.attachBaseContext(AbsReaderApplication.java:316)
        at com.qq.reader.ReaderDebugApplication.attachBaseContext(ReaderDebugApplication.java:57)
        at android.app.Application.attach(Application.java:199)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
        at android.app.Instrumentation.newApplication(Instrumentation.java:993)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:603)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5168)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5985)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.Class.getInterfaces()' on a null object reference
        at com.qihoo360.replugin.utils.ReflectUtils.getField(ReflectUtils.java:86)
        at com.qihoo360.replugin.utils.ReflectUtils.readField(ReflectUtils.java:108)
        at com.qihoo360.replugin.utils.ReflectUtils.readStaticField(ReflectUtils.java:100)
        at com.qihoo360.replugin.helper.HostConfigHelper.readField(HostConfigHelper.java:171)
        at com.qihoo360.replugin.helper.HostConfigHelper.<clinit>(HostConfigHelper.java:83)
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60) 
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964) 
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67) 
        at com.qq.reader.AbsReaderApplication.attachBaseContext(AbsReaderApplication.java:316) 
        at com.qq.reader.ReaderDebugApplication.attachBaseContext(ReaderDebugApplication.java:57) 
        at android.app.Application.attach(Application.java:199) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1009) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:993) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:603) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5168) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5985) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)

**Comment by longkehuawei** [comment]
解决了吗？
