### ISSUE TITLE
安装后启动插件的MainActivity崩溃

### ISSUE THREAD

**Issue by kylin17** [Qihoo360/RePlugin#545]
#### 问题详细描述 Detailed description of the problem
插件为第三方提供的，且检查过插件的配置是按照RePlugin文档中的配置来做的，从崩溃日志来看，貌似和插件中使用了蓝牙模块有关，有遇到过类似的问题吗？

#### 复现问题步骤 Steps to reproduce the problem
1. 启动host app，通过按钮点击出发插件安装；
2. 程序崩溃

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：Andorid4.4
Android 手机型号&ROM(Phone model & ROM): 
电视机顶盒OS

#### Logcat上下文 Logcat context

```
04-18 17:37:54.915 18892-18892/com.test.app E/PluginServiceClient: getProcessByComponentName(): Fetch Component List Error! pn=com.android.bluetooth
04-18 17:37:54.939 2583-2583/com.android.bluetooth E/bt_gap_api.c: [GAP] btmtk_host_cache_write open error 2: No such file or directory
    [GAP] btmtk_host_cache_init open error 2: No such file or directory
04-18 17:37:54.939 2583-2583/com.android.bluetooth E/bt_gap_api.c: [GAP] btmtk_paired_dev_cache_init open error 2: No such file or directory
04-18 17:37:54.957 2583-2583/com.android.bluetooth E/HeadsetStateMachine: Could not bind to Bluetooth Headset Phone Service
04-18 17:37:54.957 2583-2583/com.android.bluetooth W/BluetoothHeadsetServiceJni: Cleaning up Bluetooth Handsfree Interface before initializing...
04-18 17:37:54.958 2583-2583/com.android.bluetooth W/BluetoothHeadsetServiceJni: Cleaning up Bluetooth Handsfree callback object
04-18 17:37:54.960 2583-2583/com.android.bluetooth W/BluetoothA2dpServiceJni: Cleaning up A2DP Interface before initializing...
04-18 17:37:54.961 2583-2583/com.android.bluetooth W/BluetoothA2dpServiceJni: Cleaning up A2DP callback object
04-18 17:37:54.961 2583-2583/com.android.bluetooth W/BluetoothAvrcpServiceJni: Cleaning up Avrcp Interface before initializing...
04-18 17:37:54.961 2583-2583/com.android.bluetooth W/BluetoothAvrcpServiceJni: Cleaning up Avrcp callback object
04-18 17:37:54.968 2583-2583/com.android.bluetooth W/BluetoothHidServiceJni: Cleaning up Bluetooth HID Interface before initializing...
04-18 17:37:54.968 2583-2583/com.android.bluetooth W/BluetoothHidServiceJni: Cleaning up Bluetooth GID callback object
04-18 17:37:54.970 2583-2583/com.android.bluetooth W/BluetoothHealthServiceJni: Cleaning up Bluetooth Health Interface before initializing...
04-18 17:37:54.970 2583-2583/com.android.bluetooth W/BluetoothHealthServiceJni: Cleaning up Bluetooth Health callback object
04-18 17:37:54.988 18892-19150/com.test.app E/PluginProviderClient: getProcessByAuthority(): Not register! pn=com.test.app; au=settings
04-18 17:37:55.018 18892-18892/com.test.app E/TelephonyManager: cts.appProcess.processName:com.test.app
04-18 17:37:55.044 18892-18892/com.test.app W/dalvikvm: VFY: unable to resolve virtual method 439: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
04-18 17:37:55.173 18892-18892/com.test.app W/libc: pthread_create sched_setscheduler call failed: Operation not permitted
04-18 17:37:55.223 18892-18892/com.test.app E/CAE_LOG: resource file not found
    CAEInit failed ret=-5
    CAEDestroy(42ab7008)[in]
04-18 17:37:55.233 18892-18892/com.test.app A/libc: Fatal signal 11 (SIGSEGV) at 0x632e6e69 (code=1), thread 18892 (om.test.app)
04-18 17:37:55.782 1978-19176/system_process W/ActivityManager:   Force finishing activity com.test.app/.MainActivity
04-18 17:37:55.800 1978-2032/system_process W/InputDispatcher: channel '2ce79f20 com.test.app/com.test.app.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-18 17:37:55.800 1978-2032/system_process E/InputDispatcher: channel '2ce79f20 com.test.app/com.test.app.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-18 17:37:55.836 1978-2232/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '2ce79f20 com.test.app/com.test.app.MainActivity (server)'
04-18 17:37:55.868 1978-19176/system_process W/ActivityManager: Exception thrown during pause
    android.os.DeadObjectException
        at android.os.BinderProxy.transact(Native Method)
        at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2469)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2337)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2099)
        at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:10491)
        at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:10384)
        at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:11029)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:10580)
        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
04-18 17:37:55.873 1978-19176/system_process W/ActivityManager:   Force finishing activity com.amt.launcherah/.activity.MainActivity
04-18 17:37:55.947 3540-3540/com.amt.launcherah W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1209 android.content.ContextWrapper.sendBroadcast:365 android.app.ActivityThread.performResumeActivity:2785 android.app.ActivityThread.handleResumeActivity:2823 android.app.ActivityThread$H.handleMessage:1238 
04-18 17:37:55.951 3540-3540/com.amt.launcherah W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1209 android.content.ContextWrapper.sendBroadcast:365 android.app.ActivityThread.performPauseActivity:3061 android.app.ActivityThread.performPauseActivity:3023 android.app.ActivityThread.handlePauseActivity:3001 
04-18 17:37:55.981 10109-10109/com.amt.strategy W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1209 android.content.ContextWrapper.sendBroadcast:365 android.app.ActivityThread.performResumeActivity:2785 android.app.ActivityThread.handleResumeActivity:2823 android.app.ActivityThread$H.handleMessage:1238 
04-18 17:37:56.096 10109-10109/com.amt.strategy W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1209 android.content.ContextWrapper.sendBroadcast:365 android.app.ActivityThread.performPauseActivity:3061 android.app.ActivityThread.performPauseActivity:3023 android.app.ActivityThread.handlePauseActivity:3001 
04-18 17:37:56.136 3540-3540/com.amt.launcherah W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1209 android.content.ContextWrapper.sendBroadcast:365 android.app.ActivityThread.performResumeActivity:2785 android.app.ActivityThread.handleResumeActivity:2823 android.app.ActivityThread.handleLaunchActivity:2250 
04-18 17:37:56.139 3540-3540/com.amt.launcherah E/ViewRootImpl: 201409092 enable acc for view=com.amt.launcherah/com.amt.launcherah.activity.MainActivity
04-18 17:37:56.202 1978-1990/system_process E/ViewRootImpl: 201409092 enable acc for view=Starting com.amt.launcherah
04-18 17:37:56.321 1978-2232/system_process W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 18892 uid 10063
04-18 17:37:56.329 2165-2176/com.hisilicon.android.inputmethod.remote W/Binder: Caught a RuntimeException from the binder stub implementation.
    java.lang.NullPointerException
        at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
        at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)
04-18 17:37:56.413 1978-1990/system_process W/WindowManager: Rebuild removed 7 windows but added 6
    java.lang.RuntimeException: here
        at com.android.server.wm.WindowManagerService.rebuildAppWindowListLocked(WindowManagerService.java:8072)
        at com.android.server.wm.WindowManagerService.rebuildAppWindowListLocked(WindowManagerService.java:8008)
        at com.android.server.wm.WindowManagerService.handleAnimatingStoppedAndTransitionLocked(WindowManagerService.java:8752)
        at com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner(WindowManagerService.java:9266)
        at com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedLoop(WindowManagerService.java:8224)
        at com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLocked(WindowManagerService.java:8166)
        at com.android.server.wm.WindowManagerService.access$300(WindowManagerService.java:157)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7200)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
04-18 17:37:56.415 1978-1990/system_process W/WindowManager: This window was lost: Window{2ce54720 u0 com.amt.launcherah/com.amt.launcherah.activity.MainActivity}
    mDisplayId=0 mSession=Session{2cd5f080 3540:1000} mClient=android.os.BinderProxy@2d79a1f0
    mOwnerUid=1000 mShowToOwnerOnly=true package=com.amt.launcherah appop=NONE
    mAttrs=WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=1 fl=#1810100 pfl=0x8 wanim=0x10302a1}
    Requested w=1280 h=720 mLayoutSeq=318
    mBaseLayer=21000 mSubLayer=0 mAnimLayer=21000+0=21000 mLastLayer=21020
    mToken=AppWindowToken{2d8f5440 token=Token{2cdd74c0 ActivityRecord{2cdca1e8 u0 com.amt.launcherah/.activity.MainActivity t15}}}
    mRootToken=AppWindowToken{2d8f5440 token=Token{2cdd74c0 ActivityRecord{2cdca1e8 u0 com.amt.launcherah/.activity.MainActivity t15}}}
    mAppToken=AppWindowToken{2d8f5440 token=Token{2cdd74c0 ActivityRecord{2cdca1e8 u0 com.amt.launcherah/.activity.MainActivity t15}}}
    mViewVisibility=0x0 mHaveFrame=true mObscured=true
    mSeq=0 mSystemUiVisibility=0x0
    mGivenContentInsets=[0,0][0,0] mGivenVisibleInsets=[0,0][0,0]
    mConfiguration={1.0 ?mcc?mnc zh_CN ldltr sw720dp w1280dp h720dp 160dpi xlrg long land finger -keyb/v/h dpad/v s.4}
    mHasSurface=true mShownFrame=[0.0,0.0][1280.0,720.0] isReadyForDisplay()=false
    mFrame=[0,0][1280,720] last=[0,0][1280,720]
    mSystemDecorRect=[0,0][1280,720] last=[0,0][1280,720]
    Frames: containing=[0,0][1280,720] parent=[0,0][1280,720]
        display=[0,0][1280,720] overscan=[0,0][1280,720]
        content=[0,0][1280,720] visible=[0,0][1280,720]
        decor=[0,0][1280,720]
    Cur insets: overscan=[0,0][0,0] content=[0,0][0,0] visible=[0,0][0,0]
    Lst insets: overscan=[0,0][0,0] content=[0,0][0,0] visible=[0,0][0,0]
    WindowStateAnimator{2d7d5560 com.amt.launcherah/com.amt.launcherah.activity.MainActivity}:
      mSurface=Surface(name=com.amt.launcherah/com.amt.launcherah.activity.MainActivity)
      mDrawState=READY_TO_SHOW mLastHidden=true
      Surface: shown=false layer=21020 alpha=0.0 rect=(0.0,0.0) 1280.0 x 720.0
      mShownAlpha=0.0 mAlpha=1.0 mLastAlpha=0.0
      mGlobalScale=1.0 mDsDx=1.0 mDtDx=0.0 mDsDy=0.0 mDtDy=1.0
    mExiting=false mRemoveOnExit=false mDestroying=true mRemoved=false
    Current app token list:
04-18 17:37:56.417 1978-1990/system_process W/WindowManager: Final window list:
04-18 17:37:56.863 19205-19211/? E/jdwp: Failed sending reply to debugger: Broken pipe
04-18 17:37:57.117 3540-3540/com.amt.launcherah W/AIE_V_TextViewMg: NO KEY:TextColor
04-18 17:37:57.184 1978-17887/system_process E/SkParamService: SkParamList not contains param: itv_log_open, try get it from database.
04-18 17:37:57.185 1978-17887/system_process E/SkParamService: mSkParamDB has no param:itv_log_open
04-18 17:37:57.214 19205-19205/? W/dalvikvm: VFY: unable to resolve static method 3268: Lcom/bestv/ott/hal/BSPSystem;.getInstance (Ljava/lang/String;Ljava/lang/String;)Lcom/bestv/ott/hal/BSPSystem;
04-18 17:37:57.215 19205-19205/? W/dalvikvm: VFY: unable to resolve static method 3268: Lcom/bestv/ott/hal/BSPSystem;.getInstance (Ljava/lang/String;Ljava/lang/String;)Lcom/bestv/ott/hal/BSPSystem;
04-18 17:37:57.216 19205-19205/? W/dalvikvm: VFY: unable to resolve static method 3268: Lcom/bestv/ott/hal/BSPSystem;.getInstance (Ljava/lang/String;Ljava/lang/String;)Lcom/bestv/ott/hal/BSPSystem;
04-18 17:37:57.217 19205-19205/? W/dalvikvm: VFY: unable to resolve static method 3268: Lcom/bestv/ott/hal/BSPSystem;.getInstance (Ljava/lang/String;Ljava/lang/String;)Lcom/bestv/ott/hal/BSPSystem;
04-18 17:37:57.218 19205-19205/? W/dalvikvm: VFY: unable to resolve static method 3268: Lcom/bestv/ott/hal/BSPSystem;.getInstance (Ljava/lang/String;Ljava/lang/String;)Lcom/bestv/ott/hal/BSPSystem;
04-18 17:37:57.220 19205-19205/? W/dalvikvm: VFY: unable to resolve static method 3268: Lcom/bestv/ott/hal/BSPSystem;.getInstance (Ljava/lang/String;Ljava/lang/String;)Lcom/bestv/ott/hal/BSPSystem;
04-18 17:37:57.643 19205-19205/? E/HandlerCrash: init caught exception crash
04-18 17:37:57.653 1978-2218/system_process E/ActivityManager: ellison. app not allow running background: com.bestv.ott.baseservices, userId: 0, uid: 10030, pid: 19205, otherProcess has fg act: false, app.setSchedGroup: 0, isInstallerActivityTop=false
04-18 17:37:57.665 19205-19205/? E/CrashReport: startReportCrashInfo reportServerUrl=
04-18 17:37:57.674 19205-19224/? W/System.err: java.io.FileNotFoundException: /storage/emulated/0/UnknownVersion/temp_config.ini: open failed: ENOENT (No such file or directory)
04-18 17:37:57.680 19205-19224/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:409)
        at java.io.FileInputStream.<init>(FileInputStream.java:78)
        at java.io.FileReader.<init>(FileReader.java:42)
04-18 17:37:57.681 19205-19224/? W/System.err:     at com.fun.crash.FileUtil.readHostFromFile(FileUtil.java:63)
        at com.fun.crash.CrashReport$CrashReportTask.executeTask(CrashReport.java:179)
04-18 17:37:57.682 19205-19224/? W/System.err:     at com.fun.crash.CrashReport$1.run(CrashReport.java:49)
04-18 17:37:57.683 19205-19224/? W/System.err:     at java.lang.Thread.run(Thread.java:841)
    Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
04-18 17:37:57.684 19205-19224/? W/System.err:     at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
        at libcore.io.IoBridge.open(IoBridge.java:393)
04-18 17:37:57.685 19205-19224/? W/System.err: ... 6 more
04-18 17:37:57.741 3540-3540/com.amt.launcherah E/AIE_V_ViewMg: commandId=833902
04-18 17:37:57.754 19205-19205/? W/dalvikvm: VFY: unable to resolve instance field 9
04-18 17:37:57.755 19205-19205/? W/dalvikvm: VFY: unable to resolve virtual method 53: Landroid/app/Notification;.getSmallIcon ()Landroid/graphics/drawable/Icon;
04-18 17:37:57.756 19205-19205/? W/dalvikvm: VFY: unable to resolve virtual method 52: Landroid/app/Notification;.getLargeIcon ()Landroid/graphics/drawable/Icon;
04-18 17:37:57.758 19205-19205/? W/dalvikvm: VFY: unable to resolve instance field 9
04-18 17:37:57.759 19205-19205/? W/dalvikvm: VFY: unable to resolve virtual method 53: Landroid/app/Notification;.getSmallIcon ()Landroid/graphics/drawable/Icon;
04-18 17:37:57.760 19205-19205/? W/dalvikvm: VFY: unable to resolve virtual method 52: Landroid/app/Notification;.getLargeIcon ()Landroid/graphics/drawable/Icon;
04-18 17:37:57.761 19205-19205/? W/dalvikvm: VFY: unable to resolve instance field 9
04-18 17:37:57.769 3540-3571/com.amt.launcherah W/ReactNativeJS: getRecorderZYJHInfo>>>url:http://117.71.38.86:8181/service_zy/watch.do?uid=pwg253>>>error:TypeError: Network request failed
04-18 17:37:57.811 3540-3540/com.amt.launcherah E/AIE_V_ImageMg: commandId=833902
04-18 17:37:57.902 3540-3540/com.amt.launcherah E/AIE_V_ImageMg: commandId=833903
04-18 17:37:57.997 19205-19205/com.bestv.ott.baseservices E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.morgoo.droidplugin.hook.handle.PluginInstrumentation.fixTaskDescription
04-18 17:37:57.997 19205-19205/com.bestv.ott.baseservices W/dalvikvm: VFY: unable to resolve new-instance 35 (Landroid/app/ActivityManager$TaskDescription;) in Lcom/morgoo/droidplugin/hook/handle/PluginInstrumentation;
04-18 17:37:57.998 19205-19205/com.bestv.ott.baseservices E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.morgoo.droidplugin.hook.handle.PluginInstrumentation.fixTaskDescription
04-18 17:37:57.998 19205-19205/com.bestv.ott.baseservices W/dalvikvm: VFY: unable to resolve new-instance 35 (Landroid/app/ActivityManager$TaskDescription;) in Lcom/morgoo/droidplugin/hook/handle/PluginInstrumentation;
04-18 17:37:58.755 19205-19241/com.bestv.ott.baseservices E/UpgradeThread: [doQueryUpgrade] build retrofit error
    [doUpgrade] Upgrade no response
04-18 17:38:00.255 2690-19257/com.skyworth.ahctc.skyinforeport E/InfoReportService: PostToServer-->[http://sta.jisu8.cn/stat?id=1001&key=69C30E893A4CC03F&account=pwg253&action=app&appName=Launcher&plat=中兴&vlauncher=&vterminal=SKYWORTH_E900_AH-CTC_3.0.8]
04-18 17:38:00.314 2690-19257/com.skyworth.ahctc.skyinforeport E/InfoReportService: PostToServer--><---
04-18 17:38:00.969 1978-2215/system_process E/SkParamService: SkParamList not contains param: skyworth.params.tr069.bak_acs, try get it from database.
04-18 17:38:00.971 1978-2215/system_process E/SkParamService: mSkParamDB has no param:skyworth.params.tr069.bak_acs
04-18 17:38:01.019 1978-2231/system_process W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1209 com.android.server.SkParamService.send_broadcast:352 com.skyworth.sys.param.ISkParamManager$Stub.onTransact:151 android.os.Binder.execTransact:404 dalvik.system.NativeStart.run:-2 
04-18 17:38:02.986 2583-19142/com.android.bluetooth E/BluetoothAdapterState: Error enabling Bluetooth
04-18 17:38:02.990 1978-1998/system_process E/BluetoothA2dp: java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothA2dp$2@2cdb7258
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:931)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1681)
        at android.bluetooth.BluetoothA2dp$1.onBluetoothStateChange(BluetoothA2dp.java:121)
        at com.android.server.BluetoothManagerService.sendBluetoothStateCallback(BluetoothManagerService.java:487)
        at com.android.server.BluetoothManagerService.bluetoothStateChangeHandler(BluetoothManagerService.java:1132)
        at com.android.server.BluetoothManagerService.access$2800(BluetoothManagerService.java:48)
        at com.android.server.BluetoothManagerService$BluetoothHandler.handleMessage(BluetoothManagerService.java:867)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
04-18 17:38:02.992 1978-1998/system_process E/BluetoothHeadset: java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothHeadset$2@2ce3e270
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:931)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1681)
        at android.bluetooth.BluetoothHeadset$1.onBluetoothStateChange(BluetoothHeadset.java:239)
        at com.android.server.BluetoothManagerService.sendBluetoothStateCallback(BluetoothManagerService.java:487)
        at com.android.server.BluetoothManagerService.bluetoothStateChangeHandler(BluetoothManagerService.java:1132)
        at com.android.server.BluetoothManagerService.access$2800(BluetoothManagerService.java:48)
        at com.android.server.BluetoothManagerService$BluetoothHandler.handleMessage(BluetoothManagerService.java:867)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
04-18 17:38:02.994 1978-1998/system_process E/BluetoothManagerService: recoverBluetoothServiceFromError
04-18 17:38:03.502 2583-2583/com.android.bluetooth E/bt_ext_apis.c: [JNI] server socket uninitialized
04-18 17:38:27.188 1978-2190/system_process E/SkParamService: SkParamList not contains param: itv_log_open, try get it from database.
04-18 17:38:27.190 1978-2190/system_process E/SkParamService: mSkParamDB has no param:itv_log_open
```

**Comment by chinaShawn** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/19618811/62456213-8b3f1000-b7aa-11e9-8bc9-d3fc94c94ff0.png">
发现一个问题，这个地方的进程名显示不全，不知道会不会有影响
