### ISSUE TITLE
replugin使用dagger.android库报错

### ISSUE THREAD

**Issue by orange7** [Qihoo360/RePlugin#550]
#### 问题详细描述 Detailed description of the problem
插件和宿主工程用到了google的dagger.android库，宿主和插件的application里面需要implement dagger.android.HasActivityInjector，并且在application的onCreate中执行
DaggerAppComponent
                .builder()
                .appModule(new AppModule(this))
                .build().inject(this);
插件和宿主的项目单独运行都没有问题，但是将插件放到宿主里面运行以后，在启动插件的时候报错，
报宿主的 application does not implement dagger.android.HasActivityInjector
#### 复现问题步骤 Steps to reproduce the problem
1. 按Dagger.Android补充库https://google.github.io/dagger/android配置
2. 启动插件报错

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：26
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
04-26 15:07:06.372 21312-21312/com.crowdsource E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.crowdsource, PID: 21312
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.crowdsource/com.crowdsource.loader.a.ActivityN1NRNTS3}: java.lang.RuntimeException: com.crowdsource.MainApplication does not implement dagger.android.HasActivityInjector
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2722)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2783)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6259)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)
                                                                  Caused by: java.lang.RuntimeException: com.crowdsource.MainApplication does not implement dagger.android.HasActivityInjector
                                                                     at dagger.android.AndroidInjection.inject(AndroidInjection.java:48)
                                                                     at com.baselib.base.MvpActivity.onCreate(MvpActivity.java:20)
                                                                     at android.app.Activity.performCreate(Activity.java:6731)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2675)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2783) 
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6259) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)

**Comment by orange7** [comment]
dagger.android中AndroidInjection 的
public static void inject(Activity activity) {
    checkNotNull(activity, "activity");
    Application application = activity.getApplication();
    if (!(application instanceof HasActivityInjector)) {
      throw new RuntimeException(
          String.format(
              "%s does not implement %s",
              application.getClass().getCanonicalName(),
              HasActivityInjector.class.getCanonicalName()));
    }

    AndroidInjector<Activity> activityInjector =
        ((HasActivityInjector) application).activityInjector();
    checkNotNull(
        activityInjector,
        "%s.activityInjector() returned null",
        application.getClass().getCanonicalName());

    activityInjector.inject(activity);
  } 
插件里面执行activity.getApplication()获取到的是宿主的application，所以报错

**Comment by AItsuki** [comment]
然后大佬你是怎么解决这个问题的呢
