### ISSUE TITLE
公共jar包中的BaseActivity无法正常Load

### ISSUE THREAD

**Issue by Alex-Linrk** [Qihoo360/RePlugin#553]
问题详细描述 ：
插件无法正常load公共jar包中BaseActivity,BaseActivity继承RxAppCompatActivity
由于项目需要，抽象出一个BaseActivity,并放在公共jar包中，打包方式采用的是demo中的jar包生成方式。
在插件项目中采用compileOnly files引入，并build出一个apk，改名成插件名.jar包
在host中启动插件，提示java.lang.ClassNotFoundException: 

gradle viersion:3.1.2
replugin-host-lib Version:2.2.4 
rePlugin-plugin-lib Version:2.2.4

Android API Version：26
Android 手机型号&ROM(Phone model & ROM):  小米6 

#### Logcat上下文 Logcat context
04-27 17:11:44.029 16735-16735/com.netintellisenselitejq E/ws001: com.netintellisenselitejq.autocall.callactivity.AutoCallTestActivity
    java.lang.ClassNotFoundException: com.netintellisenselitejq.autocall.callactivity.AutoCallTestActivity
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:96)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.qihoo360.loader2.PluginProcessPer.bindActivity(PluginProcessPer.java:313)
        at com.qihoo360.loader2.PluginProcessPer.allocActivityContainer(PluginProcessPer.java:161)
        at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:437)
        at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:268)
        at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
        at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
        at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:247)
        at com.netintellisenselitejq.adapter.MainActionGidAdapter$ItemClickListener.onClick(MainActionGidAdapter.java:308)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6665)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/leadhead/baselibrary/base/BaseActivity;
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:282)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275)
        at dalvik.system.DexPathList$Element.findClass(DexPathList.java:677)
        at dalvik.system.DexPathList.findClass(DexPathList.java:466)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:91)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:96) 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312) 
        at com.qihoo360.loader2.PluginProcessPer.bindActivity(PluginProcessPer.java:313) 
        at com.qihoo360.loader2.PluginProcessPer.allocActivityContainer(PluginProcessPer.java:161) 
        at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:437) 
        at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:268) 
        at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380) 
        at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327) 
        at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:247) 
        at com.netintellisenselitejq.adapter.MainActionGidAdapter$ItemClickListener.onClick(MainActionGidAdapter.java:308) 
        at android.view.View.performClick(View.java:6266) 
        at android.view.View$PerformClick.run(View.java:24730) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6665) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.leadhead.baselibrary.base.BaseActivity" on path: DexPathList[[zip file "/data/user/0/com.netintellisenselitejq/app_plugins_v3/autocall-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/autocall-10-10-1, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:96)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at dalvik.system.DexFile.defineClassNative(Native Method) 
        at dalvik.system.DexFile.defineClass(DexFile.java:282) 
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275) 
        at dalvik.system.DexPathList$Element.findClass(DexPathList.java:677) 
        at dalvik.system.DexPathList.findClass(DexPathList.java:466) 
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:91) 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379) 
        at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:96) 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312) 
        at com.qihoo360.loader2.PluginProcessPer.bindActivity(PluginProcessPer.java:313) 
        at com.qihoo360.loader2.PluginProcessPer.allocActivityContainer(PluginProcessPer.java:161) 
        at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:437) 
        at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:268) 
        at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380) 
        at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327) 
        at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:247) 
        at com.netintellisenselitejq.adapter.MainActionGidAdapter$ItemClickListener.onClick(MainActionGidAdapter.java:308) 
        at android.view.View.performClick(View.java:6266) 
        at android.view.View$PerformClick.run(View.java:24730) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6665) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by Alex-Linrk** [comment]
后来解决了，至于原因，完全不知道
