### ISSUE TITLE
插件中使用第三方sdk中启动activity崩溃，报错requires the FLAG_ACTIVITY_NEW_TASK flag

### ISSUE THREAD

**Issue by kongpinde** [Qihoo360/RePlugin#558]
#### 问题详细描述 Detailed description of the problem
插件中使用第三方sdk，第三方sdk中启动Activity崩溃，报错android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
因为启动activity这个过程在第三方sdk中，不是插件中自己写的代码，所以没法添加设置setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)代码，请问应该如何避免这个问题？

#### 复现问题步骤 Steps to reproduce the problem
必现

#### Logcat上下文 Logcat context
05-02 17:14:04.343 6426-6426/com.replugin.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.replugin.demo, PID: 6426
                                                                 android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                                     at android.app.ContextImpl.startActivity(ContextImpl.java:1034)
                                                                     at android.app.ContextImpl.startActivity(ContextImpl.java:1021)
                                                                     at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
                                                                     at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
                                                                     at com.qihoo360.loader2.PluginContext.startActivity(PluginContext.java:472)
                                                                     at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:297)
                                                                     at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
                                                                     at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
                                                                     at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:167)
                                                                     at com.qihoo360.i.Factory2.startActivity(Factory2.java:119)
                                                                     at com.qihoo360.loader2.PluginContext.startActivity(PluginContext.java:467)
                                                                     at com.ipaynow.plugin.api.a.a(Unknown Source)
                                                                     at com.ipaynow.plugin.api.IpaynowPlugin.pay(Unknown Source)
                                                                     at com.linyou.sdk.payment.LinYouNOWPAY$1.handleMessage(LinYouNOWPAY.java:47)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5019)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by cundong** [comment]
这种情况，说明你当时这个场景， 开启Activity时，未使用Activity的上下文。

例如：用Application的上下文，或Service的上下文，触发了startActivity操作，具体还得你自己根据业务场景分析一下。

**Comment by kongpinde** [comment]
@cundong 
感谢！
确实是这样的，因为某些原因，启动的是第三方的sdk中的activity，无法使用activity的上下文来启动（因为我们也是第三方，所以是通过反射来初始化我们sdk，然后再初始化另外的第三方sdk），所以直接是通过Replugin.getPluginContext来获取的插件上下文传递给第三方sdk，因为这个过程之前没有启动一个activity或者启动了已经销毁了，到这一步的时候已经没有activity的上下文了。请问除了在这个过程中加入一个activity来转换外，是否还有其他方式？
