### ISSUE TITLE
Resource "com.xxxx.xxxx:id/scrollIndicatorUp" (7f070052)  is not a Drawable (color or path): 

### ISSUE THREAD

**Issue by wogenhaosini** [Qihoo360/RePlugin#566]
#### 问题详细描述 Detailed description of the problem

宿主包内置二个插件 都运行ui进程，初始状态时两个插件相互跳转是OK的，但是升级一个版本后出现奔溃。

我怀疑是resource id 没有固定，变更了导致奔溃。或者有没有固定id的解决方案？

#### 复现问题步骤 Steps to reproduce the problem
1. 内置二个插件。
2.重新打包  resurce id 改变 。
3.插件相互跳转。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：Android 5.0.2,level 21
Android 手机型号&ROM(Phone model & ROM): Gemotech/sabresd_6dq （工控机，应该是拿开源改的系统）

#### Logcat上下文 Logcat context
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxx.xxxx/com.xxxx.xxxx.loader.a.ActivityN1STPNTS5}: android.content.res.Resources$NotFoundException: Resource "com.xxxx.xxxx:id/scrollIndicatorUp" (7f070052)  is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=2 r=0x7f070052}
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
  at android.app.ActivityThread.access$800(ActivityThread.java:144)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5221)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: android.content.res.Resources$NotFoundException: Resource "com.xxxx.xxxx:id/scrollIndicatorUp" (7f070052)  is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=2 r=0x7f070052}
  at android.content.res.Resources.loadDrawableForCookie(Resources.java:2390)
  at android.content.res.Resources.loadDrawable(Resources.java:2330)
  at android.content.res.Resources.getDrawable(Resources.java:758)
  at android.content.Context.getDrawable(Context.java:402)
  at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:351)
  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
  at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:755)
  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
  at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:87)
  at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:128)
  at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:149)
  at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:29)
  at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:54)
  at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:202)
  at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:183)
  at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
  at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:70)
  at com.zlx.serialport.activity.IndexActivity.onCreate(IndexActivity.java:64)
  at android.app.Activity.performCreate(Activity.java:5933)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
  ... 10 more
```

**Comment by luowenyue** [comment]
> 附 JAVA 解决方案： https://github.com/wogenhaosini/ResPkgRemaker.git
> 
> 自定义 PackagerId 0xPPTTNNNN 中的PP段，可不修改aapt实现，但是对kotlin的编译不生效，对java 是成功的，希望有能力者能补上这段。

我的需求是锁定资源id的前缀，搜索到你的库可用，但是尝试后发现id变了 但找不到资源 请问有什么建议 感谢

**Comment by wogenhaosini** [comment]
> > 附 JAVA 解决方案： https://github.com/wogenhaosini/ResPkgRemaker.git
> > 自定义 PackagerId 0xPPTTNNNN 中的PP段，可不修改aapt实现，但是对kotlin的编译不生效，对java 是成功的，希望有能力者能补上这段。
> 
> 我的需求是锁定资源id的前缀，搜索到你的库可用，但是尝试后发现id变了 但找不到资源 请问有什么建议 感谢

我不太明白你这个「锁定资源id的前缀」是什么意思，也是修改PP段嘛？

**Comment by luowenyue** [comment]
> > > 附 JAVA 解决方案： https://github.com/wogenhaosini/ResPkgRemaker.git
> > > 自定义 PackagerId 0xPPTTNNNN 中的PP段，可不修改aapt实现，但是对kotlin的编译不生效，对java 是成功的，希望有能力者能补上这段。
> > 
> > 
> > 我的需求是锁定资源id的前缀，搜索到你的库可用，但是尝试后发现id变了 但找不到资源 请问有什么建议 感谢
> 
> 我不太明白你这个「锁定资源id的前缀」是什么意思，也是修改PP段嘛？

是的 就是锁定PP段 目的就是和你一样的，我尝试后发现调用的地方以及R文件的id都改变了 
但报错仍然是找不到资源
项目中使用了bufferknife 查看发现对应bufferknife生成的R2文件的id还是0x7f开头
会不会可能是这个原因 ？

**Comment by wogenhaosini** [comment]
> > > > 附 JAVA 解决方案： https://github.com/wogenhaosini/ResPkgRemaker.git
> > > > 自定义 PackagerId 0xPPTTNNNN 中的PP段，可不修改aapt实现，但是对kotlin的编译不生效，对java 是成功的，希望有能力者能补上这段。
> > > 
> > > 
> > > 我的需求是锁定资源id的前缀，搜索到你的库可用，但是尝试后发现id变了 但找不到资源 请问有什么建议 感谢
> > 
> > 
> > 我不太明白你这个「锁定资源id的前缀」是什么意思，也是修改PP段嘛？
> 
> 是的 就是锁定PP段 目的就是和你一样的，我尝试后发现调用的地方以及R文件的id都改变了
> 但报错仍然是找不到资源
> 项目中使用了butterknife 查看发现对应butterknife生成的R2文件的id还是0x7f开头
> 会不会可能是这个原因 ？

我没有用到 butterknife 库 ，你可以看看apk面中 resource.arsc 文件的资源id PP段是否已经变更，如果变更了，那就说明 需要对 butterknife 编译过程中进行修改。

**Comment by luowenyue** [comment]
> > > > > 附 JAVA 解决方案： https://github.com/wogenhaosini/ResPkgRemaker.git
> > > > > 自定义 PackagerId 0xPPTTNNNN 中的PP段，可不修改aapt实现，但是对kotlin的编译不生效，对java 是成功的，希望有能力者能补上这段。
> > > > 
> > > > 
> > > > 我的需求是锁定资源id的前缀，搜索到你的库可用，但是尝试后发现id变了 但找不到资源 请问有什么建议 感谢
> > > 
> > > 
> > > 我不太明白你这个「锁定资源id的前缀」是什么意思，也是修改PP段嘛？
> > 
> > 
> > 是的 就是锁定PP段 目的就是和你一样的，我尝试后发现调用的地方以及R文件的id都改变了
> > 但报错仍然是找不到资源
> > 项目中使用了butterknife 查看发现对应butterknife生成的R2文件的id还是0x7f开头
> > 会不会可能是这个原因 ？
> 
> 我没有用到 butterknife 库 ，你可以看看apk面中 resource.arsc 文件的资源id PP段是否已经变更，如果变更了，那就说明 需要对 butterknife 编译过程中进行修改。

查看发现resource.arsc没有改变 是不是也就坐实了编译过程中butterknife影响了结果？

**Comment by wogenhaosini** [comment]
> > > > > > 附 JAVA 解决方案： https://github.com/wogenhaosini/ResPkgRemaker.git
> > > > > > 自定义 PackagerId 0xPPTTNNNN 中的PP段，可不修改aapt实现，但是对kotlin的编译不生效，对java 是成功的，希望有能力者能补上这段。
> > > > > 
> > > > > 
> > > > > 我的需求是锁定资源id的前缀，搜索到你的库可用，但是尝试后发现id变了 但找不到资源 请问有什么建议 感谢
> > > > 
> > > > 
> > > > 我不太明白你这个「锁定资源id的前缀」是什么意思，也是修改PP段嘛？
> > > 
> > > 
> > > 是的 就是锁定PP段 目的就是和你一样的，我尝试后发现调用的地方以及R文件的id都改变了
> > > 但报错仍然是找不到资源
> > > 项目中使用了butterknife 查看发现对应butterknife生成的R2文件的id还是0x7f开头
> > > 会不会可能是这个原因 ？
> > 
> > 
> > 我没有用到 butterknife 库 ，你可以看看apk面中 resource.arsc 文件的资源id PP段是否已经变更，如果变更了，那就说明 需要对 butterknife 编译过程中进行修改。
> 
> 查看发现resource.arsc没有改变 是不是也就坐实了编译过程中butterknife影响了结果？

那就是我的库没有生效。

**Comment by wogenhaosini** [comment]
此问题修改 Resource 中的 0xPP 中的 PP 值即可

1、重新编译 aapt 工具

2、利用 Gradle Transfrom 修改 PP 值 ：https://github.com/wogenhaosini/ResPkgRemaker

3、利用 aapt 编辑参数 可直接在编译过程中 改变 PP 值。

```
android {
   aaptOptions {
    additionalParameters "--warn-manifest-validation", "--allow-reserved-package-id", "--package-id", "0x55"
   }
}
```

**Comment by wingkingbobo** [comment]
> 此问题修改 Resource 中的 0xPP 中的 PP 值即可
> 
> 1、重新编译 aapt 工具
> 
> 2、利用 Gradle Transfrom 修改 PP 值 ：https://github.com/wogenhaosini/ResPkgRemaker
> 
> 3、利用 aapt 编辑参数 可直接在编译过程中 改变 PP 值。
> 
> ```
> android {
>    aaptOptions {
>     additionalParameters "--warn-manifest-validation", "--allow-reserved-package-id", "--package-id", "0x55"
>    }
> }
> ```

[aapt2](https://developer.android.google.cn/studio/command-line/aapt2)解决了这个问题
```groovy
android {
    aaptOptions { 
        additionalParameters '--allow-reserved-package-id', '--package-id', '0x02'
    }
}
```
