### ISSUE TITLE
关于集成百度地图的老问题

### ISSUE THREAD

**Issue by NiceW** [Qihoo360/RePlugin#570]
#### 问题详细描述 Detailed description of the problem
插件集成百度地图宿主调用报错
具体信息如下
百度地图这行执行这行报错
SDKInitializer.initialize(getApplicationContext());
java.lang.RuntimeException: Unable to start activity ComponentInfo{host.dell.com.host/host.dell.com.host.loader.a.ActivityN1NRNTS0}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2855)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2930)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
        at com.baidu.mapsdkplatform.comapi.util.PermissionCheck.init(Unknown Source:33)
        at com.baidu.mapsdkplatform.comapi.a.c(Unknown Source:29)
        at com.baidu.mapsdkplatform.comapi.c.a(Unknown Source:35)
        at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source:0)
        at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source:1)
        at com.test.baidu.MainActivity.onCreate(MainActivity.java:92)
        at android.app.Activity.performCreate(Activity.java:7057)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2930) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6684) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 

这个我看了在前面有人提的问题下面的评论也有提到这个错误 没有解决办法
试过把getApplicationContext()换成RePlugin.getHostContext()或RePlugin.getPluginContext()依然报错
望官方人员释惑
谢谢
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: classpath 'com.qihoo360.replugin:replugin-host-gradle:2.2.4'
rePlugin-plugin-lib/gradle Version: com.qihoo360.replugin:replugin-plugin-gradle:2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by zmaplex** [comment]
我也遇到了这个问题，但是看对比了下，发现  `meta-data`  写在了 `application` 外面。

要写在 `application` 里面
```
 <application
        android:name="com.baidu.location.demo.LocationApplication"
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@android:style/Theme.Black">

        <!-- 声明service组件 -->
        <service
            android:name="com.baidu.location.f"
            android:enabled="true"
            android:process=":remote" >
        </service>

        <!-- AK鉴权 -->
        <!-- meta-data需要写在application中 -->
        <meta-data
            android:name="com.baidu.lbsapi.API_KEY"
            android:value="*******************" />  

        <activity
            android:name="com.baidu.location.demo.MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
   
    </application>
```
