### ISSUE TITLE
公司的项目作为单品开发没问题，作为插件就有问题，求救！

### ISSUE THREAD

**Issue by aifengshen** [Qihoo360/RePlugin#577]
#### 问题详细描述 Detailed description of the problem
公司项目作为单品开发时，可以正常拍照（已完成6.0和7.0的适配），但是集成Replugin作为插件时，就报这个错了。

java.lang.SecurityException: Uid 10443 does not have permission to uri 0 @ content://com.sdjictec.sso.fileprovider/my_images/Image/IMAGE_2018-05-18_144728.jpg

`下面是详细log：`
05-18 14:47:27.130 10856-10856/com.sdjictec.sso D/RePlugin.ws001: set activity intent cl=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.sdjictec.sso/app_p_a/707133631.jar"],nativeLibraryDirectories=[/data/user/0/com.sdjictec.sso/app_p_n/707133631, /system/lib64, /vendor/lib64]]]
    cached filename: com.sdjictec.athomeappcsc -> /data/user/0/com.sdjictec.sso/app_p_a/707133631.jar
    cached componentList /data/user/0/com.sdjictec.sso/app_p_a/707133631.jar -> com.qihoo360.replugin.component.ComponentList@d690950
05-18 14:47:27.131 10856-10856/com.sdjictec.sso D/RePlugin.activity-injector: activity = com.sdjictec.athomeappcsc.core.ui.company.TakePictureActivity@6186634
    ai = ActivityInfo{984a36c com.sdjictec.athomeappcsc.core.ui.company.TakePictureActivity}
    label = 贷后管理
    bitmap = android.graphics.Bitmap@ddd6a7c
    td = TaskDescription Label: 贷后管理 Icon: android.graphics.Bitmap@ddd6a7c IconFilename: null colorPrimary: 0 colorBackground: 0
05-18 14:47:27.145 10856-10856/com.sdjictec.sso V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@320412a
    BoostFramework() : mPerf = com.qualcomm.qti.Performance@912bb1b
05-18 14:47:27.151 10856-11596/com.sdjictec.sso D/RePlugin.ws001: PluginClientHelper.iibc(): Call Plugin! n=ComponentInfo{com.sdjictec.sso/com.baidu.location.f}
05-18 14:47:27.152 10856-11596/com.sdjictec.sso D/RePlugin.ws001: cached filename: com.sdjictec.athomeappcsc -> /data/user/0/com.sdjictec.sso/app_p_a/707133631.jar
    cached componentList /data/user/0/com.sdjictec.sso/app_p_a/707133631.jar -> com.qihoo360.replugin.component.ComponentList@d690950
05-18 14:47:27.152 10856-11596/com.sdjictec.sso D/PluginServiceClient: getProcessByComponentName(): Okay! Process=-100; pn=com.sdjictec.athomeappcsc
05-18 14:47:27.152 10856-11596/com.sdjictec.sso D/RePlugin.ws001: PluginServiceClient.fsmbp(): Exists! p=-100
05-18 14:47:27.156 10856-10856/com.sdjictec.sso D/ActivityThreadInjector: clearCachedDrawables.
05-18 14:47:27.191 10856-10856/com.sdjictec.sso D/baidu_location_client: baidu location connected ...
05-18 14:47:28.904 10856-10856/com.sdjictec.sso D/RePlugin.ws001: start activity with startActivityForResult: intent=Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 (has extras) }
05-18 14:47:28.905 10856-10856/com.sdjictec.sso I/Timeline: Timeline: Activity_launch_request time:4144566
05-18 14:47:28.928 10856-10856/com.sdjictec.sso D/AndroidRuntime: Shutting down VM
05-18 14:47:28.930 10856-10856/com.sdjictec.sso E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sdjictec.sso, PID: 10856
    java.lang.SecurityException: Uid 10443 does not have permission to uri 0 @ content://com.sdjictec.sso.fileprovider/my_images/Image/IMAGE_2018-05-18_144728.jpg
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3149)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1520)
        at android.app.Activity.startActivityForResult(Activity.java:4402)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
        at com.qihoo360.replugin.loader.a.PluginAppCompatActivity.startActivityForResult(Unknown Source)
        at com.qihoo360.replugin.loader.a.PluginAppCompatActivity.startActivityForResult(Unknown Source)
        at com.sdjictec.athomeappcsc.core.ui.company.TakePictureActivity.takepicture(TakePictureActivity.java:356)
        at com.sdjictec.athomeappcsc.core.adapter.TakePictureRecyclerViewAdapter$1.onClick(TakePictureRecyclerViewAdapter.java:75)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22462)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6205)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: com.qihoo360.replugin:replugin-host-gradle:2.2.4
rePlugin-plugin-lib/gradle Version: com.qihoo360.replugin:replugin-plugin-gradle:2.2.4

Android API Version：andorid 7.1.2
Android 手机型号&ROM(Phone model & ROM): 红米4X

**Comment by cundong** [comment]
你这个是fileprovider （Android 7）的 问题，可以参考 DEMO
