### ISSUE TITLE
宿主启动插件中的fragment，它里面包含自定义dialog时，此时dialog无法弹出并报错。

### ISSUE THREAD

**Issue by furan319** [Qihoo360/RePlugin#589]
#### 问题详细描述 Detailed description of the problem
宿主调用插件中的fragment是，当fragment包含自定义dialog时，弹出框无效并报错。dialog需要依附与activity，而插件里面是有fragment，没有ativity。
        mSelectGroupDialog = new DeviceSelectSthDialog(RePlugin.getPluginContext(), locdata, mGroupCallback);
        mSelectGroupDialog.setTitleMsg("选择分组");
        mSelectGroupDialog.show();
异常日志：
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:588)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:313)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
	at android.app.Dialog.show(Dialog.java:322)
	at com.wifiunion.intelligencegate.checkinplugin.fragment.CheckInFragment.showSelectGroupDialog(CheckInFragment.java:1092)
	at com.wifiunion.intelligencegate.checkinplugin.fragment.CheckInFragment.onClick(CheckInFragment.java:383)
RePlugin.getPluginContext() 使用了这个context的，以为要去加载插件里面布局文件，当调用show方法的时候就报错了。

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cundong** [comment]
你这种弹Dialog 的场景，Context 应该使用当前 Activity 的。

**Comment by heiniuniu** [comment]
那dialog 相关的代码和布局都得写到宿主中去吗？

**Comment by JustAllIn** [comment]
mSelectGroupDialog = new DeviceSelectSthDialog(RePlugin.getPluginContext(), locdata, mGroupCallback);
改为
mSelectGroupDialog = new DeviceSelectSthDialog(getActivity(), locdata, mGroupCallback);
即可；
