### ISSUE TITLE
两个插件调用 preload 后，出现 anr

### ISSUE THREAD

**Issue by gzgang** [Qihoo360/RePlugin#593]
#### 问题描述
调用 Replugin.preload(PluginInfo)，出现 anr

#### 复现问题步骤 
下载两个插件，安装后再调用 Replugin.preload(PluginInfo)，出现 anr

#### 其它重要信息 Other important information

replugin-host-lib/gradle 2.2.4:
rePlugin-plugin-lib/gradle 2.2.4:

Android API Version：
魅族 mx4-pro / 7.0

#### Logcat上下文

"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x74fb9950 self=0xeb785400
  | sysTid=13836 nice=-4 cgrp=default sched=0/0 handle=0xeed27534
  | state=S schedstat=( 6741010337 943947902 5416 ) utm=616 stm=58 core=0 HZ=100
  | stack=0xff668000-0xff66a000 stackSize=8MB
  | held mutexes=
  at com.qihoo360.replugin.packages.PluginManagerServer$Stub.updateUsed(PluginManagerServer.java:641)
  - waiting to lock <**0x07dc2998**> (a byte[]) held by thread 90
  at com.qihoo360.replugin.packages.IPluginManagerServer$Stub.onTransact(IPluginManagerServer.java:106)
  at android.os.Binder.execTransact(Binder.java:574)
  at android.os.BinderProxy.transactNative(Native method)
  at android.os.BinderProxy.transact(Binder.java:626)
  at com.qihoo360.loader2.IPluginClient$Stub$Proxy.onReceive(IPluginClient.java:342)
  at com.qihoo360.replugin.component.receiver.PluginReceiverProxy.onReceive(PluginReceiverProxy.java:96)
  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1190)
  at android.os.Handler.handleCallback(Handler.java:836)
  at android.os.Handler.dispatchMessage(Handler.java:103)
  at android.os.Looper.loop(Looper.java:203)
  at android.app.ActivityThread.main(ActivityThread.java:6527)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

"pool-15-thread-2" prio=5 tid=90 TimedWaiting
  | group="main" sCount=1 dsCount=0 obj=0x12cdd430 self=0xc7115400
  | sysTid=14103 nice=0 cgrp=default sched=0/0 handle=0xc44f7920
  | state=S schedstat=( 1797255568 615916606 7754 ) utm=124 stm=55 core=0 HZ=100
  | stack=0xc43f5000-0xc43f7000 stackSize=1038KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x04abb740> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:2127)
  - locked <0x04abb740> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:325)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1034)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1327)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:249)
  at com.qihoo360.replugin.base.ThreadUtils.syncToMainThreadByOthers(ThreadUtils.java:79)
  at com.qihoo360.replugin.base.ThreadUtils.syncToMainThread(ThreadUtils.java:54)
  at com.qihoo360.replugin.base.LocalBroadcastHelper.sendBroadcastSyncUi(LocalBroadcastHelper.java:44)
  at com.qihoo360.loader2.PluginProcessPer.sendIntent(PluginProcessPer.java:236)
  at com.qihoo360.loader2.PluginProcessPer.sendIntentSync(PluginProcessPer.java:227)
  at com.qihoo360.loader2.PluginProcessMain.sendIntent2Process(PluginProcessMain.java:563)
  - locked <0x0a72b679> (a com.qihoo360.loader2.PluginProcessMain$ProcessRecord[])
  at com.qihoo360.loader2.PmHostSvc.sendIntent2Process(PmHostSvc.java:506)
  at com.qihoo360.loader2.PmHostSvc.sendIntent2ProcessSync(PmHostSvc.java:480)
  at com.qihoo360.replugin.base.IPC.sendLocalBroadcast2AllSync(IPC.java:368)
  at com.qihoo360.replugin.packages.PluginInfoUpdater.updateIsUsed(PluginInfoUpdater.java:56)
  at com.qihoo360.replugin.packages.PluginManagerServer.updateUsedLocked(PluginManagerServer.java:501)
  at com.qihoo360.replugin.packages.PluginManagerServer.access$500(PluginManagerServer.java:61)
  at com.qihoo360.replugin.packages.PluginManagerServer$Stub.updateUsed(PluginManagerServer.java:642)
  - locked <**0x07dc2998**> (a byte[])
  at com.qihoo360.replugin.packages.PluginManagerProxy.updateUsedIfNeeded(PluginManagerProxy.java:137)
  at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:824)
  at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:623)
  at com.qihoo360.loader2.Plugin.load(Plugin.java:434)
  at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1093)
  at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1085)
  at com.qihoo360.loader2.PluginCommImpl.loadPluginClassLoader(PluginCommImpl.java:335)
  at com.qihoo360.replugin.packages.PluginFastInstallProvider.install(PluginFastInstallProvider.java:95)
  at com.qihoo360.replugin.packages.PluginFastInstallProvider.update(PluginFastInstallProvider.java:77)
  at android.content.ContentProvider$Transport.update(ContentProvider.java:390)
  at android.content.ContentProviderClient.update(ContentProviderClient.java:331)
  at com.qihoo360.replugin.packages.PluginFastInstallProviderProxy.install(PluginFastInstallProviderProxy.java:69)
  at com.qihoo360.replugin.RePlugin.preload(RePlugin.java:208)

**Comment by wogenhaosini** [comment]
`preload ` 是需要在子线程中调用。

**Comment by taoliuh** [comment]
插件用动态广播代替静态广播。否则安装时PluginReceiverProxy接收到广播最终会查询插件状态，造成preload启动pluginclassloader去常驻进程更新插件是否使用状态，最终依赖同一个锁。造成anr
