### ISSUE TITLE
插件运行Glide出现VectorDrawableCompat异常

### ISSUE THREAD

**Issue by starchen84** [Qihoo360/RePlugin#594]
#### 问题详细描述 Detailed description of the problem
插件运行Glide出现VectorDrawableCompat异常,请问是什么原因导致

#### 复现问题步骤 Steps to reproduce the problem
1. 插件运行Glide
2. 出现VectorDrawableCompat异常

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
Process: com.videogo:p1, PID: 32521
    java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
        at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:756)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
        at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
        at com.bumptech.glide.load.resource.drawable.DrawableDecoderCompat.loadDrawableV7(DrawableDecoderCompat.java:54)
        at com.bumptech.glide.load.resource.drawable.DrawableDecoderCompat.getDrawable(DrawableDecoderCompat.java:41)
        at com.bumptech.glide.request.SingleRequest.loadDrawable(SingleRequest.java:407)
        at com.bumptech.glide.request.SingleRequest.getPlaceholderDrawable(SingleRequest.java:388)
        at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:269)
        at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:41)
        at com.bumptech.glide.RequestManager.track(RequestManager.java:634)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:618)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:678)

**Comment by onlyloveyd** [comment]
请问这个问题有解决嘛？
