### ISSUE TITLE
android8.0下报错java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by xiaoli-style** [Qihoo360/RePlugin#601]
#### 问题详细描述 Detailed description of the problem
在三星S8下运行插件报java.lang.ClassNotFoundException找不到宿主类，宿主类已经打包jar了并在安卓7.0运行正常

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4
Android 手机型号：三星S8 Android8.0

#### Logcat上下文 Logcat context
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/lacc/addfans/utils/application;
	at com.lacc.addfans.plugins.activity_svip.k(activity_svip.java:108)
	at com.lacc.addfans.plugins.activity_svip.onCreate(activity_svip.java:95)
	at android.app.Activity.performCreate(Activity.java:7174)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.ClassNotFoundException: Calling the loadClass method failed (InvocationTargetException)
	at com.qihoo360.replugin.c.a(PluginDexClassLoader.java:140)
	at com.qihoo360.replugin.c.loadClass(PluginDexClassLoader.java:113)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.qihoo360.replugin.c.a(PluginDexClassLoader.java:130)
	... 16 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lacc.addfans.utils.application" on path: DexPathList[[zip file "/data/app/com.lacc.addfans-lpQxX2PLtyN7iygJ5xLivA==/base.apk"],nativeLibraryDirectories=[/data/app/com.lacc.addfans-lpQxX2PLtyN7iygJ5xLivA==/lib/arm64, /data/app/com.lacc.addfans-lpQxX2PLtyN7iygJ5xLivA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at com.qihoo360.replugin.f.findClass(RePluginClassLoader.java:172)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at com.qihoo360.replugin.f.loadClass(RePluginClassLoader.java:163)
	... 18 more

**Comment by cundong** [comment]
描述的不清楚。

**Comment by jueduiyheng** [comment]
我的也是这样 Calling the loadClass method failed (InvocationTargetException)
