### ISSUE TITLE
插件使用百度导航报dlopen failed: library 错误

### ISSUE THREAD

**Issue by Alex-Linrk** [Qihoo360/RePlugin#602]
#### 问题详细描述 Detailed description of the problem
使用百度地图导航开发插件，在启动插件是去注册导航事件，崩溃报错，提示
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/com.netintellisenselitejq/files/plugins_v3_data/navigation/lib/libcrypto.so" not found
可以肯定是我在宿主的lib/armeabi 有libcrypto.so 包
插件的的lib/armeabi 下有libcrypto.so 包
参考过Wiki下关于so包异常的解释及修复方式，依然没有解决
与其他项目不同的是我的项目是通过aar依赖使用的so包，不知道是否是则个影响
#### 复现问题步骤 Steps to reproduce the problem
1. 编译插件apk并重命名为插件jar包
2. 启动宿主，点击运行插件

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：26
Android 手机型号&ROM(Phone model & ROM): 
小米6 MIUI 9.8.5.8 开发板
#### Logcat上下文 Logcat context

06-11 16:20:14.199 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: start activity: intent=Intent { cmp=com.netintellisenselitejq.navigation/.main.MainActivity } plugin=com.netintellisenselitejq.navigation activity=com.netintellisenselitejq.navigation.main.MainActivity process=-2147483648
06-11 16:20:14.200 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: start activity: intent=Intent { cmp=com.netintellisenselitejq.navigation/.main.MainActivity } plugin=com.netintellisenselitejq.navigation activity=com.netintellisenselitejq.navigation.main.MainActivity process=-2147483648 download=true
06-11 16:20:14.200 16062-16062/com.netintellisenselitejq D/RePlugin.loadClass: isHookingClass(com.netintellisenselitejq.navigation , com.netintellisenselitejq.navigation.main.MainActivity) = false
06-11 16:20:14.201 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=com.netintellisenselitejq.navigation
06-11 16:20:14.203 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=navigation
06-11 16:20:14.205 16062-16062/com.netintellisenselitejq I/RePlugin.ws001: loadLocked(): Ready to lock! logtag = try1; pn = navigation
06-11 16:20:14.217 16062-16062/com.netintellisenselitejq W/PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.RECORD_AUDIO in package: com.netintellisenselitejq.navigation at: Binary XML file line #20
06-11 16:20:14.225 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: get package archive info, pi=PackageInfo{c89214f com.netintellisenselitejq.navigation}
    activity=com.netintellisenselitejq.navigation.main.MainActivity
    activity=com.netintellisenselitejq.navigation.guide.NaviGuideActivity
06-11 16:20:14.226 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: service=com.baidu.location.f
06-11 16:20:14.253 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: 从 apk 中解析 xml 耗时 26 毫秒
    解析插件 navigation : /data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar
    AndroidManifest:
	<?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="null" android:versionName="1.0" package="com.netintellisenselitejq.navigation">
    	<uses-sdk android:minSdkVersion="null" android:targetSdkVersion="null" />
    	<supports-screens android:anyDensity="null" android:smallScreens="null" android:normalScreens="null" android:largeScreens="null" android:resizeable="null" />
    	<uses-permission android:name="android.permission.RECORD_AUDIO" />
    	<uses-permission android:name="android.permission.RECORD_AUDIO" />
    	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    	<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
    	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    	<uses-permission android:name="android.permission.INTERNET" />
    	<uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    	<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    	<uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
    	<uses-permission android:name="android.permission.WRITE_SETTINGS" />
    	<uses-feature android:glEsVersion="null" android:required="null" />
    	<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    	<application android:theme="null" android:label="null" android:icon="null" android:name="com.netintellisenselitejq.navigation.PluginNavigationApp" android:allowBackup="null" android:supportsRtl="null" android:roundIcon="null">
    		<service android:name="com.baidu.location.f" android:enabled="null" android:process=":remote" />
    		<meta-data android:name="com.baidu.lbsapi.API_KEY" android:value="DqMwPw40iwzhLKHOZc0ARs7FkU8LLfBH" />
    		<activity android:theme="null" android:name="com.netintellisenselitejq.navigation.main.MainActivity" android:screenOrientation="null" android:configChanges="null">
    			<intent-filter>
    				<action android:name="android.intent.action.MAIN" />
    				<category android:name="android.intent.category.LAUNCHER" />
    			</intent-filter>
    		</activity>
    		<activity android:theme="null" android:name="com.netintellisenselitejq.navigation.guide.NaviGuideActivity" android:configChanges="null" />
    	</application>
    </manifest>
06-11 16:20:14.257 16062-16062/com.netintellisenselitejq D/RePlugin.ms-parser: 打印 Activity - IntentFilter
    key:com.netintellisenselitejq.navigation.guide.NaviGuideActivity; val:[]
    key:com.netintellisenselitejq.navigation.main.MainActivity; val:[{action:{android.intent.action.MAIN,}, category:{android.intent.category.LAUNCHER,}}, ]
    打印 Service - IntentFilter
06-11 16:20:14.258 16062-16062/com.netintellisenselitejq D/RePlugin.ms-parser: key:com.baidu.location.f; val:[]
06-11 16:20:14.258 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: mApplication: ApplicationInfo{c01b8ba com.netintellisenselitejq.navigation}
06-11 16:20:14.268 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: get binder = android.os.BinderProxy@893a97f
    proxy fetch binder: binder=android.os.BinderProxy@893a97f
06-11 16:20:14.271 16062-16062/com.netintellisenselitejq D/ws001: --- 调整插件中组件的进程 BEGIN ---
    com.netintellisenselitejq.navigation:remote -> com.netintellisenselitejq:p0
06-11 16:20:14.271 16062-16062/com.netintellisenselitejq D/task-affinity: --- 调整组件 com.baidu.location.f, com.netintellisenselitejq.navigation:remote -> com.netintellisenselitejq:p0
06-11 16:20:14.271 16062-16062/com.netintellisenselitejq D/ws001: --- 调整插件中组件的进程 END --- com.netintellisenselitejq
06-11 16:20:14.272 16062-16062/com.netintellisenselitejq D/RePlugin.task-affinity: useDefault = true
06-11 16:20:14.276 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: get resources for app, r=android.content.res.Resources@364bec8
06-11 16:20:14.276 16062-16062/com.netintellisenselitejq I/dex: load /data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar ...
06-11 16:20:14.279 16062-16062/com.netintellisenselitejq W/zygote: Skipping duplicate class check due to unrecognized classloader
06-11 16:20:14.290 16062-16062/com.netintellisenselitejq I/dex: load /data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar = com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/navigation-10-10-1, /system/lib, /system/vendor/lib]]]
06-11 16:20:14.290 16062-16062/com.netintellisenselitejq D/createClassLoader:  --无需释放DEX, (plugin=navigation, version=1), use:14, process:com.netintellisenselitejq
06-11 16:20:14.290 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: pkg context=com.qihoo360.loader2.PluginContext@ab65b61
06-11 16:20:14.290 16062-16062/com.netintellisenselitejq I/RePlugin.PluginManagerClient: updateUsedIfNeeded: pi.isUsed == used, ignore. used=true; pn=navigation
06-11 16:20:14.294 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: Plugin.loadEntryLocked(): Load entry, info=PInfo { <navigation:1(4)> [P-N] [DEX_EXTRACTED] processes=[] js={"pkgname":"com.netintellisenselitejq.navigation","ali":"navigation","name":"navigation","low":10,"high":10,"ver":1,"verv":2814792716779521,"path":"\/data\/user\/0\/com.netintellisenselitejq\/app_plugins_v3\/navigation-10-10-1.jar","type":1,"frm_ver":4} dex=/data/user/0/com.netintellisenselitejq/app_plugins_v3/oat/arm/navigation-10-10-1.odex nlib=/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/navigation-10-10-1 }
06-11 16:20:14.294 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=com.qihoo360.plugin.navigation.Entry
06-11 16:20:14.295 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=com.qihoo360.plugin.navigation.Entry
06-11 16:20:14.295 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: loadEntryMethod exception
06-11 16:20:14.297 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: found entry: className=com.qihoo360.replugin.Entry, loader=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/navigation-10-10-1, /system/lib, /system/vendor/lib]]]
06-11 16:20:14.303 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: Loader.invoke2(): plugin=/data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar, plugin.binder.cl=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/navigation-10-10-1, /system/lib, /system/vendor/lib]]]
06-11 16:20:14.303 16062-16062/com.netintellisenselitejq I/RePlugin.ws001: load /data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar 226666118 c=3 rc=true delta=97
    loadLocked(): Unlock! logtag = try1; pn = navigation
06-11 16:20:14.304 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: PAC.create(): Create and load Application. cl=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/navigation-10-10-1, /system/lib, /system/vendor/lib]]]
06-11 16:20:14.305 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: PAC.callAttachBaseContext(): Call attachBaseContext(), cl=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/navigation-10-10-1, /system/lib, /system/vendor/lib]]]
    PAC.callOnCreate(): Call onCreate(), cl=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/navigation-10-10-1, /system/lib, /system/vendor/lib]]]
06-11 16:20:14.309 16062-16062/com.netintellisenselitejq D/MscSpeechLog: process name:com.netintellisenselitejq
06-11 16:20:14.310 16062-16062/com.netintellisenselitejq D/MscSpeechLog: process name:com.netintellisenselitejqis own process
06-11 16:20:14.313 16062-16062/com.netintellisenselitejq D/MSC_LOG: JNI_OnLoad is called !
06-11 16:20:14.314 16062-16062/com.netintellisenselitejq D/MscSpeechLog: loadLibrary msc success
    SpeechUtility start login
06-11 16:20:14.316 16062-16062/com.netintellisenselitejq D/MscSpeechLog: MSC ifly ver: true
    DC create enter.
    DC resetAllValues enter.
    DC resetAllValues leave.
    DC create leave.
06-11 16:20:14.320 16062-16062/com.netintellisenselitejq D/MSC_LOG: QMSPGetVersion Begin
    QMSPGetVersion End
06-11 16:20:14.321 16062-16062/com.netintellisenselitejq D/MscSpeechLog: get msc full version name: 5.0.37.1181
06-11 16:20:14.363 16062-16062/com.netintellisenselitejq D/MscSpeechLog: create file:.2F6E2C5B63F0F83B
06-11 16:20:14.387 16062-16062/com.netintellisenselitejq D/MscSpeechLog: Location[gps 24.491107,118.181116 hAcc=240 et=+2d8h46m6s255ms alt=89.96234130859375 vAcc=768 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=40]}]
06-11 16:20:14.405 16062-16062/com.netintellisenselitejq D/MSC_LOG: QMSPLogin Begin
06-11 16:20:14.416 16062-16062/com.netintellisenselitejq D/MSC_LOG: QMSPLogin End
06-11 16:20:14.416 16062-16062/com.netintellisenselitejq D/MscSpeechLog: [MSPLogin]ret:0
06-11 16:20:14.425 16062-16062/com.netintellisenselitejq D/MscSpeechLog: DC init enable=null
    DC init enter.
    DC getEnable enter.
    DC getEnable static value=true
06-11 16:20:14.426 16062-16062/com.netintellisenselitejq D/MscSpeechLog: getMscParameter enter key=idc
    getMscParameter MSC return -1
    getMscParameter value=null
    getMscParameter leave
    DC getEnable msc val=null
    DC getEnable value=false
    DC getEnable leave.
    DC init is not enable.
    DC init leave.
06-11 16:20:14.432 16062-16143/com.netintellisenselitejq D/UserLogger:  start mergerWifiList
06-11 16:20:14.442 16062-16062/com.netintellisenselitejq W/DeviceId: galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
06-11 16:20:14.442 16062-16062/com.netintellisenselitejq I/chatty: uid=10177(u0_a177) com.netintellisenselitejq identical 1 line
06-11 16:20:14.442 16062-16062/com.netintellisenselitejq W/DeviceId: galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
06-11 16:20:14.455 16062-16062/com.netintellisenselitejq I/BaiduApiAuth: BaiduApiAuth SDK Version:1.0.20
06-11 16:20:14.460 16062-16145/com.netintellisenselitejq D/MscSpeechLog: MscHttpRequest start Post
06-11 16:20:14.462 16062-16062/com.netintellisenselitejq D/phoneInfo: mAppSysOSAPI not null
    Bundle[{screen_x=1080, screen_y=1920, mb=MI 6, os=Android26, sv=5.1.0, cpu=, glr=, glv=, net=0, pcn=com.netintellisenselitejq, cuid=3E98807A2D2B84624D0430F7FF142755|066410130193768, dpi_x=480, dpi_y=480, resid=02, channel=baidu, signature=[B@36aff74}]
06-11 16:20:14.465 16062-16068/com.netintellisenselitejq I/zygote: Do full code cache collection, code=252KB, data=211KB
06-11 16:20:14.466 16062-16068/com.netintellisenselitejq I/zygote: After code cache collection, code=246KB, data=159KB
06-11 16:20:14.482 16062-16062/com.netintellisenselitejq D/RePlugin.theme: intent.putExtra(com.netintellisenselitejq.navigation.main.MainActivity, 2131493123);
06-11 16:20:14.484 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=navigation
06-11 16:20:14.484 16062-16062/com.netintellisenselitejq I/RePlugin.ws000: loadLocked(): Initialized, is loaded = true
06-11 16:20:14.484 16062-16062/com.netintellisenselitejq D/RePlugin.task-affinity: originTaskAffinity is com.netintellisenselitejq.navigation
06-11 16:20:14.484 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: PACM: alloc registered container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2
    PACM: bindActivity: lookup activity container: container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2
06-11 16:20:14.493 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: PACM: eval plugin com.netintellisenselitejq.navigation, target=com.netintellisenselitejq.navigation.main.MainActivity, container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2
06-11 16:20:14.493 16062-16062/com.netintellisenselitejq I/RePlugin.ws001: alloc success: container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2 plugin=com.netintellisenselitejq.navigation activity=com.netintellisenselitejq.navigation.main.MainActivity
06-11 16:20:14.494 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: start activity: real intent=Intent { cat=[process:-2147483648,activity:com.netintellisenselitejq.navigation.main.MainActivity,plugin:com.netintellisenselitejq.navigation,container:com.netintellisenselitejq.loader.a.ActivityN1NRNTS2,counter:0] cmp=com.netintellisenselitejq/.loader.a.ActivityN1NRNTS2 (has extras) }
06-11 16:20:14.494 16062-16062/com.netintellisenselitejq I/Timeline: Timeline: Activity_launch_request time:135641520
06-11 16:20:14.513 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: found: ActivityState {container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2 state=restored plugin=com.netintellisenselitejq.navigation activity=com.netintellisenselitejq.navigation.main.MainActivity size=0}
    PACM: loadActivityClass in=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2 target=com.netintellisenselitejq.navigation.main.MainActivity plugin=com.netintellisenselitejq.navigation
    PStatusC.getStatus(): ps is null. pn=navigation
06-11 16:20:14.513 16062-16062/com.netintellisenselitejq I/RePlugin.ws000: loadLocked(): Initialized, is loaded = true
06-11 16:20:14.513 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: PACM: loadActivityClass, plugin activity loader: in=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2 activity=com.netintellisenselitejq.navigation.main.MainActivity
    PACM: loadActivityClass, plugin activity loader: c=class com.netintellisenselitejq.navigation.main.MainActivity, loader=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/navigation-10-10-1, /system/lib, /system/vendor/lib]]]
06-11 16:20:14.520 16062-16062/com.netintellisenselitejq W/ResourceType: Type identifier 0xd does not exist.
06-11 16:20:14.521 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: activity create before: com.netintellisenselitejq.navigation.main.MainActivity this=15201507 taskid=519
06-11 16:20:14.521 16062-16062/com.netintellisenselitejq D/RePlugin.theme: defaultThemeId = 2131558644
    dynamicThemeId = 2131558644
    manifestThemeId = 2131493123
    themeId = 2131493123
06-11 16:20:14.528 16062-16062/com.netintellisenselitejq I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
06-11 16:20:14.530 16062-16088/com.netintellisenselitejq E/ContentCatcherManager: failed to get ContentCatcherService.
06-11 16:20:14.530 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: activity create: com.netintellisenselitejq.navigation.main.MainActivity this=15201507 taskid=519
    activity create: name=com.netintellisenselitejq.navigation activity=com.netintellisenselitejq.navigation.main.MainActivity process=-2147483648 container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2 counter=0
06-11 16:20:14.530 16062-16062/com.netintellisenselitejq I/RePlugin.ws001: perfect: container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2 plugin=com.netintellisenselitejq.navigation activity=com.netintellisenselitejq.navigation.main.MainActivity
06-11 16:20:14.530 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: found: ActivityState {container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2 state=restored plugin=com.netintellisenselitejq.navigation activity=com.netintellisenselitejq.navigation.main.MainActivity size=0}
    PACM: activity created h=15201507 class=com.netintellisenselitejq.navigation.main.MainActivity container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2
06-11 16:20:14.530 16062-16062/com.netintellisenselitejq I/RePlugin.ws001: PACM: create: relaunch activity: history: container=com.netintellisenselitejq.loader.a.ActivityN1NRNTS2 plugin=com.netintellisenselitejq.navigation activity=com.netintellisenselitejq.navigation.main.MainActivity@e7f4e3
06-11 16:20:14.531 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: set activity intent cl=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.netintellisenselitejq/app_plugins_v3_libs/navigation-10-10-1, /system/lib, /system/vendor/lib]]]
    cached filename: com.netintellisenselitejq.navigation -> null
    PStatusC.getStatus(): ps is null. pn=navigation
06-11 16:20:14.532 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: cached filename: navigation -> /data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar
    cached packageInfo /data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar -> PackageInfo{c89214f com.netintellisenselitejq.navigation}
    cached componentList /data/user/0/com.netintellisenselitejq/app_plugins_v3/navigation-10-10-1.jar -> com.qihoo360.replugin.component.ComponentList@9f61599
06-11 16:20:14.532 16062-16062/com.netintellisenselitejq I/RePlugin.ws000: loadLocked(): Cached, pkgInfo loaded
06-11 16:20:14.532 16062-16062/com.netintellisenselitejq D/RePlugin.activity-injector: activity = com.netintellisenselitejq.navigation.main.MainActivity@e7f4e3
    ai = ActivityInfo{5b2005e com.netintellisenselitejq.navigation.main.MainActivity}
    label = Plugin_Navigation
06-11 16:20:14.540 16062-16062/com.netintellisenselitejq D/RePlugin.activity-injector: bitmap = null
    td = TaskDescription Label: Plugin_Navigation Icon: null IconFilename: null colorPrimary: 0 colorBackground: 0 statusBarColor: 0 navigationBarColor: 0
06-11 16:20:14.541 16062-16062/com.netintellisenselitejq D/linrk: onCreate: com.netintellisenselitejq
06-11 16:20:14.545 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=LinearLayout
06-11 16:20:14.546 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=ViewStub
06-11 16:20:14.547 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=FrameLayout
06-11 16:20:14.550 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: layout.cache: new constructor. plugin=navigation name=android.support.v7.widget.FitWindowsLinearLayout
06-11 16:20:14.551 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: layout.cache: new constructor. plugin=navigation name=android.support.v7.widget.ViewStubCompat
06-11 16:20:14.552 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: layout.cache: new constructor. plugin=navigation name=android.support.v7.widget.ContentFrameLayout
06-11 16:20:14.557 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=RelativeLayout
06-11 16:20:14.558 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: layout.cache: new constructor. plugin=navigation name=com.baidu.mapapi.map.MapView
06-11 16:20:14.561 16062-16062/com.netintellisenselitejq E/JVMContainer VMSG: RegisterNatives
06-11 16:20:14.579 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=com.baidu.platform.comapi.wnplatform.walkmap.WNaviBaiduMap
06-11 16:20:14.778 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=ImageView
06-11 16:20:14.779 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=View
06-11 16:20:14.780 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=EditText
06-11 16:20:14.789 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=ImageButton
06-11 16:20:14.790 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=CheckBox
06-11 16:20:14.794 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=RadioGroup
06-11 16:20:14.796 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=RadioButton
06-11 16:20:14.805 16062-16068/com.netintellisenselitejq I/zygote: Do partial code cache collection, code=252KB, data=194KB
    After code cache collection, code=252KB, data=194KB
    Increasing code cache capacity to 1024KB
06-11 16:20:14.836 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=Button
06-11 16:20:14.848 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: layout.cache: new constructor. plugin=navigation name=android.support.v7.widget.RecyclerView
06-11 16:20:14.865 16062-16062/com.netintellisenselitejq D/RePlugin.ws001: layout.cache: new constructor. plugin=navigation name=com.baidu.mapapi.clusterutil.clustering.RotationLayout
06-11 16:20:14.866 16062-16062/com.netintellisenselitejq W/ws001: NRH lcl.fc: c=TextView
06-11 16:20:14.879 16062-16062/com.netintellisenselitejq D/MscSpeechLog: MSC ifly ver: true
06-11 16:20:14.909 16062-16062/com.netintellisenselitejq I/WebViewFactory: Loading com.google.android.webview version 62.0.3202.84 (code 320208450)
06-11 16:20:14.927 16062-16062/com.netintellisenselitejq I/cr_LibraryLoader: Time to load native libraries: 2 ms (timestamps 1951-1953)
06-11 16:20:14.930 16062-16062/com.netintellisenselitejq I/chromium: [INFO:library_loader_hooks.cc(46)] Chromium logging enabled: level = 0, default verbosity = 0
06-11 16:20:14.931 16062-16062/com.netintellisenselitejq I/cr_LibraryLoader: Expected native library version number "62.0.3202.84", actual native library version number "62.0.3202.84"
06-11 16:20:14.939 16062-16167/com.netintellisenselitejq W/cr_ChildProcLH: Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
06-11 16:20:14.942 16062-16062/com.netintellisenselitejq I/cr_BrowserStartup: Initializing chromium process, singleProcess=false
06-11 16:20:14.983 16062-16200/com.netintellisenselitejq W/cr_CrashFileManager: /data/user/0/com.netintellisenselitejq/cache/WebView/Crash Reports does not exist or is not a directory
06-11 16:20:15.017 16062-16062/com.netintellisenselitejq D/MainActivity: initDate: true
06-11 16:20:15.021 16062-16062/com.netintellisenselitejq D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
06-11 16:20:15.022 16062-16062/com.netintellisenselitejq E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.netintellisenselitejq, PID: 16062
    java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/com.netintellisenselitejq/files/plugins_v3_data/navigation/lib/libcrypto.so" not found
        at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1621)
        at com.baidu.navisdk.adapter.impl.BaiduNaviManager.loadNativeLibrary(BaiduNaviManager.java:261)
        at com.baidu.navisdk.adapter.impl.BaiduNaviManager.loadBaiduNaviNativeLibrary(BaiduNaviManager.java:236)
        at com.baidu.navisdk.adapter.impl.BaiduNaviManager.init(BaiduNaviManager.java:408)
        at com.netintellisenselitejq.navigation.main.MainActivity.initNavi(MainActivity.java:514)
        at com.netintellisenselitejq.navigation.main.MainActivity.initDate(MainActivity.java:137)
        at com.leadhead.baselibrary.base.BaseActivity.onCreate(BaseActivity.java:47)
        at android.app.Activity.performCreate(Activity.java:7057)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2930)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by Alex-Linrk** [comment]
解决了，由于项目中依赖了百度导航的另外两个aar项目，所以必须在宿主中也相应加入对应的依赖才可以
