### ISSUE TITLE
Replguin插件中使用Fresco1.8.0版本，Fresco初始化崩溃

### ISSUE THREAD

**Issue by wangzhengyi** [Qihoo360/RePlugin#617]
#### 问题详细描述 Detailed description of the problem
在插件中，配置项目依赖的Fresco是1.8.0版本，运行Fresco.initialize方法，插件崩溃

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:com.qihoo360.replugin:replugin-host-lib:2.2.1/com.qihoo360.replugin:replugin-host-gradle:2.2.1
rePlugin-plugin-lib/gradle Version:com.qihoo360.replugin:replugin-plugin-lib:2.2.1/com.qihoo360.replugin:replugin-plugin-gradle:2.2.1

Android API Version：8.0.0
Android 手机型号&ROM(Phone model & ROM): MI6 MIUI9.5

#### Logcat上下文 Logcat context
AndroidRuntime: Caused by: java.io.IOException: cannot mkdir: /data/user/0/com.pptv.launcher/lib-main
05-17 16:00:55.978 14310 14310 E AndroidRuntime: at com.facebook.soloader.SysUtil.mkdirOrThrow(SysUtil.java:139)
05-17 16:00:55.978 14310 14310 E AndroidRuntime: at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:391)
05-17 16:00:55.978 14310 14310 E AndroidRuntime: at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:211)
05-17 16:00:55.978 14310 14310 E AndroidRuntime: at com.facebook.soloader.SoLoader.init(SoLoader.java:120)
05-17 16:00:55.978 14310 14310 E AndroidRuntime: at com.facebook.soloader.SoLoader.init(SoLoader.java:104)
05-17 16:00:55.978 14310 14310 E AndroidRuntime: at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:61)

**Comment by duhuanbiao** [comment]
需要使用宿主context

**Comment by wangzhengyi** [comment]
@duhuanbiao , 我们这边插件中是独立初始化Fresco的。使用宿主的Context虽然不崩溃了，但是图片也加载不出来了......

**Comment by Aplombs** [comment]
@wangzhengyi  问题最后解决了吗
