### ISSUE TITLE
 You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by lvtanxi** [Qihoo360/RePlugin#62]
![qq 20170703105156](https://user-images.githubusercontent.com/16009130/27776489-a7c008e6-5fdd-11e7-9759-f72c10431138.png)
我的宿主Activity都是集成的的AppCompatActivity。而两个App的Theme则是使用的默认的Theme.AppCompat.Light.DarkActionBar。运行replugin-sample中提供的demo1与demo2都可以。用我自己的就出现了这个问题。

**Comment by moziqi** [comment]
依赖arr重复了。

**Comment by tokiii** [comment]
我也遇到了这个问题，不解

**Comment by tokiii** [comment]
`07-03 13:52:34.781 30073-30073/com.lost.hostapp D/ViewRootImpl: ViewPostImeInputStage processPointer 0
07-03 13:52:34.861 30073-30073/com.lost.hostapp D/ViewRootImpl: ViewPostImeInputStage processPointer 1
07-03 13:52:34.911 30073-30073/com.lost.hostapp W/ResourcesManager: getTopLevelResources: /data/user/0/com.lost.hostapp/app_plugins_v3/easeplugin-10-10-1.jar / 1.0 running in com.lost.hostapp rsrc of package com.lost.easeplugin
07-03 13:52:34.911 30073-30073/com.lost.hostapp D/ResourcesManager: For user 0 new overlays fetched Null
07-03 13:52:34.911 30073-30073/com.lost.hostapp I/dex: load /data/user/0/com.lost.hostapp/app_plugins_v3/easeplugin-10-10-1.jar ...
07-03 13:52:34.921 30073-30073/com.lost.hostapp W/System: ClassLoader referenced unknown path: /data/user/0/com.lost.hostapp/app_plugins_v3_libs/easeplugin-10-10-1
07-03 13:52:34.921 30073-30073/com.lost.hostapp I/dex: load /data/user/0/com.lost.hostapp/app_plugins_v3/easeplugin-10-10-1.jar = com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.lost.hostapp/app_plugins_v3/easeplugin-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.lost.hostapp/app_plugins_v3_libs/easeplugin-10-10-1, /vendor/lib64, /system/lib64]]]
07-03 13:52:34.921 30073-30073/com.lost.hostapp E/ws001: Didn't find class "com.qihoo360.plugin.easeplugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.lost.hostapp/app_plugins_v3/easeplugin-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.lost.hostapp/app_plugins_v3_libs/easeplugin-10-10-1, /vendor/lib64, /system/lib64]]
                                                         java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.plugin.easeplugin.Entry" on path: DexPathList[[zip file "/data/user/0/com.lost.hostapp/app_plugins_v3/easeplugin-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.lost.hostapp/app_plugins_v3_libs/easeplugin-10-10-1, /vendor/lib64, /system/lib64]]
                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                             at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:76)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                             at com.qihoo360.loader2.Loader.loadEntryMethod2(Loader.java:419)
                                                             at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:857)
                                                             at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:822)
                                                             at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:621)
                                                             at com.qihoo360.loader2.Plugin.load(Plugin.java:432)
                                                             at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1033)
                                                             at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1018)
                                                             at com.qihoo360.loader2.PmLocalImpl.getActivityInfo(PmLocalImpl.java:443)
                                                             at com.qihoo360.loader2.PmLocalImpl.loadPluginActivity(PmLocalImpl.java:319)
                                                             at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:230)
                                                             at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                             at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                             at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                             at com.lost.hostapp.MainActivity$2.onClick(MainActivity.java:34)
                                                             at android.view.View.performClick(View.java:5697)
                                                             at android.widget.TextView.performClick(TextView.java:10815)
                                                             at android.view.View$PerformClick.run(View.java:22526)
                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:158)
                                                             at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                         	Suppressed: java.lang.ClassNotFoundException: com.qihoo360.plugin.easeplugin.Entry
                                                             at java.lang.Class.classForName(Native Method)
                                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                             		... 26 more
                                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-03 13:52:34.941 30073-30073/com.lost.hostapp I/Timeline: Timeline: Activity_launch_request id:com.lost.hostapp time:160949292
07-03 13:52:34.971 30073-30073/com.lost.hostapp W/ResourcesManager: getTopLevelResources: /data/app/com.lost.hostapp-1/base.apk / 1.0 running in com.lost.hostapp rsrc of package com.lost.hostapp
07-03 13:52:34.981 30073-30073/com.lost.hostapp I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/ResourceType: No package identifier when getting value for resource number 0x00000000
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err: android.content.res.Resources$NotFoundException: String resource ID #0x0
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.content.res.Resources.getText(Resources.java:1468)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.content.res.Resources.getString(Resources.java:1564)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.getLabel(ActivityInjector.java:139)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.injectTaskDescription(ActivityInjector.java:106)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.inject(ActivityInjector.java:80)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.inject(ActivityInjector.java:73)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.loader2.PmInternalImpl.handleActivityCreate(PmInternalImpl.java:433)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.i.Factory2.handleActivityCreate(Factory2.java:67)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at library.g.a(Unknown Source)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.b.a(Unknown Source)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.e.b(Unknown Source)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.loader.a.PluginAppCompatActivity.onCreate(Unknown Source)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.lost.easeplugin.MainActivity.onCreate(MainActivity.java:76)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.Activity.performCreate(Activity.java:6876)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:222)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.os.Looper.loop(Looper.java:158)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7237)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/ResourceType: No package identifier when getting value for resource number 0x00000000
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err: android.content.res.Resources$NotFoundException: Resource ID #0x0
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.content.res.Resources.getValue(Resources.java:2558)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.content.res.Resources.getDrawable(Resources.java:2001)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.content.res.Resources.getDrawable(Resources.java:1987)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.content.res.Resources.getDrawable(Resources.java:1961)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.getIcon(ActivityInjector.java:199)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.injectTaskDescription(ActivityInjector.java:113)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.inject(ActivityInjector.java:80)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.component.activity.ActivityInjector.inject(ActivityInjector.java:73)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.loader2.PmInternalImpl.handleActivityCreate(PmInternalImpl.java:433)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.i.Factory2.handleActivityCreate(Factory2.java:67)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at library.g.a(Unknown Source)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.b.a(Unknown Source)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.e.b(Unknown Source)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.qihoo360.replugin.loader.a.PluginAppCompatActivity.onCreate(Unknown Source)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.lost.easeplugin.MainActivity.onCreate(MainActivity.java:76)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.Activity.performCreate(Activity.java:6876)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:222)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.os.Looper.loop(Looper.java:158)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7237)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
07-03 13:52:34.981 30073-30073/com.lost.hostapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
07-03 13:52:34.991 30073-30073/com.lost.hostapp D/AndroidRuntime: Shutting down VM
07-03 13:52:34.991 30073-30073/com.lost.hostapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.lost.hostapp, PID: 30073
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lost.hostapp/com.lost.hostapp.loader.a.ActivityN1NRNTS4}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                   Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                      at com.lost.easeplugin.MainActivity.onCreate(MainActivity.java:78)
                                                                      at android.app.Activity.performCreate(Activity.java:6876)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:158) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
`

**Comment by lvtanxi** [comment]
@moziqi 不是arr重复的问题。不知道怎么的，现在就好了。

**Comment by Zhaoyy** [comment]
@lvtanxi 我也遇到这个问题，你是怎么解决的。能提供个思路么？

**Comment by lvtanxi** [comment]
@Zhaoyy 不好意思，昨天电脑蓝屏了。我主要出现这个问题好像是在assets中的插件中把"ver"设置成了1，改成100就好了

**Comment by taoliuh** [comment]
@lvtanxi  遇到相同的问题，请问你说的"ver"是什么？
