### ISSUE TITLE
三星4.4.4版本：java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by wuxinrong1981415** [Qihoo360/RePlugin#629]
#### 问题详细描述 Detailed description of the problem

采用非继承方式使用RePlugin
java.lang.ExceptionInInitializerError
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:926)

#### 复现问题步骤 Steps to reproduce the problem
1.  
2.  

#### 其它重要信息 Other important information
 
replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4

Android API Version：4.4.4
Android 手机型号&ROM(Phone model & ROM): 

三星 android

**Comment by longkehuawei** [comment]
解决了吗
