### ISSUE TITLE
Replugin和Tinker可以兼容吗？

### ISSUE THREAD

**Issue by hwldzh** [Qihoo360/RePlugin#630]
#### 问题详细描述 Detailed description of the problem
使用Replugin可以成功加载插件，最近想将Tinker也使用上，但是在加载了本地补丁成功后，重启应用，再次打开就crash了。

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information
Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.mucfc.muapp.application.MainDebugApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder com.qihoo360.loader2.PmBase.getHostBinder()' on a null object reference
        at android.app.LoadedApk.makeApplication(LoadedApk.java:853)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5748)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1716)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:185)
        at android.app.ActivityThread.main(ActivityThread.java:6615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder com.qihoo360.loader2.PmBase.getHostBinder()' on a null object reference
        at android.os.Parcel.readException(Parcel.java:1706)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
        at android.content.ContentResolver.query(ContentResolver.java:554)
        at android.content.ContentResolver.query(ContentResolver.java:495)
        at com.qihoo360.loader2.PluginProviderStub.proxyFetchHostBinder(PluginProviderStub.java:166)
        at com.qihoo360.loader2.PluginProviderStub.proxyFetchHostBinder(PluginProviderStub.java:145)
        at com.qihoo360.loader2.PluginProcessMain.connectToHostSvc(PluginProcessMain.java:365)
        at com.qihoo360.loader2.PmBase.initForClient(PmBase.java:316)
        at com.qihoo360.loader2.PmBase.init(PmBase.java:243)
        at com.qihoo360.loader2.PMF.init(PMF.java:72)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:982)
        at com.mucfc.muapp.application.MainDebugApplication.attachBaseContext(MainDebugApplication.java:72)
        at android.app.Application.attach(Application.java:198)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
        at android.app.Instrumentation.newApplication(Instrumentation.java:993)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:847)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5748) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1716) 

replugin-host-lib/gradle Version: 2.2.2
rePlugin-plugin-lib/gradle Version: 2.2.2

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by kingcxsc** [comment]
bu neng jian rong

**Comment by langxuelang** [comment]
可以兼容
