### ISSUE TITLE
自己编的插件包有资源异常

### ISSUE THREAD

**Issue by zzf61** [Qihoo360/RePlugin#64]
跑样例的没有问题，我自己编的一个插件包不行，会报资源异常，各位大神看下是什么原因，异常如下
Process: com.qihoo360.replugin.sample.host, PID: 3367
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}: android.content.res.Resources$NotFoundException: Resource ID #0x7f040019
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                     at android.os.Looper.loop(Looper.java:156)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6531)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                                  Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f040019
                                                                                     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:255)
                                                                                     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2187)
                                                                                     at android.content.res.Resources.getLayout(Resources.java:1178)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:454)
                                                                                     at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:280)
                                                                                     at android.app.Activity.setContentView(Activity.java:2515)
                                                                                     at com.dlive.keyloggerdemo.MainActivity.onCreate(MainActivity.java:27)
                                                                                     at android.app.Activity.performCreate(Activity.java:6910)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                     at android.os.Looper.loop(Looper.java:156) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6531) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**RePlugin version**:

**Android compile SDK version**:
minSdkVersion 14
targetSdkVersion 23
**Android ROM**:
 华为 mate 9

**Comment by yumodev** [comment]
+1

**Comment by ncguobiao** [comment]
+1

**Comment by kezong** [comment]
在编写插件时候，需要在app/build.gradle的尾部加上：
apply plugin: 'replugin-plugin-gradle'
repluginPluginConfig {
    includedInjectors = ['LoaderActivityInjector', 'ProviderInjector', 'LocalBroadcastInjector', 'GetIdentifierInjector']
}

其中com.qihoo360.replugin:replugin-plugin-gradle:2.1.0版本，需要手动的配置repluginPluginConfig内容。
我们会在接下来的2.1.1版本中修复该问题，并且完善接入文档。

感谢反馈。

**Comment by kezong** [comment]
replugin-plugin-gradle:2.1.1版本已经提交。

尝试将版本提到2.1.1试试

**Comment by jiongxuan** [comment]
辛苦 @kezong 兄了。您们可以试下效果 @ncguobiao @yumodev @zzf61

**Comment by zzf61** [comment]
@kezong 在插件中加了上面的配置仍然不行，一样的错误

**Comment by kezong** [comment]
@zzf61 清除数据之后试一试，现在覆盖安装，插件无法更新，可能用的还是之前的插件。

**Comment by zzf61** [comment]
@kezong 卸载重装了还是一样的错误，更新了最新的代码，清理重编译了还是不行的

**Comment by zzf61** [comment]
解决了，插件的targetSdkVersion 配置成和host的一样才可以，不然启动不了

**Comment by jiongxuan** [comment]
谢谢提醒~
