### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by 247033993** [Qihoo360/RePlugin#647]
低版本手机上异常 

Caused by: java.lang.NullPointerException
        at com.qihoo360.replugin.utils.ReflectUtils.getField(ReflectUtils.java:86)
        at com.qihoo360.replugin.utils.ReflectUtils.readField(ReflectUtils.java:108)
        at com.qihoo360.replugin.utils.ReflectUtils.readStaticField(ReflectUtils.java:100)
        at com.qihoo360.replugin.helper.HostConfigHelper.readField(HostConfigHelper.java:171)
        at com.qihoo360.replugin.helper.HostConfigHelper.<clinit>(HostConfigHelper.java:83)
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60) 
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964) 
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67) 
        at android.app.Application.attach(Application.java:181) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4351) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:137) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5089) 
        at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by xiangjianxiaoyu** [comment]
需要注意下，你的版本是不是5.0以下的设备，如果是，请将dex分包的方案加进去，即：multiDexEnabled true；这个方案，同时需要确保RePluginHostConfig在加载了基座的class.dex里面，如 RePluginHostConfig.ACTIVITY_PIT_COUNT_TASK;放入你的application的attachBaseContext方法里。这样子编译的时候，会把RePluginHostConfig加载进宿主dex文件中。

**Comment by longkehuawei** [comment]
解决了吗？
