### ISSUE TITLE
  java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by xiangjianxiaoyu** [Qihoo360/RePlugin#649]
#### 问题详细描述 Detailed description of the problem
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: recycle.com.dog, PID: 6567
    java.lang.ExceptionInInitializerError
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964)
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)
        at recycle.com.dog.RecyclerHostApp.attachBaseContext(RecyclerHostApp.java:25)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:991)
        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at com.qihoo360.replugin.utils.ReflectUtils.getField(ReflectUtils.java:86)
        at com.qihoo360.replugin.utils.ReflectUtils.readField(ReflectUtils.java:108)
        at com.qihoo360.replugin.utils.ReflectUtils.readStaticField(ReflectUtils.java:100)
        at com.qihoo360.replugin.helper.HostConfigHelper.readField(HostConfigHelper.java:171)
        at com.qihoo360.replugin.helper.HostConfigHelper.<clinit>(HostConfigHelper.java:83)
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60) 
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964) 
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67) 
        at recycle.com.dog.RecyclerHostApp.attachBaseContext(RecyclerHostApp.java:25) 
        at android.app.Application.attach(Application.java:181) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:511) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
08-23 15:39:02.559 2347-3291/? E/BufferQueue: [com.android.launcher/com.android.launcher2.Launcher] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
08-23 15:39:05.599 6584-6584/? E/memtrack: Couldn't load memtrack module (No such file or directory)

#### 复现问题步骤 Steps to reproduce the problem
1. 创建了一个新工程，按照宿主的配置方式配置上去，然后运行在4.4.2版本的设备上。
2. 在模拟器和设备上，只要是4.4.2的arm设备上，必然报这个问题

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
Android API Version：
Android 手机型号&ROM(Phone model & ROM):  模拟器安卓4.4系统

**Comment by xiangjianxiaoyu** [comment]
该问题因为无法在基座分包的宿主dex文件中找到RePluginHostConfig文件引起的，需要在这里int x = RePluginHostConfig.ACTIVITY_PIT_COUNT_TASK;类似于这样子的一个调用，将RePluginHostConfig引入宿主dex。感谢jack的帮助。

**Comment by lowly360** [comment]
一模一样的错误，楼主是具体怎么弄好的？在哪里添加调用才能引入宿主dex
HostConfigHelper.PERSISTENT_ENABLE 类加载的时候报错

在低版本手机上错误（4.4.4），高版本就没有（5.0以上）

**Comment by longkehuawei** [comment]
解决了吗

**Comment by asdf19910719** [comment]
> 该问题因为无法在基座分包的宿主dex文件中找到RePluginHostConfig文件引起的，需要在这里int x = RePluginHostConfig.ACTIVITY_PIT_COUNT_TASK;类似于这样子的一个调用，将RePluginHostConfig引入宿主dex。感谢jack的帮助。

RePluginHostConfig这个是生成的类怎么指定呢?
