### ISSUE TITLE
适配！三星note3长按Edittext页面崩溃。荣耀7x两个Toast同时展示时，第一条toast展示时间很短。

### ISSUE THREAD

**Issue by aifengshen** [Qihoo360/RePlugin#652]
#### 问题详细描述 Detailed description of the problem
如题，
1.三星note3长按Edittext页面崩溃。
2.荣耀7x两个Toast同时展示时，第一条toast展示时间很短，第二条展示时间正常。
#### 复现问题步骤 Steps to reproduce the problem
1. 三星问题：note3长按Edittext页面崩溃。
2. 荣耀问题：
    1） 流程：某个页面的recyclerview的每一项都有个提交按钮，点击提交按钮，调用相关接口，toast提交成功，然后立马调用recyclerview的刷新方法，然后toast该recyclerview一共剩余多少条。
    2） 现象：第一条toast，即提交成功，展示时间极短，第二条toast，即剩余多少条，展示时间正常。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.2.4
rePlugin-plugin-lib/gradle Version:2.2.4

Android API Version：Galaxy Note3是安卓5.0，荣耀7x是安卓7.0
Android 手机型号&ROM(Phone model & ROM): 
1.三星 SM-N9008V 

#### Logcat上下文 Logcat context
以下是三星的logcat：
08-24 18:43:12.621 14206-14206/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sdjictec.sso, PID: 14206
    android.view.InflateException: Binary XML file line #17: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:640)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
        at android.widget.Editor$ActionPopupWindow.initContentView(Editor.java:3339)
        at android.widget.Editor$PinnedPopupWindow.<init>(Editor.java:2528)
        at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:3284)
        at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:3284)
        at android.widget.Editor$HandleView.showActionPopupWindow(Editor.java:4448)
        at android.widget.Editor$InsertionHandleView.showWithActionPopup(Editor.java:4874)
        at android.widget.Editor$InsertionPointCursorController.showWithActionPopup(Editor.java:5290)
        at android.widget.Editor.performLongClick(Editor.java:958)
        at android.widget.TextView.performLongClick(TextView.java:10411)
        at android.view.View$CheckForLongPress.run(View.java:20867)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5942)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
        at android.widget.Editor$ActionPopupWindow.initContentView(Editor.java:3339) 
        at android.widget.Editor$PinnedPopupWindow.<init>(Editor.java:2528) 
        at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:3284) 
        at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:3284) 
        at android.widget.Editor$HandleView.showActionPopupWindow(Editor.java:4448) 
        at android.widget.Editor$InsertionHandleView.showWithActionPopup(Editor.java:4874) 
        at android.widget.Editor$InsertionPointCursorController.showWithActionPopup(Editor.java:5290) 
        at android.widget.Editor.performLongClick(Editor.java:958) 
        at android.widget.TextView.performLongClick(TextView.java:10411) 
        at android.view.View$CheckForLongPress.run(View.java:20867) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:5942) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=15; index=4033
        at android.content.res.StringBlock.get(StringBlock.java:65)
        at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:483)
        at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:980)
        at android.content.res.TypedArray.getString(TypedArray.java:178)
        at android.widget.TextView.<init>(TextView.java:1401)
        at android.widget.TextView.<init>(TextView.java:982)
        at android.widget.TextView.<init>(TextView.java:978)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
        at android.widget.Editor$ActionPopupWindow.initContentView(Editor.java:3339) 
        at android.widget.Editor$PinnedPopupWindow.<init>(Editor.java:2528) 
        at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:3284) 
        at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:3284) 
        at android.widget.Editor$HandleView.showActionPopupWindow(Editor.java:4448) 
        at android.widget.Editor$InsertionHandleView.showWithActionPopup(Editor.java:4874) 
        at android.widget.Editor$InsertionPointCursorController.showWithActionPopup(Editor.java:5290) 
        at android.widget.Editor.performLongClick(Editor.java:958) 
        at android.widget.TextView.performLongClick(TextView.java:10411) 
        at android.view.View$CheckForLongPress.run(View.java:20867) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:5942) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
    
    
    --------- beginning of system
08-24 18:43:12.691 971-16521/? E/android.os.Debug: ro.product_ship = true
    ro.debug_level = 0x4f4c
08-24 18:43:12.821 25686-16530/? E/SQLiteLog: (284) automatic index on crash_info_summary(package_name_touched)
08-24 18:43:14.981 1188-1188/? E/StatusBar.NetworkController: isSglteMode is false
08-24 18:43:14.981 1188-1188/? E/StatusBar.NetworkController: refreshSignalCluster: roam
    refreshSignalCluster: set mShowPhoneRSSIForData = false
08-24 18:43:14.981 1188-1188/? E/StatusBar.NetworkController: isSglteMode is false
08-24 18:43:14.981 1188-1188/? E/StatusBar.NetworkController: refreshSignalCluster: roam
    refreshSignalCluster: set mShowPhoneRSSIForData = false
08-24 18:43:14.981 1188-1188/? E/StatusBar.NetworkController: isSglteMode is false
08-24 18:43:14.981 1188-1188/? E/StatusBar.NetworkController: refreshSignalCluster: roam
    refreshSignalCluster: set mShowPhoneRSSIForData = false
08-24 18:43:14.981 1188-1188/? E/StatusBar.NetworkController: isSglteMode is false
08-24 18:43:14.981 1188-1188/? E/StatusBar.NetworkController: refreshSignalCluster: roam
    refreshSignalCluster: set mShowPhoneRSSIForData = false
08-24 18:43:17.911 5935-6189/? E/multisource: HCDN_LOG: [2018-08-24 18:43:17.920][T:6189]UpdateMaxSpeed m_pspeed:0[0,0], m_ospeed:0[0,0], m_prspeed:0[0,0], m_maxDownloadSpeed:0
08-24 18:43:19.121 6147-6282/? E/multisource: HCDN_LOG: [2018-08-24 18:43:19.135][T:6282]UpdateMaxSpeed m_pspeed:0[0,0], m_ospeed:0[0,0], m_prspeed:0[0,0], m_maxDownloadSpeed:0
08-24 18:43:22.811 971-971/? E/SContext.CaeProvider: setProperty() : attribute is null!
08-24 18:43:23.001 1235-1235/? E/MtpServerJNI: server is null in send_object_removed

**Comment by aifengshen** [comment]
toast是荣耀系统的事，跟replugin无关，小米、锤子、中兴等系统对于多条toast是一条接着一条展示，而荣耀系统是最后那条会把前面的toast快速顶掉，只正常展示最后一条toast。
