### ISSUE TITLE
java.lang.Object android.content.Context.getSystemService(java.lang.String)

### ISSUE THREAD

**Issue by shanyaodan** [Qihoo360/RePlugin#653]
#### 问题详细描述 Detailed description of the problem
创建插件工程，app 继承application，里面启动了服务， 界面只有一个fragment,
主工程启动插件fragment ,
报 java.lang.Object android.content.Context.getSystemService(java.lang.String)
demo中去掉 layout里面的fragment也会报错，

#### 复现问题步骤 Steps to reproduce the problem
开启app直接报错java.lang.Object android.content.Context.getSystemService(java.lang.String)

#### 其它重要信息 Other important information

replugin-host-lib/gradle  2.3.0:
rePlugin-plugin-lib/gradle 2.3.0:

Android API Version：
小米6

#### Logcat上下文 Logcat context
08-27 15:49:28.227 2773-5698/? W/HwPowerMonitor.DayActObserver: mModemLogStatsTimes = 0, ModemLogState = 0
    BAT_CHANGED, mIsScrnOffBatStatsEnabled = true, mIsCharging = true, mIsScrnOfBatDropMonitorStart = false
08-27 15:49:29.817 2512-2512/? E/wpa_supplicant: RSSI=-47;LINKSPEED=72;NOISE=9999;FREQUENCY=2437;
08-27 15:49:29.817 1324-1993/? E/WifiConfigStore: updateConfiguration freq=2437 BSSID=64:05:e9:0c:ec:60 RSSI=-47 "infomedia-ap"WPA_PSK
08-27 15:49:30.477 17583-17583/com.infomedia.yunbian E/CrashReport: sys default last handle start!
08-27 15:49:30.487 17583-17583/com.infomedia.yunbian E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.infomedia.yunbian, PID: 17583
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.view.LayoutInflater.from(LayoutInflater.java:231)
        at com.qihoo360.replugin.sample.demo1.fragment.DemoFragment.onCreateView(DemoFragment.java:38)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:18930)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:918)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:647)
        at android.view.View.measure(View.java:18930)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:18930)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1486)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:765)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:647)
        at android.view.View.measure(View.java:18930)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:18930)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1486)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:765)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:647)
        at android.view.View.measure(View.java:18930)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:18930)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1486)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:765)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:647)
        at android.view.View.measure(View.java:18930)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5976)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2705)
        at android.view.View.measure(View.java:18930)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2154)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1248)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1484)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
    	at android.view.ViewRootImpl$T

**Comment by shanyaodan** [comment]
已解决，

**Comment by shanyaodan** [comment]
已解决，

**Comment by jiangshihua** [comment]
怎么解决的

**Comment by ania93** [comment]
> 已解决，

同问，怎么解决的？

**Comment by smm113522** [comment]
在宿主程序中，写上 RePlugin.fetchContext("fragment");就可以了。
