### ISSUE TITLE
9.0系统崩溃

### ISSUE THREAD

**Issue by wx2013** [Qihoo360/RePlugin#658]
#### 问题详细描述 Detailed description of the problem
9.0更新支持了之后,就对插件进行了更新
然后在 AS 的模拟器上新建了9.0的系统,发现崩溃,于是又创建了8.0系统的,没有发现崩溃.
插件集成了百度语音

#### 复现问题步骤 Steps to reproduce the problem 
9.0运行插件就崩溃

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.0
rePlugin-plugin-lib/gradle Version:2.30

Android API Version：9.0
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context

 E/AndroidRuntime: FATAL EXCEPTION: Thread-64
    Process:  包名, PID: 11986
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/message/BasicNameValuePair;
        at com.baidu.tts.e.a.c(StatHelper.java:192)
        at com.baidu.tts.e.a.a(StatHelper.java:154)
        at com.baidu.tts.e.a.b(StatHelper.java:130)
        at com.baidu.tts.e.a.a(StatHelper.java:88)
        at com.baidu.tts.e.b.run(StatThread.java:19)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicNameValuePair" on path: DexPathList[[zip file "/data/user/0/包名/app_plugins_v3/tts-release-10-10-20.jar"],nativeLibraryDirectories=[/data/user/0/包名/app_plugins_v3_libs/tts-release-10-10-20, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at com.qihoo360.replugin.c.loadClass(Unknown Source:96)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.baidu.tts.e.a.c(StatHelper.java:192) 
        at com.baidu.tts.e.a.a(StatHelper.java:154) 
        at com.baidu.tts.e.a.b(StatHelper.java:130) 
        at com.baidu.tts.e.a.a(StatHelper.java:88) 
        at com.baidu.tts.e.b.run(StatThread.java:19) 
09-07 14:34:29.760 11986-12383/? E/AndroidRuntime: FATAL EXCEPTION: Thread-65
    Process: 包名, PID: 11986
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/message/BasicNameValuePair;
        at com.baidu.tts.e.a.c(StatHelper.java:192)
        at com.baidu.tts.e.a.a(StatHelper.java:154)
        at com.baidu.tts.e.a.b(StatHelper.java:130)
        at com.baidu.tts.e.a.a(StatHelper.java:88)
        at com.baidu.tts.e.b.run(StatThread.java:19)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicNameValuePair" on path: DexPathList[[zip file "/data/user/0/包名/app_plugins_v3/tts-release-10-10-20.jar"],nativeLibraryDirectories=[/data/user/0/包名/app_plugins_v3_libs/tts-release-10-10-20, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at com.qihoo360.replugin.c.loadClass(Unknown Source:96)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.baidu.tts.e.a.c(StatHelper.java:192) 
        at com.baidu.tts.e.a.a(StatHelper.java:154) 
        at com.baidu.tts.e.a.b(StatHelper.java:130) 
        at com.baidu.tts.e.a.a(StatHelper.java:88) 
        at com.baidu.tts.e.b.run(StatThread.java:19)

**Comment by bnotebook** [comment]
apache 的http库在android 9.0删除导致的，你的问题应该是使用的replugin不是最新版本或者插件中可能打包了apache 的http库。
修改建议：
1、检查下replugin是否是最新版本。
2、最好不要使用httpClient来访问网络，替换成HttpURLConnection或者OKHttp。
3、插件中如果使用apache的http库，应该使用useLibrary'org.apache.http.legacy'方式，不要把类库编译进最终生成的包中。

**Comment by runfengai** [comment]
> apache 的http库在android 9.0删除导致的，你的问题应该是使用的replugin不是最新版本或者插件中可能打包了apache 的http库。
> 修改建议：
> 1、检查下replugin是否是最新版本。
> 2、最好不要使用httpClient来访问网络，替换成HttpURLConnection或者OKHttp。
> 3、插件中如果使用apache的http库，应该使用useLibrary'org.apache.http.legacy'方式，不要把类库编译进最终生成的包中。

您好，如果在插件和宿主中都使用了apache的库的话，会有问题，现象就是两个类对应的classLoader不一致。具体是[#1011](https://github.com/Qihoo360/RePlugin/issues/1011)
