### ISSUE TITLE
插件里FragmentActivity没有被替换为PluginFragmentActivity

### ISSUE THREAD

**Issue by jiashie** [Qihoo360/RePlugin#664]
#### 问题详细描述 Detailed description of the problem
插件里有一个继承自support-v4的FragmentActivity的activity，而support-v4的jar包是通过provided的方式引用的，因为宿主里会有support-v4的代码。
生成插件apk后发现这个activity没有被替换为PluginFragmentActivity，导致在运行时跳转到这个界面时崩溃。

#### 复现问题步骤 Steps to reproduce the problem
1. 插件里添加一个继承自support-v4 fragmentActivity的acitivity
2. support-v4包通过provided方式引用

#### 其它重要信息 Other important information
**很可能是plugin-gradle在Util.getProjectClassPath()方法里没有添加provided的jar到classpath**
replugin-host-lib/gradle Version:230
rePlugin-plugin-lib/gradle Version:230

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.demo/com.my.demo.loader.a.ActivityN1NRTS1}: android.content.res.Resources$NotFoundException: Resource ID #0x7f080063
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f080063
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:279)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2310)
        at android.content.res.Resources.getLayout(Resources.java:1293)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:477)
        at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:321)
        at android.app.Activity.setContentView(Activity.java:2839)
        at com.my.plugin.activity.InnerSdkActivity.onCreate(InnerSdkActivity.java:333)
        at android.app.Activity.performCreate(Activity.java:7372)

**Comment by langxuelang** [comment]
你好，请问这个问题，解决了吗 @jiashie

**Comment by flycumt** [comment]
同样的问题，我现在是直接继承了PluginFragmentActivity来处理的，不过我有自己的基类FragmentActivity继承它的就不能继承我的了。。基类库是一个aar又不能引入plugin lib来处理，如你有好的解决方案请通知我一下，谢谢！

**Comment by weikano** [comment]
@flycumt 你继承FragmentActivity然后把PluginFragmentActivity里面的特殊处理加到你自己的Activity里面不就好了……

**Comment by chinaShawn** [comment]
> 同样的问题，我现在是直接继承了PluginFragmentActivity来处理的，不过我有自己的基类FragmentActivity继承它的就不能继承我的了。。基类库是一个aar又不能引入plugin lib来处理，如你有好的解决方案请通知我一下，谢谢！

我现在也是这种解决方案，但是对于第三房中的activity就没有办法处理了。
