### ISSUE TITLE
ThemeDialogActivity 启动失败

### ISSUE THREAD

**Issue by OOMROO** [Qihoo360/RePlugin#665]
#### 问题详细描述 Detailed description of the problem

   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRTS1}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.Activity.onCreate(Activity.java:1081)
        at com.qihoo360.replugin.loader.a.PluginActivity.onCreate(Unknown Source:3)
        at com.qihoo360.replugin.sample.demo1.activity.theme.ThemeDialogActivity.onCreate(ThemeDialogActivity.java:38)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
#### 复现问题步骤 Steps to reproduce the problem
1.  demo1 中的 ThemeDialogActivity  适配 8.0  插件可以单独运行。替换host 中的demo.jar 在host 中报错
2.  插件中已经去掉了screenOrientation="portrait"  
3 . 在华为手机上发现这个问题。 华为 honor  系统 Honor7C  ,android 8.0

#### 其它重要信息 Other important information
 

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

华为 honor 8.0

**Comment by OOMROO** [comment]
貌似 targetsdk 改为 26 可以  不是很希望改为26 有更好的办法吗

**Comment by bnotebook** [comment]
应该是安卓高版本对透明activity的限制引起的，建议跟进相应的安卓官网文档进行适配修改。

**Comment by OOMROO** [comment]
不是高版本的问题，单品在8.0版本上可以运行，在作为插件使用的时候报错（单品中已经适配）

**Comment by wangbo4020** [comment]
是坑位Activity配置了方向。

**Comment by ftyan805614** [comment]
> 不是高版本的问题，单品在8.0版本上可以运行，在作为插件使用的时候报错（单品中已经适配）

请问你的问题解决了吗
