### ISSUE TITLE
插件和宿主使用相同包名的自定义Preference会出现java.lang.ClassCastException: com.meizu.common.preference.SwitchPreference cannot be cast to com.meizu.common.preference.SwitchPreference

### ISSUE THREAD

**Issue by bramles** [Qihoo360/RePlugin#668]
#### 问题详细描述 Detailed description of the problem
java.lang.ClassCastException: com.meizu.common.preference.SwitchPreference cannot be cast to com.meizu.common.preference.SwitchPreference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2960)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1729)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6758)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

#### 复现问题步骤 Steps to reproduce the problem
1. 插件和宿主引入同样的aar
2. 使用aar中的自定义Preference
3.分别进入宿主和插件的页面，第二次会出现崩溃

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.3.0

Android API Version：27

怀疑是因为android的preference机制和View类似，findPreference时做了缓存，希望框架可以进行处理

**Comment by bnotebook** [comment]
根据描述推测：插件和宿主使用了相同的系统类，由于ClassLoader的不同，会被认为是2个不同的类，所以第一次进入宿主不会有问题，再次进入插件时，就会出现类型不匹配的错误。
解决方法：
都使用同一套类。可修改框架类加载方式，共享类库，或者使用AIDL在宿主和插件间提供服务，由一方来完成操作。
当然也可以把报错的类编译到宿主和插件包中也可。
