### ISSUE TITLE
插件Notification 使用remoteView崩溃

### ISSUE THREAD

**Issue by chrisLeeCreate** [Qihoo360/RePlugin#670]
#### 问题详细描述 Detailed description of the problem

插件Notification 使用remoteView崩溃
如果不使用remoteview不崩溃

remoteview 自定义布局是插件中的，可是一直在host中查找。导致找不到
context 使用Replugin.getPluginContex()传入。依然崩溃

#### 复现问题步骤 Steps to reproduce the problem
1. 插件中使用Notification 使用remoteView自定义布局
2. 插件自运行没事 插入host中崩溃

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.4
rePlugin-plugin-lib/gradle Version: 2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
xiaomi huawei 魅族等

#### Logcat上下文 Logcat context

android.content.res.Resources$NotFoundException: File res/mipmap-xxhdpi-v4/ic_launcher_round.png from xml type layout resource ID #0x7f030001
        at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1435)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2312)
        at android.content.res.Resources.getLayout(Resources.java:1293)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
        at android.widget.RemoteViews.inflateView(RemoteViews.java:3498)
        at android.widget.RemoteViews.apply(RemoteViews.java:3441)
        at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:2024)
        at com.android.systemui.statusbar.BaseStatusBar.createNotificationViews(BaseStatusBar.java:2605)
        at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1879)
        at com.android.systemui.statusbar.BaseStatusBar$7$2.run(BaseStatusBar.java:798)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.io.FileNotFoundException: Corrupt XML binary file
        at android.content.res.AssetManager.openXmlAssetNative(Native Method)
        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:862)
        at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1420)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2312) 
        at android.content.res.Resources.getLayout(Resources.java:1293) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:421) 
        at android.widget.RemoteViews.inflateView(RemoteViews.java:3498) 
        at android.widget.RemoteViews.apply(RemoteViews.java:3441) 
        at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:2024) 
        at com.android.systemui.statusbar.BaseStatusBar.createNotificationViews(BaseStatusBar.java:2605) 
        at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1879) 
        at com.android.systemui.statusbar.BaseStatusBar$7$2.run(BaseStatusBar.java:798) 
        at android.os.Handler.handleCallback(Handler.java:808) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
09-24 15:21:19.962 8792-8792/? I/FloatNotificationManager: removeNotification: key =0|com.qihoo360

**Comment by shaobin0604** [comment]
@chrisLeeCreate RemoteView 是 SystemUI 通过宿主的 package context 创建的，无法找到放到插件中的 layout 。RePlugin 的文档中有提到这个限制

**Comment by chrisLeeCreate** [comment]
已经解决 谢谢

**Comment by ranzhenxing** [comment]
@chrisLeeCreate 请问怎么解决的？
