### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by yyfBlog** [Qihoo360/RePlugin#671]
#### 问题详细描述 Detailed description of the problem
09-25 15:16:46.744 7024-7024/com.gzytgk.vend W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.gzytgk.model_ui.home.GoodsShowFragment" on path: DexPathList[[zip file "/data/data/com.gzytgk.vend/app_plugins_v3/model_ui-release-10-10-1.jar"],nativeLibraryDirectories=[/system/lib]]
09-25 15:16:46.744 7037-7048/com.gzytgk.vend:GuardService D/RePlugin.ws001: replace plugin info: info=PInfo { <model_ui-release:1(4)> [P-N] [DEX_EXTRACTED] [RUNNING] processes=[com.gzytgk.vend] js={"ali":"model_ui-release","frm_ver":4,"name":"model_ui-release","path":"\/data\/data\/com.gzytgk.vend\/app_plugins_v3\/model_ui-release-10-10-1.jar","verv":2814792716779521,"ver":1,"high":10,"type":1,"low":10,"pkgname":"com.gzytgk.model_ui"} dex=/data/user/0/com.gzytgk.vend/app_plugins_v3_odex/model_ui-release-10-10-1.dex nlib=/data/user/0/com.gzytgk.vend/app_plugins_v3_libs/model_ui-release-10-10-1 } rc=true
    replace plugin table: info=PInfo { <model_ui-release:1(4)> [P-N] [DEX_EXTRACTED] [RUNNING] processes=[com.gzytgk.vend] js={"ali":"model_ui-release","frm_ver":4,"name":"model_ui-release","path":"\/data\/data\/com.gzytgk.vend\/app_plugins_v3\/model_ui-release-10-10-1.jar","verv":2814792716779521,"ver":1,"high":10,"type":1,"low":10,"pkgname":"com.gzytgk.model_ui"} dex=/data/user/0/com.gzytgk.vend/app_plugins_v3_odex/model_ui-release-10-10-1.dex nlib=/data/user/0/com.gzytgk.vend/app_plugins_v3_libs/model_ui-release-10-10-1 } rc=true
09-25 15:16:46.744 7024-7024/com.gzytgk.vend W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:96)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at com.gzytgk.vend.MainActivity.initView(MainActivity.java:32)
        at com.gzytgk.vend.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
09-25 15:16:46.754 7024-7024/com.gzytgk.vend W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
09-25 15:16:46.954 7024-7024/com.gzytgk.vend W/EGL_emulation: eglSurfaceAttrib not implemented 3093 12436
09-25 15:16:47.084 274-452/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1123 com.android.server.InputMethodManagerService.hideCurrentInputLocked:1880 com.android.server.InputMethodManagerService.windowGainedFocus:1968 com.android.internal.view.IInputMethodManager$Stub.onTransact:221 com.android.server.InputMethodManagerService.onTransact:818 
09-25 15:16:47.714 274-286/? I/ActivityManager: Displayed com.gzytgk.vend/.MainActivity: +987ms
09-25 15:17:51.364 1268-1268/? E/shadowsocks: send: Connection reset by peer

#### 复现问题步骤 Steps to reproduce the problem
1.  宿主加载显示插件中的fragment出现上述问题

**Comment by bnotebook** [comment]
请检查ClassLoader是否使用正确，插件中的类加载时应该使用插件的ClassLoader对象。
