### ISSUE TITLE
宿主调用插件fragment弹dialog等问题

### ISSUE THREAD

**Issue by cr1944** [Qihoo360/RePlugin#697]
#### 问题详细描述 Detailed description of the problem
1. 在插件fragment中使用android.app.AlertDialog可以正常弹出，但是使用android.support.v4.app.AlertDialog则报错
2. 宿主activity使用appcompat主题，加载插件fragment，插件中的布局没有使用appcompat主题，如何才能使插件fragment使用宿主activity的主题？

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by cr1944** [comment]
第二个问题解决了：
RePlugin.getPluginContext().setTheme(R.style.Theme_AppCompat);

**Comment by hyongbai** [comment]
第一个问题：

- 报错的具体错误信息可以贴一下吗

- 如何调用AlertDialog的哈？能否把实现贴出来。

**Comment by cr1944** [comment]
> 第一个问题：
> 
> * 报错的具体错误信息可以贴一下吗
> * 如何调用AlertDialog的哈？能否把实现贴出来。

我是把插件的support fragment移除了然后compileOnly，从宿主加载插件的fragment，应该跟这有关
```
java.lang.UnsupportedOperationException: Can't convert value at index 1 to dimension: type=0x1
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:732)
        at android.support.v7.app.AlertController.<init>(AlertController.java:199)
        at android.support.v7.app.AlertDialog.<init>(AlertDialog.java:98)
        at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:980)
```
