### ISSUE TITLE
Android9.0手机进入插件崩溃

### ISSUE THREAD

**Issue by JeromeWJ** [Qihoo360/RePlugin#701]
#### 问题详细描述 Detailed description of the problem
使用replugin最新版本2.3.0，打开插件时崩溃

#### 复现问题步骤 Steps to reproduce the problem
1. 点击插件服务，正常下载安装
2. 进入插件崩溃

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.3.0

Android API Version：9.0
Android 手机型号&ROM(Phone model & ROM): 华为Mete20 pro

#### Logcat上下文 Logcat context
AndroidRuntime: FATAL EXCEPTION: Thread-24
    Process: 包名, PID: 5435
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/util/ByteArrayBuffer;
        at com.iflytek.cloud.thirdparty.ad.a(Unknown Source:8)
        at com.iflytek.cloud.thirdparty.ad.b(Unknown Source:210)
        at com.iflytek.cloud.thirdparty.ad.run(Unknown Source:5)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.util.ByteArrayBuffer" on path: DexPathList[[zip file "/data/user/0/包名/app_p_a/-782538389.jar"],nativeLibraryDirectories=[/data/user/0/包名/app_p_n/-782538389, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:96)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.iflytek.cloud.thirdparty.ad.a(Unknown Source:8) 
        at com.iflytek.cloud.thirdparty.ad.b(Unknown Source:210) 
        at com.iflytek.cloud.thirdparty.ad.run(Unknown Source:5)

**Comment by hyongbai** [comment]
从你贴出来的stacktrace看的出来，你宿主里面的PluginDexClassLoader不是最新版本的。

这个问题在：<https://github.com/Qihoo360/RePlugin/commit/5f616e92d89d6f8a59065ee5d271b809aa57df1c#diff-6f899b4fbd4f65ab7580201bc86f9e57> 这个提交已经解决了。

解决前：super.loadClass(className, resolve)是在96行。

解决后：super.loadClass(className, resolve)挪到了100行。

麻烦看一下出问题宿主的RePlugin版本。

注：

使用如下方式接入ApacheHttp(compileOnly/provided)

```java
android {
    useLibrary 'org.apache.http.legacy'
}
```

**Comment by hyongbai** [comment]
@JeromeWJ 

如你所说，是这么个情况。

你先自己编译个aar，然后使用MavenLocal的方式部署一下。

保证你们这边正常的逻辑。下个版本我们会一并提交到jcenter上面。

谢谢，反馈。
