### ISSUE TITLE
attachBaseContext时的空指针崩溃

### ISSUE THREAD

**Issue by Roger-Zhou** [Qihoo360/RePlugin#703]
#### 问题详细描述 Detailed description of the problem

用户反馈的崩溃

#### 复现问题步骤 Steps to reproduce the problem

用户反馈的崩溃，没有重现机型

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4

Android API Version：7.1.1 , API level 25
Android 手机型号&ROM(Phone model & ROM):  一加五

#### Logcat上下文 Logcat context

java.lang.RuntimeException: Unable to instantiate application com.stub.StubApp: java.lang.RuntimeException: Failed to call attachBaseContext.
  at android.app.LoadedApk.makeApplication(LoadedApk.java:834)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5592)
  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
  at android.app.ActivityThread.handleBindApplication(<Xposed>)
  at android.app.ActivityThread.-wrap2(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6334)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.RuntimeException: Failed to call attachBaseContext.
  at com.stub.StubApp.attachBaseContext(SourceFile:328)
  at android.app.Application.attach(Application.java:218)
  at android.app.Instrumentation.newApplication(Instrumentation.java:1012)
  at android.app.Instrumentation.newApplication(Instrumentation.java:996)
  at android.app.LoadedApk.makeApplication(LoadedApk.java:816)
  ... 13 more
Caused by: java.lang.reflect.InvocationTargetException
  at java.lang.reflect.Method.invoke(Native Method)
  at com.stub.StubApp.attachBaseContext(SourceFile:325)
  ... 17 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Application.getApplicationContext()' on a null object reference
  at me.piebridge.prevent.ui.a.a$1.replaceHookedMethod(AntiContactMod.java:24)
  at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
  at android.content.ContentResolver.query(<Xposed>)
  at com.qihoo360.loader2.ag.a(PluginProviderStub.java)
  at com.qihoo360.loader2.ag.a(PluginProviderStub.java)
  at com.qihoo360.loader2.ac.b(PluginProcessMain.java)
  at com.qihoo360.loader2.aj.b(PmBase.java)
  at com.qihoo360.loader2.n.a(PMF.java)
  at com.qihoo360.replugin.RePlugin$a.a(RePlugin.java)
  at com.xunlei.downloadprovider.app.BrothersApplication.attachBaseContext(BrothersApplication.java)
  at android.app.Application.attach(Application.java:218)
  ... 19 more

**Comment by hyongbai** [comment]
在非xposed手机上面同样的NPE吗？
