### ISSUE TITLE
java.lang.LinkageError异常

### ISSUE THREAD

**Issue by Hidderr** [Qihoo360/RePlugin#708]
应用内的插件运行报以下错误：
java.lang.LinkageError: Class com.loopj.android.http.RetryHandler method boolean com.loopj.android.http.RetryHandler.retryRequest(java.io.IOException, int, org.apache.http.protocol.HttpContext) resolves differently in interface org.apache.http.client.HttpRequestRetryHandler: Parameter 2 type mismatch: java.lang.Class<org.apache.http.protocol.HttpContext,com.qihoo360.replugin.c>(0x140d4620) vs java.lang.Class<org.apache.http.protocol.HttpContext,dalvik.system.PathClassLoader>(0x79711d40) (declaration of 'com.loopj.android.http.RetryHandler' appears in /data/user/0/com.huawei.smarthome/app_p_a/-1609019829.jar)
	at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:307)
	at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:177)
	at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:147)

问题复现：1.首先打开宿主应用，然后点击加载插件，然后运行插件，插件崩溃，报以上异常
只是出现在个别手机上，如华为Mate10Pro，

希望知道的解答一下，

**Comment by hyongbai** [comment]
调用RetryHandler.retryRequest传入的HttpContext实例是哪个ClassLoader生成的?

**Comment by Hidderr** [comment]
是new 出来的默认是PathClassLoader，出现这个问题只是在华为Mate10个别用户的手机上，其他的都正常，因为宿主不是会用代理的ClassLoader替换掉插件的PathClassLoader吗，其他手机正常，是不是和手机系统有关系请问？
