### ISSUE TITLE
外置插件首页集成了TabActivity，使用了TabHost，宿主在运行APK的时候，报错提示  host.addTab(host.newTabSpec(STATISTIC_LIST).setIndicator("tab2") .setContent(new Intent(MainActivity.this, Activity2.class)))，说找不到这个Activity，没有注册，请问这个要怎么解决呢？

### ISSUE THREAD

**Issue by androidxiayu** [Qihoo360/RePlugin#709]
#### 问题详细描述 Detailed description of the problem

外置插件首页使用了TabActivity，用TabHost 添加tab的时候，在宿主中运行报错，说是找不到Activity，说没有注册，插件版本用的是com.qihoo360.replugin:replugin-plugin-lib:2.2.4这个版本
     host.addTab(host.newTabSpec(STATISTIC).setIndicator("tab1")
                    .setContent(new Intent(MainActivity.this, Activity1.class)));
     host.addTab(host.newTabSpec(STATISTIC_LIST).setIndicator("tab2")
                    .setContent(new Intent(MainActivity.this, Activity2.class)));

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
  java.lang.RuntimeException: Unable to start activity ComponentInfo{demo.plugin.xy.cm.plugindemo/demo.plugin.xy.cm.plugindemo.loader.a.ActivityN1NRNTS5}: android.content.ActivityNotFoundException: Unable to find explicit activity class {demo.plugin.xy.cm.plugindemo/demo.plugin.xy.cm.mydemo2.Activity1}; have you declared this activity in your AndroidManifest.xml?
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2853)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918)
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                  at android.os.Looper.loop(Looper.java:203)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6406)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
                                                                               Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {demo.plugin.xy.cm.plugindemo/demo.plugin.xy.cm.mydemo2.Activity1}; have you declared this activity in your AndroidManifest.xml?
                                                                                  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1816)
                                                                                  at android.app.ActivityThread.resolveActivityInfo(ActivityThread.java:2623)
                                                                                  at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:286)
                                                                                  at android.widget.TabHost$IntentContentStrategy.getContentView(TabHost.java:724)
                                                                                  at android.widget.TabHost.setCurrentTab(TabHost.java:388)
                                                                                  at android.widget.TabHost.addTab(TabHost.java:222)
                                                                                  at demo.plugin.xy.cm.mydemo2.MainActivity.CheckOnclick(MainActivity.java:61)
                                                                                  at demo.plugin.xy.cm.mydemo2.MainActivity.initViews(MainActivity.java:49)
                                                                                  at demo.plugin.xy.cm.mydemo2.MainActivity.onCreate(MainActivity.java:38)
                                                                                  at android.app.Activity.performCreate(Activity.java:6758)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2806)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918) 
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                                  at android.os.Looper.loop(Looper.java:203) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6406) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by zlg2338781286** [comment]
采用fragment
