### ISSUE TITLE
集成需要哪些权限？麻烦文档写下

### ISSUE THREAD

**Issue by Siomt** [Qihoo360/RePlugin#716]
#### 问题详细描述 Detailed description of the problem
缺少权限android.permission.READ_SYNC_SETTINGS

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context

11-19 14:03:47.183 30411-30411/com.xxx.xxxxx  E/CrashFile: 错误CrashTime=2018-11-19 14:03:47.172
    BOARD=EVA-AL00
    CPU_ABI2=armeabi
    HOST=wuhjk0387cna
    versionName=v2.2.1
    IS_TREBLE_ENABLED=true
    SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@8107aab
    CPU_ABI=armeabi-v7a
    PERMISSIONS_REVIEW_REQUIRED=false
    IS_USERDEBUG=false
    DISPLAY=EVA-AL00 8.0.0.535(C00)
    SUPPORTED_ABIS=[Ljava.lang.String;@fa68508
    FINGERPRINT=HUAWEI/EVA-AL00/HWEVA:8.0.0/HUAWEIEVA-AL00/535(C00):user/release-keys
    PRODUCT=EVA-AL00
    HIDE_PRODUCT_INFO=false
    ID=HUAWEIEVA-AL00
    replacements=[Ljava.lang.String;@a3f76c6
    TYPE=user
    SERIAL=PBV0216B01002150
    NO_HOTA=false
    IS_CONTAINER=false
    IS_ENG=false
    DEVICE=HWEVA
    TIME=1537190797000
    IS_USER=true
    MODEL=EVA-AL00
    MANUFACTURER=HUAWEI
    USER=test
    versionCode=25
    BRAND=HUAWEI
    SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@b2604fa
    matchers=[Ljava.lang.String;@29f44a1
    HARDWARE=hi3650
    IS_DEBUGGABLE=false
    BOOTLOADER=unknown
    RADIO=unknown
    TAG=Build
    UNKNOWN=unknown
    IS_EMULATOR=false
    TAGS=release-keys
    java.lang.SecurityException: no permission to read the sync settings: Neither user 10401 nor current process has android.permission.READ_SYNC_SETTINGS.
        at android.os.Parcel.readException(Parcel.java:1946)
        at android.os.Parcel.readException(Parcel.java:1892)
        at android.content.IContentService$Stub$Proxy.getMasterSyncAutomatically(IContentService.java:1302)
        at android.content.ContentResolver.getMasterSyncAutomatically(ContentResolver.java:2637)
        at com.fsck.k9.service.MailService.startService(MailService.java:95)
        at com.fsck.k9.service.CoreService.onStartCommand(CoreService.java:245)
        at com.qihoo360.replugin.component.service.server.PluginServiceServer$1.handleMessage(PluginServiceServer.java:110)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
11-19 14:03:47.183 30411-30411/com.bjytsw.zhengtong I/Process: Sending signal. PID: 30411 SIG: 9

**Comment by Siomt** [comment]
问题我解决了，提个问题给后来的人看

**Comment by bnotebook** [comment]
需要什么权限跟进你的业务需求添加就行了
