### ISSUE TITLE
 java.lang.VerifyError: Verifier rejected class

### ISSUE THREAD

**Issue by Siomt** [Qihoo360/RePlugin#717]
#### 问题详细描述 Detailed description of the problem
程序崩溃

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
Process: com.fsck.k9.debug, PID: 9686
    java.lang.VerifyError: Verifier rejected class com.fsck.k9.activity.UpgradeDatabases: void com.fsck.k9.activity.UpgradeDatabases.setupBroadcastReceiver() failed to verify: void com.fsck.k9.activity.UpgradeDatabases.setupBroadcastReceiver(): [0x15] register v0 has type Reference: java.lang.Object but expected Precise Reference: android.support.v4.content.LocalBroadcastManager (declaration of 'com.fsck.k9.activity.UpgradeDatabases' appears in /data/app/com.fsck.k9.debug--_cnEqjNe-MACqRWEXiUUQ==/split_lib_directories_apk.apk)
        at com.fsck.k9.activity.UpgradeDatabases.actionUpgradeDatabases(Unknown Source:0)
        at com.fsck.k9.activity.Accounts.onCreate(Accounts.java:389)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by Siomt** [comment]
> 跟我遇到的问题一样android.support.v4.content.LocalBroadcastManager

改成普通的广播就好了
