### ISSUE TITLE
插件内使用第三方的资源文件找不到，只是打开本地相册的功能

### ISSUE THREAD

**Issue by xy348735514** [Qihoo360/RePlugin#726]
android.content.res.Resources$NotFoundException: Resource ID #0x7f010000
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:196)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2184)
        at android.content.res.Resources.getAnimation(Resources.java:1222)
        at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:109)
        at com.android.server.wm.AppTransition.loadAnimationRes(AppTransition.java:553)
        at com.android.server.wm.AppTransition.loadAnimation(AppTransition.java:1492)
        at com.android.server.wm.WindowManagerService.applyAnimationLocked(WindowManagerService.java:3813)
        at com.android.server.wm.WindowManagerService.setTokenVisibilityLocked(WindowManagerService.java:5121)
        at com.android.server.wm.WindowSurfacePlacer.handleClosingApps(WindowSurfacePlacer.java:1420)
        at com.android.server.wm.WindowSurfacePlacer.handleAppTransitionReadyLocked(WindowSurfacePlacer.java:1292)
        at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner(WindowSurfacePlacer.java:352)
        at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:249)
        at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:198)
        at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:3536)
        at com.android.server.wm.Session.relayout(Session.java:226)
        at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:286)
        at com.android.server.wm.Session.onTransact(Session.java:147)
        at android.os.Binder.execTransact(Binder.java:637)

**Comment by hyongbai** [comment]
<https://github.com/Qihoo360/RePlugin/wiki/局限和未来大计划#activity>

RePlugin不支持插件(如Activity)的转场动画
