### ISSUE TITLE
admob插件化 提示 Could not fetch ad response due to an Exception.

### ISSUE THREAD

**Issue by panshouye** [Qihoo360/RePlugin#744]
#### 问题详细描述 Detailed description of the problem
将admob 放到插件中，宿主运行后报，不显示广告，插件单独运行没有问题
Ads: Could not fetch ad response due to an Exception.
    java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageInfo.packageName' on a null object reference
        at com.google.android.gms.internal.ads.zzafn.zza(Unknown Source)
        at com.google.android.gms.internal.ads.zzafn.zzb(Unknown Source)
        at com.google.android.gms.internal.ads.zzafp.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by dongwangcheng** [comment]
请问解决了吗
