### ISSUE TITLE
Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x1010099 a=1}

### ISSUE THREAD

**Issue by zhangbaogithub** [Qihoo360/RePlugin#747]
#### 问题详细描述 Detailed description of the problem
插件作为单品可以正常启动，宿主中启动插件会crash

#### 复现问题步骤 Steps to reproduce the problem
1. 插件打包推送到SD卡中
2. 宿主启动插件

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.1
rePlugin-plugin-lib/gradle Version:2.3.1

Android API Version：27
Android 手机型号&ROM(Phone model & ROM): Xiaomi Redmi 5 & MIUI 10 8.12.6

#### Logcat上下文 Logcat context
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sh.clustergamesdk/com.sh.clustergamesdk.loader.a.ActivityN1STNTS0}: android.view.InflateException: Binary XML file line #94: Binary XML file line #94: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: android.view.InflateException: Binary XML file line #94: Binary XML file line #94: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #94: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:724)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:792)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.jinwan.module.b.c.h.onCreateView(Unknown Source:13)
        at android.app.Fragment.performCreateView(Fragment.java:2508)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1562)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1623)
        at android.app.BackStackRecord.executeOps(BackStackRecord.java:807)
        at android.app.FragmentManagerImpl.executeOps(FragmentManager.java:2391)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2141)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2048)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3037)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2984)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
        at android.app.Activity.performCreate(Activity.java:7094)
        at android.app.Activity.performCreate(Activity.java:7079)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
2018-12-26 20:12:53.216 24020-24020/com.sh.clustergamesdk E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x1010099 a=1}
        at android.content.res.TypedArray.getColor(TypedArray.java:471)
        at android.widget.TextView.<init>(TextView.java:894)
        at android.widget.TextView.<init>(TextView.java:820)
        at android.widget.TextView.<init>(TextView.java:816)
        	... 41 more

**Comment by zhangbaogithub** [comment]
经过验证，发现是TextView不能解析，不清楚为什么，劳烦大佬解释一下

**Comment by Alexey024** [comment]
hello请问下这个问题解决了吗

**Comment by wwluo14** [comment]
> 经过验证，发现是TextView不能解析，不清楚为什么，劳烦大佬解释一下

请问这个问题解决了吗
