### ISSUE TITLE
Replugin在Android4.x系统上运行失败

### ISSUE THREAD

**Issue by ralphgult** [Qihoo360/RePlugin#750]
在Android4.x系统版本的手机上Application中直接崩溃报错
Genymotion模拟器 Android版本：4.4.4
#### Logcat上下文 Logcat context
01-07 02:48:15.668 1558-1558/com.legion.optimus E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.legion.optimus, PID: 1558
    java.lang.ExceptionInInitializerError
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964)
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)
        at cn.yszr.meetoftuhao.utils.MyApplication.attachBaseContext(MyApplication.java:322)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:991)
        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at com.qihoo360.replugin.utils.ReflectUtils.getField(ReflectUtils.java:86)
        at com.qihoo360.replugin.utils.ReflectUtils.readField(ReflectUtils.java:108)
        at com.qihoo360.replugin.utils.ReflectUtils.readStaticField(ReflectUtils.java:100)
        at com.qihoo360.replugin.helper.HostConfigHelper.readField(HostConfigHelper.java:171)
        at com.qihoo360.replugin.helper.HostConfigHelper.<clinit>(HostConfigHelper.java:83)
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60) 
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964) 
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67) 
        at cn.yszr.meetoftuhao.utils.MyApplication.attachBaseContext(MyApplication.java:322) 
        at android.app.Application.attach(Application.java:181) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5001) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by Vove7** [comment]
https://github.com/Qihoo360/RePlugin/issues/847#issuecomment-518514762
