### ISSUE TITLE
multiDexEnabled 开启后出现错误

### ISSUE THREAD

**Issue by yyfBlog** [Qihoo360/RePlugin#751]
#### 问题详细描述 Detailed description of the problem
方法数超过65530后,在appconfig中添加 multiDexEnabled true 时出现以下异常

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:     2.2.4
rePlugin-plugin-lib/gradle Version:   2.2.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
   java.lang.ExceptionInInitializerError
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964)
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:991)
        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at com.qihoo360.replugin.utils.ReflectUtils.getField(ReflectUtils.java:86)
        at com.qihoo360.replugin.utils.ReflectUtils.readField(ReflectUtils.java:108)
        at com.qihoo360.replugin.utils.ReflectUtils.readStaticField(ReflectUtils.java:100)
        at com.qihoo360.replugin.helper.HostConfigHelper.readField(HostConfigHelper.java:171)
        at com.qihoo360.replugin.helper.HostConfigHelper.<clinit>(HostConfigHelper.java:83)
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60) 
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964) 
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67) 
        at android.app.Application.attach(Application.java:181) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5001) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617) 
        at dalvik.system.NativeStart.main(Native Method) 
01-08 19:27:40.565 20487-20487/? E/memtrack: Couldn't load memtrack module (No such file or directory)
01-08 19:27:40.565 20487-20487/? E/android.os.Debug: failed to load memtrack module: -2
01-08 19:27:40.835 20502-20502/com.gzytgk.vend E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gzytgk.vend, PID: 20502
    java.lang.ExceptionInInitializerError
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964)
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:991)
        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at com.qihoo360.replugin.utils.ReflectUtils.getField(ReflectUtils.java:86)
        at com.qihoo360.replugin.utils.ReflectUtils.readField(ReflectUtils.java:108)
        at com.qihoo360.replugin.utils.ReflectUtils.readStaticField(ReflectUtils.java:100)
        at com.qihoo360.replugin.helper.HostConfigHelper.readField(HostConfigHelper.java:171)
        at com.qihoo360.replugin.helper.HostConfigHelper.<clinit>(HostConfigHelper.java:83)
        at com.qihoo360.replugin.base.IPC.init(IPC.java:60) 
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:964) 
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67) 
        at android.app.Application.attach(Application.java:181) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5001) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by wangbo4020** [comment]
https://developer.android.com/studio/build/multidex
参考官方的这篇文章理论上可以解决问题。
找到将指定的类声明到main dex中的方法。

**Comment by zeuscode** [comment]
Task :app:rpGenerateDebugBuiltinJson FAILED

**Comment by asdf19910719** [comment]
> https://developer.android.com/studio/build/multidex
> 参考官方的这篇文章理论上可以解决问题。
> 找到将指定的类声明到main dex中的方法。

指定的类是指哪个?

**Comment by Vove7** [comment]
https://github.com/Qihoo360/RePlugin/issues/847#issuecomment-518514762
