### ISSUE TITLE
启动内置插件的activity崩溃。

### ISSUE THREAD

**Issue by wisesoftym** [Qihoo360/RePlugin#758]
#### 问题详细描述 Detailed description of the problem
Unable to start activity ComponentInfo{com.xxxx.xxxx/com.xxxx.xxxx.loader.a.ActivityN1NRNTS5}: net.grandcentrix.tray.core.TrayRuntimeException: Internal tray error. Could not find the provider authority
	at net.grandcentrix.tray.provider.TrayContract.getAuthority(TrayContract.java:138)
	at net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:109)
	at net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:80)
	at net.grandcentrix.tray.provider.TrayUri.<init>(TrayUri.java:75)
	at net.grandcentrix.tray.provider.ContentProviderStorage.<init>(ContentProviderStorage.java:146)
	at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:43)
	at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:48)
	at net.grandcentrix.tray.AppPreferences.<init>(AppPreferences.java:41)
	at com.publics.library.account.AdminUserManage.getUserInfoFromPref(AdminUserManage.java:75)
	at com.publics.library.account.AdminUserManage.<init>(AdminUserManage.java:35)
	at com.publics.library.account.AdminUserManage.getInstance(AdminUserManage.java:42)

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by bnotebook** [comment]
看日志应该是权限相关的问题导致的，建议先排查下provider是否设置或者调用正确
