### ISSUE TITLE
插件中webview 播放视频报错

### ISSUE THREAD

**Issue by yuhaoz** [Qihoo360/RePlugin#759]
单独工程运行都正常
做成插件后，在webview中播放视频一直报错：
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:1198)
        at org.chromium.android_webview.DefaultVideoPosterRequestHandler$1.run(DefaultVideoPosterRequestHandler.java:39)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by yuhaoz** [comment]
尝试了一些网上提供的方法:
重写getDefaultVideoPoster方法，返回一个默认图片，已经解决该问题
