### ISSUE TITLE
插件设置 taskAffinity 

### ISSUE THREAD

**Issue by qxpd52** [Qihoo360/RePlugin#765]
#### 问题详细描述 Detailed description of the problem
我们现在要给每一个插件设置自己 taskAffinity ， 当我们启动2个插件后，再启动第三个插件的时候 无法启动插件, 请问这个问题怎么解决，是否是最多支持设置两个插件独立的taskAffinity？ 谢谢！

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information
2019-01-30 16:32:05.976 10329-10329/com.xxx.xxx I/RePlugin.ws000: loadLocked(): Initialized, is loaded = true
2019-01-30 16:32:05.977 10329-10329/com.xxx.xxx  D/RePlugin.task-affinity: originTaskAffinity is com.xxx.xxx:pluginC
2019-01-30 16:32:05.977 10347-10370/com.xxx.xxx:GuardService D/RePlugin.task-affinity: Get groupID fail, not enough TaskAffinity group
2019-01-30 16:32:05.977 10329-10334/com.xxx.xxx I/zygote: Do partial code cache collection, code=1011KB, data=733KB
2019-01-30 16:32:05.980 10329-10329/com.xxx.xxx E/ws001: l.p.a spp|aac: length=2; index=-1
    java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
        at com.qihoo360.loader2.TaskAffinityStates.getStates(TaskAffinityStates.java:99)
        at com.qihoo360.loader2.PluginContainers.alloc(PluginContainers.java:570)
        at com.qihoo360.loader2.PluginProcessPer.bindActivity(PluginProcessPer.java:296)
        at com.qihoo360.loader2.PluginProcessPer.allocActivityContainer(PluginProcessPer.java:161)
        at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:437)
        at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:268)
        at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
        at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
        at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:248)

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by fatterx** [comment]
你需要在主工程的replugin config中 增大countTask, 目前默认是2，启动第三个自然会失败
