### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{online.ejiang.worker/online.ejiang.worker.loader.a.ActivityN1NRNTS5}: android.content.res.Resources$NotFoundException: Resource ID #0x7f09002c

### ISSUE THREAD

**Issue by w651441914** [Qihoo360/RePlugin#767]
#### 问题详细描述 Detailed description of the problem
自定义的网络请求框（请求中...）在一个moudle里面放的，宿主引入此moudle，插件也引入了，插件单个运行成功，打入宿主之后，启动崩溃

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.3.0

Android API Version：8.0
Android 手机型号&ROM(Phone model & ROM): 小米

#### Logcat上下文 Logcat context
java.lang.RuntimeException: Unable to start activity ComponentInfo{包名/包名.loader.a.ActivityN1NRNTS5}: android.content.res.Resources$NotFoundException: Resource ID #0x7f09002c
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f09002c
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:209)
        at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:94)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2159)
        at android.content.res.Resources.getLayout(Resources.java:1156)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:418)
        at android.app.Dialog.setContentView(Dialog.java:528)
        at online.ejiang.worker.common.utils.PgDialogUtils.init(PgDialogUtils.java:15)
        at online.ejiang.worker.common.base.mvp.BaseMvpActivity.onCreate(BaseMvpActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:7040)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:173) 
        at android.app.ActivityThread.main(ActivityThread.java:6698) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
2019-02-18 14:19:51.096 1923-1923/? E/ResourcesManager: failed to add asset path /data/app/online.ejiang.worker-AZ6VwhoMAfh0jJ4wg5jqGg==/base.apk

**Comment by w651441914** [comment]
在PgDialogUtils使用RePlugin.getHostContext()会报错
 java.lang.NoSuchMethodError: No static method getHostContext()Landroid/content/Context; in class Lcom/qihoo360/replugin/RePlugin; or its super classes (declaration of 'com.qihoo360.replugin.RePlugin' appears in /data/app/online.ejiang.worker-0sUZtXBksJ7CgB03wNPZag==/base.apk)

**Comment by w651441914** [comment]
求知道原因的前辈指导一下

**Comment by Yotakot** [comment]
一般插件中找不到资源都是因为context不对引起的。比如使用hostContext去加载libRes

**Comment by AlexLiuSheng** [comment]
可能是plugin的gradle插件并没有把继承的AppcompatActivity替换成PluginAppcompatActivity
