### ISSUE TITLE
运行sample崩溃,使用androidx

### ISSUE THREAD

**Issue by kenkieo** [Qihoo360/RePlugin#768]
#### 问题详细描述 Detailed description of the problem
运行sample崩溃,使用androidx

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

compileSdkVersion 28
    buildToolsVersion '28.0.3'
    defaultConfig {
        applicationId "com.qihoo360.replugin.sample.host"
        minSdkVersion 14
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile "com.qihoo360.replugin:replugin-host-lib:2.3.1"
    compile 'androidx.multidex:multidex:2.0.1'
    compile "androidx.constraintlayout:constraintlayout:1.1.3"
    compile "androidx.browser:browser:$androidxVersion"
    compile "androidx.core:core:$androidxVersion"
    compile "androidx.viewpager:viewpager:$androidxVersion"
    compile "androidx.appcompat:appcompat:$androidxVersion"
    compile "androidx.fragment:fragment:$androidxVersion"
}

replugin-host-lib/gradle Version: 2.3.1
rePlugin-plugin-lib/gradle Version: 2.3.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
02-20 15:06:04.600 31561-31561/com.qihoo360.replugin.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.qihoo360.replugin.sample.host, PID: 31561
                                                                                   java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
                                                                                       at com.qihoo360.loader2.PmBase.registerReceiverAction(PmBase.java:632)
                                                                                       at com.qihoo360.loader2.PmBase.callAppCreate(PmBase.java:622)
                                                                                       at com.qihoo360.loader2.PMF.callAppCreate(PMF.java:84)
                                                                                       at com.qihoo360.replugin.RePlugin$App.onCreate(RePlugin.java:1002)
                                                                                       at com.qihoo360.replugin.RePluginApplication.onCreate(RePluginApplication.java:74)
                                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
                                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5745)
                                                                                       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                                       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
                                                                                       at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                                                       at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6499)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.qihoo360.replugin.sample.host-xlbaeeGmiNkQr8YxZmJXNQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.qihoo360.replugin.sample.host-xlbaeeGmiNkQr8YxZmJXNQ==/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                       at com.qihoo360.loader2.PmBase.registerReceiverAction(PmBase.java:632) 
                                                                                       at com.qihoo360.loader2.PmBase.callAppCreate(PmBase.java:622) 
                                                                                       at com.qihoo360.loader2.PMF.callAppCreate(PMF.java:84) 
                                                                                       at com.qihoo360.replugin.RePlugin$App.onCreate(RePlugin.java:1002) 
                                                                                       at com.qihoo360.replugin.RePluginApplication.onCreate(RePluginApplication.java:74) 
                                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119) 
                                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5745) 
                                                                                       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                                       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361) 
                                                                                       at android.app.ActivityThread.handleBindApplication(<Xposed>) 
                                                                                       at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                       at android.os.Looper.loop(Looper.java:164) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6499) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
                                                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by bnotebook** [comment]
依赖库版本导致的问题吧？AndroidX升级后，Gradle也相应升级，会有些默认依赖项或库问题的改变。建议针对报错信息查找相关的类是否存在，确保引入相关的依赖来解决该类问题。

**Comment by androidforme** [comment]
那具体怎么解决这个问题呢？和上面报一样的错，搞了一天也不知道怎么解决

**Comment by sorosunrain** [comment]
框架没有兼容androidx 需在Hostapp引入 ：
implementation 'com.android.support:support-v4:29.0.1'
