### ISSUE TITLE
集成Replugin时，okhttp请求报错，错误如下

### ISSUE THREAD

**Issue by rookie001** [Qihoo360/RePlugin#770]
#### 问题详细描述 Detailed description of the problem
集成Replugin时，okhttp请求报错

#### 复现问题步骤 Steps to reproduce the problem
1.只要涉及到使用OkHttp这个框架进行请求就会crash

#### 其它重要信息 Other important information
java.lang.IncompatibleClassChangeError: Class 'okio.RealBufferedSink' does not implement interface 'okio.BufferedSink' in call to 'okio.BufferedSink okio.BufferedSink.write(byte[], int, int)' (declaration of 'okhttp3.RequestBody$2' appears in /data/data/com.A17zuoye.mobile.homework.debug/app_plugins_v3/liveroom-10-10-1.jar)
        at okhttp3.RequestBody$2.writeTo(RequestBody.java:98)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.3.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
小米6 vivo xplay3s huawei、锤子等

**Comment by rookie001** [comment]
OkHttp 版本是3.8.1

**Comment by bnotebook** [comment]
错误上看应该是okhttp的版本不一致，或者引入了2个okhttp库版本导致的。建议检查一下编译环境中是否存在多个版本的okhttp库。如果以上没有问题，可以看下插件使用的okhttp库和主工程的是否不一致。

**Comment by rookie001** [comment]
已解决
