### ISSUE TITLE
插件以module形式开发，host调起插件时报You need to use a Theme.AppCompat theme (or descendant) with the design library.

### ISSUE THREAD

**Issue by zhengguirong** [Qihoo360/RePlugin#782]
#### 问题详细描述 Detailed description of the problem
使用RePlugin开发全新的应用，**host和插件使用单工程开发**，host是工程的主app module，插件是子module（application类型），host和插件module均配置正确，编译也ok。

插件apk打包后修改后缀为jar并作为内置插件放于host app的/assets/plugins/文件夹下，运行时通过host调用插件时会报一个 “You need to use a Theme.AppCompat theme (or descendant) with the design library”的错误，复现几率100%。看了下历史的issue，参考了issue的解决方案还是会出现这个错误，特此求助。

>疑惑：当我把工程中的插件module抽离出去，新建单独的工程开发，打包apk改成jar再放在host的/assets/plugins/再使用相同方式调起时，又不会报这个“You need to use a Theme.AppCompat theme (or descendant) with the design library”的错误。是不是插件的开发不能作为module进行？非要使用独立的工程？项目中使用了dataBinding，这个对运行有影响吗？

#### 复现问题步骤 Steps to reproduce the problem
1.host和插件均使用到AppCompatActivity和Theme.appCompat系列的主题。
host的gradle配置中已开启useAppCompat 
```gradle
repluginHostConfig {
    /**
     * 是否使用 AppCompat 库
     * 不需要个性化配置时，无需添加
     */
    useAppCompat true
}
```
host的activity主题style定义
```xml
<style name="FlashActivityStyle" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="windowNoTitle">true</item>
        <item name="android:windowFullscreen">true</item>
</style>    
```
插件的activity主题style定义
```xml
<style name="MainActivityStyle" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="windowNoTitle">true</item>
        <item name="android:windowFullscreen">true</item>
</style>
```
插件module的manifest.xml配置中<application>标签不声明theme，只在<activity>标签中声明每个activity用到的theme，如上的定义
```xml
<application
        android:allowBackup="false"
        android:supportsRtl="true">

        <activity android:name=".MainActivity"
            android:theme="@style/MainActivityStyle">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
```

2.编译阶段均无问题，但是当通过host吊起插件apk的时候就报错了，调用代码如下
```java
 RePlugin.startActivity(FlashActivity.this, RePlugin.createIntent(
                        "com.xxx.main", "com.xxx.main.MainActivity"));
```

3.gradle配置确保了host和插件module使用的v7包版本是一致的

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.2.4
rePlugin-plugin-lib/gradle Version: 2.2.4

replugin-host-gradle:2.3.1
gradle tools 3.1.4
gralde 4.4

Android API Version：22
Android 手机型号&ROM(Phone model & ROM):  普通的Android平板

#### Logcat上下文 Logcat context

报错如下：
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.a5.host/com.xxx.a5.host.loader.a.ActivityN1NRNTS4}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:555)
        at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
        at com.xxx.gui.BaseActivity.initViewDataBinding(BaseActivity.java:205)
        at com.xxx.gui.BaseActivity.onCreate(BaseActivity.java:78)
        at android.app.Activity.performCreate(Activity.java:6222)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5280) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
```

**Comment by DengYuanting** [comment]
找到原因了吗？同遇到这个问题...也按FAQ说的配置了

**Comment by techinsight** [comment]
> 调用代码如下

请问是如何解决的？

**Comment by lugeek** [comment]
插件module的清单里，application没有设置theme？
