### ISSUE TITLE
低概率异常(Unable to instantiate fragment )

### ISSUE THREAD

**Issue by yyfBlog** [Qihoo360/RePlugin#800]
#### 问题详细描述 Detailed description of the problem
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.xxx.xxx.MainActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.xxx.xxx.AdverImgFragment: make sure class name exists, is public, and has an empty constructor that is public
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5280)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.xxx.xxx.AdverImgFragment: make sure class name exists, is public, and has an empty constructor that is public
	at android.support.v4.app.Fragment.instantiate(Fragment.java:450)
	at android.support.v4.app.FragmentContainer.instantiate(FragmentContainer.java:50)
	at android.support.v4.app.FragmentState.instantiate(FragmentState.java:80)
	at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3109)
	at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:158)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:344)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
	at com.gzytgk.vend.base_mvp.BaseMvpActivity.onCreate(BaseMvpActivity.java:15)
	at com.gzytgk.vend.base.BaseActivity.onCreate(BaseActivity.java:69)
	at android.app.Activity.performCreate(Activity.java:6222)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
	... 10 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xxx.xxx.AdverImgFragment" on path: DexPathList[[zip file "/data/app/com.xxx.xxx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-2/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:172)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:163)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.support.v4.app.Fragment.instantiate(Fragment.java:440)
	... 21 more
	Suppressed: java.lang.ClassNotFoundException: com.xxx.xxx.AdverImgFragment
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 24 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

#### 复现问题步骤 Steps to reproduce the problem
1. 因为是低概率异常所以无法提供必现步骤

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:  2.3.2
rePlugin-plugin-lib/gradle Version:  2.3.2

1.已经确保插件中有空的构造器,并且是public的
2.使用add()方式添加fragment的出现过上述异常
3.使用静态的引用fragment 也出现上述异常
4.代码并未使用混淆

**Comment by yyfBlog** [comment]
这个异常在app运行一段时间就会发生,急,请求帮助

**Comment by muxuelingyin** [comment]
我也遇到了类似问题，偶现的
