### ISSUE TITLE
插件layout资源无法加载：The tag for activity_main is invalid. Received: layout/activity_host_0

### ISSUE THREAD

**Issue by JasonKing0329** [Qihoo360/RePlugin#808]
#### 问题详细描述 Detailed description of the problem
activity_main在插件的layout目录下
宿主启动插件的MainActivity后报
Caused by: java.lang.IllegalArgumentException: The tag for activity_main is invalid. Received: layout/activity_host_0

#### 复现问题步骤 Steps to reproduce the problem
1. 插件的BaseActivity下mBinding = DataBindingUtil.setContentView(this, getLayoutRes());
派生类MainActivity下
@Override
    protected int getLayoutRes() {
        return R.layout.activity_main;
    }
2. 宿主唤起                
RePlugin.startActivity(HostActivity.this, RePlugin.createIntent(“PluginName”, "com.tcsl.caidan.module.main.MainActivity"));

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:3.1.4
rePlugin-plugin-lib/gradle Version:3.2.1

Android API Version：28
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
2019-04-22 09:44:40.725 7486-7486/com.tcsl.caidan.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tcsl.caidan.host, PID: 7486
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tcsl.caidan.host/com.tcsl.caidan.host.loader.a.ActivityN1NRNTS5}: java.lang.IllegalArgumentException: The tag for activity_main is invalid. Received: layout/activity_host_0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.IllegalArgumentException: The tag for activity_main is invalid. Received: layout/activity_host_0
        at com.tcsl.caidan.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:210)
        at android.databinding.MergedDataBinderMapper.getDataBinder(MergedDataBinderMapper.java:74)
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
        at android.databinding.DataBindingUtil.bindToAddedViews(DataBindingUtil.java:327)
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:306)
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
        at com.tcsl.caidan.base.BaseActivity.onCreate(BaseActivity.java:28)
        at android.app.Activity.performCreate(Activity.java:6720)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by JasonKing0329** [comment]
不好意思这里写错了，应该是
replugin-host-lib/gradle Version:2.3.0
rePlugin-plugin-lib/gradle Version:2.3.0

**Comment by JasonKing0329** [comment]
补充一下，提示的Received: layout/activity_host_0
这个activity_host是宿主的layout资源文件，这里为什么会提示收到这个layout文件呢？
