### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by yyfBlog** [Qihoo360/RePlugin#811]
#### 问题详细描述 Detailed description of the problem
/RePlugin.PluginInfoList: load: Load error!
    java.io.FileNotFoundException: File '/data/user/0/com.xxx.xxx/app_p_a/p.l' does not exist
        at com.qihoo360.replugin.utils.FileUtils.openInputStream(FileUtils.java:99)
        at com.qihoo360.replugin.utils.FileUtils.readFileToString(FileUtils.java:359)
        at com.qihoo360.replugin.model.PluginInfoList.load(PluginInfoList.java:71)
        at com.qihoo360.replugin.packages.PluginManagerServer.loadLocked(PluginManagerServer.java:100)
        at com.qihoo360.replugin.packages.PluginManagerServer.access$300(PluginManagerServer.java:58)
        at com.qihoo360.replugin.packages.PluginManagerServer$Stub.load(PluginManagerServer.java:623)
        at com.qihoo360.replugin.packages.PluginManagerProxy.load(PluginManagerProxy.java:91)
        at com.qihoo360.loader2.PmBase.initForServer(PmBase.java:321)
        at com.qihoo360.loader2.PmBase.init(PmBase.java:268)
        at com.qihoo360.loader2.PMF.init(PMF.java:72)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:985)
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:991)
        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
        at dalvik.system.NativeStart.main(Native Method)

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.2
rePlugin-plugin-lib/gradle Version: 2.3.2

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by hyongbai** [comment]
这个问题发生在初次运行未安装任何插件的情况下，不、无影响。

已修复，待发布。

**Comment by wenjiahui** [comment]
@hyongbai  你好，有计划什么时候发布吗？   没看到修复问题的代码提交。

**Comment by Martin0207** [comment]
2.3.3版本依然出现该问题，该如何处理呢

**Comment by lovemianhuatang** [comment]
我也出现了

**Comment by wJoven** [comment]
@hyongbai 2.3.3版本依然有这个问题，请问现在解决了吗

**Comment by chy116449859** [comment]
我今天也碰到了

**Comment by suasm** [comment]
2.3.4版本依然出现该问题，该如何处理呢

**Comment by runfengai** [comment]
> 2.3.4版本依然出现该问题，该如何处理呢

+1刚测试的。。。

**Comment by runfengai** [comment]
> 我今天也碰到了

on Mac, File->Invalidate Caches/restart

**Comment by 15130140362** [comment]
请问下这个问题有解决办法吗？我也遇到了
