### ISSUE TITLE
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.xx.xx.JavaBean

### ISSUE THREAD

**Issue by alienwings** [Qihoo360/RePlugin#812]
#### 问题详细描述 Detailed description of the problem
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.xx.xx.JavaBean
       at android.os.Parcel.readParcelableCreator(Parcel.java:2845)
       at android.os.Parcel.readParcelable(Parcel.java:2771)
       at android.os.Parcel.readValue(Parcel.java:2674)
       at android.os.Parcel.readListInternal(Parcel.java:3104)
       at android.os.Parcel.readArrayList(Parcel.java:2322)
       at android.os.Parcel.readValue(Parcel.java:2695)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3043)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
       at android.os.BaseBundle.unparcel(BaseBundle.java:232)
       at android.os.BaseBundle.getBoolean(BaseBundle.java:898)
       at android.app.Activity.restoreHasCurrentPermissionRequest(Activity.java:7763)
       at android.app.Activity.performCreate(Activity.java:7431)
       at android.app.Activity.performCreate(Activity.java:7426)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

#### 复现问题步骤 Steps to reproduce the problem
1. 偶现
2. 仅在Android 8.0或9.0出现

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
2.3.1
rePlugin-plugin-lib/gradle Version:
2.3.1

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
![image](https://user-images.githubusercontent.com/16728453/56637500-63fe8000-669e-11e9-824b-e8d986baa543.png)

**Comment by alienwings** [comment]
麻烦大佬看看哈

**Comment by hyongbai** [comment]
要打开的 Activity 所在的插件/应用中包含**com.xx.xx.JavaBean**对象吗？

如果不存在的话，parcel 在反序列化的时候发现这个 object 必然会通过其中的 class尝试进行 loadClass 的行为，此时就会出现当前这个 BUG。

RePlugin 在启动插件中的 Activity 的时候，已经将其 class 对应的 ClassLoader 设定为插件本身。

原则上此问题与 RePlugin 无逻辑上的关联。这个问题先关闭。
