### ISSUE TITLE
H5页面调用时间对话框崩溃

### ISSUE THREAD

**Issue by wavaya** [Qihoo360/RePlugin#820]
#### 问题详细描述 Detailed description of the problem
选择 时间对话框直接崩溃了。

#### 复现问题步骤 Steps to reproduce the problem
1.选择 时间对话框
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
 2019-05-20 16:34:14.398 23697-23697/com.hfjiguang.ppplatform.jiangxi E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=DatePicker, pluginName=****
2019-05-20 16:34:14.429 23697-23697/com.hfjiguang.ppplatform.jiangxi E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=ScrollView, pluginName=****
2019-05-20 16:34:14.438 23697-23697/com.hfjiguang.ppplatform.jiangxi I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-20 16:34:14.438 23697-23697/com.hfjiguang.ppplatform.jiangxi I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-20 16:34:14.438 23697-23697/com.hfjiguang.ppplatform.jiangxi D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-20 16:34:14.438 23697-23697/com.hfjiguang.ppplatform.jiangxi D/FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
2019-05-20 16:34:14.438 23697-23697/com.hfjiguang.ppplatform.jiangxi D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@7bc0a94,android.view.ContextThemeWrapper@8c1c93d
2019-05-20 16:34:14.439 23697-23697/com.hfjiguang.ppplatform.jiangxi D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
2019-05-20 16:34:14.441 23697-23697/com.hfjiguang.ppplatform.jiangxi I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-20 16:34:14.442 23697-23697/com.hfjiguang.ppplatform.jiangxi I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-20 16:34:14.442 23697-23697/com.hfjiguang.ppplatform.jiangxi D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-20 16:34:14.442 23697-23697/com.hfjiguang.ppplatform.jiangxi D/FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
2019-05-20 16:34:14.442 23697-23697/com.hfjiguang.ppplatform.jiangxi D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@b86bc39,android.view.ContextThemeWrapper@8c1c93d
2019-05-20 16:34:14.443 23697-23697/com.hfjiguang.ppplatform.jiangxi D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
2019-05-20 16:34:14.479 23697-23697/com.hfjiguang.ppplatform.jiangxi E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=ImageButton, pluginName=****
2019-05-20 16:34:14.607 23697-23697/com.hfjiguang.ppplatform.jiangxi E/latform.jiangx: No package ID 03 found for ID 0x030c0052.
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err: android.content.res.Resources$NotFoundException: String resource ID #0x30c0052
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at android.content.res.Resources.getText(Resources.java:430)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at android.content.Context.getText(Context.java:569)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at Iu.a(PG:52)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at Iu.a(PG:22)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at org.chromium.content.browser.input.DateTimeChooserAndroid.createDateTimeChooser(PG:12)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:386)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at android.os.Looper.loop(Looper.java:169)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7470)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
2019-05-20 16:34:14.608 23697-23697/com.hfjiguang.ppplatform.jiangxi W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
2019-05-20 16:34:14.611 23697-23697/com.hfjiguang.ppplatform.jiangxi A/chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
    
    
    --------- beginning of crash
2019-05-20 16:34:14.713 23697-23697/com.hfjiguang.ppplatform.jiangxi W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
2019-05-20 16:34:14.714 23697-23697/com.hfjiguang.ppplatform.jiangxi W/google-breakpad: Chrome build fingerprint:
2019-05-20 16:34:14.714 23697-23697/com.hfjiguang.ppplatform.jiangxi W/google-breakpad: 71.0.3578.99
2019-05-20 16:34:14.714 23697-23697/com.hfjiguang.ppplatform.jiangxi W/google-breakpad: 357809950
2019-05-20 16:34:14.714 23697-23697/com.hfjiguang.ppplatform.jiangxi W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
2019-05-20 16:34:14.714 23697-23697/com.hfjiguang.ppplatform.jiangxi A/libc: Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0xcbbc4d68 in tid 23697 (latform.***), pid 23697 (latform.***)

**Comment by zhaozzw** [comment]
老哥，这个要怎么解决呀
