### ISSUE TITLE
Error inflating mobilesafe class com.lianjia.common.android.lib_webview.ScrollWebView

### ISSUE THREAD

**Issue by android-ext** [Qihoo360/RePlugin#821]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by android-ext** [comment]
Fatal Exception: java.lang.RuntimeException:Unable to start activity ComponentInfo{com.homelink.im/com.homelink.im.loader.a.ActivityN1STNTS0}: android.view.InflateException: Binary XML file line #73: Binary XML file line #73: Error inflating mobilesafe class com.lianjia.common.android.lib_webview.ScrollWebView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:6701)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: android.view.InflateException:Binary XML file line #73: Binary XML file line #73: Error inflating mobilesafe class com.lianjia.common.android.lib_webview.ScrollWebView
Caused by: android.view.InflateException:Binary XML file line #73: Error inflating mobilesafe class com.lianjia.common.android.lib_webview.ScrollWebView
at com.ke.loader2.PluginContext.handleCreateView(PluginContext.java:421)
at com.ke.loader2.PluginContext.access$000(PluginContext.java:54)
at com.ke.loader2.PluginContext$1.onCreateView(PluginContext.java:80)
at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
at com.lianjia.common.android.lib_webview.BaseWebViewFragment.onCreateView(BaseWebViewFragment.java:63)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
at android.app.Activity.performStart(Activity.java:7067)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2819)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:6701)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: java.lang.reflect.InvocationTargetException:null
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
at com.ke.loader2.PluginContext.handleCreateView(PluginContext.java:414)
at com.ke.loader2.PluginContext.access$000(PluginContext.java:54)
at com.ke.loader2.PluginContext$1.onCreateView(PluginContext.java:80)
at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
at com.lianjia.common.android.lib_webview.BaseWebViewFragment.onCreateView(BaseWebViewFragment.java:63)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
at android.app.Activity.performStart(Activity.java:7067)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2819)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:6701)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: android.content.res.Resources$NotFoundException:failed to redirect ResourcesImpl
at android.app.ResourcesManager.redirectResourcesToNewImplLocked(ResourcesManager.java:1020)
at android.app.ResourcesManager.appendLibAssetForMainAssetPath(ResourcesManager.java:966)
at android.webkit.WebViewDelegate.addWebViewAssetPath(WebViewDelegate.java:206)
at com.android.webview.chromium.WebViewDelegateFactory$ProxyDelegate.addWebViewAssetPath(WebViewDelegateFactory.java:19)
at com.android.webview.chromium.WebViewChromium.<init>(WebViewChromium.java:15)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.createWebView(WebViewChromiumFactoryProvider.java:192)
at android.webkit.WebView.ensureProviderCreated(WebView.java:2468)
at android.webkit.WebView.setOverScrollMode(WebView.java:2533)
at android.view.View.<init>(View.java:4542)
at android.view.View.<init>(View.java:4676)
at android.view.ViewGroup.<init>(ViewGroup.java:597)
at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
at android.webkit.WebView.<init>(WebView.java:636)
at android.webkit.WebView.<init>(WebView.java:581)
at android.webkit.WebView.<init>(WebView.java:564)
at android.webkit.WebView.<init>(WebView.java:551)
at com.lianjia.common.android.lib_webview.ScrollWebView.<init>(ScrollWebView.java:41)
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
at com.ke.loader2.PluginContext.handleCreateView(PluginContext.java:414)
at com.ke.loader2.PluginContext.access$000(PluginContext.java:54)
at com.ke.loader2.PluginContext$1.onCreateView(PluginContext.java:80)
at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
at com.lianjia.common.android.lib_webview.BaseWebViewFragment.onCreateView(BaseWebViewFragment.java:63)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
at android.app.Activity.performStart(Activity.java:7067)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2819)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMes

**Comment by hyongbai** [comment]
检查一下ScrollWebView内部的逻辑。
