### ISSUE TITLE
 java.lang.IllegalArgumentException: Service not registered: 

### ISSUE THREAD

**Issue by lwugang** [Qihoo360/RePlugin#822]
2019-05-20 17:44:03.164 24423-24517/? E/PSDM: forgetServiceDispatcher(): Unbind Error!
    java.lang.IllegalArgumentException: Service not registered: com.mob.tools.utils.DeviceHelper$GSConnection@ae37603
        at com.qihoo360.replugin.component.service.PluginServiceDispatcherManager.forget(PluginServiceDispatcherManager.java:117)
        at com.qihoo360.replugin.component.service.PluginServiceClient.unbindService(PluginServiceClient.java:252)
        at com.qihoo360.loader2.PluginContext.unbindService(PluginContext.java:562)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
        at com.mob.tools.utils.DeviceHelper.getAdvertisingID(DeviceHelper.java:1594)
        at com.mob.commons.authorize.a.a(Authorizer.java:270)
        at com.mob.commons.authorize.a.a(Authorizer.java:40)
        at com.mob.commons.authorize.a$2.run(Authorizer.java:228)
2019-05-20 17:44:03.164 24423-24517/? E/ws001: psc.us: sd n
2019-05-20 17:44:04.863 24423-24544/? E/PSDM: forgetServiceDispatcher(): Unbind Error!
    java.lang.IllegalArgumentException: Service not registered: com.mob.tools.utils.DeviceHelper$GSConnection@bedba5
        at com.qihoo360.replugin.component.service.PluginServiceDispatcherManager.forget(PluginServiceDispatcherManager.java:117)
        at com.qihoo360.replugin.component.service.PluginServiceClient.unbindService(PluginServiceClient.java:252)
        at com.qihoo360.loader2.PluginContext.unbindService(PluginContext.java:562)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
        at com.mob.tools.utils.DeviceHelper.getAdvertisingID(DeviceHelper.java:1594)
        at com.mob.commons.authorize.a.a(Authorizer.java:270)
        at com.mob.commons.authorize.a.a(Authorizer.java:40)
        at com.mob.commons.authorize.a$2.run(Authorizer.java:228)
2019-05-20 17:44:04.863 24423-24544/? E/ws001: psc.us: sd n

**Comment by wardenlzr** [comment]
+1
java.lang.IllegalArgumentException: Service not registered: com.mob.tools.utils.DeviceHelper$GSConnection@7d4f81d
        at com.qihoo360.replugin.component.service.PluginServiceDispatcherManager.forget(PluginServiceDispatcherManager.java:117)
        at com.qihoo360.replugin.component.service.PluginServiceClient.unbindService(PluginServiceClient.java:252)
        at com.qihoo360.loader2.PluginContext.unbindService(PluginContext.java:562)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
        at com.mob.tools.utils.DeviceHelper.getAdvertisingID(DeviceHelper.java:1571)
        at com.mob.commons.authorize.a.a(Authorizer.java:266)
        at com.mob.commons.authorize.a.a(Authorizer.java:40)
        at com.mob.commons.authorize.a$2.run(Authorizer.java:227)

**Comment by drachuojin** [comment]
怎么解决

**Comment by drachuojin** [comment]
2020-07-20 22:40:57.258 1829-4522/com.albert.pluginhost E/PSDM: forgetServiceDispatcher(): Unbind Error!
    java.lang.IllegalArgumentException: Service not registered: com.umeng.commonsdk.statistics.common.a$b@a4040
        at com.qihoo360.replugin.component.service.PluginServiceDispatcherManager.forget(PluginServiceDispatcherManager.java:117)
        at com.qihoo360.replugin.component.service.PluginServiceClient.unbindService(PluginServiceClient.java:252)
        at com.qihoo360.loader2.PluginContext.unbindService(PluginContext.java:562)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
        at com.umeng.commonsdk.statistics.common.a.b(AdvertisingId.java:87)
        at com.umeng.commonsdk.statistics.common.a.a(AdvertisingId.java:50)
        at com.umeng.commonsdk.statistics.idtracking.c.f(IDFATracker.java:21)
        at com.umeng.commonsdk.statistics.idtracking.a.g(AbstractIdTracker.java:43)
        at com.umeng.commonsdk.statistics.idtracking.a.a(AbstractIdTracker.java:23)
        at com.umeng.commonsdk.statistics.idtracking.e.a(IdTracker.java:116)
        at com.umeng.commonsdk.stateless.UMSLEnvelopeBuild.buildSLEnvelope(UMSLEnvelopeBuild.java:382)
        at com.umeng.commonsdk.internal.d.c(UMInternalManager.java:114)
        at com.umeng.commonsdk.UMConfigureImpl$2.run(UMConfigureImpl.java:225)

**Comment by AAChartModel** [comment]
没有解决方案吗?

**Comment by wingkingbobo** [comment]
检查下bindService的返回值，如果是false，可能是Service没在AndroidManifest.xml中注册。
