### ISSUE TITLE
插件中so库 java.lang.UnsatisfiedLinkError 异常

### ISSUE THREAD

**Issue by e9ab98e991ab** [Qihoo360/RePlugin#824]
#### 问题详细描述 Detailed description of the problem
插件中有游戏so库 单独安装插件没有问题 在宿主中安装就会报错 启动单页面没有问题 

#### 复现问题步骤 Steps to reproduce the problem
安装后打开复现 查找相关没有看到解决方案 求解

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.2
rePlugin-plugin-lib/gradle Version:2.3.2

Android API Version：28
Android 手机型号&ROM(Phone model & ROM): mix2s开发版 MIUI9.5.17

#### Logcat上下文 Logcat context
java.lang.UnsatisfiedLinkError: No implementation found for void org.cocos2dx.lib.Cocos2dxHelper.nativeSetApkPath(java.lang.String) (tried Java_org_cocos2dx_lib_Cocos2dxHelper_nativeSetApkPath and Java_org_cocos2dx_lib_Cocos2dxHelper_nativeSetApkPath__Ljava_lang_String_2)
        at org.cocos2dx.lib.Cocos2dxHelper.nativeSetApkPath(Native Method)
        at org.cocos2dx.lib.Cocos2dxHelper.init(Cocos2dxHelper.java:104)
        at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:268)
        at org.cocos2dx.javascript.AppActivity.onCreate(AppActivity.java:47)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6809)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by bnotebook** [comment]
报错原因应该是so没找到，可以看下so路径是否正确了。可以查看下so是否释放正确了。
