### ISSUE TITLE
运行你的sample  点击“启动DEMO1插件”时出现下面的错误  help  tks!

### ISSUE THREAD

**Issue by lovezt** [Qihoo360/RePlugin#83]
Didn't find class "com.qihoo360.plugin.demo1.Entry" on path: DexPathList[[zip file "/data/user/0/qihoo.com.testreplugin/app_plugins_v3/demo1-10-10-100.jar"],nativeLibraryDirectories=[/data/user/0/qihoo.com.testreplugin/app_plugins_v3_libs/demo1-10-10-100, /vendor/lib, /system/lib]]
                                                             java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.plugin.demo1.Entry" on path: DexPathList[[zip file "/data/user/0/qihoo.com.testreplugin/app_plugins_v3/demo1-10-10-100.jar"],nativeLibraryDirectories=[/data/user/0/qihoo.com.testreplugin/app_plugins_v3_libs/demo1-10-10-100, /vendor/lib, /system/lib]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                 at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:76)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                 at com.qihoo360.loader2.Loader.loadEntryMethod2(Loader.java:419)
                                                                 at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:857)
                                                                 at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:822)
                                                                 at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:621)
                                                                 at com.qihoo360.loader2.Plugin.load(Plugin.java:432)
                                                                 at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1033)
                                                                 at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1018)
                                                                 at com.qihoo360.loader2.PmLocalImpl.getActivityInfo(PmLocalImpl.java:443)
                                                                 at com.qihoo360.loader2.PmLocalImpl.loadPluginActivity(PmLocalImpl.java:319)
                                                                 at com.qihoo360.loader2.PmInternalImpl.startActivity(PmInternalImpl.java:230)
                                                                 at com.qihoo360.loader2.PmLocalImpl.startActivity(PmLocalImpl.java:307)
                                                                 at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:324)
                                                                 at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:236)
                                                                 at qihoo.com.testreplugin.MainActivity$1.onClick(MainActivity.java:38)
                                                                 at android.view.View.performClick(View.java:5198)
                                                                 at android.view.View$PerformClick.run(View.java:21147)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                             	Suppressed: java.lang.ClassNotFoundException: com.qihoo360.plugin.demo1.Entry
                                                                 at java.lang.Class.classForName(Native Method)
                                                                 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                 		... 25 more
                                                              Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by kezong** [comment]
该日志不会影响插件的启动，插件应该是能正常启动的。
我们之后会优化这段异常输出。

**Comment by jiongxuan** [comment]
是的，如 @kezong 兄所述。我们下一版（2.1.1）会禁用掉此日志，以免对开发者造成打扰。

敬请期待。感谢您的建议。

**Comment by lovezt** [comment]
现在的问题是插件启动不了  崩溃了  上面的就是崩溃日志

**Comment by jiongxuan** [comment]
@lovezt 这个确实只是个Warning，loadEntry2只是之前“卫士插件”的一种Entry方法，已在新版本上不再使用，所以才会有这个Warning。

您要不找下，一般在Fatal Exception下面的才是真正崩溃的原因。

**Comment by wangyupeng1-iri** [comment]
请down最新版本的代码库试试
