### ISSUE TITLE
sample中host工程的插件demo1运行不起来

### ISSUE THREAD

**Issue by chinaShawn** [Qihoo360/RePlugin#830]
直接下载的github的代码，运行host工程，启动demo1的时候，出现崩溃

#### 复现问题步骤 Steps to reproduce the problem
1. 运行host代码，
2. 点击启动插件demo1.

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: "com.qihoo360.replugin:replugin-host-lib:${RP_VERSION}"
rePlugin-plugin-lib/gradle Version:"com.qihoo360.replugin:replugin-plugin-lib:${RP_VERSION}"

Android API Version：
任何手机都是

直接运行原有代码不更改任何东西。以下是崩溃信息

Process: com.qihoo360.replugin.sample.host, PID: 5583
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}: android.content.res.Resources$NotFoundException: File res/layout/content_lib_main.xml from drawable resource ID #0x7f030000
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
     Caused by: android.content.res.Resources$NotFoundException: File res/layout/content_lib_main.xml from drawable resource ID #0x7f030000
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2654)
        at android.content.res.Resources.loadDrawable(Resources.java:2538)
        at android.content.res.Resources.getDrawable(Resources.java:830)
        at android.content.Context.getDrawable(Context.java:403)
        at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:321)
        at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:745)
        at com.android.internal.policy.impl.PhoneWindow.setDefaultIcon(PhoneWindow.java:1675)
        at android.app.Activity.initWindowDecorActionBar(Activity.java:2163)
        at android.app.Activity.setContentView(Activity.java:2178)
        at com.qihoo360.replugin.sample.demo1.MainActivity.onCreate(MainActivity.java:77)
        at android.app.Activity.performCreate(Activity.java:6093)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:5541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag LinearLayout
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1124)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1032)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2637)
        at android.content.res.Resources.loadDrawable(Resources.java:2538) 
        at android.content.res.Resources.getDrawable(Resources.java:830) 
        at android.content.Context.getDrawable(Context.java:403) 
        at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:321) 
        at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:745) 
        at com.android.internal.policy.impl.PhoneWindow.setDefaultIcon(PhoneWindow.java:1675) 
        at android.app.Activity.initWindowDecorActionBar(Activity.java:2163) 
        at android.app.Activity.setContentView(Activity.java:2178) 
        at com.qihoo360.replugin.sample.demo1.MainActivity.onCreate(MainActivity.java:77) 
        at android.app.Activity.performCreate(Activity.java:6093) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:5541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by chinaShawn** [comment]
setContentView引发的这个问题，并且我自己按照文档接入的插件到宿主中，也是报同样的Resources$NotFoundException，有没有大神知道原因和解决办法？

**Comment by LiuchengGit** [comment]
问题解决没

**Comment by chinaShawn** [comment]
发现host和plugin中引用的support等包，会有影响

**Comment by qhs1573** [comment]
坑太多官方提供的例子程序跑不起来...
