### ISSUE TITLE
AppCompatActivity setContentView crash

### ISSUE THREAD

**Issue by chenyunecjtu** [Qihoo360/RePlugin#838]
#### 复现问题步骤 Steps to reproduce the problem
1. 插件activity 直接继承 AppCompatActivity
 在 oncreate 里调用setContentView(R.layout.activity_main);
2.  host 直接调用插件的activity

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.2
rePlugin-plugin-lib/gradle Version: 2.3.2

Android API Version：28
Android 手机型号&ROM(Phone model & ROM): 
oppo a83 
#### Logcat上下文 Logcat context

2019-06-25 10:04:15.137 14070-14070/com.tinker.hotdemo E/CrashReport: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tinker.hotdemo/com.tinker.hotdemo.loader.a.ActivityN1NRNTS0}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v7.widget.DecorContentParent.setWindowCallback(android.view.Window$Callback)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2973)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3097)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6910)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v7.widget.DecorContentParent.setWindowCallback(android.view.Window$Callback)' on a null object reference
        at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:611)
        at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.plugin.MainActivity.onCreateContent(MainActivity.java:58)
        at com.app.activity.CoreActivity.onCreate(CoreActivity.java:152)
        at android.app.Activity.performCreate(Activity.java:6987)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

**Comment by tangnuo** [comment]
同问，求答案
