### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by zlrambo** [Qihoo360/RePlugin#857]
#### 问题详细描述 Detailed description of the problem
在宿主app中获取插件中的Fragment报ClassNotFoundException

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information
 ClassLoader d1ClassLoader = RePlugin.fetchClassLoader("settings");
 Log.e("TAG","d1ClassLoader:" + d1ClassLoader.toString());
获取的是插件中的ClassLoader，打印如下：
TAG: d1ClassLoader:com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.umeox.watch.hostapp/app_plugins_v3/settings-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.umeox.watch.hostapp/app_plugins_v3_libs/settings-10-10-1, /system/lib, /vendor/lib]]]
replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version:2.3.3

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
2019-08-01 13:45:21.723 29684-29684/com.umeox.watch.hostapp W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.umeox.watch.settings.fragment.SettingFragment" on path: DexPathList[[zip file "/data/user/0/com.umeox.watch.hostapp/app_plugins_v3/settings-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.umeox.watch.hostapp/app_plugins_v3_libs/settings-10-10-1, /system/lib, /vendor/lib]]
2019-08-01 13:45:21.725 29684-29689/com.umeox.watch.hostapp I/zygote: Do partial code cache collection, code=30KB, data=26KB
2019-08-01 13:45:21.726 29684-29684/com.umeox.watch.hostapp W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
2019-08-01 13:45:21.727 29684-29689/com.umeox.watch.hostapp I/zygote: After code cache collection, code=30KB, data=26KB
2019-08-01 13:45:21.727 29684-29689/com.umeox.watch.hostapp I/zygote: Increasing code cache capacity to 128KB
2019-08-01 13:45:21.728 29684-29684/com.umeox.watch.hostapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2019-08-01 13:45:21.729 29684-29684/com.umeox.watch.hostapp W/System.err:     at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:100)
2019-08-01 13:45:21.730 29684-29684/com.umeox.watch.hostapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2019-08-01 13:45:21.730 29684-29684/com.umeox.watch.hostapp W/System.err:     at com.umeox.watch.hostapp.PluginFragmentActivity.onCreate(PluginFragmentActivity.java:30)
2019-08-01 13:45:21.731 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.app.Activity.performCreate(Activity.java:7023)
2019-08-01 13:45:21.731 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.app.Activity.performCreate(Activity.java:7014)
2019-08-01 13:45:21.731 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
2019-08-01 13:45:21.732 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2758)
2019-08-01 13:45:21.733 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2883)
2019-08-01 13:45:21.733 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
2019-08-01 13:45:21.734 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
2019-08-01 13:45:21.734 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-08-01 13:45:21.735 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-08-01 13:45:21.735 29684-29684/com.umeox.watch.hostapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6523)
2019-08-01 13:45:21.736 29684-29684/com.umeox.watch.hostapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-08-01 13:45:21.737 29684-29684/com.umeox.watch.hostapp W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2019-08-01 13:45:21.737 29684-29684/com.umeox.watch.hostapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
2019-08-01 13:45:21.739 29684-29684/com.umeox.watch.hostapp W/System.err: 	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/Fragment;
2019-08-01 13:45:21.740 29684-29684/com.umeox.watch.hostapp W/System.err:     at dalvik.system.DexFile.defineClassNative(Native Method)
2019-08-01 13:45:21.740 29684-29684/com.umeox.watch.hostapp W/System.err:     at dalvik.system.DexFile.defineClass(DexFile.java:282)
2019-08-01 13:45:21.741 29684-29684/com.umeox.watch.hostapp W/System.err:     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275)
2019-08-01 13:45:21.741 29684-29684/com.umeox.watch.hostapp W/System.err:     at dalvik.system.DexPathList$Element.findClass(DexPathList.java:677)
2019-08-01 13:45:21.742 29684-29684/com.umeox.watch.hostapp W/System.err:     at dalvik.system.DexPathList.findClass(DexPathList.java:466)
2019-08-01 13:45:21.742 29684-29684/com.umeox.watch.hostapp W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:123)
2019-08-01 13:45:21.743 29684-29684/com.umeox.watch.hostapp W/System.err: 		... 17 more
2019-08-01 13:45:21.744 29684-29684/com.umeox.watch.hostapp W/System.err: 	Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.Fragment" on path: DexPathList[[zip file "/data/user/0/com.umeox.watch.hostapp/app_plugins_v3/settings-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.umeox.watch.hostapp/app_plugins_v3_libs/settings-10-10-1, /system/lib, /vendor/lib]]
2019-08-01 13:45:21.745 29684-29684/com.umeox.watch.hostapp W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
2019-08-01 13:45:21.745 29684-29684/com.umeox.watch.hostapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2019-08-01 13:45:21.745 29684-29684/com.umeox.watch.hostapp W/System.err:     at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:100)
2019-08-01 13:45:21.746 29684-29684/com.umeox.watch.hostapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2019-08-01 13:45:21.746 29684-29684/com.umeox.watch.hostapp W/System.err: 		... 23 more
2019-08-01 13:45:21.747 29684-29684/com.umeox.watch.hostapp E/TAG: msg:Didn't find class "com.umeox.watch.settings.fragment.SettingFragment" on path: DexPathList[[zip file "/data/user/0/com.umeox.watch.hostapp/app_plugins_v3/settings-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.umeox.watch.hostapp/app_plugins_v3_libs/settings-10-10-1, /system/lib, /vendor/lib]]

**Comment by techinsight** [comment]
插件名使用applicationId尝试下，在build.gradle中配置的pluginName 没有用
