### ISSUE TITLE
在AndroidThings中使用RePlugin问题：RuntimeException: Stub!

### ISSUE THREAD

**Issue by FeatherSeven** [Qihoo360/RePlugin#861]
####问题详细描述 Detailed description of the problem

 在AndroidThings开发（硬件为树莓派3）中使用Replugin，从宿主调用插件运行至PeripheralManager.getInstance()时报错

#### 复现问题步骤 Steps to reproduce the problem
1. 宿主及插件单独测试时，调用PeripheralManager.getInstance()等一系列AndroidThings库中函数皆运行正常
2. 将插件打包为apk，重命名为.jar放入宿主Assets/plugins，RePlugin.startActivity调用插件，运行至PeripheralManager.getInstance()报错

#### 其它重要信息 Other important information

猜测问题与Manifest中<uses-library android:name="com.google.android.things" />配置相关，宿主或插件单独测试时若去掉此配置，会产生和本问题相同报错。

replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version:2.3.3
Android API Version：Android 8.1.0 API27
Android 手机型号&ROM(Phone model & ROM): Google lot_rpi3树莓派3

#### Logcat上下文 Logcat context
2009-01-01 08:38:59.010 297-363/system_process E/InputDispatcher: channel '676e592 com.wutu.buffet/com.wutu.buffet.HostMainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2009-01-01 08:38:59.568 21508-21508/com.wutu.buffet E/buffet: host onCreate
2009-01-01 08:38:59.716 21508-21508/com.wutu.buffet E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.plugin.buffet_plugin1.Entry, pluginName=buffet_plugin1
2009-01-01 08:38:59.717 21508-21508/com.wutu.buffet E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.plugin.buffet_plugin1.Entry, pluginName=buffet_plugin1
2009-01-01 08:38:59.901 21508-21508/com.wutu.buffet E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=LinearLayout, pluginName=buffet_plugin1
2009-01-01 08:38:59.904 21508-21508/com.wutu.buffet E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=ViewStub, pluginName=buffet_plugin1
2009-01-01 08:38:59.906 21508-21508/com.wutu.buffet E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=android.widget.ViewStub, pluginName=buffet_plugin1
2009-01-01 08:38:59.907 21508-21508/com.wutu.buffet E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=android.webkit.ViewStub, pluginName=buffet_plugin1
2009-01-01 08:38:59.909 21508-21508/com.wutu.buffet E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=android.app.ViewStub, pluginName=buffet_plugin1
2009-01-01 08:38:59.912 21508-21508/com.wutu.buffet E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=FrameLayout, pluginName=buffet_plugin1
2009-01-01 08:38:59.947 21508-21508/com.wutu.buffet E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=TextView, pluginName=buffet_plugin1
2009-01-01 08:38:59.967 21508-21508/com.wutu.buffet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wutu.buffet, PID: 21508
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wutu.buffet/com.wutu.buffet.loader.a.ActivityN1NRNTS3}: java.lang.RuntimeException: Stub!
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: Stub!
        at com.google.android.things.pio.PeripheralManager.getInstance(PeripheralManager.java:21)
        at com.wutu.buffet_plugin1.MainActivity.testUart(MainActivity.java:65)
        at com.wutu.buffet_plugin1.MainActivity.onCreate(MainActivity.java:60)
        at android.app.Activity.performCreate(Activity.java:7010)
        at android.app.Activity.performCreate(Activity.java:7001)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by keyescgm** [comment]
解决了吗
