### ISSUE TITLE
可否利用RePlugin实现多态特性

### ISSUE THREAD

**Issue by liangxin1988** [Qihoo360/RePlugin#862]
#### 问题详细描述 Detailed description of the problem
希望不同插件中封装同一个类的不同子类，宿主项目通过基类引用插件中的类，以实现基类行为由插件实现的目的。目前会抛出类型转换异常，不知道该需求可否实现及怎样实现。

#### 复现问题步骤 Steps to reproduce the problem
1. Project中定义三个Module：app,plugin,base。其中app为宿主项目，plugin为插件项目，base为依赖库，分别被app和plugin依赖。

2. base中定义BaseClass：
```java
package ink.liangxin.base;
public class BaseClass {
    public void print(){
        System.out.println("I am BaseClass");
    }
}
```

3. plugin中定义PluginBaseClass类，并继承BaseClass:
```java
package ink.liangxin.plugin;
import ink.liangxin.base.BaseClass;
public class PluginBaseClass extends BaseClass {
    @Override
    public void print() {
        System.out.println("I am PluginBaseClass");
    }
}
```

4. 宿主项目app中安装plugin插件，通过反射获取PluginBaseClass，并使用BaseClass类型的引用持有这个对象：
```java
        PluginInfo plugin = RePlugin.install("/sdcard/plugin-debug.apk");
        ClassLoader pluginClassLoader = RePlugin.fetchClassLoader(plugin.getName());
        try {
            BaseClass baseClass = pluginClassLoader.loadClass("ink.liangxin.plugin.PluginBaseClass")
                    .asSubclass(BaseClass.class).newInstance();
            baseClass.print();
        } catch (Exception e) {
            e.printStackTrace();
        } 
```
5. 执行宿主项目后，在执行`asSubclass`会抛出如下异常：
```
     Caused by: java.lang.ClassCastException: ink.liangxin.plugin.PluginBaseClass cannot be cast to ink.liangxin.base.BaseClass
        at java.lang.Class.asSubclass(Class.java:1486)
        at ink.liangxin.replugintest.MainActivity.onCreate(MainActivity.java:24)
        at android.app.Activity.performCreate(Activity.java:6309)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5737) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:732) 
```

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.3  Gradle:3.4.0
rePlugin-plugin-lib/gradle Version:2.3.3  Gradle:3.4.0

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by weikano** [comment]
plugin的base依赖用provide的方式


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
