### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList

### ISSUE THREAD

**Issue by raylee2012** [Qihoo360/RePlugin#866]
#### 问题详细描述 Detailed description of the problem
内部插件在数组中加载，点击跳转插件没有任何反应，日志如下：
 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.3
rePlugin-plugin-lib/gradle Version:2.3.3

Android API Version：5.1.1
Android 手机型号&ROM(Phone model & ROM): 华为SCL-TL00H

#### Logcat上下文 Logcat context
08-26 17:13:50.347 16932-16932/com.fhzz.mobilepolice E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.plugin.qwstatistic.Entry, pluginName=qwstatistic
08-26 17:13:50.347 16932-16932/com.fhzz.mobilepolice E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.plugin.qwstatistic.Entry, pluginName=qwstatistic
08-26 17:13:50.347 16932-16932/com.fhzz.mobilepolice E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.replugin.Entry, pluginName=qwstatistic
08-26 17:13:50.347 16932-16932/com.fhzz.mobilepolice E/ws001: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/data/com.fhzz.mobilepolice/app_plugins_v3/qwstatistic-10-10-1.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/data/com.fhzz.mobilepolice/app_plugins_v3/qwstatistic-10-10-1.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:100)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:476)
        at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:888)
        at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:845)
        at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:623)
        at com.qihoo360.loader2.Plugin.load(Plugin.java:434)
        at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1102)
        at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1087)
        at com.qihoo360.loader2.PluginCommImpl.getActivityInfo(PluginCommImpl.java:561)
        at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:411)
        at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:268)
        at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
        at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
        at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:248)
        at com.fhzz.mobilepolice.main.adapter.ModuleAdapter$1$1.onClick(ModuleAdapter.java:86)
        at android.view.View.performClick(View.java:4793)
        at android.view.View$PerformClick.run(View.java:19960)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5593)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 26 more
    		Suppressed: java.lang.ClassNotFoundException: com.qihoo360.replugin.Entry
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        			... 27 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
08-26 17:13:50.347 16932-16932/com.fhzz.mobilepolice E/ws001: p.lel f qwstatistic
08-26 17:13:50.347 16932-16932/com.fhzz.mobilepolice E/ws001: try1: loading fail1
08-26 17:13:50.347 16932-16932/com.fhzz.mobilepolice E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.plugin.qwstatistic.Entry, pluginName=qwstatistic
08-26 17:13:50.347 16932-16932/com.fhzz.mobilepolice E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.plugin.qwstatistic.Entry, pluginName=qwstatistic
08-26 17:13:50.347 16932-16932/com.fhzz.mobilepolice E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.replugin.Entry, pluginName=qwstatistic
08-26 17:13:50.357 16932-16932/com.fhzz.mobilepolice E/ws001: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/data/com.fhzz.mobilepolice/app_plugins_v3/qwstatistic-10-10-1.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[zip file "/data/data/com.fhzz.mobilepolice/app_plugins_v3/qwstatistic-10-10-1.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at com.qihoo360.replugin.PluginDexClassLoader.loadClass(PluginDexClassLoader.java:100)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.qihoo360.loader2.Loader.loadEntryMethod3(Loader.java:476)
        at com.qihoo360.loader2.Plugin.loadEntryLocked(Plugin.java:888)
        at com.qihoo360.loader2.Plugin.doLoad(Plugin.java:845)
        at com.qihoo360.loader2.Plugin.tryLoadAgain(Plugin.java:745)
        at com.qihoo360.loader2.Plugin.loadLocked(Plugin.java:691)
        at com.qihoo360.loader2.Plugin.load(Plugin.java:434)
        at com.qihoo360.loader2.PmBase.loadPlugin(PmBase.java:1102)
        at com.qihoo360.loader2.PmBase.loadAppPlugin(PmBase.java:1087)
        at com.qihoo360.loader2.PluginCommImpl.getActivityInfo(PluginCommImpl.java:561)
        at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:411)
        at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:268)
        at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
        at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
        at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:248)
        at com.fhzz.mobilepolice.main.adapter.ModuleAdapter$1$1.onClick(ModuleAdapter.java:86)
        at android.view.View.performClick(View.java:4793)
        at android.view.View$PerformClick.run(View.java:19960)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5593)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.replugin.Entry" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 27 more
    		Suppressed: java.lang.ClassNotFoundException: com.qihoo360.replugin.Entry
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        			... 28 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
08-26 17:13:50.357 16932-16932/com.fhzz.mobilepolice E/ws001: p.lel f qwstatistic
08-26 17:13:50.357 16932-16932/com.fhzz.mobilepolice E/ws001: try2: loading fail2
08-26 17:13:50.357 16932-16932/com.fhzz.mobilepolice E/ws001: pmb.lp: f to l. lt=3; i=PInfo { <qwstatistic:1(4)> [P-N] [RUNNING] processes=[com.fhzz.mobilepolice] js={ver=1, verv=2814792716779521, type=1, path=/data/data/com.fhzz.mobilepolice/app_plugins_v3/qwstatistic-10-10-1.jar, high=10, frm_ver=4, low=10, pkgname=com.fhzz.mobilepolice, name=qwstatistic, ali=qwstatistic} dex=/data/data/com.fhzz.mobilepolice/app_plugins_v3_odex/qwstatistic-10-10-1.dex nlib=/data/data/com.fhzz.mobilepolice/app_plugins_v3_libs/qwstatistic-10-10-1 }

**Comment by keyescgm** [comment]
你的问题解决了吗？

**Comment by raylee2012** [comment]
> 你的问题解决了吗？

我把gradle4.6改回到3.3就好了，你试试

**Comment by keyescgm** [comment]
但是这个不是必现的啊，你看这具体的crash信息
 





------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年10月21日(星期一) 中午1:58
收件人: "Qihoo360/RePlugin"<RePlugin@noreply.github.com>;
抄送: "第一号伤心人"<1175426782@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Qihoo360/RePlugin] java.lang.ClassNotFoundException: Didn't findclass "com.qihoo360.replugin.Entry" on path: DexPathList (#866)



 
你的问题解决了吗？
  
我把gradle4.6改回到3.3就好了，你试试

**Comment by keyescgm** [comment]
我的问题不是必现，但是crash比较高












------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年10月21日(星期一) 中午1:58
收件人: "Qihoo360/RePlugin"<RePlugin@noreply.github.com>;
抄送: "第一号伤心人"<1175426782@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Qihoo360/RePlugin] java.lang.ClassNotFoundException: Didn't findclass "com.qihoo360.replugin.Entry" on path: DexPathList (#866)



 
你的问题解决了吗？
  
我把gradle4.6改回到3.3就好了，你试试

**Comment by raylee2012** [comment]
.



> 我的问题不是必现，但是crash比较高
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "notifications"<notifications@github.com>; 发送时间: 2019年10月21日(星期一) 中午1:58 收件人: "Qihoo360/RePlugin"<RePlugin@noreply.github.com>; 抄送: "第一号伤心人"<1175426782@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Qihoo360/RePlugin] java.lang.ClassNotFoundException: Didn't findclass "com.qihoo360.replugin.Entry" on path: DexPathList (#866) 你的问题解决了吗？ 我把gradle4.6改回到3.3就好了，你试试 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我改完以后暂时还没出现类似的crash

**Comment by keyescgm** [comment]
你之前也是偶现吗？

**Comment by keyescgm** [comment]
而且我的Gradle是4.4版本的

**Comment by raylee2012** [comment]
.



> 我的问题不是必现，但是crash比较高
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "notifications"<notifications@github.com>; 发送时间: 2019年10月21日(星期一) 中午1:58 收件人: "Qihoo360/RePlugin"<RePlugin@noreply.github.com>; 抄送: "第一号伤心人"<1175426782@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Qihoo360/RePlugin] java.lang.ClassNotFoundException: Didn't findclass "com.qihoo360.replugin.Entry" on path: DexPathList (#866) 你的问题解决了吗？ 我把gradle4.6改回到3.3就好了，你试试 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我改完以后暂时还没出现类似的crash

> 而且我的Gradle是4.4版本的

把gradle版本换一下试试

**Comment by keyescgm** [comment]
你说是插件里面的还是宿主的里面的？
