### ISSUE TITLE
使用autolayout在获取屏幕宽高的时候，打印出来为0，想请教下各位大神，是什么问题引起的

### ISSUE THREAD

**Issue by danny2012** [Qihoo360/RePlugin#870]
Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS0}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class LinearLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class LinearLayout
     Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class LinearLayout
     Caused by: java.lang.NumberFormatException: Infinity or NaN: NaN
        at java.math.BigDecimal.<init>(BigDecimal.java:465)
        at com.zhy.autolayout.config.AutoLayoutConifg.reSetScreen(AutoLayoutConifg.java:85)
        at com.zhy.autolayout.config.AutoLayoutConifg.init(AutoLayoutConifg.java:77)
        at com.zhy.autolayout.utils.AutoLayoutHelper.initAutoLayoutConfig(AutoLayoutHelper.java:107)
        at com.zhy.autolayout.utils.AutoLayoutHelper.<init>(AutoLayoutHelper.java:100)
        at com.zhy.autolayout.AutoLinearLayout.<init>(AutoLinearLayout.java:18)
        at com.zhy.autolayout.AutoLayoutActivity.onCreateView(AutoLayoutActivity.java:30)
        at com.worker.apptestplugin.TestAcy.onCreateView(TestAcy.java:41)
        at android.app.Activity.onCreateView(Activity.java:6184)
        at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:41)
        at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1901)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2579)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2652)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2066)
        at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.worker.apptestplugin.TestAcy.onCreate(TestAcy.java:20)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)

**Comment by danny2012** [comment]
目测找到问题，是打包没有把对应的class文件给打包进去，正在找方法

**Comment by danny2012** [comment]
是meta-data获取值的问题，想问问插件中获取插件里面的meta-data为何会失败呢

**Comment by danny2012** [comment]
String path = RePlugin.getPluginInfo(插件名）.getPath;
PackageInfo info = packageManager.getPackageArchiveInfo(path,PackageManager.GET_META_DATA);
使用了这个方法拿到的info.applicationInfo的meta-data还是空的，想请教有人知道么

**Comment by danny2012** [comment]
莫非要代码写死我的配置值才行？有大神解答下么

**Comment by danny2012** [comment]
是配置问题，配置meta-data需要写在主程里面，包括类似于权限等配置，同理

**Comment by yangxipeng321** [comment]
我在插件的AndroidManifest中配置了com.qihoo360.plugin.name与com.qihoo360.plugin.version.ver的meta-data后也是报了类似的错误，怎么解决呢？
