### ISSUE TITLE
java.lang.VerifyError: android.support.v4.view.PagerAdapter

### ISSUE THREAD

**Issue by techinsight** [Qihoo360/RePlugin#888]
#### 问题详细描述 Detailed description of the problem
改造原有APP实现，在Fragment内使用ViewPager.setAdapter(PagerAdapter)，传入FragmentPagerAdapter子类，在运行时抛出异常。

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version:2.3.3

Android API Version：25
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
10-08 17:33:00.066 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-Server: openresty/1.13.6.2
10-08 17:33:00.066 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-Date: Tue, 08 Oct 2019 09:32:58 GMT
10-08 17:33:00.066 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-Content-Type: application/json;charset=UTF-8
10-08 17:33:00.066 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-Transfer-Encoding: chunked
10-08 17:33:00.066 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-Connection: keep-alive
10-08 17:33:00.066 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-Access-Control-Allow-Origin: *
10-08 17:33:00.066 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-Access-Control-Allow-Methods: PUT,GET,POST,OPTIONS
10-08 17:33:00.066 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-Accept-Ranges: bytes
10-08 17:33:00.114 14334 14334 W System.err: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
10-08 17:33:00.114 14334 14334 W System.err: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
10-08 17:33:00.115 14334 14334 W System.err: 	at android.os.Handler.handleCallback(Handler.java:758)
10-08 17:33:00.115 14334 14334 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-08 17:33:00.115 14334 14334 W System.err: 	at android.os.Looper.loop(Looper.java:154)
10-08 17:33:00.115 14334 14334 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6144)
10-08 17:33:00.115 14334 14334 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-08 17:33:00.115 14334 14334 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-08 17:33:00.115 14334 14334 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-08 17:33:00.115 14334 14334 W System.err: Caused by: java.lang.VerifyError: Verifier rejected class com.androidteam.policeportalapp.adapter.recycleradapter.MultiListNewAdapter: void com.androidteam.policeportalapp.adapter.recycleradapter.MultiListNewAdapter._handleDailyComVPChart(com.androidteam.policeportalapp.adapter.recyclerhelper.BaseViewHolder, java.util.ArrayList) failed to verify: void com.androidteam.policeportalapp.adapter.recycleradapter.MultiListNewAdapter._handleDailyComVPChart(com.androidteam.policeportalapp.adapter.recyclerhelper.BaseViewHolder, java.util.ArrayList): [0x1AD] register v0 has type Precise Reference: com.androidteam.policeportalapp.ui.Fragments.Chart.TabFragmentPagerAdapter but expected Reference: android.support.v4.view.PagerAdapter (declaration of 'com.androidteam.policeportalapp.adapter.recycleradapter.MultiListNewAdapter' appears in /data/user/0/com.mobilepolice/app_p_a/-1607123362.jar:classes2.dex)
10-08 17:33:00.115 14334 14334 W System.err: 	at com.androidteam.policeportalapp.ui.Fragments.Front.Personal.FrontPageFragment.loadData(FrontPageFragment.java:115)
10-08 17:33:00.115 14334 14334 W System.err: 	at com.androidteam.policeportalapp.ui.Fragments.Front.Personal.FrontPagePresent$14$1.onCompleted(FrontPagePresent.java:567)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:79)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.observers.SerializedObserver.onCompleted(SerializedObserver.java:176)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.observers.SerializedSubscriber.onCompleted(SerializedSubscriber.java:64)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OperatorTakeUntil$1.onCompleted(OperatorTakeUntil.java:58)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:281)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
10-08 17:33:00.116 14334 14334 W System.err: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
10-08 17:33:00.116 14334 14334 W System.err: 	... 7 more
10-08 17:33:00.206 14334 14334 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 128)
10-08 17:33:00.207 14334 14334 E CrashHandler: dump crash info failed
10-08 17:33:00.207 14334 14334 E CrashHandler: ###############################################################
10-08 17:33:00.208 14334 14334 E CrashHandler: 鍙戠敓浜嗛敊璇細 
10-08 17:33:00.208 14334 14334 E CrashHandler: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at android.os.Handler.handleCallback(Handler.java:758)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at android.os.Looper.loop(Looper.java:154)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at android.app.ActivityThread.main(ActivityThread.java:6144)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at java.lang.reflect.Method.invoke(Native Method)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-08 17:33:00.208 14334 14334 E CrashHandler: Caused by: java.lang.VerifyError: Verifier rejected class com.androidteam.policeportalapp.adapter.recycleradapter.MultiListNewAdapter: void com.androidteam.policeportalapp.adapter.recycleradapter.MultiListNewAdapter._handleDailyComVPChart(com.androidteam.policeportalapp.adapter.recyclerhelper.BaseViewHolder, java.util.ArrayList) failed to verify: void com.androidteam.policeportalapp.adapter.recycleradapter.MultiListNewAdapter._handleDailyComVPChart(com.androidteam.policeportalapp.adapter.recyclerhelper.BaseViewHolder, java.util.ArrayList): [0x1AD] register v0 has type Precise Reference: com.androidteam.policeportalapp.ui.Fragments.Chart.TabFragmentPagerAdapter but expected Reference: android.support.v4.view.PagerAdapter (declaration of 'com.androidteam.policeportalapp.adapter.recycleradapter.MultiListNewAdapter' appears in /data/user/0/com.mobilepolice/app_p_a/-1607123362.jar:classes2.dex)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at com.androidteam.policeportalapp.ui.Fragments.Front.Personal.FrontPageFragment.loadData(FrontPageFragment.java:115)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at com.androidteam.policeportalapp.ui.Fragments.Front.Personal.FrontPagePresent$14$1.onCompleted(FrontPagePresent.java:567)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:79)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.observers.SerializedObserver.onCompleted(SerializedObserver.java:176)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.observers.SerializedSubscriber.onCompleted(SerializedSubscriber.java:64)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OperatorTakeUntil$1.onCompleted(OperatorTakeUntil.java:58)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:281)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
10-08 17:33:00.208 14334 14334 E CrashHandler: 	... 7 more
10-08 17:33:00.430 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-
10-08 17:33:00.449 14334 14400 D !com.basic.http.retrofit.HttpLogger: [RxCachedThreadScheduler-37]-{"resultMsg":"鎴愬姛","updateTime":1570527178233,"data":[{"loginAccount":"cs1_js4440","userCode":"20190724440","userName":"娴嬭瘯1姹熻嫃4440","userSex":"鐢?,"dictPoliceType":null,"dictPoliceTypeCode":null,"dictPost":null,"dictPostCode":null,"userIdentityNumber":null,"userPhoneNumber":null,"userContactNumber":null,"userValidityDay":null,"userRegisterTime":null,"userDescription":null,"userEmail":null,"userSpell":"娴嬭瘯1姹熻嫃4440,20190724440","orgCode":"avcs_dep1693","orgName":"姹熻嫃瀛愰儴闂?693","roleCode":null,"roleName":null,"userSignature":null,"headImageUrl":null,"updateTime":1570524557698,"manageOrgCode":null,"manageOrgName":null,"domainCode":"DEFAULT","isCurrDomain":0,"trainId":null,"state":1},{"loginAccount":"cs1_js4441","userCode":"20190724441","userName":"娴嬭瘯1姹熻嫃4441","userSex":"鐢?,"dictPoliceType":null,"dictPoliceTypeCode":null,"dictPost":null,"dictPostCode":null,"userIdentityNumber":null,"userPhoneNumber":null,"userContactNumber":null,"userValidityDay":null,"userRegisterTime":null,"userDescription":null,"userEmail":null,"userSpell":"娴嬭瘯1姹熻嫃4441,20190724441","orgCode":"avcs_dep1693","orgName":"姹熻嫃瀛愰儴闂?693","roleCode":null,"roleName":null,"userSignature":null,"headImageUrl":null,"updateTime":1570524557749,"manageOrgCode":null,"manageOrgName":null,"domainCode":"DEFAULT","isCurrDomain":0,"trainId":null,"state":1},{"loginAccount":"cs1_js4442","userCode":"20190724442","userName":"娴嬭瘯1姹熻嫃4442","userSex":"鐢?,"dictPoliceType":null,"dictPoliceTypeCode":null,"dictPost":null,"dictPostCode":null,"userIdentityNumber":null,"userPhoneNumber":null,"userContactNumber":null,"userValidityDay":null,"userRegisterTime":null,"userDescription":null,"userEmail":null,"userSpell":"娴嬭瘯1姹熻嫃4442,20190724442","orgCode":"avcs_dep1693","orgName":"姹熻嫃瀛愰儴闂?693","roleCode":null,"roleName":null,"userSignature":null,"headImageUrl":null,"updateTime":1570524557812,"manageOrgCode":null,"manageOrgName":null,"domainCode":"DEFAULT","isCurrDomain":0,"trainId":null,"state":1},{"loginAccount":"cs1_js4443","userCode":"20190724443","userName":"娴嬭瘯1姹熻嫃4

**Comment by techinsight** [comment]
register v0 has type Precise Reference: com.androidteam.policeportalapp.ui.Fragments.Chart.TabFragmentPagerAdapter but expected Reference: android.support.v4.view.PagerAdapter (declaration of 'com.androidteam.policeportalapp.adapter.recycleradapter.MultiListNewAdapter' appears in /data/user/0/com.mobilepolice/app_p_a/-1607123362.jar:classes2.dex)

**Comment by techinsight** [comment]
与fragment.jar类似的操作，将viewpager库剔除。
