### ISSUE TITLE
support库与androidx库能否共存使用

### ISSUE THREAD

**Issue by qihao3768** [Qihoo360/RePlugin#889]
#### 问题详细描述 Detailed description of the problem
老项目support包，新项目androidx包，把旧项目作为插件放到新项目中，点击跳转报错

#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version:2.3.3

Android API Version：29
Android 手机型号&ROM(Phone model & ROM): nexus 6p

#### Logcat上下文 Logcat context
 Process: com.qihoo360.replugin.sample.host, PID: 9492
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS1}: java.lang.IllegalStateException: Required view 'chatting_length_iv' with ID 2131230972 for field 'activity_splash_im' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Required view 'chatting_length_iv' with ID 2131230972 for field 'activity_splash_im' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
        at butterknife.internal.Utils.findRequiredView(Utils.java:3)
        at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:1)
        at com.wxreader.com.activity.SplashActivity_ViewBinding.<init>(SplashActivity_ViewBinding.java:4)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at butterknife.ButterKnife.bind(ButterKnife.java:14)
        at butterknife.ButterKnife.bind(ButterKnife.java:2)
        at com.wxreader.com.activity.SplashActivity.onCreate(SplashActivity.java:8)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
2019-10-09 14:03:09.660 9854-9854/com.qihoo360.replugin.sample.host:p0 E/EaseUI: enter the service process!
2019-10-09 14:03:10.446 9854-9869/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.plugin.novel.Entry, pluginName=novel
2019-10-09 14:03:10.450 9854-9869/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.qihoo360.plugin.novel.Entry, pluginName=novel
2019-10-09 14:03:10.506 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.message.PushAgent, pluginName=novel
2019-10-09 14:03:10.636 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.analytics.vismode.V, pluginName=novel
2019-10-09 14:03:10.641 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.visual.UMVisualAgent, pluginName=novel
2019-10-09 14:03:10.646 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.message.PushAgent, pluginName=novel
2019-10-09 14:03:10.664 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.error.UMError, pluginName=novel
2019-10-09 14:03:10.846 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.message.PushAgent, pluginName=novel
2019-10-09 14:03:10.853 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.message.PushAgent, pluginName=novel
2019-10-09 14:03:10.911 582-1024/? E/QC-QMI: linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
2019-10-09 14:03:10.911 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMLWHandler, pluginName=novel
2019-10-09 14:03:10.912 582-1024/? E/QC-QMI: linux_qmi_qmux_io_wake_unlock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
2019-10-09 14:03:10.927 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.SinaSimplyHandler, pluginName=novel
2019-10-09 14:03:10.935 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.SinaSsoHandler, pluginName=novel
2019-10-09 14:03:10.939 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMPinterestHandler, pluginName=novel
2019-10-09 14:03:10.957 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.RenrenSsoHandler, pluginName=novel
2019-10-09 14:03:10.958 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.TencentWBSsoHandler, pluginName=novel
2019-10-09 14:03:10.981 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMYXHandler, pluginName=novel
2019-10-09 14:03:10.996 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.EmailHandler, pluginName=novel
2019-10-09 14:03:11.006 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMEvernoteHandler, pluginName=novel
2019-10-09 14:03:11.008 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMFacebookHandler, pluginName=novel
2019-10-09 14:03:11.016 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMFlickrHandler, pluginName=novel
2019-10-09 14:03:11.018 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMFourSquareHandler, pluginName=novel
2019-10-09 14:03:11.020 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMGooglePlusHandler, pluginName=novel
2019-10-09 14:03:11.026 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMInstagramHandler, pluginName=novel
2019-10-09 14:03:11.027 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMKakaoHandler, pluginName=novel
2019-10-09 14:03:11.029 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMLineHandler, pluginName=novel
2019-10-09 14:03:11.031 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMLinkedInHandler, pluginName=novel
2019-10-09 14:03:11.037 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMPocketHandler, pluginName=novel
2019-10-09 14:03:11.040 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMWhatsAppHandler, pluginName=novel
2019-10-09 14:03:11.041 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMYNoteHandler, pluginName=novel
2019-10-09 14:03:11.042 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.SmsHandler, pluginName=novel
2019-10-09 14:03:11.044 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.DoubanHandler, pluginName=novel
2019-10-09 14:03:11.049 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMTumblrHandler, pluginName=novel
2019-10-09 14:03:11.051 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.TwitterHandler, pluginName=novel
2019-10-09 14:03:11.053 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.AlipayHandler, pluginName=novel
2019-10-09 14:03:11.057 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMDingSSoHandler, pluginName=novel
2019-10-09 14:03:11.058 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMVKHandler, pluginName=novel
2019-10-09 14:03:11.060 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.socialize.handler.UMDropBoxHandler, pluginName=novel
2019-10-09 14:03:11.105 9854-9854/com.qihoo360.replugin.sample.host:p0 E/priviteSocial: 欢迎使用友盟社会化分享业务，您没有添加debug库，如需看log，请根据文档提示添加：https://developer.umeng.com/docs/66632/detail/66890#h2-u67E5u770Bu65E5u5FD74
2019-10-09 14:03:11.112 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.error.UMError, pluginName=novel
2019-10-09 14:03:11.151 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.visual.UMVisualAgent, pluginName=novel
2019-10-09 14:03:11.152 9854-9854/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.umeng.analytics.vismode.event.VisualHelper, pluginName=novel
2019-10-09 14:03:11.588 9854-9994/com.qihoo360.replugin.sample.host:p0 E/RePlugin.PluginDexClassLoader: loadClass ClassNotFoundException, from PluginClassLoader, cn=com.tencent.bugly.agent.GameAgent, pluginName=novel

**Comment by techinsight** [comment]
androidX 还没有支持吧

**Comment by qihao3768** [comment]
> androidX 还没有支持吧

2.3.3应该是已经支持了，我这边可以取到jar包的信息
