### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.meizu.media.gallery/com.meizu.media.gallery.loader.a.ActivityN1NRNTS3}: java.lang.ClassCastException: android.arch.lifecycle.ReportFragment cannot be cast to android.arch.lifecycle.ReportFragment

### ISSUE THREAD

**Issue by meifangshala** [Qihoo360/RePlugin#898]
#### 问题详细描述 Detailed description of the problem

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.meizu.media.gallery/com.meizu.media.gallery.loader.a.ActivityN1NRNTS3}: java.lang.ClassCastException: android.arch.lifecycle.ReportFragment cannot be cast to android.arch.lifecycle.ReportFragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2740)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2822)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6027)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
Caused by: java.lang.ClassCastException: android.arch.lifecycle.ReportFragment cannot be cast to android.arch.lifecycle.ReportFragment
	at android.arch.lifecycle.ReportFragment.get(SourceFile:46)
	at android.arch.lifecycle.ProcessLifecycleOwner$3.onActivityCreated(SourceFile:160)
	at android.app.Application.dispatchActivityCreated(Application.java:207)
	at android.app.Activity.onCreate(Activity.java:952)
	at android.support.v4.app.SupportActivity.onCreate(SourceFile:66)
	at android.support.v4.app.FragmentActivity.onCreate(SourceFile:321)
	at com.qihoo360.replugin.loader.a.PluginFragmentActivity.onCreate(Unknown Source)
	at com.meizu.media.gallery.facebeauty.FaceBeauty.onCreate(SourceFile:43)
	at android.app.Activity.performCreate(Activity.java:6401)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
	... 9 mo
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version:2.3.3

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by TigerBetree** [comment]
我这边也报这个问题

**Comment by Voidruiyi** [comment]
我这边也复现了

**Comment by fantasy1722** [comment]
宿主和插件的classload都加载的lifecycle reportfragment。如果运行时转换发起类的classload和取fragment classload不一样，就报这个错，大概率随机。插件不依赖lifecycle 1.1.1可以回避这个问题。

**Comment by coder-reus** [comment]
> 宿主和插件的classload都加载的lifecycle reportfragment。如果运行时转换发起类的classload和取fragment classload不一样，就报这个错，大概率随机。插件不依赖lifecycle 1.1.1可以回避这个问题。

切换到lifecycle别的版本就ok了吗？

**Comment by fantasy1722** [comment]
> > 宿主和插件的classload都加载的lifecycle reportfragment。如果运行时转换发起类的classload和取fragment classload不一样，就报这个错，大概率随机。插件不依赖lifecycle 1.1.1可以回避这个问题。
> 
> 切换到lifecycle别的版本就ok了吗？

光切lifecycle版本没用。需要降级插件的support版本，降级到support版本不插入reportfragment的版本，比如24。也可以从根本上改，改classload，对于lifcycle的类，统一用宿主的。因为，坑位在宿主，坑位加载了，就加载了宿主的reportfragment。这个思路也可以吧插件包的lifcycle类去除。这样插件又不能单装单跑了。

**Comment by JaydenHoFly** [comment]
仔细研究了这个问题，问题原因和解决方案都在这篇博客中：https://blog.csdn.net/Jaden_hool/article/details/104780163

**Comment by fantasy1722** [comment]
> 仔细研究了这个问题，问题原因和解决方案都在这篇博客中：https://blog.csdn.net/Jaden_hool/article/details/104780163
正解！

**Comment by qq2748** [comment]
实测正确解法: 
`savedInstanceState?.putParcelable("android:fragments", null)`

**Comment by jjyw** [comment]
我也报了这个问题，后面发现是宿主中依赖中添加了implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'，在这个库中有一个lifecycle-process的模块，这个模块是监听整个App的生命周期的，比如App处于前台或者后台如果不需要监听App生命周期，可以在宿主中将该模块移除，我这边是这样处理的
implementation ('androidx.lifecycle:lifecycle-extensions:2.2.0'){
        exclude group:'androidx.lifecycle',module:'lifecycle-process'
    }
