### ISSUE TITLE
修改demo1的MainActivity为MyMainActivity后，启动报错！

### ISSUE THREAD

**Issue by SlippyBoy** [Qihoo360/RePlugin#90]
**RePlugin version**:
2.1.0
**Android compile SDK version**:
25
**Android ROM**:
lineageos

1.修改demo1MainActivity为MyMainActivity，Manifest里也修改了。（单独安装运行没有问题）

2.将新的demo1 apk改名为demo1.jar放入host工程assests/plugins下。

3.host工程里点击事件也改成了MyMainActivity:
RePlugin.startActivity(MainActivity.this, RePlugin.createIntent("demo1", "com.qihoo360.replugin.sample.demo1.**MyMainActivity**"));

4.卸载host应用，重新运行安装host。

5.点击启动demo1按钮，报错信息为：
07-03 04:16:11.897 6869-6869/com.qihoo360.replugin.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.qihoo360.replugin.sample.host, PID: 6869
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS2}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
                                                                                     at com.qihoo360.replugin.sample.demo1.MyMainActivity.onCreate(MyMainActivity.java:191)
                                                                                     at android.app.Activity.performCreate(Activity.java:6684)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751) 
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6186) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by ncguobiao** [comment]
+1

**Comment by jiongxuan** [comment]
您试下最新的Sample中是否有这个问题？
