### ISSUE TITLE
evalPluginProcess实现严重bug,不能contains(":p")，而应match :p\d

### ISSUE THREAD

**Issue by xfront** [Qihoo360/RePlugin#903]
#### 问题详细描述 Detailed description of the problem
凡是有:pXX进程的项目，无法安装插件！！！！！！！

#### 复现问题步骤 Steps to reproduce the problem
1. 主工程有子进程叫:push
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 

#### Logcat上下文 Logcat context
 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.qihoo360.loader2.PluginManager.evalPluginProcess(PluginManager.java:111)
        at com.qihoo360.loader2.PluginManager.init(PluginManager.java:94)
        at com.qihoo360.loader2.PMF.init(PMF.java:69)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:985)
        at com.qihoo360.replugin.RePluginApplication.attachBaseContext(RePluginApplication.java:67)

**Comment by nh632343** [comment]
我也遇到了，这个bug挺严重啊

**Comment by Nocturner** [comment]
我们项目也有：push,但只要是避免这个进程进行初始化就可以了
