### ISSUE TITLE
关于资源ID找不到

### ISSUE THREAD

**Issue by sorosunrain** [Qihoo360/RePlugin#914]
#### 问题详细描述 Detailed description of the problem
报错：
android.content.res.Resources$NotFoundException: Resource ID
看源码，经过验证，是无法替换继承自androidx的AppCompatActivity。
希望提供手动替换的接口(例如gradle映射) 或者 暴露方法自己在BaseActiviy中createContext。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version:2.3.3

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
6.0模拟器
#### Logcat上下文 Logcat context
11-19 23:25:16.906 16137-16137/com.sunrain.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sunrain.app, PID: 16137
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sunrain.app/com.sunrain.app.loader.a.ActivityN1NRNTS5}: android.content.res.Resources$NotFoundException: Resource ID #0x400c001d
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x400c001d
        at android.content.res.Resources.getValue(Resources.java:1351)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2774)
        at android.content.res.Resources.getLayout(Resources.java:1165)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
        at android.app.Activity.setContentView(Activity.java:2166)
        at com.sunrain.plugin.app.MainActivity.onCreate(MainActivity.java:31)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148)

**Comment by sorosunrain** [comment]
另外 框架中代码中引用了support-v4  support-v7的类，无疑也给框架增加了限制，望改进。

**Comment by wavaya** [comment]
我也遇到Android6就报错，不知道怎么解决。

**Comment by froyohuang** [comment]
可以看下这个repo
https://github.com/froyohuang/RePlugin-AndroidX
