### ISSUE TITLE
插件中无法正常使用VpnService

### ISSUE THREAD

**Issue by guhan121** [Qihoo360/RePlugin#920]
#### 问题详细描述 Detailed description of the problem
使用一个外置的插件来实现VpnService，在宿主中进程Java类占坑。
宿主 AndroidManifest.xml
```
<service
            android:name="com.hezi.vpn.service.OpenVPNService"
            android:exported="true"
            android:process=":GuardService"
            android:permission="android.permission.BIND_VPN_SERVICE">
            <intent-filter>
                <action android:name="android.net.VpnService" />
            </intent-filter>
        </service>
```

插件 AndroidManifest.xml
```
        <meta-data
                android:name="process_map"
                android:value="[
            {'from':'com.hezi.vpn.service.OpenVPNService:GuardService','to':'$p0'}
            ]" />

<service
            android:name=".OpenVPNService"
            android:exported="true"
            android:process=":GuardService"
            android:permission="android.permission.BIND_VPN_SERVICE">
            <intent-filter>
                <action android:name="android.net.VpnService" />
            </intent-filter>
        </service>
```
插件 MainActivity
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ...
        Intent intent = new Intent(getApplicationContext(), OpenVPNService.class);
        startService(intent);
        getApplicationContext().bindService(intent, mServiceConnection, 0);
       ....
    }

    void pressConnect(){
        startService(intent);
        bindService(intent, mServiceConnection, 0);
    }
```
#### 复现问题步骤 Steps to reproduce the problem
1.   点击按钮后可以正常启动vpn，系统显示VPN连接正常。 点击断开也可以正常断开； 但是如果在系统中（设置/或者状态栏下拉） 关闭vpn，服务不会收到vpn 断开的消息，导致ui还是处于连接状态。
查看日志发现从设置页面返回vpn 应用的时候，host重新绑定了服务，使用的ServiceRecord 进行还原服务。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.2
rePlugin-plugin-lib/gradle Version:2.3.2

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by FreedomIsntFree** [comment]
为啥我的replugin 插件vpn就会崩溃，
如果吧这个注释掉就不会崩溃，
        vpnDescriptor = builder.establish();
        崩溃log

08-25 18:06:56.267  6786  6786 D AndroidRuntime: Shutting down VM
08-25 18:06:56.271  6786  6786 E AndroidRuntime: FATAL EXCEPTION: main
08-25 18:06:56.271  6786  6786 E AndroidRuntime: Process: com.guard.myhost, PID: 6786
08-25 18:06:56.271  6786  6786 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service com.guard.myplugindemo.MyVpnService: java.lang.ClassNotFoundException: Didn't find class "com.guard.myplugindemo.MyVpnService" on path: DexPathList[[zip file "/data/app/com.guard.myhost-NsRQZiO9fRYu99mvJGjJ2Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.guard.myhost-NsRQZiO9fRYu99mvJGjJ2Q==/lib/arm64, /system/lib64, /system/vendor/lib64]]
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3428)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at android.app.ActivityThread.-wrap4(Unknown Source:0)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1712)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:173)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6698)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.guard.myplugindemo.MyVpnService" on path: DexPathList[[zip file "/data/app/com.guard.myhost-NsRQZiO9fRYu99mvJGjJ2Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.guard.myhost-NsRQZiO9fRYu99mvJGjJ2Q==/lib/arm64, /system/lib64, /system/vendor/lib64]]
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:172)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:163)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3425)
08-25 18:06:56.271  6786  6786 E AndroidRuntime: 	... 8 more
