### ISSUE TITLE
调转到插件的activity报This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.

### ISSUE THREAD

**Issue by kong747734** [Qihoo360/RePlugin#921]
#### 问题详细描述 Detailed description of the problem
调转到插件的activity报This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
在部分手机没啥问题，但在一台oppo上，就会报错。

#### 复现问题步骤 Steps to reproduce the problem
1. 插件单独运行没问题
2. 主项目安装插件成功，但跳转的时候报错

#### 其它重要信息 Other important information
插件Activity代码
public class MainActivity extends PluginAppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
插件gradle只有如下
apply plugin: 'replugin-plugin-gradle'
implementation 'com.qihoo360.replugin:replugin-plugin-lib:2.3.3'

replugin-host-lib/gradle Version:gradle:3.5.0
rePlugin-plugin-lib/gradle Version:gradle:3.5.0

Android API Version：29
Android 手机型号&ROM(Phone model & ROM): Oppo A83，7.1.1版本，armv8架构
Replugin版本:2.3.3

#### Logcat上下文 Logcat context
 Caused by: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
at
androidx.appcompat.widget.ResourceManagerInternal.checkVectorDrawableSetup(ResourceManagerInternal.java:507)
     at
androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
        at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:411)
        at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
        at androidx.appcompat.app.AppCompatDelegateImpl.attachToWindow(AppCompatDelegateImpl.java:647)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureWindow(AppCompatDelegateImpl.java:623)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:350)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:105)
        at com.qihoo360.replugin.loader.a.PluginAppCompatActivity.onCreate(Unknown Source)
        at com.sicpay.repluginapp2.MainActivity.onCreate(MainActivity.java:13)
        at android.app.Activity.performCreate(Activity.java:6987)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2921)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3097) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:232) 
        at android.app.ActivityThread.main(ActivityThread.java:6910) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by ljmkjth** [comment]
请问这个问题解决了吗?

**Comment by sunshengfei** [comment]
插件activity **extends PluginAppCompatActivity**
