### ISSUE TITLE
宿主启动内置插件报错

### ISSUE THREAD

**Issue by lovemianhuatang** [Qihoo360/RePlugin#930]
插件
![image](https://user-images.githubusercontent.com/41498415/72523689-4cee6680-389b-11ea-9ab9-db431e1a5bdf.png)

2020-01-16 20:01:12.103 7151-7151/com.theblue.lrelugin D/RePlugin.ws001: PACM: eval plugin pluginone, target=com.theblue.pluginone.ui.TestActivity, container=com.theblue.lrelugin.loader.a.ActivityN1NRNTS0
2020-01-16 20:01:12.103 7151-7151/com.theblue.lrelugin I/RePlugin.ws001: alloc success: container=com.theblue.lrelugin.loader.a.ActivityN1NRNTS0 plugin=pluginone activity=com.theblue.pluginone.ui.TestActivity
2020-01-16 20:01:12.104 7151-7151/com.theblue.lrelugin D/RePlugin.ws001: start activity: real intent=Intent { cat=[container:com.theblue.lrelugin.loader.a.ActivityN1NRNTS0,process:-2147483648,plugin:pluginone,counter:0,activity:com.theblue.pluginone.ui.TestActivity] cmp=com.theblue.lrelugin/.loader.a.ActivityN1NRNTS0 (has extras) }
2020-01-16 20:01:12.134 7151-7151/com.theblue.lrelugin W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@2a48cae
2020-01-16 20:01:12.138 7151-7151/com.theblue.lrelugin D/RePlugin.ws001: found: ActivityState {container=com.theblue.lrelugin.loader.a.ActivityN1NRNTS0 state=occupied plugin=pluginone activity=com.theblue.pluginone.ui.TestActivity size=0}
2020-01-16 20:01:12.138 7151-7151/com.theblue.lrelugin D/RePlugin.ws001: PACM: loadActivityClass in=com.theblue.lrelugin.loader.a.ActivityN1NRNTS0 target=com.theblue.pluginone.ui.TestActivity plugin=pluginone
2020-01-16 20:01:12.138 7151-7151/com.theblue.lrelugin D/RePlugin.ws001: PStatusC.getStatus(): ps is null. pn=pluginone
2020-01-16 20:01:12.138 7151-7151/com.theblue.lrelugin I/RePlugin.ws000: loadLocked(): Initialized, is loaded = true
2020-01-16 20:01:12.139 7151-7151/com.theblue.lrelugin D/RePlugin.ws001: PACM: loadActivityClass, plugin activity loader: in=com.theblue.lrelugin.loader.a.ActivityN1NRNTS0 activity=com.theblue.pluginone.ui.TestActivity
2020-01-16 20:01:12.139 7151-7151/com.theblue.lrelugin D/RePlugin.ws001: PACM: loadActivityClass, plugin activity loader: c=class com.theblue.pluginone.ui.TestActivity, loader=com.qihoo360.replugin.PluginDexClassLoader[DexPathList[[zip file "/data/user/0/com.theblue.lrelugin/app_plugins_v3/pluginone-10-10-1.jar"],nativeLibraryDirectories=[/data/user/0/com.theblue.lrelugin/app_plugins_v3_libs/pluginone-10-10-1, /system/lib64, /system/vendor/lib64]]]
2020-01-16 20:01:12.141 7151-7151/com.theblue.lrelugin D/AppCompatDelegate: Exception while getting ActivityInfo
    android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.theblue.lrelugin/com.theblue.pluginone.ui.TestActivity}
        at android.app.ApplicationPackageManager.getActivityInfoAsUser(ApplicationPackageManager.java:528)
        at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:512)
        at androidx.appcompat.app.AppCompatDelegateImpl.isActivityManifestHandlingUiMode(AppCompatDelegateImpl.java:2413)
        at androidx.appcompat.app.AppCompatDelegateImpl.updateForNightMode(AppCompatDelegateImpl.java:2266)
        at androidx.appcompat.app.AppCompatDelegateImpl.applyDayNight(AppCompatDelegateImpl.java:2170)
        at androidx.appcompat.app.AppCompatDelegateImpl.attachBaseContext(AppCompatDelegateImpl.java:334)
        at androidx.appcompat.app.AppCompatActivity.attachBaseContext(AppCompatActivity.java:98)
        at com.qihoo360.replugin.loader.a.PluginAppCompatActivity.attachBaseContext(Unknown Source:4)
        at android.app.Activity.attach(Activity.java:7242)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3055)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

![image](https://user-images.githubusercontent.com/41498415/72523720-5d064600-389b-11ea-9f2f-fcd43aafa032.png)

请问什么问题？

**Comment by NiLuogege** [comment]
同问

**Comment by 13121221** [comment]
同问，这个RePlugin的issue的闭环率也太低了，仿佛没有人维护一样

**Comment by junyao-yu** [comment]
这个问题没人回答么？
