### ISSUE TITLE
Program type already present: com.qihoo360.replugin.model.PluginInfo

### ISSUE THREAD

**Issue by wuzhenmin** [Qihoo360/RePlugin#941]
#### 问题详细描述 Detailed description of the problem
assembleRelease 打包失败

#### 其它重要信息 Other important information
com.android.tools.build:gradle:3.2.1

rePlugin-plugin-lib/gradle Version:2.3.0

#### Logcat上下文 Logcat context
Program type already present: com.qihoo360.replugin.model.PluginInfo
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:36)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:65)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
        at com.android.tools.r8.D8.run(D8.java:90)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:115)
        ... 2 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: com.qihoo360.replugin.model.PluginInfo
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:116)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:74)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:59)
        ... 5 more

**Comment by marufei** [comment]
请问这个问题解决了吗？

**Comment by wuzhenmin** [comment]
已收到邮件
