### ISSUE TITLE
插件正常显示，但是长按选择文本后闪退

### ISSUE THREAD

**Issue by wavaya** [Qihoo360/RePlugin#955]
#### 问题详细描述 Detailed description of the problem
插件正常显示，但是长按选择文本后闪退

#### 复现问题步骤 Steps to reproduce the problem
1. 打开插件没问题，查看详情时也没问题
2. 但是长按文本，也能选中文本，然后闪退

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version: 2.3.3

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 华为

#### Logcat上下文 Logcat context
java.lang.ClassCastException: androidx.fragment.app.FragmentManagerState cannot be cast to androidx.fragment.app.FragmentManagerState
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)

**Comment by playactorzxc** [comment]
我猜测是用法问题，看上去是PluginAClassLoader加载的FragmentManagerState 对象不能转换类型为PluginBClassLoader加载的FragmentManagerState 类类型
