### ISSUE TITLE
宿主APP activity-alias 崩溃

### ISSUE THREAD

**Issue by hanlyjiang** [Qihoo360/RePlugin#964]
#### 问题详细描述 Detailed description of the problem
主APP中声明一个activity-alias，打开此activity时APP会崩溃。

#### 复现问题步骤 Steps to reproduce the problem
1. Manifest中声明 activity-alias
2. 使用别名启动此activity
3. app崩溃；

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version: 2.3.2

Android API Version：8
Android 手机型号&ROM(Phone model & ROM):  EMUI/8.0

#### Logcat上下文 Logcat context
```
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xiuying.android.wxapi.WXEntryActivity" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.xiuying.android-aheB9Q9pRvC0z9buzqK43w==/base.apk"],nativeLibraryDirectories=[/data/app/com.xiuying.android-aheB9Q9pRvC0z9buzqK43w==/lib/arm, /data/app/com.xiuying.android-aheB9Q9pRvC0z9buzqK43w==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at com.qihoo360.replugin.RePluginClassLoader.findClass(RePluginClassLoader.java:172)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at com.qihoo360.replugin.RePluginClassLoader.loadClass(RePluginClassLoader.java:163)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1178)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3191)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
```

**Comment by hanlyjiang** [comment]
提问错误
