### ISSUE TITLE
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020003

### ISSUE THREAD

**Issue by mChenys** [Qihoo360/RePlugin#968]
#### 问题详细描述 Detailed description of the problem
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qihoo360.replugin.sample.host/com.qihoo360.replugin.sample.host.loader.a.ActivityN1NRNTS0}: android.content.res.Resources$NotFoundException: Resource ID #0x7f020003
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020003
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:292)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2390)
        at android.content.res.Resources.getLayout(Resources.java:1341)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:498)
        at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:342)
        at android.app.Activity.setContentView(Activity.java:2941)
        at com.qihoo360.replugin.sample.demo1.MainActivity.onCreate(MainActivity.java:77)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 

#### 复现问题步骤 Steps to reproduce the problem
1. 将replugin-sample中的host项目的gradle插件版本提升到3.5.3，gradle版本提升到5.4.1
2. 将replugin-sample中的plugin/plugin-demo1插件项目的gradle插件版本提升到3.5.3，gradle版本提升到5.4.1
3.修改host项目和plugin-demo1插件项目的compileSdkVersion=28，buildToolsVersion=28.0.3，minSdkVersion=21，targetSdkVersion=28
4.编译插件plugin-demo1，生成apk文件，重命名为demo1.jar，然后将其复制到replugin-sample中的host项目assets/plugins/目录内并替换原来的demo1.jar

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.4
rePlugin-plugin-lib/gradle Version:2.3.4

Android API Version：28
Android 手机型号&ROM(Phone model & ROM): 
华为荣耀20

**Comment by mChenys** [comment]
如果将plugin-demo1插件项目的gradle插件版本降低到3.2.0版本，则没有此问题。

**Comment by hjqiaho** [comment]
降下来会有这个问题
cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
这遇到过吗
