### ISSUE TITLE
宿主app中在布局中使用插件的Fragment会报错

### ISSUE THREAD

**Issue by mChenys** [Qihoo360/RePlugin#969]
#### 问题详细描述 Detailed description of the problem
使用内置插件中的fragment报错

![1598006517725](https://user-images.githubusercontent.com/19259572/90882444-8ca3a080-e3de-11ea-8df6-20bfd817234e.png)

#### 复现问题步骤 Steps to reproduce the problem
1.宿主app的Activity布局中使用插件的fragment
插件的fragment用的是Replugin 插件demo1的
![1598006819259](https://user-images.githubusercontent.com/19259572/90882632-d3919600-e3de-11ea-9c65-dc392229782c.png)

`
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_weight="2"
    android:orientation="vertical">

    <fragment
        android:id="@+id/fragment"
        class="com.cys.demo_replugin_plugin.fragment.DemoFragment"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />

    
    <LinearLayout
        android:layout_width="match_parent"
        android:background="@color/colorAccent"
        android:layout_height="1dp"/>

    <FrameLayout
        android:id="@+id/container2"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />

</LinearLayout>

`
2.对应的Activity，其实就是copy host demo中的PluginFragmentActivity 做修改的
`public class PluginFragmentActivity extends FragmentActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        boolean isBuiltIn = true;
        String pluginName = isBuiltIn ? "demo1" : "com.cys.demo_replugin_plugin";

        //注册相关Fragment的类
        //注册一个全局Hook用于拦截系统对XX类的寻找定向到Demo1中的XX类主要是用于在xml中可以直接使用插件中的类
        RePlugin.registerHookingClass("com.cys.demo_replugin_plugin.fragment.DemoFragment",
                RePlugin.createComponentName(pluginName, "com.cys.demo_replugin_plugin.fragment.DemoFragment"), null);
        setContentView(R.layout.activity_plugin_fragment);

        //代码使用插件Fragment
        ClassLoader d1ClassLoader = RePlugin.fetchClassLoader(pluginName);//获取插件的ClassLoader
        try {
            Fragment fragment = d1ClassLoader.loadClass("com.cys.demo_replugin_plugin.fragment.DemoCodeFragment").asSubclass(Fragment.class).newInstance();//使用插件的Classloader获取指定Fragment实例
            getSupportFragmentManager().beginTransaction().add(R.id.container2, fragment).commit();//添加Fragment到UI
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }
}`

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version: 2.3.4
rePlugin-plugin-lib/gradle Version:2.3.4

Android API Version：
Android 手机型号&ROM(Phone model & ROM): 
华为荣耀20

#### Logcat上下文 Logcat context

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cys.demo_replugin_host/com.cys.demo_replugin_host.PluginFragmentActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class fragment
     Caused by: android.app.Fragment$InstantiationException: Trying to instantiate a class com.cys.demo_replugin_plugin.fragment.DemoFragment that is not a Fragment`

**Comment by IamMusicBoom** [comment]
这个东西有解了吗？遇到了同样的问题。

**Comment by IamMusicBoom** [comment]
用android.app.Fragment吧，我应该是因为项目里面用的androidx的Fragment，RePlugin使用的是Support的Fragment，无法强转。
