### ISSUE TITLE
打开插件报 android.os.DeadObjectException

### ISSUE THREAD

**Issue by chengfei602** [Qihoo360/RePlugin#971]
#### 问题详细描述 Detailed description of the problem
打开插件出错

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:    2.3.0
rePlugin-plugin-lib/gradle Version:  2.3.0

Android API Version：4.4.2
Android 手机型号&ROM(Phone model & ROM):机顶盒

#### Logcat上下文 Logcat context
android.os.DeadObjectException
        at android.os.BinderProxy.transact(Native Method)
        at com.qihoo360.loader2.IPluginHost$Stub$Proxy.startPluginProcess(IPluginHost.java:555)
        at com.qihoo360.loader2.MP.startPluginProcess(MP.java:434)
        at com.qihoo360.loader2.PluginCommImpl.loadPluginActivity(PluginCommImpl.java:431)
        at com.qihoo360.loader2.PluginLibraryInternalProxy.startActivity(PluginLibraryInternalProxy.java:268)
        at com.qihoo360.loader2.PluginCommImpl.startActivity(PluginCommImpl.java:380)
        at com.qihoo360.i.Factory.startActivityWithNoInjectCN(Factory.java:327)
        at com.qihoo360.replugin.RePlugin.startActivity(RePlugin.java:248)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at library.f.a(Unknown Source)
        at com.qihoo360.replugin.b.a(Unknown Source)
        at com.qihoo360.replugin.RePlugin.startActivity(Unknown Source)
        at com.gong.ui.GameLoadingActivity.startGameActivity(GameLoadingActivity.java:224)
        at com.gong.ui.GameLoadingActivity.access$300(GameLoadingActivity.java:53)
        at com.gong.ui..GameLoadingActivity$3.handleMessage(GameLoadingActivity.java:212)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5030)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:861)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:677)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by Spider-007** [comment]
大佬，我也遇到了，本地集成正常，但是第三方测试就安装不上！如何解决，在线等 急！
