### ISSUE TITLE
插件内webview加载资源崩溃问题

### ISSUE THREAD

**Issue by chenxian0258** [Qihoo360/RePlugin#976]
#### 问题详细描述 Detailed description of the problem
在三星手机上切换设置导航条样式，导致的webview加载资源崩溃问题
#### 复现问题步骤 Steps to reproduce the problem
1. 在三星手机上（华为，小米未发现此问题）
2. 宿主页面打开插件内webview正常加载页面
3，不退出应用的情况下，切换到设置内导航条，更改导航条样式（三星这里有两种，一种导航按钮，一种全屏手势）
4，更改导航条以后，切换会应用，这时webview还可以正常运行。
5，退出webview页面，回到宿主页面，再次进入webview时崩溃。
6，切换导航条以后，杀掉应用进程，在进是不会崩溃的。

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:2.3.3
rePlugin-plugin-lib/gradle Version:2.3.3

Android API Version：10
Android 手机型号&ROM(Phone model & ROM): 
三星Galaxy S20 5G  型号：SM-G9810
#### Logcat上下文 Logcat context
2020-09-10 10:26:41.600 15772-15772/com.samsung.android.game.gamehome E/d.game.gamehom: No package ID 02 found for ID 0x02090005.
2020-09-10 10:26:41.600 15772-15772/com.samsung.android.game.gamehome W/System.err: android.content.res.Resources$NotFoundException: Resource ID #0x2090005
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:276)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.content.res.Resources.getInteger(Resources.java:1216)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at org.chromium.ui.base.DeviceFormFactor.isTablet(PG:2)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at J.N.Mq8l4Aae(Native Method)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at org.chromium.android_webview.AwSettings.a(PG:10)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at org.chromium.android_webview.AwContents.b(PG:69)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at org.chromium.android_webview.AwContents.a(PG:73)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at org.chromium.android_webview.AwContents.<init>(PG:69)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.android.webview.chromium.WebViewChromium.a(PG:8)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at N3.run(PG:1)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at bp.a(PG:6)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at Zo.run(PG:1)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at org.chromium.base.task.PostTask.a(PG:14)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at bp.a(PG:3)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.android.webview.chromium.WebViewChromium.init(PG:72)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.webkit.WebView.<init>(WebView.java:429)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.webkit.WebView.<init>(WebView.java:353)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.webkit.WebView.<init>(WebView.java:336)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.webkit.WebView.<init>(WebView.java:323)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.cocos.vs.core.widget.webview.RepluginWebView.<init>(RepluginWebView.java:17)
2020-09-10 10:26:41.602 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.cocos.vs.core.widget.webview.RepluginWebView.<init>(RepluginWebView.java:13)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.cocos.vs.h5.module.singlegame.SingleGameWebActivity.initView(SingleGameWebActivity.java:233)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.cocos.vs.h5.module.singlegame.SingleGameWebActivity.init(SingleGameWebActivity.java:223)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.cocos.vs.base.ui.b.init(BasePresenter.java:39)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.cocos.vs.base.ui._BaseMVPActivity.initPresenter(_BaseMVPActivity.java:10)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.cocos.vs.core.base.ui.BaseMVPActivity.initPresenter(BaseMVPActivity.java:119)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.cocos.vs.base.ui._BaseMVPActivity.onCreate(_BaseMVPActivity.java:20)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.cocos.vs.core.base.ui.BaseMVPActivity.onCreate(BaseMVPActivity.java:111)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.Activity.performCreate(Activity.java:7957)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.Activity.performCreate(Activity.java:7946)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3539)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3716)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.os.Looper.loop(Looper.java:237)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8034)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
2020-09-10 10:26:41.603 15772-15772/com.samsung.android.game.gamehome W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by QQHEZhangyubin** [comment]
我准备也出现了同样的问题，请问有处理方式吗？

**Comment by QQHEZhangyubin** [comment]
我准备也出现了同样的问题，请问有解决方案吗？
